import type { QuizQuestionTranslation } from "./types";

/**
 * English rendering of the 1Z0-076 bank (`quiz-data-dataguard.ts`).
 * Keyed by question id; option order preserved.
 */
export const dataGuardEnglish: Record<string, QuizQuestionTranslation> = {
  "dg-q1": {
    question: "Which risk does Data Guard NOT protect against?",
    options: [
      "A logical error, such as an unfortunate DROP TABLE",
      "Loss of the production site",
      "Failure of the primary server",
      "Physical corruption of a data file",
    ],
    explanation: "Data Guard faithfully replicates everything that commits, errors included: a DROP TABLE reaches the standby within seconds. Only backups, Flashback and restore points protect against a logical error.",
    topic: "Data Guard scope",
  },
  "dg-q2": {
    question: "Which process applies redo on a physical standby?",
    options: ["MRP0", "LSP0", "RFS", "LNS"],
    explanation: "MRP0 (Managed Recovery Process) applies redo on a physical standby — that is Redo Apply. LSP0 replays SQL statements on a logical standby, RFS receives redo on the standby side, LNS ships it on the primary side.",
    topic: "Processes",
  },
  "dg-q3": {
    question: "Which statements about a snapshot standby are correct? (Choose three.)",
    options: [
      "It is open read-write",
      "A guaranteed restore point is created automatically on conversion",
      "It keeps receiving redo without applying it",
      "It applies redo continuously",
      "It can never become a physical standby again",
    ],
    explanation: "Conversion creates a guaranteed restore point and opens the database read-write for testing. Redo keeps arriving but stays pending. CONVERT … TO PHYSICAL STANDBY flashes back to that point then catches up on all accumulated redo.",
    topic: "Snapshot standby",
  },
  "dg-q4": {
    question: "In a multitenant environment, at which level does a Data Guard configuration apply?",
    options: [
      "To the whole CDB",
      "To each PDB independently",
      "To CDB$ROOT only",
      "To the application container alone",
    ],
    explanation: "Redo is shared by every container of a CDB, so Data Guard replicates the whole CDB. Replicating a single PDB is the job of a refreshable clone or GoldenGate, not Data Guard.",
    topic: "Multitenant",
  },
  "dg-q5": {
    question: "Which standby type allows extra indexes absent from the primary?",
    options: ["Logical", "Physical", "Snapshot", "Far Sync"],
    explanation: "A logical standby replays SQL statements and stays open read-write: it can carry its own indexes, materialized views and even tables. A physical standby is a block-for-block copy, structurally identical.",
    topic: "Standby types",
  },
  "dg-q6": {
    question: "Why is a static listener.ora entry mandatory on the standby side?",
    options: [
      "Because PMON cannot register a stopped instance, which RMAN and the Broker must nevertheless reach",
      "Because dynamic registration is disabled in 19c",
      "Because it speeds up redo transport",
      "Because FORCE LOGGING requires it",
    ],
    explanation: "Dynamic registration by PMON assumes a started instance. Yet the RMAN duplicate and the Broker must reach an instance in NOMOUNT, or even stopped, to start it. Only a static entry allows that — with the _DGMGRL suffix for the Broker.",
    topic: "Oracle Net",
  },
  "dg-q7": {
    question: "How many standby redo log groups should you create, and at what size?",
    options: [
      "One more than the number of online redo log groups, at exactly the same size",
      "As many as the online groups, at double the size",
      "A single group, whatever its size",
      "Twice the number of online groups, at half the size",
    ],
    explanation: "The rule is n+1 groups at exactly the same size as the online redo logs. A different size prevents the RFS process from using the group, and transport silently falls back to archive mode.",
    topic: "Standby redo logs",
  },
  "dg-q8": {
    question: "Which prerequisites must be met on the primary? (Choose three.)",
    options: [
      "FORCE LOGGING",
      "ARCHIVELOG mode",
      "Flashback Database enabled, to make REINSTATE possible",
      "NOARCHIVELOG mode",
      "The COMPATIBLE parameter set to 11.2",
    ],
    explanation: "FORCE LOGGING forbids unlogged operations, ARCHIVELOG mode is mandatory for any redo transport, and Flashback Database makes it possible to reinstate the former primary after a failover without rebuilding it.",
    topic: "Prerequisites",
  },
  "dg-q9": {
    question: "Which RMAN command creates a physical standby directly from the running database?",
    options: [
      "DUPLICATE TARGET DATABASE FOR STANDBY FROM ACTIVE DATABASE",
      "BACKUP DATABASE PLUS ARCHIVELOG",
      "RESTORE STANDBY CONTROLFILE",
      "RECOVER DATABASE UNTIL CANCEL",
    ],
    explanation: "DUPLICATE … FOR STANDBY FROM ACTIVE DATABASE copies the running database to the auxiliary instance, with no prior backup. The DORECOVER option applies the redo generated during the copy.",
    topic: "Creation with RMAN",
  },
  "dg-q10": {
    question: "What does the DBMS_DBCOMP.DBCOMP procedure do?",
    options: [
      "It compares the primary and its standby block by block and reports divergences",
      "It compresses the shipped redo",
      "It compares execution plans between the two databases",
      "It converts a physical standby into a logical one",
    ],
    explanation: "Introduced in 12.2, DBCOMP physically compares the blocks of both databases. It is the check that proves the replica is faithful — useful after a transport incident or a suspicious NOLOGGING operation.",
    topic: "DBMS_DBCOMP",
  },
  "dg-q11": {
    question: "Which view confirms that no archived log is missing on the standby?",
    options: ["V$ARCHIVE_GAP", "V$LOGFILE", "V$DATAFILE_HEADER", "V$RECOVERY_FILE_DEST"],
    explanation: "V$ARCHIVE_GAP must stay empty. If it returns rows, the FAL_SERVER parameter failed to close the gap automatically and the missing archives must be shipped by hand.",
    topic: "Transport checks",
  },
  "dg-q12": {
    question: "Which parameter avoids having to create data files manually on the standby?",
    options: [
      "STANDBY_FILE_MANAGEMENT = AUTO",
      "DB_FILE_NAME_CONVERT",
      "LOG_ARCHIVE_CONFIG",
      "FAL_CLIENT",
    ],
    explanation: "With STANDBY_FILE_MANAGEMENT = AUTO, a file added on the primary is created automatically on the standby. DB_FILE_NAME_CONVERT only translates paths; without the first parameter, redo apply stops.",
    topic: "File management",
  },
  "dg-q13": {
    question: "Which view must you check BEFORE creating a logical standby?",
    options: [
      "DBA_LOGSTDBY_UNSUPPORTED",
      "V$DATAGUARD_STATS",
      "DBA_LOGSTDBY_LOG",
      "V$MANAGED_STANDBY",
    ],
    explanation: "DBA_LOGSTDBY_UNSUPPORTED lists objects SQL Apply cannot replicate, because of unsupported data types. If critical tables appear there they will never be synchronised — and you only find out after switching over.",
    topic: "Logical standby",
  },
  "dg-q14": {
    question: "Which supplemental logging does SQL Apply require?",
    options: [
      "ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY, UNIQUE INDEX) COLUMNS",
      "ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS only",
      "None: the redo is enough",
      "ALTER DATABASE FORCE LOGGING alone",
    ],
    explanation: "SQL Apply must be able to identify each row uniquely in order to replay an UPDATE or a DELETE. Supplemental logging of primary keys and unique indexes makes that identification possible.",
    topic: "Supplemental logging",
  },
  "dg-q15": {
    question: "Which procedure resynchronises a single diverged table on a logical standby?",
    options: [
      "DBMS_LOGSTDBY.INSTANTIATE_TABLE",
      "DBMS_LOGSTDBY.SKIP",
      "DBMS_LOGSTDBY.APPLY_SET",
      "DBMS_LOGSTDBY.SKIP_ERROR",
    ],
    explanation: "INSTANTIATE_TABLE re-copies a table from the primary and returns it to the SQL Apply stream, without rebuilding the whole standby. SKIP excludes an object, SKIP_ERROR ignores an error, APPLY_SET tunes parallelism.",
    topic: "SQL Apply",
  },
  "dg-q16": {
    question: "In Maximum Protection mode, what happens if no standby can acknowledge?",
    options: [
      "The primary shuts down",
      "Transport automatically falls back to asynchronous",
      "Transactions are queued then committed",
      "The mode automatically becomes Maximum Availability",
    ],
    explanation: "Maximum Protection guarantees zero loss literally: rather than commit an unreplicated transaction, the primary shuts down. That is why the mode requires at least two standbys in practice.",
    topic: "Protection modes",
  },
  "dg-q17": {
    question: "What does FASTSYNC mean?",
    options: [
      "SYNC NOAFFIRM: the standby acknowledges as soon as redo is received in memory",
      "ASYNC with compression enabled",
      "Synchronous transport plus an immediate disk write",
      "The default mode of Maximum Performance",
    ],
    explanation: "FASTSYNC = SYNC NOAFFIRM. The standby confirms as soon as redo is in memory, without waiting for the disk write. You keep most of the synchronous guarantee while markedly cutting COMMIT latency.",
    topic: "Redo transport",
  },
  "dg-q18": {
    question: "What is Active Data Guard's main contribution?",
    options: [
      "Serving read queries while redo is being applied",
      "Replicating a single PDB",
      "Removing the need for standby redo logs",
      "Turning a physical standby into a logical one",
    ],
    explanation: "Without Active Data Guard a physical standby is either open read-only or applying — never both. Active Data Guard lifts that exclusion: OPEN MODE becomes READ ONLY WITH APPLY. It is a paid option.",
    topic: "Active Data Guard",
  },
  "dg-q19": {
    question: "Which problem does a Far Sync instance solve?",
    options: [
      "Achieving zero data loss without imposing intercontinental latency on every COMMIT",
      "Applying redo faster on the standby",
      "Replicating several PDBs separately",
      "Compressing RMAN backups",
    ],
    explanation: "Far Sync is a lightweight instance — control file and standby redo logs, no data files — placed near production. It receives redo synchronously, then forwards it asynchronously to the remote standby.",
    topic: "Far Sync",
  },
  "dg-q20": {
    question: "What does a Far Sync instance contain? (Choose two.)",
    options: [
      "A control file",
      "Standby redo logs",
      "The database's data files",
      "An MRP0 process applying redo",
    ],
    explanation: "A Far Sync instance has neither data files nor redo apply: it only receives and forwards. Its role shows as FAR SYNC in V$DATABASE.DATABASE_ROLE.",
    topic: "Far Sync",
  },
  "dg-q21": {
    question: "What does Real-Time Cascade add from 12c onwards?",
    options: [
      "The standby forwards redo as it arrives, without waiting for the log file to complete",
      "The primary ships redo to every standby simultaneously",
      "Redo apply becomes parallel",
      "Archived logs are compressed automatically",
    ],
    explanation: "Before 12c a cascading standby waited for the log file to complete before forwarding. Since then forwarding is immediate: a three-tier configuration becomes almost as responsive as a direct link.",
    topic: "Cascade",
  },
  "dg-q22": {
    question: "Which view shows the protection mode actually in force?",
    options: [
      "V$DATABASE, columns PROTECTION_MODE and PROTECTION_LEVEL",
      "V$MANAGED_STANDBY",
      "V$ARCHIVE_DEST_STATUS only",
      "V$LOGFILE",
    ],
    explanation: "PROTECTION_MODE shows the configured mode, PROTECTION_LEVEL the mode actually delivered at that instant. A gap between them — MAXIMUM AVAILABILITY configured, RESYNCHRONIZATION in progress — signals a degraded configuration.",
    topic: "Mode checking",
  },
  "dg-q23": {
    question: "Which parameter must be enabled on each database to use the Broker?",
    options: ["DG_BROKER_START = TRUE", "DG_BROKER_CONFIG_FILE1", "LOG_ARCHIVE_CONFIG", "FAL_SERVER"],
    explanation: "DG_BROKER_START = TRUE starts the DMON process on each database. DG_BROKER_CONFIG_FILE1 and 2 only point to the configuration files.",
    topic: "Broker",
  },
  "dg-q24": {
    question: "Once the Broker is active, how do you change a transport destination?",
    options: [
      "Through EDIT DATABASE … SET PROPERTY in DGMGRL",
      "Through ALTER SYSTEM SET log_archive_dest_2 in SQL",
      "By editing the Broker configuration file directly",
      "By restarting the instance with a modified pfile",
    ],
    explanation: "The Broker rewrites the LOG_ARCHIVE_DEST_n parameters from its own configuration: any SQL change disappears without warning. You must go through EDIT DATABASE … SET PROPERTY.",
    topic: "Broker",
  },
  "dg-q25": {
    question: "What does the DGMGRL VALIDATE DATABASE command report? (Choose three.)",
    options: [
      "The database's ability to perform a switchover or failover",
      "Missing or out-of-step data files",
      "The state of the password file and of Flashback",
      "The execution plan of the slowest queries",
      "The compression ratio of backups",
    ],
    explanation: "VALIDATE DATABASE, introduced in 12.2, answers the question that matters before an incident: “can I switch over now, and what would I lose?”. It checks files, missing redo, password file, Flashback, standby redo logs and service roles.",
    topic: "VALIDATE",
  },
  "dg-q26": {
    question: "Which suffix must GLOBAL_DBNAME carry in listener.ora for the Broker?",
    options: ["_DGMGRL", "_STANDBY", "_BROKER", "_DG"],
    explanation: "The Broker expects a static entry whose GLOBAL_DBNAME is <db_unique_name>_DGMGRL. Without it, VALIDATE STATIC CONNECT IDENTIFIER fails and the Broker cannot restart the instance during a role transition.",
    topic: "Broker",
  },
  "dg-q27": {
    question: "What essential difference separates a switchover from a failover?",
    options: [
      "A switchover is planned and lossless; a failover is forced and may lose data",
      "A switchover only works with a logical standby",
      "A failover is reversible without intervention",
      "A switchover requires an observer",
    ],
    explanation: "A switchover cleanly exchanges roles: the former primary becomes the standby with no rebuild. A failover is forced and leaves the former primary diverged: it must be reinstated or rebuilt.",
    topic: "Role transitions",
  },
  "dg-q28": {
    question: "Why must Flashback Database be enabled before a failover?",
    options: [
      "To make REINSTATE DATABASE possible without rebuilding the former primary",
      "To speed up redo transport",
      "To allow Maximum Protection mode",
      "To create the standby redo logs automatically",
    ],
    explanation: "After a failover, the former primary holds transactions the new one never received. With Flashback, REINSTATE rewinds it to the divergence SCN then resynchronises it in minutes; without it, everything must be rebuilt.",
    topic: "Flashback and REINSTATE",
  },
  "dg-q29": {
    question: "Where must the Fast-Start Failover observer run?",
    options: [
      "On a third site, distinct from the primary and the standby",
      "On the primary",
      "On the standby",
      "On either of the two databases, indifferently",
    ],
    explanation: "An observer hosted on the primary would vanish with it and could decide nothing; hosted on the standby, it could not distinguish a real failure from a network cut. The third site provides the arbitration.",
    topic: "Fast-Start Failover",
  },
  "dg-q30": {
    question: "Which minimum protection mode does Fast-Start Failover require?",
    options: [
      "Maximum Availability (or Maximum Performance depending on the configuration)",
      "Maximum Protection, mandatorily",
      "No particular mode",
      "Maximum Performance only",
    ],
    explanation: "Fast-Start Failover is supported in Maximum Availability — the reference, zero-loss configuration — and in Maximum Performance since 11.2, with a loss objective set by FastStartFailoverLagLimit.",
    topic: "Fast-Start Failover",
  },
  "dg-q31": {
    question: "Which procedure lets an application trigger a Fast-Start Failover immediately?",
    options: [
      "DBMS_DG.INITIATE_FS_FAILOVER",
      "DBMS_SERVICE.STOP_SERVICE",
      "DBMS_LOGSTDBY.SKIP",
      "DBMS_DBCOMP.DBCOMP",
    ],
    explanation: "DBMS_DG.INITIATE_FS_FAILOVER lets an application that has detected corruption or unavailability request the transition without waiting for FastStartFailoverThreshold to expire.",
    topic: "Fast-Start Failover",
  },
  "dg-q32": {
    question: "Since 12.2, what happens to a restore point created on the primary?",
    options: [
      "It is automatically propagated to the standby, prefixed with its original name",
      "It stays local to the primary",
      "It interrupts redo apply",
      "It can no longer be guaranteed",
    ],
    explanation: "Replicated restore points let you rewind both databases to the same logical instant after an application error. The REPLICATED column of V$RESTORE_POINT identifies them on the standby side.",
    topic: "Replicated restore points",
  },
  "dg-q33": {
    question: "What does Automatic Block Media Recovery allow?",
    options: [
      "Repairing a corrupt block from the other database, with no intervention and no downtime",
      "Rebuilding a whole data file",
      "Converting a physical standby into a logical one",
      "Compressing transferred blocks",
    ],
    explanation: "With Active Data Guard, a corrupt block found on the primary is repaired automatically from the standby — and vice versa. The session involved waits a moment then carries on; the event is traced in the alert log.",
    topic: "Block repair",
  },
  "dg-q34": {
    question: "Which RMAN command resynchronises a badly lagging standby, with no file restore?",
    options: [
      "RECOVER STANDBY DATABASE FROM SERVICE orcl_pr",
      "RESTORE DATABASE FROM TAG standby",
      "DUPLICATE DATABASE FOR STANDBY",
      "RECOVER DATABASE UNTIL CANCEL",
    ],
    explanation: "RECOVER … FROM SERVICE fetches blocks directly over the network from the source database, without going through a backup. The same syntax works the other way to recover the primary from the standby.",
    topic: "Recovery over the network",
  },
  "dg-q35": {
    question: "Which package automates a rolling database upgrade?",
    options: ["DBMS_ROLLING", "DBMS_LOGSTDBY", "DBMS_DG", "DBMS_REDEFINITION"],
    explanation: "DBMS_ROLLING chains INIT_PLAN, BUILD_PLAN, START_PLAN, SWITCHOVER and FINISH_PLAN: it converts the standby into a transient logical standby, upgrades it, switches over, then puts everything back. It is the recommended method since 12c.",
    topic: "Rolling upgrade",
  },
  "dg-q36": {
    question: "Why offload RMAN backups to the physical standby?",
    options: [
      "Because the copy is block-for-block identical, so it can restore the primary",
      "Because RMAN cannot back up an open database",
      "Because the recovery catalog requires it",
      "Because the standby has more space",
    ],
    explanation: "A physical standby is a block-for-block replica: a backup taken from it restores the primary. Production is thereby relieved of the backup cost — one of Data Guard's immediate returns on investment.",
    topic: "Offloaded backup",
  },
  "dg-q37": {
    question: "Which NOLOGGING modes does 19c introduce to reconcile fast loads with a usable standby? (Choose two.)",
    options: [
      "STANDBY NOLOGGING FOR DATA AVAILABILITY",
      "STANDBY NOLOGGING FOR LOAD PERFORMANCE",
      "FORCE LOGGING FOR STANDBY",
      "NOLOGGING FOR REDO APPLY",
    ],
    explanation: "Both modes allow lightly logged loads while guaranteeing the standby stays usable: the first favours data availability, the second load speed.",
    topic: "19c NOLOGGING",
  },
  "dg-q38": {
    question: "A high transport lag together with a low apply lag indicates:",
    options: [
      "A network problem between the primary and the standby",
      "A standby that cannot apply fast enough",
      "Stale statistics",
      "An out-of-step password file",
    ],
    explanation: "Transport lag measures reception delay, apply lag application delay. A high transport lag alone points to the network: SDU, TCP buffers, redo compression. The reverse points to standby I/O.",
    topic: "Diagnosing lags",
  },
  "dg-q39": {
    question: "Which view gives the transport lag and the apply lag?",
    options: ["V$DATAGUARD_STATS", "V$DATAGUARD_STATUS", "V$MANAGED_STANDBY", "V$ARCHIVED_LOG"],
    explanation: "V$DATAGUARD_STATS exposes transport lag, apply lag and apply finish time. V$DATAGUARD_STATUS holds event messages, V$MANAGED_STANDBY the state of the transport and apply processes.",
    topic: "Monitoring",
  },
  "dg-q40": {
    question: "Which change on the primary requires MANUAL action on the standby? (Choose two.)",
    options: [
      "Adding a redo log group",
      "Changing the SYS password",
      "Adding a data file with STANDBY_FILE_MANAGEMENT = AUTO",
      "Creating a table",
    ],
    explanation: "Adding a redo group means adding a standby redo log too. Changing the SYS password means copying the password file across, otherwise transport stops with ORA-16191.",
    topic: "Structural changes",
  },
  "dg-q41": {
    question: "Which error signals an out-of-step password file between the two databases?",
    options: ["ORA-16191", "ORA-01017 only", "ORA-16000", "ORA-00600"],
    explanation: "ORA-16191 (“Primary log shipping client not logged on standby”) appears in the primary's alert log when the password file differs. It is the most frequent operational failure after a password rotation.",
    topic: "Troubleshooting",
  },
  "dg-q42": {
    question: "How do you ensure a service starts only on the database holding the PRIMARY role?",
    options: [
      "A service driven by a DB_ROLE_CHANGE trigger, or declared with srvctl -role PRIMARY",
      "A TNS alias pointing only at the primary",
      "A restricted user profile",
      "The SERVICE_NAMES parameter set statically",
    ],
    explanation: "A role-bound service starts automatically on the right side after a transition. A fixed TNS alias forces every client to be reconfigured; a static SERVICE_NAMES would start the service on both databases at once.",
    topic: "Client connectivity",
  },
  "dg-q43": {
    question: "What does Application Continuity add over TAF connection failover?",
    options: [
      "The driver replays the interrupted transaction on the new primary",
      "Reconnection is faster",
      "No service configuration is needed",
      "It works without Data Guard",
    ],
    explanation: "TAF reconnects the session, but the application still receives an error on the in-flight transaction. Application Continuity replays it transparently; it requires a FAILOVER_TYPE=TRANSACTION service and a compatible driver.",
    topic: "Application Continuity",
  },
  "dg-q44": {
    question: "Which command increases redo apply parallelism?",
    options: [
      "ALTER DATABASE RECOVER MANAGED STANDBY DATABASE PARALLEL 8 DISCONNECT",
      "ALTER SYSTEM SET parallel_degree_policy = AUTO",
      "ALTER DATABASE ADD STANDBY LOGFILE",
      "ALTER SYSTEM SET log_archive_max_processes = 8",
    ],
    explanation: "The PARALLEL clause of RECOVER MANAGED STANDBY DATABASE sets the number of apply processes. LOG_ARCHIVE_MAX_PROCESSES acts on archiving, not on apply at the standby.",
    topic: "Apply tuning",
  },
  "dg-q45": {
    question: "Which LOG_ARCHIVE_DEST_n attribute enables compression of the shipped redo?",
    options: ["COMPRESSION=ENABLE", "SYNC AFFIRM", "VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE)", "REOPEN=60"],
    explanation: "COMPRESSION=ENABLE cuts the volume shipped over a slow link; the attribute belongs to the Advanced Compression option. The other attributes control transport mode, role validity and retry delay respectively.",
    topic: "Redo transport",
  },
};
