import type { QuizQuestionTranslation } from "./types";

/**
 * English rendering of the 1Z0-083 bank (`quiz-data-ocp2.ts` + `-b.ts`).
 * Keyed by question id; option order preserved.
 */
export const ocp2English: Record<string, QuizQuestionTranslation> = {
  "ocp2-q1": {
    question: "Which items are shared by every PDB of the same CDB? (Choose three.)",
    options: ["The redo log files", "The control file", "The background processes and the SGA", "The SYSTEM tablespace", "The application data dictionary"],
    explanation: "The CDB provides a single instance — SGA, processes, redo logs, control file. Each PDB brings its own SYSTEM, SYSAUX and dictionary: that is what makes it transportable from one CDB to another.",
    topic: "CDB / PDB sharing",
  },
  "ocp2-q2": {
    question: "Which CON_ID identifies the PDB$SEED container?",
    options: ["0", "1", "2", "3"],
    explanation: "CON_ID 0 designates the CDB as a whole, 1 the CDB$ROOT, 2 the PDB$SEED, and user PDBs get 3 and above. PDB$SEED stays read-only: it is the template for new PDBs.",
    topic: "CON_ID",
  },
  "ocp2-q3": {
    question: "What does local undo mode (LOCAL_UNDO_ENABLED) make possible? (Choose three.)",
    options: ["Hot cloning of a PDB", "Flashback PDB", "Point-in-time recovery of a single PDB", "Sharing one undo tablespace across all PDBs", "Dropping the root's UNDO tablespace"],
    explanation: "Local undo gives each PDB its own undo tablespace, which enables hot cloning, Flashback PDB and isolated PITR. It is precisely the opposite of sharing a single undo, which is the legacy mode.",
    topic: "Local undo",
  },
  "ocp2-q4": {
    question: "From inside a PDB, what does a CDB_ view show?",
    options: ["Every container of the CDB", "The current container only", "The CDB$ROOT only", "Nothing: CDB_ views do not exist inside a PDB"],
    explanation: "CDB_ views exist everywhere, but from inside a PDB they return only the current container: the full picture is available from CDB$ROOT alone. The CON_ID column then tells the origins apart.",
    topic: "CDB_ views",
  },
  "ocp2-q5": {
    question: "Which commands reveal the current container? (Choose two.)",
    options: ["SHOW CON_NAME", "SELECT SYS_CONTEXT('USERENV','CON_NAME') FROM DUAL", "SHOW PARAMETER container", "SELECT container_name FROM v$database"],
    explanation: "SHOW CON_NAME is the SQL*Plus command, SYS_CONTEXT the equivalent queryable from any tool. V$PDBS and V$CONTAINERS complete the inventory; the other two proposals do not exist.",
    topic: "Current container",
  },
  "ocp2-q6": {
    question: "In which cases is the USER_TABLESPACES clause useful on a CREATE PLUGGABLE DATABASE? (Choose two.)",
    options: ["To bring across only a specific list of user tablespaces", "To exclude certain tablespaces during a non-CDB to PDB conversion", "To convert tablespaces to the target platform format", "To automatically encrypt the tablespaces brought across"],
    explanation: "USER_TABLESPACES accepts an explicit list or the ALL EXCEPT form. Excluded tablespaces are created offline and empty: the structure is there, the data is not. Platform conversion is RMAN CONVERT's job, encryption is TDE's.",
    topic: "USER_TABLESPACES",
  },
  "ocp2-q7": {
    question: "After plugging in a PDB, which view must always be queried?",
    options: ["V$PDBS", "PDB_PLUG_IN_VIOLATIONS", "CDB_PDBS", "DBA_REGISTRY"],
    explanation: "PDB_PLUG_IN_VIOLATIONS lists the discrepancies found at plug-in time: version, character set, installed options, parameters. An ERROR-level violation prevents a normal open and forces RESTRICTED mode until fixed.",
    topic: "Plug-in violations",
  },
  "ocp2-q8": {
    question: "Which clauses decide the fate of the data files when plugging in? (Choose three.)",
    options: ["COPY", "MOVE", "NOCOPY", "CONVERT", "MIRROR"],
    explanation: "COPY duplicates the files leaving the source intact — the default. MOVE relocates them. NOCOPY reuses them in place: fastest, but destructive if you pick the wrong manifest. CONVERT belongs to RMAN, MIRROR does not exist here.",
    topic: "Plugging in a PDB",
  },
  "ocp2-q9": {
    question: "Without SAVE STATE, what state are the PDBs in after a CDB STARTUP?",
    options: ["OPEN READ WRITE", "OPEN READ ONLY", "MOUNTED", "RESTRICTED"],
    explanation: "A CDB startup leaves the PDBs MOUNTED: you must open them explicitly, or have recorded their state with ALTER PLUGGABLE DATABASE … SAVE STATE. DBA_PDB_SAVED_STATES lists the recorded states.",
    topic: "SAVE STATE",
  },
  "ocp2-q10": {
    question: "Which statements are true about common objects in an application container? (Choose two.)",
    options: ["An object can be metadata-linked: shared structure, per-PDB data", "A common object can live in CDB$ROOT or in an application root", "A data-linked object is updatable from each application PDB", "SHARING = NONE shares the object with every PDB"],
    explanation: "SHARING = METADATA shares the definition, each PDB keeping its own rows. SHARING = DATA also shares the data, but read-only from the PDBs. Common objects live in CDB$ROOT or an application root. SHARING = NONE makes the object strictly local.",
    topic: "Application containers",
  },
  "ocp2-q11": {
    question: "Which function checks that a PDB can be plugged in before attempting the operation?",
    options: ["DBMS_PDB.CHECK_PLUG_COMPATIBILITY", "DBMS_TTS.TRANSPORT_SET_CHECK", "DBMS_PDB.DESCRIBE", "DBMS_SPACE.VERIFY"],
    explanation: "CHECK_PLUG_COMPATIBILITY evaluates the XML manifest and returns a boolean; the detail of the discrepancies is then read from PDB_PLUG_IN_VIOLATIONS. DBMS_PDB.DESCRIBE produces the manifest. TRANSPORT_SET_CHECK is about transportable tablespaces.",
    topic: "Plug-in compatibility",
  },
  "ocp2-q12": {
    question: "What is a refreshable clone? (Choose two.)",
    options: ["A PDB cloned from a remote source and periodically resynchronised", "It stays read-only between two refreshes", "It is open read-write at all times", "It requires the source to be shut down"],
    explanation: "REFRESH MODE EVERY n MINUTES — or MANUAL — keeps a clone aligned with its source through a database link. The PDB stays read-only between refreshes, which makes it an ideal reporting target without loading production.",
    topic: "Refreshable clone",
  },
  "ocp2-q13": {
    question: "Which statements are true about common users? (Choose three.)",
    options: ["They can only be created from CDB$ROOT", "Their name must start with C## or U##, apart from Oracle-supplied accounts", "They exist in every container of the CDB", "They can be created from any PDB", "They are automatically administrators of every PDB"],
    explanation: "A common user is created from the root with CONTAINER = ALL and carries the prefix imposed by COMMON_USER_PREFIX. It exists everywhere, but only holds the privileges explicitly granted — existing is not the same as being able.",
    topic: "Common users",
  },
  "ocp2-q14": {
    question: "A privilege is granted with CONTAINER = ALL. A PDB is plugged in afterwards. What happens?",
    options: ["The new PDB retroactively inherits the grant", "The grant must be replayed to apply to the new PDB", "The grant is automatically revoked everywhere", "The PDB refuses to open"],
    explanation: "CONTAINER = ALL only covers the containers existing at grant time: there is no retroactive effect. It is a frequent oversight after plugging in, showing up as missing privileges in the newly arrived PDB.",
    topic: "CONTAINER = ALL",
  },
  "ocp2-q15": {
    question: "What is the CONTAINER_DATA clause on a common user for?",
    options: ["To restrict which containers they see in CDB_ and V$ views", "To give them access to every tablespace", "To make them administrator of every container", "To encrypt their data"],
    explanation: "ALTER USER … SET CONTAINER_DATA = (…) limits the scope visible in the aggregation views. It is how you give an audit account a cross-container view restricted to a few PDBs only.",
    topic: "CONTAINER_DATA",
  },
  "ocp2-q16": {
    question: "Can a local user be created from CDB$ROOT?",
    options: ["Yes, with CONTAINER = CURRENT", "No: a local user must be created from its own PDB", "Yes, if it carries the C## prefix", "Yes, but only in RESTRICTED mode"],
    explanation: "From the root, only common users can be created. CONTAINER = CURRENT would mean the root itself, not a PDB. To create a local account you must first ALTER SESSION SET CONTAINER = the_pdb.",
    topic: "Local users",
  },
  "ocp2-q17": {
    question: "The read phase of a compressed incremental RMAN backup is a bottleneck. Which measures can improve throughput? (Choose two.)",
    options: ["Enable asynchronous disk I/O", "Raise the RMAN multiplexing level", "Disable FORCE LOGGING on the database", "Increase the buffer cache size"],
    explanation: "Multiplexing sets how many files a channel reads at once, and asynchronous I/O keeps the process from waiting on each read. FORCE LOGGING only affects redo generation, and the buffer cache does not serve RMAN reads, which bypass the SGA.",
    topic: "RMAN performance",
  },
  "ocp2-q18": {
    question: "What separates a differential incremental from a cumulative incremental?",
    options: ["The differential starts from the last level 0 or 1; the cumulative from the last level 0", "The cumulative starts from the last level 1; the differential from the last level 0", "The cumulative only backs up archived logs", "There is no practical difference"],
    explanation: "The differential — the default — backs up since the last level 0 or 1 incremental: fast to produce, slower to restore. The cumulative starts from the last level 0: bulkier, but it shortens restore since fewer files must be applied.",
    topic: "Incremental backups",
  },
  "ocp2-q19": {
    question: "What advantages does block change tracking bring? (Choose two.)",
    options: ["RMAN reads only the blocks flagged as changed during an incremental", "Incremental backup time drops sharply on large databases", "It removes the need for level 0 backups", "It automatically compresses backup sets"],
    explanation: "Without it, an incremental rescans the whole database to work out what changed. The tracking file lets RMAN go straight to the blocks concerned. A level 0 is still required as the base of the chain, and compression is a separate option.",
    topic: "Block change tracking",
  },
  "ocp2-q20": {
    question: "Which RMAN setting is the most critical for restoring a database whose control file is lost?",
    options: ["CONFIGURE BACKUP OPTIMIZATION ON", "CONFIGURE CONTROLFILE AUTOBACKUP ON", "CONFIGURE DEVICE TYPE DISK PARALLELISM 4", "CONFIGURE ENCRYPTION FOR DATABASE ON"],
    explanation: "Autobackup places a copy of the control file and SPFILE in a predictable location that RMAN can find without a catalogue or a control file: that is what makes RESTORE CONTROLFILE FROM AUTOBACKUP possible from NOMOUNT.",
    topic: "Autobackup",
  },
  "ocp2-q21": {
    question: "Which statements correctly contrast a backup set with an image copy? (Choose two.)",
    options: ["A backup set skips never-used blocks, an image copy does not", "An image copy is immediately usable through SWITCH, with no restore", "A backup set can be read with a plain operating-system command", "An image copy can be compressed with CONFIGURE COMPRESSION"],
    explanation: "A backup set is a compact proprietary format that omits empty blocks and can be compressed. An image copy is a block-for-block replica, immediately usable through SWITCH DATAFILE TO COPY — hence a very short time back in service.",
    topic: "Backup set and image copy",
  },
  "ocp2-q22": {
    question: "What does the sequence BACKUP INCREMENTAL LEVEL 1 FOR RECOVER OF COPY followed by RECOVER COPY OF DATABASE achieve?",
    options: ["An incrementally updated backup: an image copy kept continuously current", "A weekly full backup", "A purge of obsolete backups", "A block consistency check"],
    explanation: "The principle: an initial image copy, then a daily level 1 incremental applied onto that copy. You therefore always hold a recent image, restorable by a simple SWITCH — the best trade-off between space used and time to recover.",
    topic: "Incrementally updated backup",
  },
  "ocp2-q23": {
    question: "Which conditions are required for an open-database backup? (Choose two.)",
    options: ["The database must be in ARCHIVELOG mode", "The matching archived logs must be backed up together with the data", "The database must be in RESTRICTED mode", "Every PDB must be closed"],
    explanation: "A hot backup is inconsistent by nature: it is only usable together with the archived logs needed to roll redo forward to a consistent point. Hence the systematic PLUS ARCHIVELOG. Neither restricted mode nor closing the PDBs is required.",
    topic: "Hot backup",
  },
  "ocp2-q24": {
    question: "In which configurations is the Data Recovery Advisor unavailable? (Choose two.)",
    options: ["Real Application Clusters", "Data Guard standby database", "Single-instance database in ARCHIVELOG", "Multitenant container database"],
    explanation: "LIST FAILURE, ADVISE FAILURE and REPAIR FAILURE support neither RAC nor standby databases: on those configurations diagnosis becomes manual again. A single instance, multitenant included, benefits from it normally.",
    topic: "Data Recovery Advisor",
  },
  "ocp2-q25": {
    question: "Which sequence restores a database whose control files have all been lost?",
    options: ["STARTUP MOUNT, RESTORE CONTROLFILE, RECOVER DATABASE, OPEN", "STARTUP NOMOUNT, RESTORE CONTROLFILE FROM AUTOBACKUP, ALTER DATABASE MOUNT, RECOVER DATABASE, OPEN RESETLOGS", "STARTUP FORCE, RECOVER DATABASE, OPEN", "STARTUP RESTRICT, RESTORE DATABASE, OPEN"],
    explanation: "Without a control file the database cannot be mounted: you must start in NOMOUNT, restore the control file from autobackup, then mount, recover and open with RESETLOGS — the restored control file being older than the data.",
    topic: "Control file loss",
  },
  "ocp2-q26": {
    question: "Which statements are true about Block Media Recovery? (Choose two.)",
    options: ["It runs with the database open", "Only the corrupt blocks are unavailable during the operation", "It requires the data file to be taken offline", "It forces an OPEN RESETLOGS"],
    explanation: "RECOVER DATAFILE n BLOCK m — or RECOVER CORRUPTION LIST — repairs a few blocks without touching the rest: the database keeps serving, only the targeted blocks are unreachable meanwhile. It is the answer to ORA-01578.",
    topic: "Block media recovery",
  },
  "ocp2-q27": {
    question: "What consequences does an incomplete recovery have? (Choose two.)",
    options: ["It must end with ALTER DATABASE OPEN RESETLOGS", "It opens a new database incarnation, hence an immediate full backup", "It keeps every transaction up to the failure", "It can be done with the database open"],
    explanation: "Rewinding the database to an earlier point forces the logs to be reset: the sequence counter restarts, a new incarnation is born, and earlier backups become hard to use. Hence the immediate full backup.",
    topic: "Incomplete recovery",
  },
  "ocp2-q28": {
    question: "What is required to recover a single PDB to a point in time, without stopping the others? (Choose two.)",
    options: ["Local undo mode", "An AUXILIARY DESTINATION", "Closing every PDB of the CDB", "NOARCHIVELOG mode"],
    explanation: "PDB point-in-time recovery assumes the PDB owns its undo, and RMAN needs somewhere to build a temporary auxiliary instance. The other PDBs stay available throughout — which is the whole point of the approach.",
    topic: "PDB PITR",
  },
  "ocp2-q29": {
    question: "What does the RESTORE DATABASE PREVIEW command return?",
    options: ["The list of backups RMAN would use, without restoring anything", "A read-only restore", "The list of corrupt blocks", "A performance report on the last backup"],
    explanation: "PREVIEW simulates the restore and reports which backup sets and archived logs would be needed — including those to recall from tape. It is the check to run before any real operation. SUMMARY gives a condensed version.",
    topic: "RESTORE PREVIEW",
  },
  "ocp2-q30": {
    question: "Which Flashback technologies rely on undo? (Choose three.)",
    options: ["Flashback Query", "Flashback Version Query", "Flashback Transaction Query", "Flashback Database", "Flashback Drop"],
    explanation: "Query, Version Query, Transaction Query and Table draw on undo: their horizon is therefore bounded by UNDO_RETENTION. Flashback Database relies on the flashback logs in the recovery area, and Flashback Drop on the recycle bin.",
    topic: "Flashback dependencies",
  },
  "ocp2-q31": {
    question: "What must be enabled before running FLASHBACK TABLE … TO TIMESTAMP?",
    options: ["ARCHIVELOG mode", "ENABLE ROW MOVEMENT on the table", "The flashback logs", "Flashback Data Archive"],
    explanation: "Flashback Table reinserts rows at their earlier state, which changes their ROWID: row movement must therefore be allowed. Neither ARCHIVELOG nor the flashback logs are required — those are for Flashback Database.",
    topic: "Flashback Table",
  },
  "ocp2-q32": {
    question: "What advantages does a guaranteed restore point offer before a migration? (Choose two.)",
    options: ["The flashback logs are retained even if the recovery area fills up", "Rolling back is far faster than a full restore", "It removes the need for backups", "It works without ARCHIVELOG mode"],
    explanation: "CREATE RESTORE POINT … GUARANTEE FLASHBACK DATABASE guarantees the needed logs are kept, even at the cost of failing other operations if the FRA saturates — hence the need to watch the space. It replaces no backup whatsoever.",
    topic: "Guaranteed restore point",
  },
  "ocp2-q33": {
    question: "Which technology keeps a history spanning several years, beyond the undo retention?",
    options: ["Flashback Query", "Flashback Data Archive", "Flashback Drop", "Flashback Version Query"],
    explanation: "Flashback Data Archive — Total Recall — has its own history store, independent of undo, with a retention configurable in years. It is the answer to compliance and audit requirements.",
    topic: "Flashback Data Archive",
  },
  "ocp2-q34": {
    question: "Which clause recovers a dropped table, renaming it in the process?",
    options: ["FLASHBACK TABLE … TO BEFORE DROP RENAME TO …", "FLASHBACK TABLE … TO SCN … RENAME TO …", "RECOVER TABLE … RENAME TO …", "UNDROP TABLE … AS …"],
    explanation: "TO BEFORE DROP draws on the recycle bin; RENAME TO avoids a clash if a table of the same name has been recreated meanwhile. The operation fails if the drop used PURGE, or if the recycle bin has been emptied.",
    topic: "Flashback Drop",
  },
  "ocp2-q35": {
    question: "Which conditions must the auxiliary instance of an RMAN duplicate meet? (Choose three.)",
    options: ["Be started in NOMOUNT", "Have a password file", "Be reachable through the listener, generally via a static registration", "Be in ARCHIVELOG mode", "Already contain a copy of the data files"],
    explanation: "RMAN connects to an empty instance started in NOMOUNT, which implies password-file authentication and a listener able to reach it — hence the static entry, since PMON cannot advertise a database that is not mounted.",
    topic: "RMAN duplication",
  },
  "ocp2-q36": {
    question: "When is the NOFILENAMECHECK clause needed during a duplicate?",
    options: ["When source and target share the same file paths", "When the target is on a different platform", "When the database is in NOARCHIVELOG", "When the duplicate is active"],
    explanation: "RMAN refuses by default to write where source-database files already sit, to avoid overwriting it. On distinct servers sharing the same directory layout that check becomes pointless — hence NOFILENAMECHECK, to be used with care.",
    topic: "NOFILENAMECHECK",
  },
  "ocp2-q37": {
    question: "Which steps are essential when transporting a set of tablespaces? (Choose three.)",
    options: ["Check the set is self-contained with DBMS_TTS.TRANSPORT_SET_CHECK", "Set the tablespaces read only", "Export the metadata with TRANSPORT_TABLESPACES", "Switch the database to NOARCHIVELOG", "Drop every index involved"],
    explanation: "The set must be self-contained — no object referencing outside it — frozen read-only for the duration of the copy, and accompanied by its metadata exported through Data Pump. An RMAN conversion is added when the platforms differ in endianness.",
    topic: "Transportable tablespaces",
  },
  "ocp2-q38": {
    question: "Which view tells whether two platforms share the same byte order?",
    options: ["V$TRANSPORTABLE_PLATFORM", "V$DATABASE", "DBA_TABLESPACES", "V$CONTROLFILE"],
    explanation: "V$TRANSPORTABLE_PLATFORM maps each platform to its ENDIAN_FORMAT. If source and target formats differ, RMAN CONVERT becomes mandatory; if they match, a plain file copy is enough.",
    topic: "Endianness",
  },
  "ocp2-q39": {
    question: "What does the Oracle Database preinstall RPM do? (Choose three.)",
    options: ["It creates the system accounts and groups, oinstall among them", "It sets the kernel parameters and resource limits", "It prepares the configuration needed to reach ASM devices", "It installs the Oracle Database software", "It automatically creates a database"],
    explanation: "The preinstall RPM prepares the system: oracle account and oinstall/dba groups, sysctl parameters, limits, dependencies, ASM permissions. It installs neither the software — that is runInstaller — nor the database — that is DBCA.",
    topic: "Preinstallation",
  },
  "ocp2-q40": {
    question: "You applied a Release Update with opatch. The database starts but objects are invalid. What did you skip?",
    options: ["Running datapatch to apply the SQL part of the patch", "Re-running opatch with the -force option", "Recreating the SPFILE", "Putting the database in UPGRADE mode"],
    explanation: "opatch changes the binaries, datapatch brings the dictionary in line with them. Skipping datapatch is the most common mistake after a patch. You then run utlrp.sql to recompile, and check DBA_REGISTRY_SQLPATCH.",
    topic: "opatch and datapatch",
  },
  "ocp2-q41": {
    question: "Which statements are true about Oracle Restart? (Choose two.)",
    options: ["It automatically restarts the instance, the listener and ASM after a failure", "Resources must be managed with srvctl rather than manually", "It provides automatic failover between cluster nodes", "It replaces RMAN backups"],
    explanation: "Oracle Restart watches and restarts components on a single server. A manual stop through SQL*Plus or lsnrctl would be read as a failure and followed by an immediate restart: hence the exclusive use of srvctl. Multi-node failover belongs to RAC.",
    topic: "Oracle Restart",
  },
  "ocp2-q42": {
    question: "How do you upgrade a single application hosted in a PDB, without touching the others?",
    options: ["Unplug the PDB and plug it into a CDB of a higher version", "Run dbupgrade on the whole CDB", "Recreate the PDB from PDB$SEED", "It is not possible in multitenant"],
    explanation: "This is one of multitenant's great strengths: the unit of migration becomes the PDB. You unplug it from the old CDB, plug it into an already-upgraded one, then datapatch brings its dictionary in line. The other PDBs are untouched.",
    topic: "Selective upgrade",
  },
  "ocp2-q43": {
    question: "Which view lists the SQL patches actually applied to the dictionary?",
    options: ["DBA_REGISTRY_SQLPATCH", "DBA_REGISTRY", "V$PATCHES", "DBA_OBJECTS"],
    explanation: "DBA_REGISTRY_SQLPATCH records what datapatch actually applied, with the action and status. opatch lsinventory only accounts for the binary side: comparing the two reveals a forgotten datapatch.",
    topic: "Patch tracking",
  },
  "ocp2-q44": {
    question: "Which statements are true about thresholds, metrics and alerts? (Choose three.)",
    options: ["Cleared stateful alerts can be found in DBA_ALERT_HISTORY", "A space usage alert clears automatically once the cause is gone", "A metric is a statistical count expressed per unit", "Alerts are generated by SMON when a tablespace reaches 97%", "STATISTICS_LEVEL must be ALL for alerts to work"],
    explanation: "Alerts are produced by MMON, not SMON. Stateful alerts leave DBA_OUTSTANDING_ALERTS for DBA_ALERT_HISTORY as soon as the cause is gone. STATISTICS_LEVEL at TYPICAL — the default — is enough; ALL is not required.",
    topic: "Alerts and metrics",
  },
  "ocp2-q45": {
    question: "Which statements are true about ADDM? (Choose two.)",
    options: ["It runs automatically after every AWR snapshot", "It can be launched manually over any pair of snapshots", "It replaces optimizer statistics gathering", "It only works in RESTRICTED mode"],
    explanation: "ADDM analyses the interval between two AWR snapshots and ranks problems by impact, offering recommendations. It fires by itself after each snapshot, and can be re-run on demand through addmrpt.sql or DBMS_ADDM.",
    topic: "ADDM",
  },
  "ocp2-q46": {
    question: "What is the most common cause of a suddenly inefficient execution plan?",
    options: ["Missing or stale optimizer statistics", "An oversized buffer cache", "ARCHIVELOG mode", "Too many redo log groups"],
    explanation: "The optimizer reasons on statistics: stale ones lead it to misjudge cardinalities and therefore pick a poor plan. Gather with DBMS_STATS before blaming the optimizer, then freeze the good plan through SQL Plan Management.",
    topic: "Statistics and plans",
  },
  "ocp2-q47": {
    question: "What is the difference between AWR and ASH? (Choose two.)",
    options: ["AWR keeps periodic snapshots of cumulative statistics", "ASH samples active sessions once per second", "ASH has replaced AWR since release 19c", "AWR is only available in multitenant"],
    explanation: "AWR photographs activity at regular intervals — hourly by default — and keeps the history in SYSAUX. ASH samples active sessions continuously, which lets you analyse a brief incident an AWR snapshot would have smoothed away. The two complement each other.",
    topic: "AWR and ASH",
  },
  "ocp2-q48": {
    question: "How do you stop a validated execution plan from regressing after an upgrade?",
    options: ["By creating an accepted baseline through SQL Plan Management", "By deleting all statistics", "By disabling the cost-based optimizer", "By putting the database in RESTRICTED mode"],
    explanation: "SQL Plan Management keeps a set of accepted plans per statement: the optimizer may only adopt a new plan once it has proven it better. It is the standard safety net before any upgrade.",
    topic: "SQL Plan Management",
  },

  // ─── quiz-data-ocp2-b ───────────────────────────────────────────────────
  "ocp2-q50": {
    question: "Which views are used to monitor wait events? (Choose three.)",
    options: ["V$SESSION_EVENT", "V$SERVICE_EVENT", "V$SESSION_WAIT", "V$CONTROLFILE", "V$LOGFILE"],
    explanation: "V$SESSION_EVENT accumulates a session's waits since connect time, V$SESSION_WAIT gives the current wait, V$SERVICE_EVENT aggregates by service. The last two views describe files, unrelated to waits.",
    topic: "Wait views",
  },
  "ocp2-q51": {
    question: "Which statements are true about stateless alerts? (Choose two.)",
    options: ["They can be cleared manually", "They can be cleared automatically after a delay", "They disappear as soon as their cause ends", "They never appear in DBA_ALERT_HISTORY"],
    explanation: "A stateless alert describes a one-off event — a log switch, a corruption — with no persistent cause to disappear. It goes straight to the history, where it is purged manually or by the retention policy.",
    topic: "Stateless alerts",
  },
  "ocp2-q52": {
    question: "Excessive hard parsing is observed. Which advisor should be consulted first?",
    options: ["The Memory Advisor for the shared pool", "The Segment Advisor", "The Undo Advisor", "The SQL Access Advisor"],
    explanation: "Excessive hard parsing points to an undersized shared pool — or to statements that cannot be shared for lack of bind variables. The Memory Advisor quantifies the gain expected from a larger shared pool.",
    topic: "Memory Advisor",
  },
  "ocp2-q53": {
    question: "Which statements are true about the Statistics Advisor? (Choose three.)",
    options: ["It is part of the DBMS_ADVISOR package", "It makes recommendations about statistics gathering", "It runs automatically every night", "It replaces DBMS_STATS", "It only works in multitenant"],
    explanation: "Introduced in 12.2, the Statistics Advisor analyses how statistics are gathered and flags departures from best practice. It runs in the nightly maintenance window, but gathers nothing itself: DBMS_STATS still does the work.",
    topic: "Statistics Advisor",
  },
  "ocp2-q54": {
    question: "Which statements are true about SQL Performance Analyzer? (Choose two.)",
    options: ["It predicts the impact of a change on a captured set of statements", "It provides a before/after comparison, statement by statement", "It applies the corrections automatically", "It replaces SQL Plan Management baselines"],
    explanation: "SPA replays a SQL Tuning Set before and after a change — upgrade, parameter, statistics — and classifies statements by regression or improvement. It observes; the administrator decides, possibly freezing a plan through a baseline.",
    topic: "SQL Performance Analyzer",
  },
  "ocp2-q55": {
    question: "Which statements correctly describe a tuning approach driven by the Oracle time model? (Choose two.)",
    options: ["The time model helps identify the most rewarding tuning targets", "Tuning should stop once the service levels are met", "Tuning should continue until the CPU saturates", "The time model replaces AWR"],
    explanation: "The Time Model breaks down where the database spends its time and points at the dominant component. The stopping rule is contractual: once the SLAs hold, going further costs more than it returns.",
    topic: "Time model",
  },
  "ocp2-q56": {
    question: "Which statements are true about gathering statistics in multitenant? (Choose two.)",
    options: ["From CDB$ROOT, gathering covers every open PDB, excluding PDB$SEED", "From a PDB open read-write, gathering covers that PDB only", "PDB$SEED is always included", "Gathering is only possible from the root"],
    explanation: "DBMS_STATS works within the current container's scope. Launched from the root it walks the open PDBs — the seed, being read-only, is excluded. Launched from a PDB it stays local.",
    topic: "Statistics and containers",
  },
  "ocp2-q57": {
    question: "LOCAL_UNDO_ENABLED is set to FALSE. What are the consequences? (Choose two.)",
    options: ["Every PDB, new and existing, uses the CDB$ROOT undo", "PDBs already open must be closed and reopened for the change to take effect", "Each PDB keeps its own undo tablespace", "The change is immediate, with no reopening"],
    explanation: "The undo mode is a CDB property, changed in UPGRADE mode. Reverting to shared undo sends every PDB back to the root's undo, and each must be reopened to take it into account — at the cost of losing isolated PITR and hot cloning.",
    topic: "Switching undo mode",
  },
  "ocp2-q58": {
    question: "Which statements are true about the XML manifest produced by an unplug? (Choose two.)",
    options: ["Its compatibility must be checked with DBMS_PDB.CHECK_PLUG_COMPATIBILITY", "It does not necessarily hold the current location of the data files", "It contains a copy of the PDB's data", "It makes the data files unnecessary"],
    explanation: "The manifest only describes metadata: version, character set, options, file list. If those files have since been moved, the paths it carries are stale — hence the SOURCE_FILE_NAME_CONVERT and FILE_NAME_CONVERT clauses at plug-in time.",
    topic: "Unplug manifest",
  },
  "ocp2-q59": {
    question: "Which statements are true about managing parallelism across PDBs? (Choose two.)",
    options: ["An unlimited PDB can take every parallel process of the CDB", "A minimum share can be guaranteed to a PDB by the Resource Manager", "Parallelism is split evenly by default", "Parallelism is disabled in multitenant"],
    explanation: "With no resource plan, a greedy PDB can consume all the parallelism and starve the others. The CDB Resource Plan assigns shares and limits — the tool for isolating performance between tenants.",
    topic: "Resource Manager in a CDB",
  },
  "ocp2-q60": {
    question: "A data file of PDB2 must be restored. Which conditions allow the operation? (Choose two.)",
    options: ["The CDB can stay open", "PDB2 must be closed", "Every PDB must be closed", "The CDB must be in NOMOUNT"],
    explanation: "This is multitenant's operational strength: only the PDB concerned stops, while the CDB and the other tenants keep serving. A critical file of the root would, however, force a complete shutdown.",
    topic: "Restoring a PDB",
  },
  "ocp2-q61": {
    question: "Which statements are true about duplexing a backup set? (Choose two.)",
    options: ["A set written to disk can be duplexed to another disk location", "A set can be duplexed from disk to tape", "Duplexing applies to image copies", "Duplexing doubles the read time on the source"],
    explanation: "BACKUP COPIES, or CONFIGURE DATAFILE BACKUP COPIES, produces several copies from a single read of the source — hence a cost far below two successive backups. Duplexing only applies to backup sets, not image copies.",
    topic: "Duplexing",
  },
  "ocp2-q62": {
    question: "Which statements are true about BACKUP RECOVERY FILES? (Choose two.)",
    options: ["It backs up the recovery files of the FRA not yet backed up", "The destination can be disk or an SBT device", "It empties the FRA", "It only covers control files"],
    explanation: "The command sweeps the fast recovery area and backs up whatever is not already backed up: archived logs, copies, backup sets. It is the usual way to move the FRA out to tape before purging its obsolete content.",
    topic: "BACKUP RECOVERY FILES",
  },
  "ocp2-q63": {
    question: "Which statements are true about RMAN configuration and the fast recovery area? (Choose three.)",
    options: ["The persistent RMAN configuration is stored in the control file", "Backups that have become obsolete in the FRA are deleted automatically when space runs short", "A retention policy must be defined for obsolescence to mean anything", "The FRA deletes backups as soon as they become obsolete, without waiting", "The RMAN configuration is stored in the SPFILE"],
    explanation: "The configuration lives in the control file — hence the importance of its autobackup. The FRA does not purge proactively: it waits for space pressure, then deletes first what the retention policy marks as obsolete.",
    topic: "FRA and retention",
  },
  "ocp2-q64": {
    question: "When are the flashback logs deleted?",
    options: ["After the retention window expires, proactively and before any space pressure", "Only when the recovery area is full", "At every instance restart", "Never, apart from a manual deletion"],
    explanation: "Unlike obsolete backups, flashback logs beyond DB_FLASHBACK_RETENTION_TARGET are deleted without waiting for saturation. Only a guaranteed restore point prevents that purge — hence the risk of filling the FRA if you forget it.",
    topic: "Flashback log purge",
  },
  "ocp2-q65": {
    question: "What do the timings reported by RMAN's VALIDATE command reveal? (Choose two.)",
    options: ["They tell whether the bottleneck sits in reading or in writing", "A high SHORT_WAITS value suggests an asynchronous I/O problem", "They measure the compression ratio", "They report the number of corrupt blocks only"],
    explanation: "V$BACKUP_ASYNC_IO and V$BACKUP_SYNC_IO break the time down between read, validate and write. A high count of short waits shows asynchronous I/O is not working as intended and the process is spinning.",
    topic: "RMAN diagnostics",
  },
  "ocp2-q66": {
    question: "Which statements are true about RMAN CONVERT during a cross-platform transport? (Choose three.)",
    options: ["The conversion can run on the source platform", "The conversion can run on the destination platform", "It is required when the two platforms differ in byte order", "It is required even between platforms of the same endianness", "It also converts the character set"],
    explanation: "CONVERT runs on either side, as you choose — often on the less loaded machine. It only has a purpose when endianness differs; otherwise a raw copy is enough. The character set, meanwhile, must be compatible from the outset.",
    topic: "RMAN CONVERT",
  },
  "ocp2-q67": {
    question: "Which statements are true about RMAN duplication? (Choose three.)",
    options: ["It can work in pull mode, the auxiliary pulling the data", "It can work in push mode, the source pushing the data", "It can duplicate only a subset of the database", "It requires the source database to be shut down", "It requires the target to carry the same name as the source"],
    explanation: "Active duplication accepts both transfer directions, push mode making better use of bandwidth on fast links. SKIP TABLESPACE and TABLESPACE narrow the scope. The source stays open, and the target carries a distinct name.",
    topic: "Duplication modes",
  },
  "ocp2-q68": {
    question: "Which statements are true about opatchauto? (Choose three.)",
    options: ["It applies patches across the Grid Infrastructure and database stack", "It operates in non-rolling mode by default", "It can apply one-off patches", "It replaces datapatch", "It only works on a standalone database"],
    explanation: "opatchauto orchestrates the application across the whole stack, stopping the services concerned — hence non-rolling by default, rolling having to be requested and only making sense in a cluster. It never removes the need for datapatch on the SQL side.",
    topic: "opatchauto",
  },
  "ocp2-q69": {
    question: "Which statements are true about installation accounts and groups? (Choose two.)",
    options: ["The owner's primary group must be the Oracle Inventory group (oinstall)", "The Grid owner holds the Oracle Restart and ASM binaries", "The database owner must be root", "A single account can hold every installation, with no dedicated group"],
    explanation: "oinstall as primary group ensures the central inventory stays reachable by every installation. Role separation — one grid account, one oracle account — is the recommended setup. root is only used for post-installation scripts.",
    topic: "Installation accounts",
  },
  "ocp2-q70": {
    question: "Which statements are true about a silent installation? (Choose two.)",
    options: ["Running orainstRoot.sh can be automated through sudo or root", "The sudo password can be supplied in the response file", "The response file stores database passwords in clear text, harmlessly", "A silent installation cannot create a database"],
    explanation: "The response file accepts privilege-escalation parameters, which allows a fully automated installation. It does however hold secrets: it must be protected and then deleted after use.",
    topic: "Silent installation",
  },
  "ocp2-q71": {
    question: "What does the rhpctl move database command allow? (Choose two.)",
    options: ["Switching a database to a newer version", "Switching a database to an already-patched home", "Moving the data files to another disk", "Converting a non-CDB into a PDB"],
    explanation: "Rapid Home Provisioning moves a database from one Oracle Home to another — an upgrade or a patched home — reducing downtime and keeping a rollback available. It touches neither the data files nor the multitenant architecture.",
    topic: "Rapid Home Provisioning",
  },
  "ocp2-q72": {
    question: "Which environment variables come into play before installation? (Choose three.)",
    options: ["ORACLE_BASE, which sets the root of the OFA tree", "TNS_ADMIN, which locates the Oracle Net configuration files", "ORACLE_HOME, which designates the binaries", "DB_RECOVERY_FILE_DEST, which defines the FRA", "UNDO_TABLESPACE, which names the undo tablespace"],
    explanation: "These three variables belong to the operating system and come before installation. The last two proposals are database initialization parameters, set much later.",
    topic: "Environment variables",
  },
  "ocp2-q73": {
    question: "Which statements are true about choosing a character set? (Choose two.)",
    options: ["A single-byte set performs better in storage and processing", "Unicode (AL32UTF8) can store every language", "The character set is easy to change after creation", "A single-byte set is enough for a multilingual application"],
    explanation: "AL32UTF8 is the default choice and the only viable one for multilingual data, at the cost of a variable 1 to 4 bytes per character. Changing it afterwards is a heavy, risky operation: the decision is made at creation time.",
    topic: "Character sets",
  },
};
