import type { QuizQuestion } from "./types";

/**
 * Banque anglaise 1Z0-071 — domaines officiels 9 à 16.
 *
 * Suite de `lib/quiz-data-en-oca.ts`. Mêmes règles : libellé officiel du
 * domaine comme sujet, module réellement correspondant, explication qui
 * justifie la clé *et* écarte les distracteurs, position de bonne réponse
 * variée, questions multi-réponses là où l'examen en pose.
 */
export const enOcaQuestionsB: QuizQuestion[] = [
  // ══════════ 9. Using SET Operators (m8) ══════════
  {
    id: "en-oca-q81", moduleId: "m8",
    question: "Which set operator combines two result sets and removes duplicates?",
    options: ["UNION ALL", "UNION", "INTERSECT", "MINUS"],
    correctIndexes: [1],
    explanation: "UNION eliminates duplicates, which forces a sort and therefore costs more. UNION ALL keeps everything and is faster; INTERSECT returns the common rows and MINUS the difference.",
    topic: "Using SET Operators", difficulty: "easy",
  },
  {
    id: "en-oca-q82", moduleId: "m8",
    question: "Why is UNION ALL usually faster than UNION?",
    options: [
      "It reads fewer rows",
      "It uses an index that UNION cannot",
      "It performs no deduplication and therefore no sort",
      "It runs the two queries in parallel",
    ],
    correctIndexes: [2],
    explanation: "UNION must sort or hash to detect duplicates; UNION ALL simply concatenates. Both read the same rows, and parallelism depends on the plan, not on the operator.",
    topic: "Using SET Operators", difficulty: "medium",
  },
  {
    id: "en-oca-q83", moduleId: "m8",
    question: "Which operator returns the rows present in the first query but absent from the second?",
    options: ["INTERSECT", "UNION", "EXCEPT", "MINUS"],
    correctIndexes: [3],
    explanation: "Oracle spells the difference operator MINUS; EXCEPT is the ANSI name accepted only from 21c onwards. INTERSECT returns the common rows and UNION the combination.",
    topic: "Using SET Operators", difficulty: "medium",
  },
  {
    id: "en-oca-q84", moduleId: "m8",
    question: "Which two conditions must the SELECT lists of a set operation satisfy? (Choose two.)",
    options: [
      "The same number of columns",
      "Identical column names",
      "Compatible data types, position by position",
      "The same table in FROM",
    ],
    correctIndexes: [0, 2],
    explanation: "Only the count and the positional type compatibility matter. The names may differ — the result takes those of the first query — and the sources are free, which is the whole point of a set operation.",
    topic: "Using SET Operators", difficulty: "medium",
  },
  {
    id: "en-oca-q85", moduleId: "m8",
    question: "Where must ORDER BY appear in a compound query?",
    options: [
      "After each SELECT",
      "It is forbidden in a compound query",
      "Before the set operator",
      "Once only, at the very end",
    ],
    correctIndexes: [3],
    explanation: "A single ORDER BY closes the whole compound query and sorts the combined result. Placing one inside a branch raises ORA-00933, since each branch produces an intermediate set with no ordering of its own.",
    topic: "Using SET Operators", difficulty: "hard",
  },
  {
    id: "en-oca-q86", moduleId: "m8",
    question: "Which set operators are commutative — A op B gives the same rows as B op A? (Choose two.)",
    options: ["UNION", "MINUS", "INTERSECT", "UNION ALL"],
    correctIndexes: [0, 2],
    explanation: "UNION and INTERSECT are commutative. MINUS is not, since the difference depends on which side comes first. UNION ALL returns the same rows either way but in a different order, so it is not commutative as a sequence.",
    topic: "Using SET Operators", difficulty: "hard",
  },
  {
    id: "en-oca-q87", moduleId: "m8",
    question: "How do you sort a compound query when the branches use different column names?",
    options: [
      "By the column name of the first query, or by its position",
      "By the column name of the second query",
      "Sorting is impossible in that case",
      "By using an alias in each branch",
    ],
    correctIndexes: [0],
    explanation: "The result takes the headings of the first query, so ORDER BY uses those names — or a positional number, which sidesteps the question entirely. An alias defined in a later branch is not visible to the final ORDER BY.",
    topic: "Using SET Operators", difficulty: "hard",
  },
  {
    id: "en-oca-q88", moduleId: "m8",
    question: "Which operation best finds the identifiers present in both a current table and an archive table?",
    options: ["UNION", "MINUS", "INTERSECT", "A CROSS JOIN"],
    correctIndexes: [2],
    explanation: "INTERSECT returns exactly the rows common to both sets. A join could do the job but would also multiply rows on duplicates, whereas INTERSECT deduplicates by construction.",
    topic: "Using SET Operators", difficulty: "medium",
  },

  // ══════════ 10. Managing Tables using DML statements (m9) ══════════
  {
    id: "en-oca-q89", moduleId: "m9",
    question: "Which statement adds rows to a table?",
    options: ["UPDATE", "ALTER", "INSERT", "GRANT"],
    correctIndexes: [2],
    explanation: "INSERT is the only DML statement that creates rows. UPDATE modifies existing ones, ALTER is DDL and acts on the table's structure, and GRANT is DCL and acts on privileges.",
    topic: "Managing Tables using DML statements", difficulty: "easy",
  },
  {
    id: "en-oca-q90", moduleId: "m9",
    question: "What does DELETE without a WHERE clause do?",
    options: [
      "It deletes every row, and the operation can be rolled back",
      "It deletes every row and cannot be rolled back",
      "It deletes the table",
      "It raises an error",
    ],
    correctIndexes: [0],
    explanation: "DELETE is DML: it generates undo, so a ROLLBACK restores the rows. TRUNCATE, by contrast, is DDL — it commits implicitly and cannot be undone.",
    topic: "Managing Tables using DML statements", difficulty: "medium",
  },
  {
    id: "en-oca-q91", moduleId: "m9",
    question: "Which two differences separate DELETE from TRUNCATE? (Choose two.)",
    options: [
      "DELETE can be rolled back, TRUNCATE cannot",
      "TRUNCATE lowers the high water mark, DELETE does not",
      "DELETE is faster on a large table",
      "TRUNCATE accepts a WHERE clause",
    ],
    correctIndexes: [0, 1],
    explanation: "TRUNCATE is DDL: it commits implicitly, releases the extents and resets the high water mark, which is what makes it fast and irreversible. It takes no WHERE clause — it is all or nothing.",
    topic: "Managing Tables using DML statements", difficulty: "hard",
  },
  {
    id: "en-oca-q92", moduleId: "m9",
    question: "What is a SAVEPOINT?",
    options: [
      "An automatic backup of the table",
      "A named marker inside a transaction that ROLLBACK TO can return to",
      "A partial commit of the changes",
      "A lock placed on the modified rows",
    ],
    correctIndexes: [1],
    explanation: "A savepoint marks a point in the transaction; ROLLBACK TO SAVEPOINT undoes only what followed it, and the transaction stays open. Nothing is committed, and no backup is taken.",
    topic: "Managing Tables using DML statements", difficulty: "medium",
  },
  {
    id: "en-oca-q93", moduleId: "m9",
    question: "Why does a ROLLBACK issued after a CREATE TABLE fail to undo the INSERTs that preceded it?",
    options: [
      "Because the INSERTs were made in a different session",
      "Because CREATE TABLE deletes the undo",
      "Because ROLLBACK only works on the last statement",
      "Because DDL issues an implicit COMMIT before and after it runs",
    ],
    correctIndexes: [3],
    explanation: "Every DDL statement commits implicitly, both before and after execution. The pending INSERTs were therefore committed for good the moment CREATE TABLE ran, and the later ROLLBACK has nothing left to undo.",
    topic: "Managing Tables using DML statements", difficulty: "hard",
  },
  {
    id: "en-oca-q94", moduleId: "m9",
    question: "Which statement inserts the result of a query into a table?",
    options: [
      "INSERT INTO t VALUES (SELECT ...)",
      "INSERT INTO t SELECT ...",
      "INSERT t FROM SELECT ...",
      "COPY INTO t FROM SELECT ...",
    ],
    correctIndexes: [1],
    explanation: "The subquery replaces the VALUES clause entirely; the two are mutually exclusive, so the first option is a syntax error. The other two are not Oracle SQL.",
    topic: "Managing Tables using DML statements", difficulty: "medium",
  },
  {
    id: "en-oca-q95", moduleId: "m9",
    question: "Which statement synchronizes a target table with a source in a single pass?",
    options: ["UPSERT", "MERGE", "REPLACE INTO", "SYNC"],
    correctIndexes: [1],
    explanation: "MERGE reads the source once and applies WHEN MATCHED THEN UPDATE or WHEN NOT MATCHED THEN INSERT. UPSERT and REPLACE INTO belong to other dialects, and SYNC is not SQL.",
    topic: "Managing Tables using DML statements", difficulty: "medium",
  },
  {
    id: "en-oca-q96", moduleId: "m9",
    question: "Which MERGE branch updates the rows that already exist in the target?",
    options: ["WHEN NOT MATCHED THEN INSERT", "ON MATCHED UPDATE", "WHEN MATCHED THEN UPDATE", "WHEN EXISTS THEN UPDATE"],
    correctIndexes: [2],
    explanation: "WHEN MATCHED THEN UPDATE handles rows found by the ON condition; WHEN NOT MATCHED THEN INSERT handles the rest. The other two forms do not parse.",
    topic: "Managing Tables using DML statements", difficulty: "medium",
  },
  {
    id: "en-oca-q97", moduleId: "m9",
    question: "Which feature inserts rows into several target tables from one source query?",
    options: [
      "A multitable INSERT, with INSERT ALL or INSERT FIRST",
      "A MERGE with several WHEN clauses",
      "A UNION of several INSERTs",
      "A cursor loop",
    ],
    correctIndexes: [0],
    explanation: "INSERT ALL feeds every matching branch, INSERT FIRST stops at the first one that matches — both read the source a single time. MERGE writes to one target only, and UNION combines queries, not DML.",
    topic: "Managing Tables using DML statements", difficulty: "hard",
  },
  {
    id: "en-oca-q98", moduleId: "m9",
    question: "Which two statements end a transaction? (Choose two.)",
    options: ["COMMIT", "SAVEPOINT", "ROLLBACK", "SET TRANSACTION"],
    correctIndexes: [0, 2],
    explanation: "COMMIT makes the changes permanent and ROLLBACK discards them; both release the locks and close the transaction. SAVEPOINT marks a point inside it, and SET TRANSACTION configures the one about to begin.",
    topic: "Managing Tables using DML statements", difficulty: "medium",
  },

  // ══════════ 11. Use DDL to manage tables and their relationships (m10) ══════════
  {
    id: "en-oca-q99", moduleId: "m10",
    question: "Which clause of CREATE TABLE supplies a value when the column is omitted on INSERT?",
    options: ["NOT NULL", "CHECK", "DEFAULT", "IDENTITY"],
    correctIndexes: [2],
    explanation: "DEFAULT applies when the column is absent from the INSERT — but not when an explicit NULL is supplied, which is a classic trap. NOT NULL forbids the absence of a value without providing one.",
    topic: "Use DDL to manage tables and their relationships", difficulty: "medium",
  },
  {
    id: "en-oca-q100", moduleId: "m10",
    question: "Which DEFAULT clause is syntactically correct?",
    options: [
      "qty NUMBER DEFAULT = 1",
      "qty NUMBER = DEFAULT 1",
      "qty NUMBER DEFAULT '1' NOT NULL ONLY",
      "qty NUMBER DEFAULT 1",
    ],
    correctIndexes: [3],
    explanation: "DEFAULT is followed directly by the expression, with no equals sign — the sign is the most frequent error. A character literal must use single quotes; double quotes would designate an identifier.",
    topic: "Use DDL to manage tables and their relationships", difficulty: "medium",
  },
  {
    id: "en-oca-q101", moduleId: "m10",
    question: "What does ALTER TABLE ... SET UNUSED do to a column?",
    options: [
      "It deletes it immediately and frees the space",
      "It makes it invisible and unusable, without freeing the space",
      "It renames it",
      "It makes it read-only",
    ],
    correctIndexes: [1],
    explanation: "SET UNUSED is instantaneous because it only marks the column in the dictionary; the data stays on disk until DROP UNUSED COLUMNS. It is the way to retire a column from a large table without a long-running operation.",
    topic: "Use DDL to manage tables and their relationships", difficulty: "hard",
  },
  {
    id: "en-oca-q102", moduleId: "m10",
    question: "Which two operations does ALTER TABLE ... MODIFY allow on a populated column? (Choose two.)",
    options: [
      "Increasing the size of a VARCHAR2",
      "Reducing the size below the longest stored value",
      "Adding a NOT NULL constraint when no row is NULL",
      "Changing NUMBER to DATE while data is present",
    ],
    correctIndexes: [0, 2],
    explanation: "Widening is always allowed, and NOT NULL can be added provided the existing data satisfies it. Narrowing below the stored data raises ORA-01441, and an incompatible type change requires an empty column.",
    topic: "Use DDL to manage tables and their relationships", difficulty: "hard",
  },
  {
    id: "en-oca-q103", moduleId: "m10",
    question: "What is the difference between a global temporary table's ON COMMIT DELETE ROWS and ON COMMIT PRESERVE ROWS?",
    options: [
      "The first empties on COMMIT, the second at the end of the session",
      "The first empties at the end of the session, the second on COMMIT",
      "The first is transaction-scoped, the second is not persistent at all",
      "There is none, both empty on COMMIT",
    ],
    correctIndexes: [0],
    explanation: "DELETE ROWS scopes the data to the transaction, PRESERVE ROWS to the session. In both cases the structure is permanent and shared, while the data remains private to each session.",
    topic: "Use DDL to manage tables and their relationships", difficulty: "hard",
  },
  {
    id: "en-oca-q104", moduleId: "m10",
    question: "What is an external table?",
    options: [
      "A table stored in another schema",
      "A table without any constraint",
      "A table replicated to another database",
      "A table whose data stays in an operating-system file, read at query time",
    ],
    correctIndexes: [3],
    explanation: "An external table exposes a flat file as read-only rows; nothing is loaded into the database and no DML is possible. It is the usual way to query a delivered file before loading it.",
    topic: "Use DDL to manage tables and their relationships", difficulty: "hard",
  },
  {
    id: "en-oca-q105", moduleId: "m10",
    question: "Which constraint can be defined at column level as well as at table level?",
    options: [
      "NOT NULL",
      "A composite PRIMARY KEY",
      "UNIQUE on a single column",
      "A FOREIGN KEY spanning two columns",
    ],
    correctIndexes: [2],
    explanation: "A single-column UNIQUE can be written either way. NOT NULL exists only at column level, and any constraint spanning several columns — composite primary or foreign key — must be declared at table level.",
    topic: "Use DDL to manage tables and their relationships", difficulty: "hard",
  },
  {
    id: "en-oca-q106", moduleId: "m10",
    question: "What does ON DELETE CASCADE do on a foreign key?",
    options: [
      "It forbids deleting the parent row",
      "It sets the child key to NULL",
      "It defers the constraint check",
      "It deletes the child rows along with the parent row",
    ],
    correctIndexes: [3],
    explanation: "CASCADE propagates the deletion to the children. ON DELETE SET NULL nulls the child key instead, and the default — no clause at all — blocks the deletion with ORA-02292.",
    topic: "Use DDL to manage tables and their relationships", difficulty: "medium",
  },

  // ══════════ 12. Managing Views (m13) ══════════
  {
    id: "en-oca-q107", moduleId: "m13",
    question: "What does a view store?",
    options: ["A copy of the data", "The query definition only", "An index on the base table", "A snapshot refreshed nightly"],
    correctIndexes: [1],
    explanation: "A view stores only its defining query, executed each time it is used — so it always reflects the current data. A materialized view is the object that stores an actual copy.",
    topic: "Managing Views", difficulty: "easy",
  },
  {
    id: "en-oca-q108", moduleId: "m13",
    question: "Which clause makes a view reject any DML through it?",
    options: ["WITH CHECK OPTION", "WITH READ ONLY", "FORCE", "NOT UPDATABLE"],
    correctIndexes: [1],
    explanation: "WITH READ ONLY forbids every INSERT, UPDATE and DELETE through the view. WITH CHECK OPTION allows them but refuses any row that would fall outside the view's own WHERE clause.",
    topic: "Managing Views", difficulty: "medium",
  },
  {
    id: "en-oca-q109", moduleId: "m13",
    question: "What does WITH CHECK OPTION guarantee?",
    options: [
      "That the view is never modified",
      "That the base table has a primary key",
      "That a row inserted or updated through the view remains visible through it",
      "That the view is recompiled on every use",
    ],
    correctIndexes: [2],
    explanation: "The clause blocks any change that would push a row outside the view's WHERE clause — inserting a row into a view of department 10 with department 20 raises ORA-01402. It does not forbid modification altogether.",
    topic: "Managing Views", difficulty: "hard",
  },
  {
    id: "en-oca-q110", moduleId: "m13",
    question: "Which two constructs prevent DML through a view? (Choose two.)",
    options: [
      "A group function in the select list",
      "A WHERE clause",
      "The DISTINCT keyword",
      "A column alias",
    ],
    correctIndexes: [0, 2],
    explanation: "Aggregation and DISTINCT make it impossible to map a view row back to a single base row, so the view becomes non-updatable — as do GROUP BY and set operators. A WHERE clause and an alias leave the mapping intact.",
    topic: "Managing Views", difficulty: "hard",
  },
  {
    id: "en-oca-q111", moduleId: "m13",
    question: "What does CREATE FORCE VIEW allow?",
    options: [
      "Creating the view even if the base table does not yet exist",
      "Forcing the recompilation of an existing view",
      "Creating a view over another view",
      "Bypassing privilege checks",
    ],
    correctIndexes: [0],
    explanation: "FORCE creates the view in an invalid state, to be compiled when the base object appears — useful when deploying objects in an arbitrary order. It grants no privilege whatsoever.",
    topic: "Managing Views", difficulty: "hard",
  },

  // ══════════ 13. Managing Indexes Synonyms and Sequences (m13) ══════════
  {
    id: "en-oca-q112", moduleId: "m13",
    question: "Which pseudocolumn returns the next value of a sequence?",
    options: ["CURRVAL", "NEXTVAL", "NEXT", "SEQVAL"],
    correctIndexes: [1],
    explanation: "NEXTVAL increments the sequence and returns the new value. CURRVAL returns the last value produced in the session and raises ORA-08002 if NEXTVAL has not been called first.",
    topic: "Managing Indexes Synonyms and Sequences", difficulty: "easy",
  },
  {
    id: "en-oca-q113", moduleId: "m13",
    question: "Which two situations create gaps in a sequence? (Choose two.)",
    options: [
      "A rollback after NEXTVAL",
      "An instance shutdown with cached values unused",
      "Using CURRVAL",
      "Declaring NOCYCLE",
    ],
    correctIndexes: [0, 1],
    explanation: "A sequence is never rolled back, so an aborted transaction burns its value; and a shutdown loses the values still held in cache. CURRVAL consumes nothing, and NOCYCLE merely stops the sequence at its limit.",
    topic: "Managing Indexes Synonyms and Sequences", difficulty: "hard",
  },
  {
    id: "en-oca-q114", moduleId: "m13",
    question: "What is a synonym?",
    options: [
      "A copy of an object",
      "An index on several columns",
      "A view without a WHERE clause",
      "An alternative name for another object",
    ],
    correctIndexes: [3],
    explanation: "A synonym is a name pointing at an object, which hides the owning schema and any later relocation. It holds no data of its own, and dropping it leaves the target untouched.",
    topic: "Managing Indexes Synonyms and Sequences", difficulty: "easy",
  },
  {
    id: "en-oca-q115", moduleId: "m13",
    question: "What distinguishes a public synonym from a private one?",
    options: [
      "The public synonym is visible to every user, the private one to its owner alone",
      "The public synonym is faster",
      "The private synonym cannot point at a table",
      "The public synonym grants access to the object",
    ],
    correctIndexes: [0],
    explanation: "A public synonym belongs to PUBLIC and is visible to all, but confers no privilege: without a GRANT, using it still raises ORA-00942. Creating one requires CREATE PUBLIC SYNONYM.",
    topic: "Managing Indexes Synonyms and Sequences", difficulty: "medium",
  },
  {
    id: "en-oca-q116", moduleId: "m13",
    question: "Which two actions automatically create an index? (Choose two.)",
    options: [
      "Declaring a PRIMARY KEY",
      "Declaring a UNIQUE constraint",
      "Declaring a NOT NULL constraint",
      "Declaring a CHECK constraint",
    ],
    correctIndexes: [0, 1],
    explanation: "Oracle needs a unique index to enforce primary-key and unique constraints, so it creates one unless a suitable index already exists. NOT NULL and CHECK are verified row by row and need no structure.",
    topic: "Managing Indexes Synonyms and Sequences", difficulty: "hard",
  },
  {
    id: "en-oca-q117", moduleId: "m13",
    question: "When is a function-based index used by the optimizer?",
    options: [
      "Whenever the indexed column appears in the query",
      "When the query's predicate uses exactly the same expression",
      "Only in a GROUP BY clause",
      "Only if the table is partitioned",
    ],
    correctIndexes: [1],
    explanation: "An index on UPPER(last_name) serves WHERE UPPER(last_name) = 'KING' but not WHERE last_name = 'King'. The expressions must match, and the function must be deterministic.",
    topic: "Managing Indexes Synonyms and Sequences", difficulty: "hard",
  },
  {
    id: "en-oca-q118", moduleId: "m13",
    question: "What happens to the index of a primary key when the constraint is dropped?",
    options: [
      "It is kept and becomes an ordinary index",
      "It is converted into a unique constraint",
      "It becomes invalid",
      "It is dropped along with the constraint unless KEEP INDEX is specified",
    ],
    correctIndexes: [3],
    explanation: "Dropping the constraint drops the index Oracle created for it, unless DROP ... KEEP INDEX is used. An index that already existed beforehand and was merely reused is preserved.",
    topic: "Managing Indexes Synonyms and Sequences", difficulty: "hard",
  },

  // ══════════ 14. Controlling User Access (m16) ══════════
  {
    id: "en-oca-q119", moduleId: "m16",
    question: "Which privilege allows a user to open a database session?",
    options: ["CONNECT SESSION", "CREATE SESSION", "LOGIN", "OPEN SESSION"],
    correctIndexes: [1],
    explanation: "CREATE SESSION is the system privilege that permits connection; without it, a valid account still receives ORA-01045. CONNECT is a role that happens to include it, not a privilege in its own right.",
    topic: "Controlling User Access", difficulty: "medium",
  },
  {
    id: "en-oca-q120", moduleId: "m16",
    question: "What distinguishes a system privilege from an object privilege?",
    options: [
      "A system privilege authorises an action, an object privilege access to a named object",
      "A system privilege applies to one table, an object privilege to the whole database",
      "There is no difference, only the name changes",
      "A system privilege can only be granted to a role",
    ],
    correctIndexes: [0],
    explanation: "CREATE TABLE is a system privilege — the right to perform an action; SELECT ON hr.employees is an object privilege — the right to reach a specific object. Both may be granted to a user or a role.",
    topic: "Controlling User Access", difficulty: "medium",
  },
  {
    id: "en-oca-q121", moduleId: "m16",
    question: "What does WITH GRANT OPTION permit on an object privilege?",
    options: [
      "Modifying the object",
      "Granting the same privilege on to others",
      "Dropping the object",
      "Bypassing the constraints",
    ],
    correctIndexes: [1],
    explanation: "The recipient may pass the privilege on. Crucially, revoking it cascades: the grants made downstream disappear too — which is not the case for WITH ADMIN OPTION on a system privilege.",
    topic: "Controlling User Access", difficulty: "hard",
  },
  {
    id: "en-oca-q122", moduleId: "m16",
    question: "What is the essential difference between revoking WITH GRANT OPTION and WITH ADMIN OPTION?",
    options: [
      "Revoking the object privilege cascades, revoking the system privilege does not",
      "Revoking the system privilege cascades, revoking the object privilege does not",
      "Both cascade",
      "Neither cascades",
    ],
    correctIndexes: [0],
    explanation: "Revoking an object privilege granted WITH GRANT OPTION removes the downstream grants as well. Revoking a system privilege granted WITH ADMIN OPTION leaves them in place — an asymmetry the exam tests directly.",
    topic: "Controlling User Access", difficulty: "hard",
  },
  {
    id: "en-oca-q123", moduleId: "m16",
    question: "What is a role?",
    options: [
      "A user with elevated rights",
      "A synonym for a set of tables",
      "A schema without objects",
      "A named collection of privileges that can be granted as a unit",
    ],
    correctIndexes: [3],
    explanation: "A role groups privileges so they can be granted and revoked in one operation. It cannot own objects and cannot connect: it is a container, not an account.",
    topic: "Controlling User Access", difficulty: "easy",
  },
  {
    id: "en-oca-q124", moduleId: "m16",
    question: "Which privilege suits a reporting account that must only read one table?",
    options: [
      "SELECT ANY TABLE",
      "The DBA role",
      "SELECT on that one table",
      "CREATE TABLE",
    ],
    correctIndexes: [2],
    explanation: "Least privilege dictates granting exactly the access required and nothing more. SELECT ANY TABLE opens every schema, and DBA hands over the whole instance for a need that is one table wide.",
    topic: "Controlling User Access", difficulty: "medium",
  },
  {
    id: "en-oca-q125", moduleId: "m16",
    question: "Which two statements about privileges obtained through a role are correct? (Choose two.)",
    options: [
      "They apply immediately to interactive queries",
      "They are not taken into account when compiling a stored procedure with definer's rights",
      "They cannot be revoked",
      "They take precedence over direct privileges",
    ],
    correctIndexes: [0, 1],
    explanation: "A role works at once for ordinary SQL, but a definer's-rights PL/SQL unit ignores roles — the privilege must be granted directly to the owner. Roles are revoked like any other grant and enjoy no precedence.",
    topic: "Controlling User Access", difficulty: "hard",
  },

  // ══════════ 15. Managing Objects with Data Dictionary Views (m13) ══════════
  {
    id: "en-oca-q126", moduleId: "m13",
    question: "What does the USER_ prefix denote in a dictionary view?",
    options: [
      "Objects accessible to the current user",
      "Objects belonging to other users",
      "Every object in the database",
      "Objects owned by the current user",
    ],
    correctIndexes: [3],
    explanation: "USER_ shows only what the current user owns and therefore has no OWNER column, since it would be constant. ALL_ adds what has been granted to the user, and DBA_ covers the whole database.",
    topic: "Managing Objects with Data Dictionary Views", difficulty: "medium",
  },
  {
    id: "en-oca-q127", moduleId: "m13",
    question: "Which view lists the tables the current user may query, including those of others?",
    options: ["USER_TABLES", "DBA_TABLES", "ALL_TABLES", "V$TABLES"],
    correctIndexes: [2],
    explanation: "ALL_TABLES covers what the user owns plus what has been granted to them. USER_TABLES stops at ownership, DBA_TABLES requires an administrative privilege, and V$TABLES does not exist.",
    topic: "Managing Objects with Data Dictionary Views", difficulty: "medium",
  },
  {
    id: "en-oca-q128", moduleId: "m13",
    question: "Which view describes the columns of the current user's tables?",
    options: ["USER_COLUMNS", "USER_TAB_COLUMNS", "USER_TABLE_COLS_ALL", "COLUMNS"],
    correctIndexes: [1],
    explanation: "The view is USER_TAB_COLUMNS, with ALL_ and DBA_ counterparts. USER_TAB_COLS also exists and additionally shows hidden and virtual columns; USER_COLUMNS does not exist.",
    topic: "Managing Objects with Data Dictionary Views", difficulty: "hard",
  },
  {
    id: "en-oca-q129", moduleId: "m13",
    question: "Which two views let you check the constraints defined on a table? (Choose two.)",
    options: [
      "USER_CONSTRAINTS",
      "USER_CONS_COLUMNS",
      "USER_INDEXES",
      "USER_TAB_PRIVS",
    ],
    correctIndexes: [0, 1],
    explanation: "USER_CONSTRAINTS lists the constraints with their type and status, USER_CONS_COLUMNS the columns each one spans — a join between the two is needed for a composite key. Indexes and privileges are other subjects entirely.",
    topic: "Managing Objects with Data Dictionary Views", difficulty: "hard",
  },
  {
    id: "en-oca-q130", moduleId: "m13",
    question: "Which view lists every object owned by the current user, whatever its type?",
    options: ["USER_OBJECTS", "USER_TABLES", "USER_SEGMENTS", "USER_CATALOG"],
    correctIndexes: [0],
    explanation: "USER_OBJECTS covers tables, views, indexes, sequences, procedures and the rest, with an OBJECT_TYPE column. USER_CATALOG is restricted to tables, views, synonyms and sequences, and USER_SEGMENTS describes storage rather than objects.",
    topic: "Managing Objects with Data Dictionary Views", difficulty: "medium",
  },
  {
    id: "en-oca-q131", moduleId: "m13",
    question: "Which view shows the object privileges granted to the current user by others?",
    options: ["USER_TAB_PRIVS_MADE", "USER_SYS_PRIVS", "USER_TAB_PRIVS_RECD", "USER_ROLE_PRIVS"],
    correctIndexes: [2],
    explanation: "RECD stands for received, MADE for granted by the user to others. USER_SYS_PRIVS lists system privileges and USER_ROLE_PRIVS the roles held — three distinct questions, three distinct views.",
    topic: "Managing Objects with Data Dictionary Views", difficulty: "hard",
  },

  // ══════════ 16. Managing Data in Different Time Zones (m4) ══════════
  {
    id: "en-oca-q132", moduleId: "m4",
    question: "Which type stores a date and time without any time-zone information?",
    options: ["TIMESTAMP WITH TIME ZONE", "TIMESTAMP", "TIMESTAMP WITH LOCAL TIME ZONE", "INTERVAL DAY TO SECOND"],
    correctIndexes: [1],
    explanation: "A plain TIMESTAMP holds a date and time with fractional seconds and no zone. WITH TIME ZONE stores the offset alongside, WITH LOCAL TIME ZONE normalises to the database zone, and INTERVAL is a duration.",
    topic: "Managing Data in Different Time Zones", difficulty: "medium",
  },
  {
    id: "en-oca-q133", moduleId: "m4",
    question: "What characterises TIMESTAMP WITH LOCAL TIME ZONE?",
    options: [
      "It stores the offset supplied by the client",
      "It refuses any value carrying a time zone",
      "It normalises to the database time zone and displays in the session time zone",
      "It is identical to TIMESTAMP",
    ],
    correctIndexes: [2],
    explanation: "The value is converted to the database zone on storage and back to the session zone on reading, so two users in different zones each see their own local time for the same instant. Nothing is stored alongside it.",
    topic: "Managing Data in Different Time Zones", difficulty: "hard",
  },
  {
    id: "en-oca-q134", moduleId: "m4",
    question: "Which function returns the current date and time in the session time zone, as a TIMESTAMP WITH TIME ZONE?",
    options: ["SYSDATE", "SYSTIMESTAMP", "CURRENT_TIMESTAMP", "LOCALTIMESTAMP"],
    correctIndexes: [2],
    explanation: "CURRENT_TIMESTAMP follows the session zone and carries its offset. LOCALTIMESTAMP returns the same instant as a plain TIMESTAMP without offset, while SYSDATE and SYSTIMESTAMP follow the server's zone.",
    topic: "Managing Data in Different Time Zones", difficulty: "hard",
  },
  {
    id: "en-oca-q135", moduleId: "m4",
    question: "What is the difference between SYSDATE and CURRENT_DATE?",
    options: [
      "SYSDATE follows the database server's zone, CURRENT_DATE the session's",
      "SYSDATE follows the session's zone, CURRENT_DATE the server's",
      "They are synonyms",
      "CURRENT_DATE returns a TIMESTAMP",
    ],
    correctIndexes: [0],
    explanation: "SYSDATE reads the operating-system clock of the server, CURRENT_DATE applies the session time zone. Both return a DATE, so the two differ whenever the session sits in another zone.",
    topic: "Managing Data in Different Time Zones", difficulty: "hard",
  },
  {
    id: "en-oca-q136", moduleId: "m4",
    question: "Which two functions report a time zone rather than an instant? (Choose two.)",
    options: ["DBTIMEZONE", "SYSTIMESTAMP", "SESSIONTIMEZONE", "LOCALTIMESTAMP"],
    correctIndexes: [0, 2],
    explanation: "DBTIMEZONE returns the database's zone and SESSIONTIMEZONE the session's — both offsets or region names. SYSTIMESTAMP and LOCALTIMESTAMP return points in time.",
    topic: "Managing Data in Different Time Zones", difficulty: "medium",
  },
  {
    id: "en-oca-q137", moduleId: "m4",
    question: "Which two INTERVAL types does Oracle provide? (Choose two.)",
    options: [
      "INTERVAL YEAR TO MONTH",
      "INTERVAL DAY TO SECOND",
      "INTERVAL MONTH TO DAY",
      "INTERVAL HOUR TO YEAR",
    ],
    correctIndexes: [0, 1],
    explanation: "The two families are deliberately separate, because a month has no fixed number of days: mixing the scales would make arithmetic ambiguous. The other two forms do not exist.",
    topic: "Managing Data in Different Time Zones", difficulty: "medium",
  },
  {
    id: "en-oca-q138", moduleId: "m4",
    question: "Which expression converts a TIMESTAMP WITH TIME ZONE to another zone?",
    options: [
      "CONVERT(ts, 'Europe/Paris')",
      "ts WITH TIME ZONE 'Europe/Paris'",
      "TO_TIMEZONE(ts, 'Europe/Paris')",
      "ts AT TIME ZONE 'Europe/Paris'",
    ],
    correctIndexes: [3],
    explanation: "AT TIME ZONE performs the conversion, accepting either a region name or an offset. CONVERT changes character sets, and the other two forms are not Oracle SQL.",
    topic: "Managing Data in Different Time Zones", difficulty: "hard",
  },
];
