import type { QuizQuestion } from "./types";

/**
 * Banque 1Z0-078 — Oracle Database 19c: Clusterware, ASM and Real Application
 * Clusters.
 *
 * Une question par concept distinct, rattachée à la session du cursus qui le
 * traite (`lib/course-rac.ts`).
 */
export const racQuestions: QuizQuestion[] = [
  // ─── Session 1 — Architecture du cluster et Grid Infrastructure ─────────
  {
    id: "rac-q1", track: "ocp-rac", moduleId: "rac-session-1",
    question: "Contre quel risque un cluster RAC ne protège-t-il PAS ?",
    options: [
      "L'arrêt planifié d'une instance pour maintenance",
      "La panne d'un serveur du cluster",
      "La perte du site, puisque tous les nœuds partagent le même stockage",
      "La saturation d'un nœud unique",
    ],
    correctIndexes: [2],
    explanation: "RAC protège de la panne d'un nœud, pas du sinistre de site : la baie de disques partagée reste un point de défaillance unique. C'est Data Guard qui couvre ce risque, et les sauvegardes qui couvrent l'erreur logique.",
    topic: "Périmètre de RAC", difficulty: "medium",
  },
  {
    id: "rac-q2", track: "ocp-rac", moduleId: "rac-session-1",
    question: "Quel composant de Clusterware décide de l'éviction d'un nœud ?",
    options: ["OHASD", "CRSD", "EVMD", "CSSD"],
    correctIndexes: [3],
    explanation: "CSSD (Cluster Synchronization Services) gère l'appartenance au cluster, les heartbeats réseau et disque, et décide de l'éviction. CRSD gère les ressources de haut niveau, EVMD diffuse les événements, OHASD démarre la pile au boot.",
    topic: "Composants Clusterware", difficulty: "medium",
  },
  {
    id: "rac-q3", track: "ocp-rac", moduleId: "rac-session-1",
    question: "Combien d'adresses le nom SCAN doit-il résoudre, et par quel moyen ?",
    options: [
      "Une adresse, déclarée dans /etc/hosts",
      "Trois adresses, par tourniquet DNS",
      "Une adresse par nœud du cluster",
      "Deux adresses, par GNS uniquement",
    ],
    correctIndexes: [1],
    explanation: "Le SCAN doit résoudre vers trois adresses en tourniquet DNS. Le déclarer dans /etc/hosts ne renvoie qu'une adresse : l'installateur le refuse ou produit un cluster dégradé. C'est l'erreur d'installation manuelle la plus fréquente.",
    topic: "SCAN", difficulty: "hard",
  },
  {
    id: "rac-q4", track: "ocp-rac", moduleId: "rac-session-1",
    question: "Quelles adresses faut-il prévoir par nœud avant l'installation ? (Choisissez trois réponses.)",
    options: [
      "Une adresse publique",
      "Une adresse privée d'interconnexion",
      "Une VIP non affectée avant l'installation",
      "Trois adresses SCAN par nœud",
      "Une adresse pour l'OCR",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "Chaque nœud a une adresse publique, au moins une adresse privée dédiée à l'interconnexion, et une VIP qui doit être résolue par DNS mais NON affectée avant l'installation. Les trois adresses SCAN valent pour tout le cluster, pas par nœud.",
    topic: "Prérequis réseau", difficulty: "hard",
  },
  {
    id: "rac-q5", track: "ocp-rac", moduleId: "rac-session-1",
    question: "Quel utilitaire vérifie les prérequis d'installation d'un cluster ?",
    options: ["cluvfy (runcluvfy.sh)", "opatchauto", "asmcmd", "srvctl"],
    correctIndexes: [0],
    explanation: "Le Cluster Verification Utility s'exécute avant l'installation par runcluvfy.sh, puis après par cluvfy. Il contrôle réseau, stockage partagé, paramètres noyau, utilisateurs et paquets. L'exécuter en amont évite l'essentiel des échecs.",
    topic: "cluvfy", difficulty: "easy",
  },
  {
    id: "rac-q6", track: "ocp-rac", moduleId: "rac-session-1",
    question: "Comment root.sh doit-il être exécuté lors d'une installation de Grid Infrastructure ?",
    options: [
      "Après le démarrage de la base RAC",
      "Simultanément sur tous les nœuds pour gagner du temps",
      "Uniquement sur le nœud portant le SCAN",
      "Séquentiellement, un nœud après l'autre, en commençant par le premier",
    ],
    correctIndexes: [3],
    explanation: "root.sh configure la pile cluster et initialise l'OCR et les voting disks sur le premier nœud ; les suivants s'y rattachent. Le lancer en parallèle corrompt la configuration.",
    topic: "Installation", difficulty: "hard",
  },

  // ─── Session 2 — CRSCTL, SRVCTL, OCR, voting disks ──────────────────────
  {
    id: "rac-q7", track: "ocp-rac", moduleId: "rac-session-2",
    question: "Quel outil sert à arrêter une instance de base dans un cluster ?",
    options: [
      "crsctl stop crs",
      "srvctl stop instance",
      "crsctl stop cluster",
      "asmcmd shutdown",
    ],
    correctIndexes: [1],
    explanation: "srvctl pilote les ressources Oracle : bases, instances, services, listeners, ASM, VIP. crsctl pilote la pile cluster elle-même. Règle de tri : si l'objet existerait sans Oracle Database, c'est crsctl.",
    topic: "crsctl vs srvctl", difficulty: "medium",
  },
  {
    id: "rac-q8", track: "ocp-rac", moduleId: "rac-session-2",
    question: "Pourquoi le nombre de voting disks doit-il être impair ?",
    options: [
      "Parce que l'OCR en exige un par nœud",
      "Parce qu'ASM ne sait gérer qu'un nombre impair de disques",
      "Parce qu'un nœud doit voir plus de la moitié des voting disks pour rester dans le cluster",
      "Parce que le SCAN en utilise trois",
    ],
    correctIndexes: [2],
    explanation: "Le quorum exige la majorité stricte. Avec deux voting disks, en perdre un fait tomber tout le cluster : il en faut donc 1, 3 ou 5. En redondance normale, ASM en place automatiquement trois.",
    topic: "Voting disks", difficulty: "hard",
  },
  {
    id: "rac-q9", track: "ocp-rac", moduleId: "rac-session-2",
    question: "Quelle différence sépare l'OCR de l'OLR ?",
    options: [
      "L'OCR décrit tout le cluster ; l'OLR est local à un nœud et lu avant l'accès à l'OCR",
      "L'OLR décrit tout le cluster ; l'OCR est local",
      "Les deux sont identiques, l'OLR n'est qu'une sauvegarde",
      "L'OLR ne contient que les voting disks",
    ],
    correctIndexes: [0],
    explanation: "L'OLR permet à OHASD de démarrer la pile locale avant que le stockage partagé — donc l'OCR — ne soit accessible. Il se sauvegarde manuellement par ocrconfig -local -manualbackup, alors que l'OCR est sauvegardé automatiquement.",
    topic: "OCR et OLR", difficulty: "hard",
  },
  {
    id: "rac-q10", track: "ocp-rac", moduleId: "rac-session-2",
    question: "À quelle fréquence l'OCR est-il sauvegardé automatiquement ?",
    options: ["Toutes les heures", "Toutes les 4 heures", "Une fois par jour", "À chaque modification"],
    correctIndexes: [1],
    explanation: "Clusterware sauvegarde l'OCR toutes les 4 heures et conserve une semaine de sauvegardes. ocrconfig -showbackup les liste. Les voting disks, eux, ne sont pas sauvegardés : ils se recréent.",
    topic: "Sauvegarde de l'OCR", difficulty: "medium",
  },
  {
    id: "rac-q11", track: "ocp-rac", moduleId: "rac-session-2",
    question: "Quel processus démarre la pile Clusterware au démarrage du serveur ?",
    options: ["CSSD", "CRSD", "OHASD", "GPNPD"],
    correctIndexes: [2],
    explanation: "OHASD (Oracle High Availability Services Daemon) démarre au boot puis lance GPNPD, GIPCD, MDNSD et CSSD. CSSD lit alors les voting disks, ASM monte les groupes de disques, et CRSD lit l'OCR pour démarrer les ressources.",
    topic: "Séquence de démarrage", difficulty: "hard",
  },
  {
    id: "rac-q12", track: "ocp-rac", moduleId: "rac-session-2",
    question: "Quelle commande affiche l'état de toutes les ressources du cluster ?",
    options: ["oclumon dumpnodeview", "srvctl config database", "ocrcheck", "crsctl stat res -t"],
    correctIndexes: [3],
    explanation: "crsctl stat res -t présente un tableau lisible de toutes les ressources, locales et cluster, avec leur état par nœud. L'ajout de -init montre les ressources de bas niveau gérées par OHASD.",
    topic: "Diagnostic du cluster", difficulty: "easy",
  },

  // ─── Session 3 — ASM : architecture et redondance ───────────────────────
  {
    id: "rac-q13", track: "ocp-rac", moduleId: "rac-session-3",
    question: "Quelle affirmation décrit correctement une instance ASM ?",
    options: [
      "Elle a une SGA et des processus mais aucun fichier de données, et ne sert jamais de requêtes utilisateur",
      "Elle contient une copie du dictionnaire de la base",
      "Elle intercepte toutes les entrées-sorties de la base",
      "Elle remplace le buffer cache de l'instance de base",
    ],
    correctIndexes: [0],
    explanation: "ASM indique aux instances de base où se trouvent les extents, puis s'efface : les entrées-sorties vont directement du serveur de base au disque. C'est un gestionnaire de métadonnées, pas un intermédiaire de données.",
    topic: "Instance ASM", difficulty: "medium",
  },
  {
    id: "rac-q14", track: "ocp-rac", moduleId: "rac-session-3",
    question: "Quel privilège permet de créer et de supprimer un groupe de disques ASM ?",
    options: ["SYSOPER", "SYSDBA", "SYSASM", "SYSBACKUP"],
    correctIndexes: [2],
    explanation: "SYSASM est le privilège d'administration complète d'ASM depuis la 11g. SYSDBA sur une instance ASM ne donne qu'un accès aux fichiers depuis une base ; SYSOPER permet de démarrer, arrêter et monter sans modifier la configuration.",
    topic: "Privilèges ASM", difficulty: "medium",
  },
  {
    id: "rac-q15", track: "ocp-rac", moduleId: "rac-session-3",
    question: "Combien de groupes de pannes minimum exige la redondance HIGH ?",
    options: ["Cinq", "Deux", "Un", "Trois"],
    correctIndexes: [3],
    explanation: "HIGH maintient trois copies de chaque extent et exige donc trois groupes de pannes ; NORMAL en maintient deux et en exige deux ; EXTERNAL n'en maintient qu'une et délègue la protection à la baie.",
    topic: "Redondance ASM", difficulty: "medium",
  },
  {
    id: "rac-q16", track: "ocp-rac", moduleId: "rac-session-3",
    question: "Quel est le rôle d'un groupe de pannes (failure group) ?",
    options: [
      "Grouper les disques de même taille",
      "Rassembler les disques qui tombent ensemble, pour qu'ASM n'y place jamais deux copies du même extent",
      "Isoler les disques réservés à la FRA",
      "Définir l'ordre de rééquilibrage",
    ],
    correctIndexes: [1],
    explanation: "Un groupe de pannes correspond à un domaine de défaillance : une baie, un contrôleur, une armoire. Déclarer deux groupes de pannes sur la même baie physique donne une illusion de redondance — l'erreur de conception la plus coûteuse.",
    topic: "Groupes de pannes", difficulty: "hard",
  },
  {
    id: "rac-q17", track: "ocp-rac", moduleId: "rac-session-3",
    question: "Que contrôle la clause POWER d'un ALTER DISKGROUP … REBALANCE ?",
    options: [
      "La vitesse du rééquilibrage, de 0 (suspendu) à 1024",
      "Le nombre de copies conservées",
      "La taille des unités d'allocation",
      "Le nombre de groupes de pannes",
    ],
    correctIndexes: [0],
    explanation: "POWER va de 0 à 1024 ; sa valeur par défaut vient d'ASM_POWER_LIMIT. La valeur 0 suspend le rééquilibrage. V$ASM_OPERATION donne l'avancement et une estimation du temps restant.",
    topic: "Rééquilibrage", difficulty: "medium",
  },
  {
    id: "rac-q18", track: "ocp-rac", moduleId: "rac-session-3",
    question: "Pourquoi retirer un disque et en ajouter un autre dans une seule instruction ?",
    options: [
      "Pour conserver les alias de fichiers",
      "Pour éviter de perdre la redondance",
      "Parce qu'ASM refuse deux opérations successives",
      "Pour ne déclencher qu'un seul rééquilibrage au lieu de deux",
    ],
    correctIndexes: [3],
    explanation: "Deux instructions séparées provoquent deux rééquilibrages complets successifs. Une instruction unique n'en déclenche qu'un, deux fois plus rapide au total — sur une grosse baie, l'écart se compte en heures.",
    topic: "Rééquilibrage", difficulty: "hard",
  },

  // ─── Session 4 — Fichiers ASM, ACFS et surveillance ─────────────────────
  {
    id: "rac-q19", track: "ocp-rac", moduleId: "rac-session-4",
    question: "Que signifie une valeur négative de USABLE_FILE_MB dans V$ASM_DISKGROUP ?",
    options: [
      "Le groupe de disques est corrompu",
      "Le groupe est trop plein pour pouvoir se reconstruire après la perte d'un groupe de pannes",
      "Le rééquilibrage est en cours",
      "La redondance a été désactivée",
    ],
    correctIndexes: [1],
    explanation: "USABLE_FILE_MB indique l'espace encore inscriptible tout en conservant la capacité de reconstruction. Une valeur négative signifie que la redondance existe encore, mais que la prochaine panne de disque sera définitive. C'est le seuil d'alerte à surveiller, pas FREE_MB.",
    topic: "Surveillance ASM", difficulty: "hard",
  },
  {
    id: "rac-q20", track: "ocp-rac", moduleId: "rac-session-4",
    question: "Que permet ACFS que ASM seul ne permet pas ?",
    options: [
      "Assurer la redondance des données",
      "Répartir les extents entre plusieurs disques",
      "Stocker des fichiers qui ne sont pas des fichiers de base de données, montés sur tous les nœuds",
      "Héberger les voting disks",
    ],
    correctIndexes: [2],
    explanation: "ASM ne stocke que des fichiers de base. ACFS est un système de fichiers en cluster monté simultanément sur tous les nœuds : binaires Oracle, exports Data Pump, journaux applicatifs. Il offre instantanés et redimensionnement en ligne.",
    topic: "ACFS", difficulty: "medium",
  },
  {
    id: "rac-q21", track: "ocp-rac", moduleId: "rac-session-4",
    question: "Quel utilitaire permet de parcourir les groupes de disques ASM en ligne de commande ?",
    options: ["asmcmd", "adrci", "crsctl", "oclumon"],
    correctIndexes: [0],
    explanation: "asmcmd offre une navigation de type shell : lsdg, ls, du, lsof, cp. C'est le moyen le plus rapide d'inspecter le contenu d'un groupe de disques sans passer par SQL.",
    topic: "asmcmd", difficulty: "easy",
  },
  {
    id: "rac-q22", track: "ocp-rac", moduleId: "rac-session-4",
    question: "À quoi sert un modèle (template) ASM ?",
    options: [
      "Créer automatiquement des alias",
      "Définir la redondance et la granularité de répartition par type de fichier",
      "Fixer la taille des unités d'allocation du groupe",
      "Déclarer les groupes de pannes",
    ],
    correctIndexes: [1],
    explanation: "Les modèles permettent, dans un même groupe de disques, d'appliquer HIGH aux fichiers de contrôle et NORMAL aux fichiers de données, avec une répartition fine ou grossière selon le type. V$ASM_TEMPLATE les liste.",
    topic: "Modèles ASM", difficulty: "hard",
  },

  // ─── Session 5 — RAC, Cache Fusion, services ────────────────────────────
  {
    id: "rac-q23", track: "ocp-rac", moduleId: "rac-session-5",
    question: "Quel processus transfère les blocs entre instances dans Cache Fusion ?",
    options: ["LMON", "LMD", "LMS", "LCK0"],
    correctIndexes: [2],
    explanation: "LMS (Global Cache Service Process) est le cœur de Cache Fusion : il envoie les blocs à l'instance qui les demande via l'interconnexion. LMD gère les demandes de verrous globaux, LMON l'appartenance et la reconfiguration.",
    topic: "Cache Fusion", difficulty: "medium",
  },
  {
    id: "rac-q24", track: "ocp-rac", moduleId: "rac-session-5",
    question: "Pourquoi faut-il interroger les vues GV$ plutôt que V$ en RAC ?",
    options: [
      "Parce que V$ ne fonctionne qu'avec ASM",
      "Parce que les vues V$ sont supprimées en RAC",
      "Parce que GV$ est plus rapide",
      "Parce que V$ ne montre que l'instance locale, alors que GV$ agrège toutes les instances",
    ],
    correctIndexes: [3],
    explanation: "Chaque vue V$ a une contrepartie GV$ qui ajoute une colonne INST_ID et agrège tout le cluster. Diagnostiquer sur V$SESSION en RAC ne montre qu'un nœud — une source d'erreur permanente.",
    topic: "Vues GV$", difficulty: "medium",
  },
  {
    id: "rac-q25", track: "ocp-rac", moduleId: "rac-session-5",
    question: "Quels paramètres doivent obligatoirement différer d'une instance RAC à l'autre ? (Choisissez deux réponses.)",
    options: [
      "UNDO_TABLESPACE",
      "INSTANCE_NUMBER",
      "DB_NAME",
      "DB_BLOCK_SIZE",
      "CONTROL_FILES",
    ],
    correctIndexes: [0, 1],
    explanation: "Chaque instance a son propre tablespace d'annulation et son propre numéro d'instance, donc son propre thread de redo. DB_NAME, DB_BLOCK_SIZE et CONTROL_FILES décrivent la base unique et sont forcément identiques.",
    topic: "Paramètres RAC", difficulty: "hard",
  },
  {
    id: "rac-q26", track: "ocp-rac", moduleId: "rac-session-5",
    question: "Que se passe-t-il lorsqu'un client se connecte au nom SCAN ?",
    options: [
      "Un listener SCAN le redirige vers le listener local de l'instance la moins chargée",
      "Le client est connecté au premier nœud déclaré",
      "La connexion échoue si le nœud maître est arrêté",
      "Le client doit préciser l'instance dans le descripteur",
    ],
    correctIndexes: [0],
    explanation: "Le SCAN résout vers trois adresses en tourniquet ; le listener SCAN atteint connaît la charge de tous les nœuds et redirige vers le listener local approprié. Ajouter ou retirer un nœud ne change rien côté client.",
    topic: "SCAN", difficulty: "medium",
  },
  {
    id: "rac-q27", track: "ocp-rac", moduleId: "rac-session-5",
    question: "À quoi sert un service dans un environnement RAC ?",
    options: [
      "Déclarer les groupes de disques ASM",
      "Remplacer le listener local",
      "Définir sur quelles instances une application s'exécute et où elle bascule",
      "Fixer le degré de parallélisme des requêtes",
    ],
    correctIndexes: [2],
    explanation: "Un service est l'unité de travail du RAC : instances préférées, instances de repli, politique d'équilibrage, mesure des ressources. Sans services, toutes les applications se connectent partout et rien n'est isolable.",
    topic: "Services", difficulty: "medium",
  },
  {
    id: "rac-q28", track: "ocp-rac", moduleId: "rac-session-5",
    question: "Quelle différence sépare une instance « préférée » (preferred) d'une instance « disponible » (available) ?",
    options: [
      "Il n'y a aucune différence fonctionnelle",
      "Les disponibles sont plus rapides",
      "Les préférées sont limitées à une seule par service",
      "Le service démarre sur les préférées et ne bascule sur les disponibles qu'en cas de panne",
    ],
    correctIndexes: [3],
    explanation: "Une instance préférée héberge le service en fonctionnement normal ; une instance disponible ne le reçoit qu'en cas de défaillance d'une préférée. C'est ce qui permet de réserver un nœud à une charge donnée.",
    topic: "Services", difficulty: "hard",
  },
  {
    id: "rac-q29", track: "ocp-rac", moduleId: "rac-session-5",
    question: "Quels mécanismes améliorent la continuité côté client en RAC ? (Choisissez trois réponses.)",
    options: [
      "TAF (Transparent Application Failover)",
      "FAN avec Fast Connection Failover",
      "Application Continuity",
      "Le rééquilibrage ASM",
      "Le catalogue de récupération RMAN",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "TAF reconnecte la session et peut poursuivre un SELECT en cours ; FAN notifie immédiatement le pool sans attendre un délai TCP ; Application Continuity rejoue la transaction interrompue. Les deux autres options n'ont aucun rapport avec la connectivité.",
    topic: "Continuité client", difficulty: "hard",
  },

  // ─── Session 6 — Performance, sauvegarde, correctifs, dépannage ─────────
  {
    id: "rac-q30", track: "ocp-rac", moduleId: "rac-session-6",
    question: "Que traduit un événement « gc cr block lost » ?",
    options: [
      "Un plan d'exécution inefficace",
      "Un problème matériel sur l'interconnexion",
      "Un manque de mémoire dans la SGA",
      "Une contention sur un bloc chaud",
    ],
    correctIndexes: [1],
    explanation: "Un bloc perdu sur l'interconnexion signale un défaut réseau : carte saturée, MTU mal alignée, perte de paquets. C'est à traiter en priorité, avant toute analyse SQL.",
    topic: "Attentes globales", difficulty: "hard",
  },
  {
    id: "rac-q31", track: "ocp-rac", moduleId: "rac-session-6",
    question: "Une attente « gc buffer busy acquire » importante indique :",
    options: [
      "Plusieurs instances se disputant le même bloc",
      "Un disque défaillant",
      "Une base de secours en retard",
      "Un shared pool trop petit",
    ],
    correctIndexes: [0],
    explanation: "C'est un bloc chaud partagé entre instances : séquence sans cache, index sur clé croissante, ligne de compteur. Les remèdes sont structurels — CACHE NOORDER, index inversé, partitionnement de l'application par service.",
    topic: "Attentes globales", difficulty: "hard",
  },
  {
    id: "rac-q32", track: "ocp-rac", moduleId: "rac-session-6",
    question: "Comment configurer une séquence pour limiter la contention en RAC ?",
    options: [
      "NOCACHE NOORDER",
      "ORDER NOCACHE",
      "CACHE 20 ORDER",
      "CACHE 1000 NOORDER",
    ],
    correctIndexes: [3],
    explanation: "Un cache important réduit les accès au dictionnaire, et NOORDER évite de sérialiser l'attribution entre instances. À l'inverse, ORDER force une coordination globale à chaque valeur : c'est le pire choix en cluster.",
    topic: "Séquences en RAC", difficulty: "hard",
  },
  {
    id: "rac-q33", track: "ocp-rac", moduleId: "rac-session-6",
    question: "Lors d'une récupération RMAN d'une base RAC, que faut-il garantir ?",
    options: [
      "Que chaque instance restaure sa propre partie de la base",
      "Que les fichiers d'archive de TOUS les threads soient accessibles",
      "Que le catalogue de récupération soit local à un nœud",
      "Que toutes les instances soient ouvertes simultanément",
    ],
    correctIndexes: [1],
    explanation: "Chaque instance produit son propre thread de redo. La récupération rejoue les redo de tous les threads : les archives doivent donc être dans un emplacement partagé, typiquement la FRA sur ASM. Une seule instance monte la base pour restaurer.",
    topic: "Sauvegarde RAC", difficulty: "hard",
  },
  {
    id: "rac-q34", track: "ocp-rac", moduleId: "rac-session-6",
    question: "Quel utilitaire applique un correctif en mode progressif sur un cluster ?",
    options: ["srvctl", "cluvfy", "opatchauto", "asmca"],
    correctIndexes: [2],
    explanation: "opatchauto arrête la pile du nœud, applique le correctif puis redémarre, pendant que les autres nœuds continuent de servir. Vérifier au préalable que le correctif est bien déclaré « rolling » par opatch query.",
    topic: "Correctifs progressifs", difficulty: "medium",
  },
  {
    id: "rac-q35", track: "ocp-rac", moduleId: "rac-session-6",
    question: "Quelles sont les deux causes d'éviction d'un nœud ? (Choisissez deux réponses.)",
    options: [
      "Perte du heartbeat réseau au-delà de misscount",
      "Perte de l'accès aux voting disks au-delà de disktimeout",
      "Saturation du buffer cache",
      "Absence de statistiques sur une table",
    ],
    correctIndexes: [0, 1],
    explanation: "Ce sont les deux seuls critères d'éviction. Le cluster préfère perdre un nœud plutôt que de risquer un split-brain : l'éviction n'est pas un défaut, c'est la protection qui fonctionne. misscount vaut 30 s par défaut, disktimeout 200 s.",
    topic: "Éviction de nœud", difficulty: "hard",
  },
  {
    id: "rac-q36", track: "ocp-rac", moduleId: "rac-session-6",
    question: "Quel fichier de trace donne le motif exact d'une éviction de nœud ?",
    options: ["ocssd.trc", "crsd.trc", "alert_ORCL.log", "listener.log"],
    correctIndexes: [0],
    explanation: "ocssd.trc consigne les décisions de CSSD, dont le motif de l'éviction : heartbeat réseau ou heartbeat disque. Le journal d'alertes du cluster donne le contexte, crsd.trc les échecs de démarrage de ressources.",
    topic: "Dépannage", difficulty: "hard",
  },
  {
    id: "rac-q37", track: "ocp-rac", moduleId: "rac-session-6",
    question: "Quel outil collecte l'ensemble des diagnostics du cluster pour le support ?",
    options: [
      "tkprof",
      "diagcollection.sh",
      "opatch lsinventory",
      "ocrconfig -showbackup",
    ],
    correctIndexes: [1],
    explanation: "diagcollection.sh --collect --crs rassemble journaux, traces et configuration de la pile Clusterware en une archive. oclumon dumpnodeview complète en fournissant l'historique des ressources système par nœud.",
    topic: "Dépannage", difficulty: "medium",
  },
  {
    id: "rac-q38", track: "ocp-rac", moduleId: "rac-session-6",
    question: "Quelle commande déplace un service d'une instance à l'autre sans coupure ?",
    options: [
      "crsctl relocate resource",
      "srvctl stop service puis srvctl start service",
      "srvctl relocate service",
      "alter system set service_names",
    ],
    correctIndexes: [2],
    explanation: "srvctl relocate service démarre le service sur l'instance cible avant de l'arrêter sur la source, ce qui permet aux connexions de migrer progressivement. Un stop suivi d'un start coupe le service entre les deux.",
    topic: "Services", difficulty: "hard",
  },
];
