import type { QuizQuestion } from "./types";

/**
 * Banque anglaise 1Z0-071 — domaines officiels 1 à 8.
 *
 * Reconstruite à partir du workbook source, dont l'analyse du 31 août 2026 a
 * montré qu'il souffrait de quatre défauts structurels :
 *
 *  1. 67 questions sur 224 étaient des **doublons reformulés** — même jeu
 *     d'options, même clé, énoncé réécrit. La déduplication précédente n'avait
 *     retiré que les doublons stricts.
 *  2. À partir du cinquième module, chaque question était rattachée au
 *     **mauvais module** : une question sur les opérateurs ensemblistes
 *     renvoyait vers le module DML.
 *  3. Les explications se contentaient de reformuler la bonne réponse
 *     (45 caractères en moyenne) sans jamais écarter les distracteurs.
 *  4. Aucune question multi-réponses, alors que l'examen réel en comporte,
 *     et 93 % des bonnes réponses en première position dans les données.
 *
 * Chaque question porte ici le **libellé officiel du domaine** comme sujet, le
 * module réellement correspondant, une explication qui justifie la clé *et*
 * écarte les distracteurs, et une position de bonne réponse variée.
 */
export const enOcaQuestionsA: QuizQuestion[] = [
  // ══════════ 1. Relational Database Concepts (m1) ══════════
  {
    id: "en-oca-q1", moduleId: "m1",
    question: "Which database object stores relational data as rows and columns?",
    options: ["Sequence", "Table", "Synonym", "Role"],
    correctIndexes: [1],
    explanation: "A table is the only object that physically stores rows and columns. A sequence generates numbers, a synonym is just an alternative name for another object, and a role is a named collection of privileges — none of them hold data.",
    topic: "Relational Database Concepts", difficulty: "easy",
  },
  {
    id: "en-oca-q2", moduleId: "m1",
    question: "Which two properties must a primary key satisfy? (Choose two.)",
    options: [
      "It uniquely identifies each row",
      "It may contain NULL in at most one row",
      "None of its columns may be NULL",
      "It must be a single column",
    ],
    correctIndexes: [0, 2],
    explanation: "A primary key is unique and NOT NULL on every column it spans. It may perfectly well be composite, so requiring a single column is wrong; and unlike a UNIQUE constraint it tolerates no NULL at all, not even one.",
    topic: "Relational Database Concepts", difficulty: "medium",
  },
  {
    id: "en-oca-q3", moduleId: "m1",
    question: "Which constraint enforces a parent-child relationship between two tables?",
    options: ["CHECK", "UNIQUE", "FOREIGN KEY", "DEFAULT"],
    correctIndexes: [2],
    explanation: "A FOREIGN KEY enforces referential integrity: a child value must exist in the referenced parent key. CHECK validates a condition inside one row, UNIQUE forbids duplicates in one table, and DEFAULT merely supplies a value when none is given.",
    topic: "Relational Database Concepts", difficulty: "easy",
  },
  {
    id: "en-oca-q4", moduleId: "m1",
    question: "What is a candidate key?",
    options: [
      "Any index defined on the table",
      "Any foreign key column",
      "The key a view is sorted on",
      "A minimal set of attributes that uniquely identifies a row",
    ],
    correctIndexes: [3],
    explanation: "A candidate key uniquely identifies a row and is minimal — remove any column and uniqueness is lost. One candidate key becomes the primary key; the others are alternate keys. An index does not imply uniqueness, and a foreign key identifies a parent row, not this one.",
    topic: "Relational Database Concepts", difficulty: "medium",
  },
  {
    id: "en-oca-q5", moduleId: "m1",
    question: "What is normalization mainly intended to reduce?",
    options: [
      "The number of SQL keywords needed",
      "Redundancy and update anomalies",
      "Network traffic between client and server",
      "The length of stored passwords",
    ],
    correctIndexes: [1],
    explanation: "Normalization removes repeating data so a fact is stored once, which eliminates the insert, update and delete anomalies that duplication causes. It says nothing about SQL syntax, network behaviour or security.",
    topic: "Relational Database Concepts", difficulty: "medium",
  },
  {
    id: "en-oca-q6", moduleId: "m1",
    question: "Which constraint restricts column values using a Boolean condition?",
    options: ["INDEX", "UNIQUE", "FOREIGN KEY", "CHECK"],
    correctIndexes: [3],
    explanation: "CHECK evaluates a condition — for example salary > 0 — and rejects rows that fail it. UNIQUE and FOREIGN KEY compare against other rows rather than testing a condition, and an index is a performance structure, not a constraint.",
    topic: "Relational Database Concepts", difficulty: "easy",
  },
  {
    id: "en-oca-q7", moduleId: "m1",
    question: "One department employs many employees. Which relationship is this?",
    options: ["One-to-one", "Many-to-many", "One-to-many", "Zero-to-zero"],
    correctIndexes: [2],
    explanation: "One parent row relates to many child rows: that is one-to-many, implemented by a foreign key on the child. It would be many-to-many only if an employee could also belong to several departments, which this statement does not say.",
    topic: "Relational Database Concepts", difficulty: "easy",
  },
  {
    id: "en-oca-q8", moduleId: "m1",
    question: "Which design correctly represents a many-to-many relationship?",
    options: [
      "A junction table holding two foreign keys",
      "A comma-separated list of IDs in one column",
      "A sequence shared by both tables",
      "A public synonym on each table",
    ],
    correctIndexes: [0],
    explanation: "A many-to-many relationship is resolved by an associative table carrying a foreign key to each side. Storing a list of IDs in one column breaks first normal form and makes joins and integrity impossible; sequences and synonyms have no bearing on cardinality.",
    topic: "Relational Database Concepts", difficulty: "medium",
  },
  {
    id: "en-oca-q9", moduleId: "m1",
    question: "What does a column's data type define?",
    options: [
      "Which users may read the column",
      "The join order chosen by the optimizer",
      "The name of the primary key",
      "The values the column accepts and how they are stored",
    ],
    correctIndexes: [3],
    explanation: "The data type fixes the domain of acceptable values and their storage format — which in turn governs comparison and sorting rules. Access is governed by privileges, join order by the optimizer, and the primary key by its own constraint.",
    topic: "Relational Database Concepts", difficulty: "easy",
  },
  {
    id: "en-oca-q10", moduleId: "m1",
    question: "Which statement about a foreign key is true?",
    options: [
      "It must always be named ID",
      "It automatically sorts the child rows",
      "It is always also the primary key",
      "It can reference a key in the same table",
    ],
    correctIndexes: [3],
    explanation: "A self-referencing foreign key is perfectly valid — the classic case is an employee's MANAGER_ID pointing at another employee. Naming is free, a foreign key is normally not the primary key, and it imposes no ordering.",
    topic: "Relational Database Concepts", difficulty: "medium",
  },
  {
    id: "en-oca-q11", moduleId: "m1",
    question: "Which two clauses of a SELECT statement map most directly to an entity-relationship diagram? (Choose two.)",
    options: [
      "FROM, which names the entities",
      "ORDER BY, which names the primary keys",
      "JOIN, which follows the relationships",
      "HAVING, which names the attributes",
    ],
    correctIndexes: [0, 2],
    explanation: "FROM names the entities of the diagram and JOIN walks the relationships drawn between them. ORDER BY only sorts the result, and HAVING filters groups — neither corresponds to anything on the diagram.",
    topic: "Relational Database Concepts", difficulty: "hard",
  },

  // ══════════ 2. Retrieving Data using the SQL SELECT Statement (m2) ══════════
  {
    id: "en-oca-q12", moduleId: "m2",
    question: "Which statement returns every column of HR.EMPLOYEES?",
    options: [
      "SELECT ALL FROM hr.employees",
      "GET * FROM hr.employees",
      "SELECT * FROM hr.employees",
      "SELECT columns FROM hr.employees",
    ],
    correctIndexes: [2],
    explanation: "The asterisk projects every column. ALL is a duplicate-handling keyword, not a column list, so SELECT ALL alone is a syntax error; GET is not SQL; and COLUMNS is simply an unknown identifier.",
    topic: "Retrieving Data using the SQL SELECT Statement", difficulty: "easy",
  },
  {
    id: "en-oca-q13", moduleId: "m2",
    question: "Which operator concatenates character expressions in Oracle?",
    options: ["+", "&&", "||", "CONCAT+"],
    correctIndexes: [2],
    explanation: "Oracle uses the double pipe. The plus sign is arithmetic and would attempt an implicit numeric conversion, && introduces a substitution variable in SQL*Plus, and CONCAT+ does not exist — CONCAT is a function taking exactly two arguments.",
    topic: "Retrieving Data using the SQL SELECT Statement", difficulty: "easy",
  },
  {
    id: "en-oca-q14", moduleId: "m2",
    question: "What does DISTINCT do in a SELECT statement?",
    options: [
      "It deletes duplicate rows from the table",
      "It groups the rows",
      "It sorts the result set",
      "It removes duplicate rows from the result set",
    ],
    correctIndexes: [3],
    explanation: "DISTINCT eliminates duplicates from the result only; the stored data is untouched — it is a query, not DML. It also guarantees no ordering, even though the deduplication often produces sorted-looking output.",
    topic: "Retrieving Data using the SQL SELECT Statement", difficulty: "medium",
  },
  {
    id: "en-oca-q15", moduleId: "m2",
    question: "Which clause identifies the row source of a query?",
    options: ["SELECT", "WHERE", "HAVING", "FROM"],
    correctIndexes: [3],
    explanation: "FROM names the table, view or subquery the rows come from. SELECT projects columns, WHERE filters rows once they are read, and HAVING filters groups after aggregation.",
    topic: "Retrieving Data using the SQL SELECT Statement", difficulty: "easy",
  },
  {
    id: "en-oca-q16", moduleId: "m2",
    question: "Which reference to a table alias is valid?",
    options: [
      "SELECT e.employee_id FROM employees e",
      "SELECT employees.e.employee_id FROM employees e",
      "SELECT e:employee_id FROM employees e",
      "SELECT alias.e.employee_id FROM employees e",
    ],
    correctIndexes: [0],
    explanation: "Once a table alias is declared, the column is qualified as alias.column — and the original table name can no longer be used. The other three either chain two qualifiers or use a separator that is not the dot.",
    topic: "Retrieving Data using the SQL SELECT Statement", difficulty: "medium",
  },
  {
    id: "en-oca-q17", moduleId: "m2",
    question: "Which query concatenates the first and last name separated by a space?",
    options: [
      "SELECT first_name + ' ' + last_name FROM employees",
      "SELECT first_name AND last_name FROM employees",
      "SELECT CONCAT(first_name, last_name, ' ') FROM employees",
      "SELECT first_name || ' ' || last_name FROM employees",
    ],
    correctIndexes: [3],
    explanation: "Only the double pipe concatenates. The plus sign forces a numeric conversion and raises ORA-01722, AND is a logical operator, and Oracle's CONCAT accepts exactly two arguments — three raises ORA-00909.",
    topic: "Retrieving Data using the SQL SELECT Statement", difficulty: "medium",
  },
  {
    id: "en-oca-q18", moduleId: "m2",
    question: "Why is DUAL used in a query such as SELECT 2+3 FROM dual?",
    options: [
      "It supplies exactly one row so the expression is evaluated once",
      "It is the only table on which arithmetic is allowed",
      "It stores the results of arithmetic expressions",
      "It is required by every SELECT statement",
    ],
    correctIndexes: [0],
    explanation: "DUAL holds a single row and a single column, so selecting an expression from it returns that expression once. Arithmetic works against any table; DUAL simply avoids repeating the result as many times as the table has rows.",
    topic: "Retrieving Data using the SQL SELECT Statement", difficulty: "medium",
  },
  {
    id: "en-oca-q19", moduleId: "m2",
    question: "In which clause can a column alias defined in the SELECT list be referenced?",
    options: ["WHERE", "ORDER BY", "The join condition", "HAVING"],
    correctIndexes: [1],
    explanation: "ORDER BY is evaluated after the select list, so the alias already exists. WHERE, the join condition and HAVING are all evaluated before projection, which is why referencing an alias there raises ORA-00904.",
    topic: "Retrieving Data using the SQL SELECT Statement", difficulty: "hard",
  },
  {
    id: "en-oca-q20", moduleId: "m2",
    question: "Which two statements about a SELECT list are correct? (Choose two.)",
    options: [
      "It may contain literals and expressions",
      "It may contain single-row functions",
      "It may contain only stored column names",
      "It modifies the underlying data",
    ],
    correctIndexes: [0, 1],
    explanation: "The select list accepts columns, literals, arithmetic and function calls alike. It is restricted to stored columns only in the sense that data comes from somewhere — but expressions are perfectly legal, and a SELECT never modifies data.",
    topic: "Retrieving Data using the SQL SELECT Statement", difficulty: "medium",
  },
  {
    id: "en-oca-q21", moduleId: "m2",
    question: "What is the result of the expression salary * NULL for a row where salary is 5000?",
    options: ["5000", "0", "NULL", "An ORA-01476 error"],
    correctIndexes: [2],
    explanation: "Any arithmetic involving NULL yields NULL, because NULL means an unknown value and the product of a known and an unknown is unknown. Only division by zero raises ORA-01476, and NULL is not treated as zero.",
    topic: "Retrieving Data using the SQL SELECT Statement", difficulty: "medium",
  },
  {
    id: "en-oca-q22", moduleId: "m2",
    question: "Which operator lets a literal contain a single quote without doubling it?",
    options: ["The alternative quote operator q'[...]'", "The escape operator \\", "The concatenation operator ||", "The DISTINCT keyword"],
    correctIndexes: [0],
    explanation: "The q operator lets you pick your own delimiter, so q'[It's here]' needs no doubled quote. Oracle's string literals do not use a backslash escape; concatenation joins values, and DISTINCT has nothing to do with literals.",
    topic: "Retrieving Data using the SQL SELECT Statement", difficulty: "hard",
  },

  // ══════════ 3. Restricting and Sorting Data (m3) ══════════
  {
    id: "en-oca-q23", moduleId: "m3",
    question: "Which clause filters individual rows before any grouping takes place?",
    options: ["HAVING", "WHERE", "ORDER BY", "GROUP BY"],
    correctIndexes: [1],
    explanation: "WHERE runs before GROUP BY, so it filters rows and therefore reduces what is aggregated. HAVING filters the groups afterwards, GROUP BY forms them, and ORDER BY only sorts the final result.",
    topic: "Restricting and Sorting Data", difficulty: "easy",
  },
  {
    id: "en-oca-q24", moduleId: "m3",
    question: "Which operator tests an inclusive range?",
    options: ["IN", "LIKE", "BETWEEN", "EXISTS"],
    correctIndexes: [2],
    explanation: "BETWEEN 1000 AND 2000 includes both bounds — it is equivalent to >= 1000 AND <= 2000. IN tests a list of discrete values, LIKE matches a pattern, and EXISTS tests whether a subquery returns rows.",
    topic: "Restricting and Sorting Data", difficulty: "easy",
  },
  {
    id: "en-oca-q25", moduleId: "m3",
    question: "How do you correctly test that COMMISSION_PCT holds no value?",
    options: [
      "WHERE commission_pct = NULL",
      "WHERE commission_pct IS NULL",
      "WHERE commission_pct = ''",
      "WHERE commission_pct != NULL",
    ],
    correctIndexes: [1],
    explanation: "NULL is not a value, so no comparison operator can match it: both = NULL and != NULL return unknown and therefore no rows. IS NULL is the only test. In Oracle an empty string is itself NULL, so the third option is a disguised = NULL.",
    topic: "Restricting and Sorting Data", difficulty: "medium",
  },
  {
    id: "en-oca-q26", moduleId: "m3",
    question: "Which LIKE wildcard matches exactly one character?",
    options: ["%", "*", "_", "?"],
    correctIndexes: [2],
    explanation: "The underscore matches exactly one character, the percent sign matches zero or more. The asterisk and question mark are shell wildcards and have no special meaning inside LIKE.",
    topic: "Restricting and Sorting Data", difficulty: "easy",
  },
  {
    id: "en-oca-q27", moduleId: "m3",
    question: "In an expression combining NOT, AND and OR, what is the order of precedence?",
    options: ["OR, then AND, then NOT", "AND, then OR, then NOT", "NOT, then AND, then OR", "They are all equal, evaluated left to right"],
    correctIndexes: [2],
    explanation: "NOT binds tightest, then AND, then OR. This is why a IS NULL OR b = 1 AND c = 2 groups as a IS NULL OR (b = 1 AND c = 2) — parentheses are the only way to force a different reading.",
    topic: "Restricting and Sorting Data", difficulty: "hard",
  },
  {
    id: "en-oca-q28", moduleId: "m3",
    question: "What is the default sort direction of ORDER BY, and where do NULLs land?",
    options: [
      "Ascending, with NULLs last",
      "Ascending, with NULLs first",
      "Descending, with NULLs last",
      "Descending, with NULLs first",
    ],
    correctIndexes: [0],
    explanation: "ORDER BY sorts ascending by default, and Oracle places NULLs last in that direction — the opposite of a descending sort, where they come first. NULLS FIRST and NULLS LAST override this explicitly.",
    topic: "Restricting and Sorting Data", difficulty: "hard",
  },
  {
    id: "en-oca-q29", moduleId: "m3",
    question: "Which SQL*Plus command creates a substitution variable?",
    options: ["SET", "DEFINE", "ACCEPT ONLY", "VERIFY"],
    correctIndexes: [1],
    explanation: "DEFINE creates and assigns a substitution variable, and DEFINE on its own lists them. SET changes SQL*Plus settings, VERIFY controls whether the substituted text is echoed, and ACCEPT ONLY is not a command.",
    topic: "Restricting and Sorting Data", difficulty: "medium",
  },
  {
    id: "en-oca-q30", moduleId: "m3",
    question: "What is the difference between &variable and &&variable?",
    options: [
      "&& prompts once and keeps the value for the session, & prompts every time",
      "& prompts once, && prompts every time",
      "There is none, && is only a readability convention",
      "&& is reserved for numeric values",
    ],
    correctIndexes: [0],
    explanation: "A double ampersand defines the variable on first use, so later references reuse the value without prompting. A single ampersand substitutes without defining, which means each occurrence prompts again.",
    topic: "Restricting and Sorting Data", difficulty: "hard",
  },
  {
    id: "en-oca-q31", moduleId: "m3",
    question: "What does SET VERIFY ON display?",
    options: [
      "The number of rows returned",
      "The execution plan of the statement",
      "A confirmation prompt before each DML statement",
      "The line before and after substitution",
    ],
    correctIndexes: [3],
    explanation: "VERIFY echoes the old and new text of a line containing a substitution variable, which is how you check what was actually substituted. Row counts come from FEEDBACK, plans from AUTOTRACE, and there is no DML confirmation setting.",
    topic: "Restricting and Sorting Data", difficulty: "hard",
  },
  {
    id: "en-oca-q32", moduleId: "m3",
    question: "Which two clauses limit the number of rows returned in Oracle 12c and later? (Choose two.)",
    options: [
      "FETCH FIRST n ROWS ONLY",
      "LIMIT n",
      "OFFSET n ROWS",
      "TOP n",
    ],
    correctIndexes: [0, 2],
    explanation: "The row-limiting clause is OFFSET … FETCH FIRST … ROWS ONLY, and both halves are valid on their own. LIMIT belongs to MySQL and PostgreSQL, TOP to SQL Server; neither parses in Oracle.",
    topic: "Restricting and Sorting Data", difficulty: "medium",
  },

  // ══════════ 4. Using Single-Row Functions to Customize Output (m4) ══════════
  {
    id: "en-oca-q33", moduleId: "m4",
    question: "Which function returns the number of characters in a string?",
    options: ["SIZE", "COUNT", "LENGTH", "CHARS"],
    correctIndexes: [2],
    explanation: "LENGTH returns a character count — LENGTHB returns bytes, which differs in a multibyte character set. COUNT is a group function that counts rows, and neither SIZE nor CHARS is a SQL function.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "easy",
  },
  {
    id: "en-oca-q34", moduleId: "m4",
    question: "What does SUBSTR('ORACLE', 2, 3) return?",
    options: ["'ORA'", "'RAC'", "'ACL'", "'CLE'"],
    correctIndexes: [1],
    explanation: "SUBSTR starts at position 2 — the R — and takes 3 characters, giving RAC. Positions are 1-based, not 0-based; a negative start would count from the end of the string instead.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "medium",
  },
  {
    id: "en-oca-q35", moduleId: "m4",
    question: "Which function returns the position of a substring inside another string?",
    options: ["INSTR", "SUBSTR", "POSITION", "LOCATE"],
    correctIndexes: [0],
    explanation: "INSTR returns the position, and 0 when the substring is absent. SUBSTR extracts rather than locates; POSITION and LOCATE belong to other dialects.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "easy",
  },
  {
    id: "en-oca-q36", moduleId: "m4",
    question: "What does ROUND(156.78, -1) return?",
    options: ["156.8", "150", "160", "157"],
    correctIndexes: [2],
    explanation: "A negative second argument rounds to the left of the decimal point: -1 means tens, so 156.78 rounds to 160. Rounding to -2 would give 200, and omitting the argument would give 157.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "hard",
  },
  {
    id: "en-oca-q37", moduleId: "m4",
    question: "What is the difference between ROUND(156.78, -1) and TRUNC(156.78, -1)?",
    options: [
      "There is none, both return 160",
      "ROUND returns 160, TRUNC returns 150",
      "ROUND returns 150, TRUNC returns 160",
      "TRUNC rejects a negative second argument",
    ],
    correctIndexes: [1],
    explanation: "ROUND goes to the nearest ten and gives 160; TRUNC simply cuts and gives 150. Both accept a negative argument — that is precisely how they operate to the left of the decimal point.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "hard",
  },
  {
    id: "en-oca-q38", moduleId: "m4",
    question: "Which function returns the remainder of a division?",
    options: ["REMAINDER", "DIV", "MOD", "TRUNC"],
    correctIndexes: [2],
    explanation: "MOD(10, 3) returns 1. REMAINDER exists but rounds the quotient to the nearest integer rather than truncating it, so MOD and REMAINDER disagree on negative operands; DIV is not an Oracle function.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "medium",
  },
  {
    id: "en-oca-q39", moduleId: "m4",
    question: "What does SYSDATE + 1 return?",
    options: [
      "The same date one hour later",
      "The same date one month later",
      "An error: a number cannot be added to a date",
      "The same date one day later",
    ],
    correctIndexes: [3],
    explanation: "Adding a number to a DATE adds that many days, so + 1 is tomorrow and + 1/24 is one hour later. Adding a month requires ADD_MONTHS, since months do not all have the same length.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "medium",
  },
  {
    id: "en-oca-q40", moduleId: "m4",
    question: "What is the data type of the result of the expression date2 - date1?",
    options: ["NUMBER, a count of days", "DATE", "INTERVAL DAY TO SECOND", "TIMESTAMP"],
    correctIndexes: [0],
    explanation: "Subtracting two DATE values yields a NUMBER of days, with the fractional part representing the time. Subtracting two TIMESTAMP values, by contrast, yields an INTERVAL DAY TO SECOND.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "hard",
  },
  {
    id: "en-oca-q41", moduleId: "m4",
    question: "Which function returns the last day of the month containing a given date?",
    options: ["MONTHS_BETWEEN", "LAST_DAY", "NEXT_DAY", "TRUNC"],
    correctIndexes: [1],
    explanation: "LAST_DAY returns the 28th, 29th, 30th or 31st as appropriate. NEXT_DAY returns the next occurrence of a named weekday, MONTHS_BETWEEN measures a gap, and TRUNC would give the first day of the month.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "medium",
  },
  {
    id: "en-oca-q42", moduleId: "m4",
    question: "Which two function calls return a date one month after HIRE_DATE? (Choose two.)",
    options: [
      "ADD_MONTHS(hire_date, 1)",
      "hire_date + 30",
      "hire_date + INTERVAL '1' MONTH",
      "NEXT_DAY(hire_date, 'MONTH')",
    ],
    correctIndexes: [0, 2],
    explanation: "ADD_MONTHS and an INTERVAL MONTH literal both move by a calendar month and land on the same day number. Adding 30 days is only correct in a 30-day month, and NEXT_DAY expects a weekday name, not MONTH.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "hard",
  },
  {
    id: "en-oca-q43", moduleId: "m4",
    question: "Which two functions change the case of a character string? (Choose two.)",
    options: ["UPPER", "CAPITALIZE", "INITCAP", "TOUPPER"],
    correctIndexes: [0, 2],
    explanation: "UPPER converts everything to capitals and INITCAP capitalises the first letter of each word while lowering the rest. LOWER completes the trio; CAPITALIZE and TOUPPER do not exist in Oracle SQL.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "easy",
  },
  {
    id: "en-oca-q44", moduleId: "m4",
    question: "Nested functions are evaluated in which order?",
    options: [
      "From the outside in",
      "In an order the optimizer chooses",
      "Left to right, ignoring nesting",
      "From the inside out",
    ],
    correctIndexes: [3],
    explanation: "The innermost call is evaluated first and its result becomes the argument of the enclosing call. In UPPER(SUBSTR(name, 1, 3)) the substring is extracted before the case conversion is applied.",
    topic: "Using Single-Row Functions to Customize Output", difficulty: "medium",
  },

  // ══════════ 5. Using Conversion Functions and Conditional Expressions (m4) ══════════
  {
    id: "en-oca-q45", moduleId: "m4",
    question: "Which function converts a character string to a DATE?",
    options: ["TO_CHAR", "CAST_DATE", "TO_DATE", "CONVERT"],
    correctIndexes: [2],
    explanation: "TO_DATE reads a string using a format model and returns a DATE. TO_CHAR goes the other way, CONVERT changes character sets rather than data types, and CAST_DATE is not a function.",
    topic: "Using Conversion Functions and Conditional Expressions", difficulty: "easy",
  },
  {
    id: "en-oca-q46", moduleId: "m4",
    question: "Which format model element represents a four-digit year?",
    options: ["YY", "YYYY", "RR", "Y4"],
    correctIndexes: [1],
    explanation: "YYYY is the four-digit year. YY takes the century from the current date, RR applies the pivot rule around the year 50 to interpret two digits, and Y4 does not exist.",
    topic: "Using Conversion Functions and Conditional Expressions", difficulty: "medium",
  },
  {
    id: "en-oca-q47", moduleId: "m4",
    question: "In a format model, what is the difference between MM and MON?",
    options: [
      "MM gives the month number, MON its abbreviated name",
      "MM gives the abbreviated name, MON the number",
      "MM gives the full name, MON the abbreviation",
      "There is none, they are synonyms",
    ],
    correctIndexes: [0],
    explanation: "MM yields 01 to 12, MON the three-letter abbreviation, and MONTH the full name padded with blanks. The distinction matters because MON and MONTH depend on NLS_DATE_LANGUAGE while MM does not.",
    topic: "Using Conversion Functions and Conditional Expressions", difficulty: "medium",
  },
  {
    id: "en-oca-q48", moduleId: "m4",
    question: "What does NVL(commission_pct, 0) return when COMMISSION_PCT is NULL?",
    options: ["NULL", "0", "commission_pct", "An error"],
    correctIndexes: [1],
    explanation: "NVL returns its second argument when the first is NULL, and the first otherwise — so a NULL commission becomes 0. Both arguments must be of compatible data types, or Oracle attempts an implicit conversion.",
    topic: "Using Conversion Functions and Conditional Expressions", difficulty: "easy",
  },
  {
    id: "en-oca-q49", moduleId: "m4",
    question: "What does NVL2(expr1, expr2, expr3) return when expr1 is NOT NULL?",
    options: ["expr3", "NULL", "expr1", "expr2"],
    correctIndexes: [3],
    explanation: "NVL2 returns expr2 when expr1 is NOT NULL, and expr3 when it is NULL. The order is the reverse of what most people expect, and it is precisely what the exam tests.",
    topic: "Using Conversion Functions and Conditional Expressions", difficulty: "hard",
  },
  {
    id: "en-oca-q50", moduleId: "m4",
    question: "What does NULLIF(a, b) return when a equals b?",
    options: ["a", "b", "NULL", "0"],
    correctIndexes: [2],
    explanation: "NULLIF returns NULL when the two arguments are equal, and the first argument otherwise. It is the exact inverse of NVL, and is typically used to turn a placeholder value into a genuine NULL.",
    topic: "Using Conversion Functions and Conditional Expressions", difficulty: "medium",
  },
  {
    id: "en-oca-q51", moduleId: "m4",
    question: "Which function returns the first non-NULL expression in a list?",
    options: ["COALESCE", "NVL", "NULLIF", "DECODE"],
    correctIndexes: [0],
    explanation: "COALESCE takes any number of arguments and returns the first that is not NULL, evaluating them lazily. NVL takes exactly two, NULLIF compares two, and DECODE performs equality mapping.",
    topic: "Using Conversion Functions and Conditional Expressions", difficulty: "medium",
  },
  {
    id: "en-oca-q52", moduleId: "m4",
    question: "Which two statements about CASE and DECODE are correct? (Choose two.)",
    options: [
      "CASE is ANSI standard, DECODE is specific to Oracle",
      "DECODE performs only equality comparisons",
      "CASE performs only equality comparisons",
      "DECODE can use range comparisons such as greater-than",
    ],
    correctIndexes: [0, 1],
    explanation: "DECODE compares for equality alone, which is why a range test requires CASE — or a nested SIGN trick. CASE is the ANSI form, handles any condition, and is the one to prefer in new code.",
    topic: "Using Conversion Functions and Conditional Expressions", difficulty: "hard",
  },
  {
    id: "en-oca-q53", moduleId: "m4",
    question: "What happens during an implicit conversion of '2024-01-15' to a DATE?",
    options: [
      "It always succeeds, the ISO format being universal",
      "It succeeds only if NLS_DATE_FORMAT matches the string",
      "It is forbidden, an explicit TO_DATE is required",
      "It converts the date to a number of days",
    ],
    correctIndexes: [1],
    explanation: "An implicit conversion uses the session's NLS_DATE_FORMAT: the same statement succeeds for one user and raises ORA-01861 for another. This is why TO_DATE with an explicit format model is the only reliable form.",
    topic: "Using Conversion Functions and Conditional Expressions", difficulty: "hard",
  },
  {
    id: "en-oca-q54", moduleId: "m4",
    question: "What does TO_CHAR(salary, '999') return when SALARY is 5000?",
    options: ["'5000'", "'####'", "' 500'", "NULL"],
    correctIndexes: [1],
    explanation: "The model provides only three digit positions and the value needs four, so Oracle fills the whole width with hash signs rather than truncating. Lengthening the model to '9999' fixes it.",
    topic: "Using Conversion Functions and Conditional Expressions", difficulty: "hard",
  },

  // ══════════ 6. Reporting Aggregated Data Using Group Functions (m5) ══════════
  {
    id: "en-oca-q55", moduleId: "m5",
    question: "What is the difference between COUNT(*) and COUNT(commission_pct)?",
    options: [
      "There is none",
      "COUNT(column) is faster and returns the same result",
      "COUNT(*) counts columns, COUNT(column) counts rows",
      "COUNT(*) counts rows, COUNT(column) counts non-NULL values",
    ],
    correctIndexes: [3],
    explanation: "COUNT(*) counts every row, NULLs included, because it counts rows rather than values. COUNT(column) ignores NULLs — which is exactly why the two return different numbers on a nullable column.",
    topic: "Reporting Aggregated Data Using Group Functions", difficulty: "medium",
  },
  {
    id: "en-oca-q56", moduleId: "m5",
    question: "How do group functions treat NULL values?",
    options: [
      "They ignore them, except COUNT(*)",
      "They treat them as zero",
      "They return NULL as soon as one value is NULL",
      "They raise an error",
    ],
    correctIndexes: [0],
    explanation: "AVG, SUM, MIN and MAX skip NULLs entirely, so AVG over 10 rows of which 3 are NULL divides by 7, not 10. Only COUNT(*) counts them, because it counts rows rather than values.",
    topic: "Reporting Aggregated Data Using Group Functions", difficulty: "hard",
  },
  {
    id: "en-oca-q57", moduleId: "m5",
    question: "Which rule governs a SELECT list that also contains a group function?",
    options: [
      "Every column may be listed freely",
      "Only aggregated columns are allowed",
      "Every non-aggregated column must appear in GROUP BY",
      "GROUP BY is optional in every case",
    ],
    correctIndexes: [2],
    explanation: "Any column in the select list that is not inside an aggregate must appear in GROUP BY, otherwise Oracle raises ORA-00979. A query aggregating the whole table needs no GROUP BY, but then it may project nothing else.",
    topic: "Reporting Aggregated Data Using Group Functions", difficulty: "medium",
  },
  {
    id: "en-oca-q58", moduleId: "m5",
    question: "Which clause filters groups after aggregation?",
    options: ["WHERE", "HAVING", "GROUP BY", "ORDER BY"],
    correctIndexes: [1],
    explanation: "HAVING applies to groups and may therefore reference a group function, as in HAVING SUM(salary) > 100000. WHERE runs beforehand and cannot see an aggregate — putting one there raises ORA-00934.",
    topic: "Reporting Aggregated Data Using Group Functions", difficulty: "medium",
  },
  {
    id: "en-oca-q59", moduleId: "m5",
    question: "Which expression counts the distinct departments represented?",
    options: [
      "COUNT(DISTINCT department_id)",
      "DISTINCT COUNT(department_id)",
      "COUNT(department_id DISTINCT)",
      "COUNT(UNIQUE(department_id))",
    ],
    correctIndexes: [0],
    explanation: "DISTINCT goes inside the parentheses, immediately before the expression being counted. The other three are syntax errors: DISTINCT cannot precede the function name nor follow the argument.",
    topic: "Reporting Aggregated Data Using Group Functions", difficulty: "medium",
  },
  {
    id: "en-oca-q60", moduleId: "m5",
    question: "Which two group functions accept a character argument? (Choose two.)",
    options: ["MIN", "SUM", "MAX", "AVG"],
    correctIndexes: [0, 2],
    explanation: "MIN and MAX work on characters and dates as well as numbers, comparing them in their own sort order. SUM and AVG are strictly numeric and raise ORA-01722 on character data.",
    topic: "Reporting Aggregated Data Using Group Functions", difficulty: "hard",
  },
  {
    id: "en-oca-q61", moduleId: "m5",
    question: "Which query correctly returns departments whose total salary exceeds 100000?",
    options: [
      "SELECT department_id, SUM(salary) FROM employees WHERE SUM(salary) > 100000 GROUP BY department_id",
      "SELECT department_id, SUM(salary) FROM employees ORDER BY SUM(salary) > 100000",
      "SELECT department_id, SUM(salary) FROM employees HAVING SUM(salary) > 100000",
      "SELECT department_id, SUM(salary) FROM employees GROUP BY department_id HAVING SUM(salary) > 100000",
    ],
    correctIndexes: [3],
    explanation: "A condition on an aggregate belongs in HAVING, after GROUP BY. Placing it in WHERE raises ORA-00934, omitting GROUP BY while projecting DEPARTMENT_ID raises ORA-00979, and ORDER BY does not filter.",
    topic: "Reporting Aggregated Data Using Group Functions", difficulty: "medium",
  },
  {
    id: "en-oca-q62", moduleId: "m5",
    question: "Can group functions be nested, as in MAX(AVG(salary))?",
    options: [
      "No, nesting aggregates is forbidden",
      "Yes, to any depth",
      "Yes, up to two levels and only with a GROUP BY",
      "Yes, but only with COUNT",
    ],
    correctIndexes: [2],
    explanation: "Oracle allows two levels of nesting: MAX(AVG(salary)) with GROUP BY department_id returns the highest departmental average. A third level raises ORA-00935, and the GROUP BY is mandatory for the inner aggregate to have groups to work on.",
    topic: "Reporting Aggregated Data Using Group Functions", difficulty: "hard",
  },

  // ══════════ 7. Displaying Data from Multiple Tables (m6) ══════════
  {
    id: "en-oca-q63", moduleId: "m6",
    question: "Which join returns only the rows that match on both sides?",
    options: ["LEFT OUTER JOIN", "FULL OUTER JOIN", "INNER JOIN", "CROSS JOIN"],
    correctIndexes: [2],
    explanation: "An INNER JOIN keeps only matching pairs. The outer joins preserve unmatched rows from one side or both, and a CROSS JOIN pairs every row with every other regardless of any condition.",
    topic: "Displaying Data from Multiple Tables", difficulty: "easy",
  },
  {
    id: "en-oca-q64", moduleId: "m6",
    question: "Which join keeps every row of the left table, matched or not?",
    options: ["RIGHT OUTER JOIN", "LEFT OUTER JOIN", "INNER JOIN", "NATURAL JOIN"],
    correctIndexes: [1],
    explanation: "LEFT OUTER JOIN preserves the left-hand table and fills the right-hand columns with NULL where there is no match. In the legacy Oracle syntax the (+) marker goes on the side that may be missing — that is, the right.",
    topic: "Displaying Data from Multiple Tables", difficulty: "medium",
  },
  {
    id: "en-oca-q65", moduleId: "m6",
    question: "Why does a filter on the optional table placed in WHERE turn an outer join into an inner join?",
    options: [
      "Because WHERE is evaluated before the join",
      "It does not, the behaviour is unchanged",
      "Because Oracle rewrites the query automatically",
      "Because WHERE eliminates the rows where the optional columns are NULL",
    ],
    correctIndexes: [3],
    explanation: "The outer join produces NULLs for unmatched rows, and a WHERE condition on those columns evaluates to unknown and discards them — leaving exactly the inner join. Putting the condition in the ON clause preserves the outer behaviour.",
    topic: "Displaying Data from Multiple Tables", difficulty: "hard",
  },
  {
    id: "en-oca-q66", moduleId: "m6",
    question: "What is a self join?",
    options: [
      "A join of a table with itself using two aliases",
      "A join without any condition",
      "A join between a table and a view of that table",
      "A join whose condition uses an operator other than equals",
    ],
    correctIndexes: [0],
    explanation: "A self join reads one table twice under two aliases, typically to link an employee to their manager. A join with no condition is a Cartesian product, and a non-equality condition makes it a non-equijoin.",
    topic: "Displaying Data from Multiple Tables", difficulty: "medium",
  },
  {
    id: "en-oca-q67", moduleId: "m6",
    question: "What is a non-equijoin?",
    options: [
      "A join that returns no rows",
      "A join between tables with no foreign key",
      "A join whose condition uses an operator other than equals",
      "A join written without the JOIN keyword",
    ],
    correctIndexes: [2],
    explanation: "A non-equijoin uses BETWEEN, greater-than and the like — for example placing a salary in a grade band. The absence of a foreign key changes nothing, and the legacy comma syntax is a matter of style.",
    topic: "Displaying Data from Multiple Tables", difficulty: "medium",
  },
  {
    id: "en-oca-q68", moduleId: "m6",
    question: "What distinguishes USING from ON in an ANSI join?",
    options: [
      "USING requires identically named columns and merges them into one",
      "ON requires identically named columns",
      "USING allows any condition",
      "There is no difference",
    ],
    correctIndexes: [0],
    explanation: "USING (department_id) demands the same name on both sides and yields a single merged column that must never be qualified by an alias. ON accepts any condition and keeps both columns distinct.",
    topic: "Displaying Data from Multiple Tables", difficulty: "hard",
  },
  {
    id: "en-oca-q69", moduleId: "m6",
    question: "What does a NATURAL JOIN join on?",
    options: [
      "The primary and foreign keys",
      "The columns named in a USING clause",
      "The first column of each table",
      "Every column having the same name and a compatible type in both tables",
    ],
    correctIndexes: [3],
    explanation: "A NATURAL JOIN infers its condition from every same-named column, which makes it fragile: adding a CREATED_DATE column to both tables silently changes the result. USING is the explicit, safe alternative.",
    topic: "Displaying Data from Multiple Tables", difficulty: "hard",
  },
  {
    id: "en-oca-q70", moduleId: "m6",
    question: "Two tables hold 100 and 50 rows. How many rows does a CROSS JOIN return?",
    options: ["150", "100", "5000", "50"],
    correctIndexes: [2],
    explanation: "A Cartesian product pairs every row with every other: 100 × 50 = 5000. The same result appears accidentally whenever a join condition is forgotten in the legacy comma syntax.",
    topic: "Displaying Data from Multiple Tables", difficulty: "medium",
  },
  {
    id: "en-oca-q71", moduleId: "m6",
    question: "Which two statements about FULL OUTER JOIN are correct? (Choose two.)",
    options: [
      "It preserves the unmatched rows of both tables",
      "It can be written with the (+) operator on both sides",
      "It is equivalent to a UNION of a left and a right outer join",
      "It returns the same rows as a CROSS JOIN",
    ],
    correctIndexes: [0, 2],
    explanation: "A full outer join keeps everything from both sides and is indeed expressible as the union of a left and a right outer join. The legacy (+) operator cannot be placed on both sides — ORA-01468 — and a cross join ignores conditions altogether.",
    topic: "Displaying Data from Multiple Tables", difficulty: "hard",
  },

  // ══════════ 8. Using Subqueries to Solve Queries (m7) ══════════
  {
    id: "en-oca-q72", moduleId: "m7",
    question: "What is a single-row subquery?",
    options: [
      "A subquery returning exactly one row",
      "A subquery returning exactly one column",
      "A subquery placed in the FROM clause",
      "A subquery executed once per outer row",
    ],
    correctIndexes: [0],
    explanation: "A single-row subquery returns at most one row, which is what lets it be compared with =, > and the like. Returning more raises ORA-01427; a subquery executed once per outer row is a correlated subquery.",
    topic: "Using Subqueries to Solve Queries", difficulty: "medium",
  },
  {
    id: "en-oca-q73", moduleId: "m7",
    question: "Which operators suit a subquery returning several rows? (Choose two.)",
    options: ["IN", "=", "ANY", ">"],
    correctIndexes: [0, 2],
    explanation: "IN, ANY and ALL all accept several values. A bare comparison operator expects a single value and raises ORA-01427 as soon as the subquery returns more than one row.",
    topic: "Using Subqueries to Solve Queries", difficulty: "medium",
  },
  {
    id: "en-oca-q74", moduleId: "m7",
    question: "What is > ALL(subquery) equivalent to?",
    options: [
      "Greater than the minimum returned",
      "Greater than the maximum returned",
      "Greater than the average returned",
      "Greater than at least one value returned",
    ],
    correctIndexes: [1],
    explanation: "Being greater than every returned value means being greater than the largest, so > ALL is equivalent to > MAX. By the same reasoning > ANY is equivalent to > MIN — the pair is a classic exam confusion.",
    topic: "Using Subqueries to Solve Queries", difficulty: "hard",
  },
  {
    id: "en-oca-q75", moduleId: "m7",
    question: "What is a correlated subquery?",
    options: [
      "A subquery placed in the SELECT list",
      "A subquery returning a single value",
      "A subquery containing another subquery",
      "A subquery referencing a column of the outer query",
    ],
    correctIndexes: [3],
    explanation: "A correlated subquery references the outer query and is therefore evaluated once per candidate row. An uncorrelated one is evaluated a single time, its result reused throughout.",
    topic: "Using Subqueries to Solve Queries", difficulty: "medium",
  },
  {
    id: "en-oca-q76", moduleId: "m7",
    question: "Which operator tests whether a subquery returns at least one row?",
    options: ["EXISTS", "IN", "ANY", "HAVING"],
    correctIndexes: [0],
    explanation: "EXISTS stops at the first row found and returns a Boolean, without caring what the subquery projects — hence the SELECT 1 convention. IN compares values and behaves differently in the presence of NULLs.",
    topic: "Using Subqueries to Solve Queries", difficulty: "medium",
  },
  {
    id: "en-oca-q77", moduleId: "m7",
    question: "Why can NOT IN return no rows when the subquery contains a NULL?",
    options: [
      "Because NOT IN forbids NULL",
      "Because the comparison with NULL is unknown, never true",
      "Because Oracle rewrites NOT IN into NOT EXISTS",
      "Because NOT IN ignores NULLs",
    ],
    correctIndexes: [1],
    explanation: "NOT IN expands to a chain of != comparisons, and any comparison with NULL is unknown, so the whole condition never becomes true. NOT EXISTS does not suffer from this and is the safe form.",
    topic: "Using Subqueries to Solve Queries", difficulty: "hard",
  },
  {
    id: "en-oca-q78", moduleId: "m7",
    question: "What is a subquery placed in the FROM clause commonly called?",
    options: ["A scalar subquery", "A correlated subquery", "An inline view", "A materialized view"],
    correctIndexes: [2],
    explanation: "A subquery in FROM acts as an unnamed view for the duration of the statement — an inline view. A scalar subquery returns one value in the select list, and a materialized view is a stored object holding data.",
    topic: "Using Subqueries to Solve Queries", difficulty: "medium",
  },
  {
    id: "en-oca-q79", moduleId: "m7",
    question: "Which query returns the employees earning more than the company average?",
    options: [
      "SELECT * FROM employees WHERE salary > AVG(salary)",
      "SELECT * FROM employees WHERE salary > ALL(SELECT salary FROM employees)",
      "SELECT * FROM employees HAVING salary > AVG(salary)",
      "SELECT * FROM employees WHERE salary > (SELECT AVG(salary) FROM employees)",
    ],
    correctIndexes: [3],
    explanation: "The average must be computed by a subquery, because a group function cannot appear in WHERE — the first and third options raise ORA-00934 and ORA-00979. The fourth asks for more than the maximum, which returns nothing.",
    topic: "Using Subqueries to Solve Queries", difficulty: "medium",
  },
  {
    id: "en-oca-q80", moduleId: "m7",
    question: "Which two statements correctly update rows using a correlated subquery? (Choose two.)",
    options: [
      "UPDATE employees e SET salary = (SELECT AVG(salary) FROM employees WHERE department_id = e.department_id)",
      "UPDATE employees SET salary = AVG(salary) GROUP BY department_id",
      "DELETE FROM employees e WHERE EXISTS (SELECT 1 FROM departments d WHERE d.department_id = e.department_id AND d.location_id = 1700)",
      "DELETE FROM employees WHERE department_id = AVG(department_id)",
    ],
    correctIndexes: [0, 2],
    explanation: "Both valid forms reference the outer row — e.department_id — inside the subquery, which is exactly what makes them correlated. The other two place a group function directly in a DML statement, which Oracle rejects.",
    topic: "Using Subqueries to Solve Queries", difficulty: "hard",
  },
];
