import type { QuizQuestionTranslation } from "./types";

/**
 * English rendering of the 1Z0-084 bank (`quiz-data-tuning.ts`).
 * Keyed by question id; option order preserved.
 */
export const tuningEnglish: Record<string, QuizQuestionTranslation> = {
  "tun-q1": {
    question: "What is the first step of a rigorous tuning approach?",
    options: [
      "Define a measurable, quantified goal before changing anything",
      "Increase the SGA to rule out a memory lead",
      "Re-gather statistics on every schema",
      "Enable a 10046 trace on the whole instance",
    ],
    explanation: "Without a quantified goal — “this batch must finish under 4 minutes” — you can neither prove a gain nor know when to stop. Every other option is an action: those come after the diagnosis, never before it.",
    topic: "Methodology",
  },
  "tun-q2": {
    question: "What does the DB time time-model statistic measure?",
    options: [
      "Total time user sessions spend in the database, CPU and waits included",
      "CPU time consumed by background processes",
      "Execution time of the slowest query",
      "Time elapsed since instance startup",
    ],
    explanation: "DB time sums CPU time and wait time across all active user sessions. It is the reference measure of load: reducing DB time is what tuning means. Background processes are excluded.",
    topic: "Time model",
  },
  "tun-q3": {
    question: "Which views expose the time model? (Choose two.)",
    options: ["V$SYS_TIME_MODEL", "V$SESS_TIME_MODEL", "V$SQL_PLAN", "V$LOCK", "V$DATAFILE"],
    explanation: "V$SYS_TIME_MODEL gives the time model at instance level, V$SESS_TIME_MODEL per session. The other three views describe plans, locks and files.",
    topic: "Time model",
  },
  "tun-q4": {
    question: "At which lifecycle phase is tuning cheapest?",
    options: [
      "While designing the data model and the access paths",
      "During functional testing",
      "At the first production incident",
      "During an upgrade to a new release",
    ],
    explanation: "A poorly normalised model or a missing access path costs a few hours to fix on paper, and months once the application is written and the data loaded. Tuning in production is always the most constrained.",
    topic: "Lifecycle",
  },
  "tun-q5": {
    question: "A report shows a 92 % buffer cache hit ratio. What can you conclude?",
    options: [
      "Nothing reliable: a high hit ratio can accompany a very slow system",
      "The buffer cache is correctly sized",
      "I/O is not a problem",
      "DB_CACHE_SIZE should be reduced to free memory",
    ],
    explanation: "The hit ratio is a ratio, not a time. A query re-reading the same block a thousand times through an inefficient nested loop shows an excellent ratio while saturating the CPU. Only time — DB time, wait events — supports a conclusion.",
    topic: "Misleading indicators",
  },
  "tun-q6": {
    question: "What is the default AWR snapshot interval, and the default retention in 19c?",
    options: [
      "60 minutes, retained for 8 days",
      "30 minutes, retained for 7 days",
      "60 minutes, retained for 30 days",
      "15 minutes, retained for 14 days",
    ],
    explanation: "By default AWR takes a snapshot every 60 minutes and keeps them for 8 days. Both values change through DBMS_WORKLOAD_REPOSITORY.MODIFY_SNAPSHOT_SETTINGS.",
    topic: "AWR",
  },
  "tun-q7": {
    question: "How often does ASH sample active sessions?",
    options: ["Once per second", "Once every 10 seconds", "On every commit", "Once per AWR snapshot"],
    explanation: "ASH samples the state of every active session once a second into a circular SGA buffer (V$ACTIVE_SESSION_HISTORY). One tenth of those samples is persisted to DBA_HIST_ACTIVE_SESS_HISTORY.",
    topic: "ASH",
  },
  "tun-q8": {
    question: "An incident lasted three minutes, two hours ago. Which tool can analyse it?",
    options: [
      "ASH, which samples every second",
      "AWR, whose interval is hourly",
      "ADDM, which analyses an interval between two snapshots",
      "The Segment Advisor",
    ],
    explanation: "A three-minute spike dissolves inside a one-hour AWR snapshot, so ADDM — which builds on AWR — will not see it. ASH keeps a per-second trace and lets you target the exact interval.",
    topic: "ASH vs AWR",
  },
  "tun-q9": {
    question: "Which statements about ADDM are correct? (Choose three.)",
    options: [
      "It runs automatically after every AWR snapshot",
      "It ranks its findings by impact on DB time",
      "It produces quantified recommendations",
      "It applies its recommendations automatically",
      "It replaces statistics gathering",
    ],
    explanation: "ADDM runs after every snapshot, orders findings by share of DB time and quantifies the expected gain. It never changes anything by itself: the decision to apply stays human.",
    topic: "ADDM",
  },
  "tun-q10": {
    question: "What is an AWR baseline for?",
    options: [
      "Pinning a reference period so a future workload can be compared to it",
      "Backing up optimizer statistics",
      "Preventing archived log files from being purged",
      "Forcing a given execution plan",
    ],
    explanation: "An AWR baseline keeps the snapshots of a representative period — month-end close, say — indefinitely, so future behaviour can be compared to a known reference. It is exempt from automatic purging.",
    topic: "AWR baselines",
  },
  "tun-q11": {
    question: "Which package creates an AWR snapshot on demand?",
    options: [
      "DBMS_WORKLOAD_REPOSITORY.CREATE_SNAPSHOT",
      "DBMS_STATS.GATHER_DATABASE_STATS",
      "DBMS_ADVISOR.CREATE_TASK",
      "DBMS_MONITOR.SESSION_TRACE_ENABLE",
    ],
    explanation: "DBMS_WORKLOAD_REPOSITORY drives all of AWR: CREATE_SNAPSHOT, DROP_SNAPSHOT_RANGE, MODIFY_SNAPSHOT_SETTINGS and CREATE_BASELINE. Bracketing a test with two manual snapshots is the good practice.",
    topic: "AWR",
  },
  "tun-q12": {
    question: "Which option is required to use AWR, ASH and ADDM?",
    options: [
      "The Enterprise Edition Diagnostics Pack option",
      "The Tuning Pack option alone",
      "None: these tools are included in Standard Edition",
      "The Advanced Compression option",
    ],
    explanation: "AWR, ASH and ADDM belong to the Diagnostics Pack, licensed on top of Enterprise Edition. The CONTROL_MANAGEMENT_PACK_ACCESS parameter governs their use. Without that licence, Statspack is the free alternative.",
    topic: "Licensing",
  },
  "tun-q13": {
    question: "What does the “db file sequential read” wait event indicate?",
    options: [
      "A single-block read, typically an index access",
      "A multi-block read, typically a full scan",
      "A DBWn write to the data files",
      "A wait on the redo log",
    ],
    explanation: "Despite its name, “sequential read” means one block at a time — index access. It is “db file scattered read” that corresponds to the multi-block read of a full scan. The vocabulary is counter-intuitive and appears regularly on the exam.",
    topic: "Wait events",
  },
  "tun-q14": {
    question: "A session waits on “log file sync”. What is the most likely cause?",
    options: [
      "Commits that are too frequent, or slow storage for the redo logs",
      "A buffer cache that is too small",
      "Stale statistics",
      "A full scan on a large table",
    ],
    explanation: "“log file sync” measures a session waiting while LGWR writes redo at COMMIT. Two causes: too many commits (a loop committing row by row), or slow redo log storage. Neither the cache nor statistics play any part.",
    topic: "Wait events",
  },
  "tun-q15": {
    question: "Which wait classes are systematically considered idle? (Choose two.)",
    options: ["Idle", "Network", "User I/O", "Concurrency", "Configuration"],
    explanation: "The Idle class covers a session at rest (SQL*Net message from client). The Network class measures network exchanges, often outside the database's scope. The other three describe real waits to analyse.",
    topic: "Wait classes",
  },
  "tun-q16": {
    question: "Which view gives a session's current wait, at the moment you query it?",
    options: ["V$SESSION", "V$SESSION_EVENT", "V$SYSTEM_EVENT", "DBA_HIST_SNAPSHOT"],
    explanation: "Since 10g, V$SESSION carries EVENT, WAIT_CLASS and STATE directly: that is the snapshot. V$SESSION_EVENT accumulates since connection, V$SYSTEM_EVENT since instance startup.",
    topic: "Diagnostic views",
  },
  "tun-q17": {
    question: "Which package sets an alert threshold on a metric?",
    options: [
      "DBMS_SERVER_ALERT.SET_THRESHOLD",
      "DBMS_ALERT.SIGNAL",
      "DBMS_STATS.SET_TABLE_PREFS",
      "DBMS_MONITOR.CLIENT_ID_TRACE_ENABLE",
    ],
    explanation: "DBMS_SERVER_ALERT.SET_THRESHOLD attaches a warning and a critical threshold to a metric. Triggered alerts appear in DBA_OUTSTANDING_ALERTS then DBA_ALERT_HISTORY. DBMS_ALERT is an unrelated application-level mechanism.",
    topic: "Thresholds and alerts",
  },
  "tun-q18": {
    question: "A stateful alert leaves DBA_OUTSTANDING_ALERTS when:",
    options: [
      "The condition that raised it stops being true",
      "An administrator clears it manually",
      "The instance restarts",
      "AWR retention expires",
    ],
    explanation: "A stateful alert — a tablespace at 90 %, say — tracks a persisting condition: it clears itself as soon as the condition no longer holds and moves to history. A stateless alert, by contrast, must be cleared by hand.",
    topic: "Alerts",
  },
  "tun-q19": {
    question: "In which order do the phases of SQL statement processing run?",
    options: [
      "Parse, optimization, row source generation, execution, fetch",
      "Optimization, parse, execution, fetch",
      "Parse, execution, optimization, fetch",
      "Plan generation, parse, fetch, execution",
    ],
    explanation: "Parse (syntax, semantics, shared pool lookup), then optimization by the CBO, then plan generation by the row source generator, then execution, and finally fetch for queries. A soft parse skips optimization.",
    topic: "SQL processing",
  },
  "tun-q20": {
    question: "What essential difference separates EXPLAIN PLAN from DBMS_XPLAN.DISPLAY_CURSOR?",
    options: [
      "EXPLAIN PLAN predicts a plan without executing; DISPLAY_CURSOR shows the plan actually used",
      "EXPLAIN PLAN is more accurate because it accounts for bind variables",
      "DISPLAY_CURSOR only works on materialized views",
      "Both always produce the same result",
    ],
    explanation: "EXPLAIN PLAN predicts what the optimizer would do, with no bind peeking and no execution. DISPLAY_CURSOR reads the plan of the cursor that actually ran, with estimated and actual rows when GATHER_PLAN_STATISTICS is used. For diagnosis, DISPLAY_CURSOR is authoritative.",
    topic: "Execution plans",
  },
  "tun-q21": {
    question: "In a plan obtained with the ALLSTATS LAST format, a wide gap between E-Rows and A-Rows indicates:",
    options: [
      "A wrong cardinality estimate, often caused by unsuitable statistics",
      "A locking problem",
      "Insufficient PGA space",
      "Adaptive plans being disabled",
    ],
    explanation: "E-Rows is the optimizer's estimate, A-Rows the reality. A factor of ten or more means the optimizer is working from a wrong picture of the data: stale statistics, correlated columns, a complex predicate. It is the first thing to check on a plan.",
    topic: "Cardinality",
  },
  "tun-q22": {
    question: "Which statements about adaptive plans are correct? (Choose two.)",
    options: [
      "The optimizer can change join method during the first execution",
      "A statistics collector counts actual rows at execution time",
      "They replace SQL plan baselines",
      "They are disabled by default in 19c",
    ],
    explanation: "An adaptive plan embeds an alternative subplan and a statistics collector: if the actual row count crosses a threshold, the optimizer switches from nested loops to hash join mid-execution. OPTIMIZER_ADAPTIVE_PLANS is TRUE by default in 19c.",
    topic: "Adaptive plans",
  },
  "tun-q23": {
    question: "What is a SQL plan directive?",
    options: [
      "A persistent note telling the optimizer to use an extra mechanism on a set of columns",
      "A frozen plan imposed on a statement",
      "A SQL profile generated by SQL Tuning Advisor",
      "An integrity constraint on statistics",
    ],
    explanation: "A directive is born from a repeated misestimate: the optimizer records that a column group is badly estimated and triggers dynamic sampling or the creation of extended statistics. It applies to columns, not to a statement — unlike a profile or a baseline.",
    topic: "Plan directives",
  },
  "tun-q24": {
    question: "What does automatic reoptimization do?",
    options: [
      "It corrects the plan on SUBSEQUENT executions, from the gaps observed",
      "It changes the plan mid-execution",
      "It re-gathers the table's statistics",
      "It invalidates the whole shared pool",
    ],
    explanation: "Unlike an adaptive plan, which acts during execution, reoptimization records the cardinality gaps observed and reuses them at the next hard parse. The IS_REOPTIMIZABLE column of V$SQL flags an affected cursor.",
    topic: "Reoptimization",
  },
  "tun-q25": {
    question: "Which ESTIMATE_PERCENT value has been recommended since 11g?",
    options: [
      "DBMS_STATS.AUTO_SAMPLE_SIZE",
      "100, for maximum accuracy",
      "10, as a compromise",
      "1, for speed",
    ],
    explanation: "Since 11g AUTO_SAMPLE_SIZE relies on a single-pass hashing algorithm that delivers the accuracy of a 100 % sample at the cost of a reduced one. Setting a percentage by hand has become counter-productive.",
    topic: "Statistics gathering",
  },
  "tun-q26": {
    question: "What is a column histogram for?",
    options: [
      "Describing an uneven value distribution so estimates get sharper",
      "Speeding up inserts",
      "Replacing an index",
      "Compressing the column's data",
    ],
    explanation: "Without a histogram the optimizer assumes values are evenly spread. On a STATUS column where 99 % of rows read “closed”, that assumption produces an absurd estimate. The histogram describes the real distribution.",
    topic: "Histograms",
  },
  "tun-q27": {
    question: "Which histogram types were introduced in 12c? (Choose two.)",
    options: ["Hybrid", "Top-Frequency", "Frequency", "Height-Balanced", "Bitmap"],
    explanation: "12c adds the hybrid histogram — which combines frequency and height-balanced — and top-frequency, which keeps only the dominant values. Frequency and height-balanced already existed; “bitmap” is an index type, not a histogram.",
    topic: "Histograms",
  },
  "tun-q28": {
    question: "What do extended statistics enable?",
    options: [
      "Describing correlation between several columns, or an expression",
      "Keeping statistics history longer",
      "Gathering system statistics",
      "Extending AWR to standby databases",
    ],
    explanation: "The optimizer assumes predicates are independent: on CITY = 'Lyon' AND DEPARTMENT = 69 it multiplies two selectivities and grossly underestimates. A column group created by DBMS_STATS.CREATE_EXTENDED_STATS restores the real correlation.",
    topic: "Extended statistics",
  },
  "tun-q29": {
    question: "How long is statistics history kept by default?",
    options: ["31 days", "8 days", "7 days", "90 days"],
    explanation: "DBMS_STATS keeps 31 days of history by default, which makes DBMS_STATS.RESTORE_TABLE_STATS possible after a gather that degraded a plan. The value is read with GET_STATS_HISTORY_RETENTION and changed with ALTER_STATS_HISTORY_RETENTION.",
    topic: "Statistics history",
  },
  "tun-q30": {
    question: "Which parameter controls the degree of dynamic sampling?",
    options: [
      "OPTIMIZER_DYNAMIC_SAMPLING",
      "OPTIMIZER_INDEX_COST_ADJ",
      "OPTIMIZER_MODE",
      "DB_FILE_MULTIBLOCK_READ_COUNT",
    ],
    explanation: "OPTIMIZER_DYNAMIC_SAMPLING ranges from 0 to 11. Value 11 lets the optimizer decide by itself when to sample at parse time — the behaviour adopted by adaptive sampling from 12c onwards.",
    topic: "Optimizer parameters",
  },
  "tun-q31": {
    question: "Which automated maintenance task gathers stale statistics?",
    options: [
      "auto optimizer stats collection",
      "auto space advisor",
      "sql tuning advisor",
      "auto segment shrink",
    ],
    explanation: "Three tasks run in the maintenance window: auto optimizer stats collection, auto space advisor and sql tuning advisor. The first re-gathers statistics for objects whose rows have changed by more than 10 %.",
    topic: "Automated tasks",
  },
  "tun-q32": {
    question: "What is the difference between a SQL profile and a SQL plan baseline?",
    options: [
      "The profile corrects the optimizer's estimates; the baseline pins a set of accepted plans",
      "The profile pins a plan; the baseline corrects estimates",
      "Both pin the same plan, only the name differs",
      "A baseline only applies to materialized views",
    ],
    explanation: "A SQL profile hands the optimizer cardinality correction factors: the plan can still evolve. A baseline lists explicitly accepted plans and forbids any new plan until it is verified. The profile guides, the baseline locks.",
    topic: "Profiles and baselines",
  },
  "tun-q33": {
    question: "What does SQL Access Advisor recommend?",
    options: [
      "Indexes, materialized views and partitioning for a workload",
      "A rewrite of the SQL statement",
      "SGA sizing",
      "A backup strategy",
    ],
    explanation: "SQL Access Advisor reasons about access structures for a whole workload: indexes, materialized views, materialized view logs, partitioning. SQL Tuning Advisor works statement by statement.",
    topic: "Advisors",
  },
  "tun-q34": {
    question: "Which recommendations can SQL Tuning Advisor produce? (Choose three.)",
    options: [
      "Accepting a SQL profile",
      "Gathering missing or stale statistics",
      "Creating an index",
      "Increasing the buffer cache",
      "Changing the archiving mode",
    ],
    explanation: "SQL Tuning Advisor analyses one statement and may recommend a profile, statistics, an index or a rewrite. Memory sizing belongs to the Memory Advisor; archiving has nothing to do with tuning a query.",
    topic: "SQL Tuning Advisor",
  },
  "tun-q35": {
    question: "What does DBMS_SPM.EVOLVE_SQL_PLAN_BASELINE do?",
    options: [
      "Verifies that a new plan performs better before accepting it",
      "Drops every baseline in a schema",
      "Forces the use of the latest plan found",
      "Re-gathers statistics on the objects involved",
    ],
    explanation: "When the optimizer finds a plan absent from the baseline, it records it as unaccepted. EVOLVE runs it and compares it to the accepted plan: it is promoted only if it does better. That is what stops a plan regression from winning silently.",
    topic: "SQL Plan Management",
  },
  "tun-q36": {
    question: "Which parameter enables Automatic Memory Management (AMM) across both SGA and PGA?",
    options: ["MEMORY_TARGET", "SGA_TARGET", "PGA_AGGREGATE_TARGET", "DB_CACHE_SIZE"],
    explanation: "MEMORY_TARGET drives AMM and arbitrates between SGA and PGA. SGA_TARGET alone enables ASMM, which only tunes SGA components. PGA_AGGREGATE_TARGET caps session work-area memory.",
    topic: "Memory management",
  },
  "tun-q37": {
    question: "Which view quantifies the gain expected from a larger buffer cache?",
    options: [
      "V$DB_CACHE_ADVICE",
      "V$SGA_DYNAMIC_COMPONENTS",
      "V$PGA_TARGET_ADVICE",
      "V$SHARED_POOL_ADVICE",
    ],
    explanation: "V$DB_CACHE_ADVICE simulates several cache sizes and reports, for each, how many physical reads would be avoided. It is a quantified decision table, to be preferred over the hit ratio.",
    topic: "Memory advisors",
  },
  "tun-q38": {
    question: "A decision-support workload produces many disk sorts. Which lever comes first?",
    options: [
      "Increase PGA_AGGREGATE_TARGET",
      "Increase DB_CACHE_SIZE",
      "Increase SHARED_POOL_SIZE",
      "Reduce LOG_BUFFER",
    ],
    explanation: "Sorts, hashes and index builds consume session work-area memory, governed by PGA_AGGREGATE_TARGET. Spilling shows up in V$SQL_WORKAREA_HISTOGRAM (multi-pass) and in “direct path read temp” waits.",
    topic: "PGA",
  },
  "tun-q39": {
    question: "What is the consequence of an undersized shared pool?",
    options: [
      "Excessive hard parsing and ORA-04031 errors",
      "Extra physical reads on tables",
      "Disk sorts",
      "A slower DBWn",
    ],
    explanation: "The shared pool hosts the library cache and the dictionary cache. Too small, it evicts cursors, which forces constant re-parsing and can raise ORA-04031. Missing bind variables produce the same symptom without size being the cause.",
    topic: "Shared pool",
  },
  "tun-q40": {
    question: "Which tool measures storage I/O capacity independently of the SQL workload?",
    options: [
      "DBMS_RESOURCE_MANAGER.CALIBRATE_IO",
      "DBMS_STATS.GATHER_SYSTEM_STATS",
      "DBMS_ADVISOR.QUICK_TUNE",
      "DBMS_MONITOR.DATABASE_TRACE_ENABLE",
    ],
    explanation: "CALIBRATE_IO puts the storage under random and sequential read load and returns maximum IOPS, throughput and latency. Results feed V$IO_CALIBRATION_STATUS and serve as an objective baseline.",
    topic: "I/O",
  },
  "tun-q41": {
    question: "High “buffer busy waits” on a segment indicates:",
    options: [
      "Several sessions contending for the same in-memory block",
      "A failing disk",
      "Stale statistics",
      "A saturated shared pool",
    ],
    explanation: "These are hot blocks: a segment header block, the trailing block of an ascending-key index, a single counter row. The remedies are structural — reverse-key index, cached sequence, ASSM, more freelists — not hardware.",
    topic: "Concurrency",
  },
  "tun-q42": {
    question: "What does the “enq: TX - row lock contention” wait indicate?",
    options: [
      "A session waits for another to commit or roll back on the same row",
      "A lock on a table definition",
      "Redo log saturation",
      "A block on the control file",
    ],
    explanation: "A TX lock in exclusive mode signals row-level contention: the blocked session waits for the blocker's COMMIT or ROLLBACK. V$SESSION.BLOCKING_SESSION names the culprit directly. A lock on an object definition would be enq: TM.",
    topic: "Locking",
  },
  "tun-q43": {
    question: "In which case is Statspack still relevant in 19c?",
    options: [
      "When the Diagnostics Pack is not licensed",
      "When the database runs in NOARCHIVELOG mode",
      "When the database exceeds 10 TB",
      "When the database is a standby",
    ],
    explanation: "Statspack is free and shipped with the database: it remains the only legal historical instrumentation when AWR — hence the Diagnostics Pack — has not been purchased. It installs through spcreate.sql under the PERFSTAT user.",
    topic: "Statspack",
  },
  "tun-q44": {
    question: "Which 10046 trace level includes both bind variable values and wait events?",
    options: ["Level 12", "Level 4", "Level 8", "Level 1"],
    explanation: "Level 1: basic trace. Level 4: adds bind variables. Level 8: adds wait events. Level 12: both, that is 4 + 8. It is the level used for a complete diagnosis.",
    topic: "SQL Trace",
  },
  "tun-q45": {
    question: "Above which threshold is a statement automatically tracked by Real-Time SQL Monitoring?",
    options: [
      "5 seconds of CPU or I/O, or a parallel execution",
      "1 second of elapsed time",
      "30 seconds of elapsed time",
      "As soon as it reads more than 1,000 blocks",
    ],
    explanation: "Tracking starts by itself as soon as a statement consumes 5 seconds of CPU or I/O, or as soon as it runs in parallel. The /*+ MONITOR */ hint forces it on a shorter statement. The data is read in V$SQL_MONITOR.",
    topic: "SQL Monitoring",
  },
  "tun-q46": {
    question: "What does DBMS_SQL_MONITOR.BEGIN_OPERATION allow?",
    options: [
      "Grouping several statements into one operation tracked end to end",
      "Forcing an execution plan",
      "Creating an AWR snapshot",
      "Enabling tracing for a service",
    ],
    explanation: "BEGIN_OPERATION / END_OPERATION delimit a composite database operation — a nightly batch, a multi-step load — and let you obtain a single report covering the whole, instead of separate per-statement reports.",
    topic: "Database Operations Monitoring",
  },
  "tun-q47": {
    question: "Which utility formats a raw trace file produced by SQL Trace?",
    options: ["tkprof", "adrci", "orapwd", "expdp"],
    explanation: "tkprof turns the raw trace into a readable report, with parse/execute/fetch counters, elapsed time and waits. adrci navigates the diagnostic repository, without formatting SQL traces.",
    topic: "SQL Trace",
  },
  "tun-q48": {
    question: "Which parameter enables the In-Memory column store?",
    options: ["INMEMORY_SIZE", "MEMORY_TARGET", "DB_CACHE_SIZE", "RESULT_CACHE_MAX_SIZE"],
    explanation: "INMEMORY_SIZE reserves a dedicated area of the SGA, distinct from the buffer cache. The parameter cannot be reduced dynamically and requires a restart when first enabled. The Database In-Memory option is licensed separately.",
    topic: "In-Memory",
  },
  "tun-q49": {
    question: "Which statements about the In-Memory column store are correct? (Choose three.)",
    options: [
      "It stores data by column, in addition to the row format on disk",
      "It speeds up analytics scanning many rows and few columns",
      "It does not replace indexes for single-row access",
      "It makes data files unnecessary",
      "It can only be enabled for the entire database",
    ],
    explanation: "In-Memory duplicates data in column format in memory — the row format persists on disk, unchanged. It excels at analytic scans, is useless for a primary-key lookup, and is enabled table by table, partition by partition.",
    topic: "In-Memory",
  },
  "tun-q50": {
    question: "Which RESULT_CACHE_MODE value caches only queries carrying the RESULT_CACHE hint?",
    options: ["MANUAL", "FORCE", "AUTO", "NONE"],
    explanation: "MANUAL is the default: only queries annotated /*+ RESULT_CACHE */ are cached. FORCE tries to cache everything and almost always causes contention on the “Result Cache: RC Latch” latch.",
    topic: "Result Cache",
  },
  "tun-q51": {
    question: "When is a result cache entry invalidated?",
    options: [
      "As soon as a transaction modifies any object the result depends on",
      "At every AWR snapshot",
      "After one hour",
      "Only when the instance restarts",
    ],
    explanation: "Invalidation is immediate and dependency-based: any committed DML on a source table makes results derived from it unusable. That is why the result cache suits rarely modified reference tables, not transactional ones.",
    topic: "Result Cache",
  },
};
