import type { QuizQuestion } from "./types";

/**
 * Complément de la banque 1Z0-082 — couvre les concepts corrigés de
 * `docs/OCA/ocp 1/OCP.docx` + `Reponses.docx` non traités dans
 * `lib/quiz-data-ocp1.ts`.
 *
 * Les 142 corrigés du document ne portent que **100 concepts distincts** :
 * 42 numéros répètent un point déjà testé ailleurs. Une question est écrite
 * par concept distinct, jamais par numéro — pour ne pas reproduire le défaut
 * de doublons relevé dans le workbook (constat PED-02).
 */
export const ocp1QuestionsB: QuizQuestion[] = [
  // ─── Architecture et instance ───────────────────────────────────────────
  {
    id: "ocp1-q50", track: "ocp-dba-i", moduleId: "ocp1-session-2",
    question: "À l'état NOMOUNT, quel fichier Oracle a-t-il lu ?",
    options: ["Le fichier de contrôle", "Le fichier de paramètres (SPFILE ou PFILE)", "Les fichiers de données", "Les fichiers de journalisation"],
    correctIndexes: [1],
    explanation: "NOMOUNT se limite à lire le fichier de paramètres pour allouer la SGA et démarrer les processus. Le fichier de contrôle n'est lu qu'au MOUNT, les datafiles et redo logs qu'à l'OPEN.",
    topic: "État NOMOUNT", difficulty: "medium",
  },
  {
    id: "ocp1-q51", track: "ocp-dba-i", moduleId: "ocp1-session-2",
    question: "Un ALTER SYSTEM est exécuté sans clause SCOPE, l'instance ayant démarré sur un PFILE. Que se passe-t-il ?",
    options: ["La modification s'applique à l'instance courante uniquement et disparaît au redémarrage", "Elle est écrite dans le PFILE", "L'instruction échoue", "Elle s'applique au prochain démarrage seulement"],
    correctIndexes: [0],
    explanation: "Sans SPFILE, la seule portée acceptée est MEMORY : le changement vit le temps de l'instance. Avec un SPFILE, l'absence de SCOPE équivaut à BOTH, donc mémoire et fichier.",
    topic: "ALTER SYSTEM sans SCOPE", difficulty: "hard",
  },
  {
    id: "ocp1-q52", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quels processus écrivent des fichiers de trace dans l'ADR ? (Choisissez deux réponses.)",
    options: ["Les processus d'arrière-plan", "Les processus serveur", "Le processus client SQL*Plus", "L'écouteur uniquement"],
    correctIndexes: [0, 1],
    explanation: "Les deux familles produisent des traces : les processus d'arrière-plan dans leur répertoire dédié, les processus serveur dans celui des traces utilisateur. L'ADR couvre aussi l'écouteur, mais dans une arborescence distincte.",
    topic: "Fichiers de trace", difficulty: "medium",
  },
  {
    id: "ocp1-q53", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles vues permettent d'analyser les attentes d'une session ? (Choisissez deux réponses.)",
    options: ["V$SESSION_WAIT", "V$SESSION", "V$PARAMETER", "V$CONTROLFILE"],
    correctIndexes: [0, 1],
    explanation: "V$SESSION_WAIT expose l'attente en cours d'une session ; depuis la 10g, V$SESSION porte elle aussi les colonnes d'attente. V$SESSION_EVENT cumule les attentes depuis la connexion.",
    topic: "Diagnostic des attentes", difficulty: "medium",
  },
  {
    id: "ocp1-q54", track: "ocp-dba-i", moduleId: "ocp1-session-4",
    question: "Pourquoi la génération d'undo produit-elle elle-même du redo ?",
    options: ["Parce que l'undo est stocké dans des segments d'une base qui doit rester récupérable", "Parce que l'undo est écrit dans les redo logs", "Parce que le redo remplace l'undo après un COMMIT", "C'est faux : l'undo ne génère aucun redo"],
    correctIndexes: [0],
    explanation: "Les segments d'undo sont des blocs de données comme les autres : toute modification doit être journalisée pour qu'une récupération d'instance puisse les reconstruire. Une transaction génère donc du redo pour la donnée et pour son undo.",
    topic: "Undo et redo", difficulty: "hard",
  },

  // ─── Stockage ───────────────────────────────────────────────────────────
  {
    id: "ocp1-q55", track: "ocp-dba-i", moduleId: "ocp1-session-4",
    question: "Quelles affirmations sont exactes concernant un tablespace BIGFILE ? (Choisissez deux réponses.)",
    options: ["Il ne comporte qu'un seul fichier de données", "Ce fichier peut être en extension automatique", "Il accepte jusqu'à 1 022 fichiers", "Il impose une gestion des extents par le dictionnaire"],
    correctIndexes: [0, 1],
    explanation: "Un BIGFILE n'a qu'un fichier, mais beaucoup plus grand qu'en SMALLFILE grâce à un adressage différent. AUTOEXTEND reste possible. C'est le SMALLFILE qui accepte jusqu'à 1 022 fichiers — un smallfile multi-fichiers peut donc dépasser un bigfile.",
    topic: "BIGFILE et SMALLFILE", difficulty: "hard",
  },
  {
    id: "ocp1-q56", track: "ocp-dba-i", moduleId: "ocp1-session-4",
    question: "Quelles affirmations sont exactes sur la relation entre segments, extents et fichiers ? (Choisissez deux réponses.)",
    options: ["Un segment peut s'étendre sur plusieurs fichiers de données du même tablespace", "Un segment peut n'occuper qu'un seul extent", "Un extent peut chevaucher deux fichiers de données", "Un segment appartient forcément à un seul extent"],
    correctIndexes: [0, 1],
    explanation: "Un segment grandit par extents qui peuvent se répartir sur tous les fichiers du tablespace. Un extent, lui, est toujours contigu dans un seul fichier. Un segment tout juste créé n'a qu'un extent.",
    topic: "Segments et extents", difficulty: "hard",
  },
  {
    id: "ocp1-q57", track: "ocp-dba-i", moduleId: "ocp1-session-4",
    question: "Quelles affirmations sont exactes concernant les segments d'undo ? (Choisissez trois réponses.)",
    options: ["Ils s'étendent automatiquement si le tablespace le permet", "Plusieurs transactions peuvent partager un même segment d'undo", "Un segment d'undo peut reboucler sur son premier extent une fois l'undo expiré", "Chaque transaction obtient un tablespace d'undo dédié", "Ils sont stockés dans le tablespace temporaire"],
    correctIndexes: [0, 1, 2],
    explanation: "Les segments d'undo sont circulaires : ils s'étendent tant que le tablespace le permet, puis réutilisent leurs premiers extents dès que l'undo qu'ils contiennent a dépassé la rétention. Plusieurs transactions peuvent y coexister.",
    topic: "Segments d'undo", difficulty: "hard",
  },
  {
    id: "ocp1-q58", track: "ocp-dba-i", moduleId: "ocp1-session-4",
    question: "Une transaction échoue avec ORA-30036 « unable to extend segment in undo tablespace ». Quelle est la cause ?",
    options: ["Le tablespace d'undo est saturé et ne peut plus s'étendre", "Le quota de l'utilisateur est atteint", "Le tablespace temporaire est plein", "Les redo logs sont pleins"],
    correctIndexes: [0],
    explanation: "ORA-30036 signale un tablespace d'undo à court d'espace. On l'agrandit, on active AUTOEXTEND, ou l'on abaisse UNDO_RETENTION — à ne pas confondre avec ORA-01555, qui concerne un undo écrasé trop tôt.",
    topic: "ORA-30036", difficulty: "medium",
  },
  {
    id: "ocp1-q59", track: "ocp-dba-i", moduleId: "ocp1-session-4",
    question: "Quels effets a RETENTION GUARANTEE sur un tablespace d'undo ? (Choisissez deux réponses.)",
    options: ["L'undo non expiré n'est jamais écrasé", "Les erreurs « snapshot too old » deviennent rares", "Les nouvelles transactions ne peuvent plus échouer", "La rétention devient illimitée"],
    correctIndexes: [0, 1],
    explanation: "La garantie de rétention protège l'undo jusqu'à l'expiration d'UNDO_RETENTION, ce qui fait quasiment disparaître ORA-01555. Le prix à payer est l'inverse : une transaction peut désormais échouer faute de place plutôt que d'écraser de l'undo encore utile.",
    topic: "RETENTION GUARANTEE", difficulty: "hard",
  },
  {
    id: "ocp1-q60", track: "ocp-dba-i", moduleId: "ocp1-session-4",
    question: "Quelle syntaxe de compression maintient le gain lors des DML ordinaires ?",
    options: ["COMPRESS BASIC", "ROW STORE COMPRESS ADVANCED", "COMPRESS FOR QUERY LOW", "NOCOMPRESS"],
    correctIndexes: [1],
    explanation: "ROW STORE COMPRESS ADVANCED recompresse les blocs au fil des insertions et mises à jour. BASIC ne compresse que le chemin direct, et les modes FOR QUERY relèvent d'Hybrid Columnar Compression, réservé à certains stockages.",
    topic: "Compression avancée", difficulty: "medium",
  },
  {
    id: "ocp1-q61", track: "ocp-dba-i", moduleId: "ocp1-session-4",
    question: "Quelles conditions permettent de renommer un fichier de données ? (Choisissez deux réponses.)",
    options: ["Mettre le tablespace hors ligne, la base restant ouverte", "Monter la base sans l'ouvrir", "Avoir la base en NOARCHIVELOG", "Supprimer d'abord le tablespace"],
    correctIndexes: [0, 1],
    explanation: "Renommer suppose que le fichier ne soit pas en cours d'utilisation : soit on met son tablespace hors ligne base ouverte, soit on travaille à l'état MOUNT. Il faut copier le fichier au niveau du système avant d'exécuter ALTER DATABASE RENAME FILE.",
    topic: "Renommer un datafile", difficulty: "hard",
  },
  {
    id: "ocp1-q62", track: "ocp-dba-i", moduleId: "ocp1-session-4",
    question: "Comment créer un tablespace sans indiquer de chemin de fichier ?",
    options: ["En définissant DB_CREATE_FILE_DEST", "En omettant la clause DATAFILE, sans autre réglage", "En utilisant BIGFILE", "Ce n'est pas possible"],
    correctIndexes: [0],
    explanation: "Le paramètre DB_CREATE_FILE_DEST active les Oracle Managed Files : Oracle nomme et place lui-même le fichier, et le supprime avec le tablespace. Sans ce paramètre, la clause DATAFILE reste obligatoire.",
    topic: "Oracle Managed Files", difficulty: "medium",
  },

  // ─── Sécurité et objets ─────────────────────────────────────────────────
  {
    id: "ocp1-q63", track: "ocp-dba-i", moduleId: "ocp1-session-3",
    question: "Quelle clause crée un compte dont l'authentification est déléguée au système d'exploitation ?",
    options: ["IDENTIFIED BY VALUES", "IDENTIFIED EXTERNALLY", "IDENTIFIED GLOBALLY", "IDENTIFIED BY OS"],
    correctIndexes: [1],
    explanation: "IDENTIFIED EXTERNALLY délègue au système : le nom du compte est préfixé par OS_AUTHENT_PREFIX, souvent OPS$. IDENTIFIED GLOBALLY délègue à un annuaire d'entreprise.",
    topic: "Authentification externe", difficulty: "medium",
  },
  {
    id: "ocp1-q64", track: "ocp-dba-i", moduleId: "ocp1-session-3",
    question: "Quelles affirmations sont exactes sur les clés d'une table ? (Choisissez trois réponses.)",
    options: ["Une table n'admet qu'une seule clé primaire", "Une table peut porter plusieurs clés étrangères", "ON DELETE SET NULL et ON DELETE CASCADE sont deux comportements possibles", "Une contrainte ne peut être déclarée qu'au niveau colonne", "Une clé étrangère impose une clé primaire sur la table enfant"],
    correctIndexes: [0, 1, 2],
    explanation: "Une seule clé primaire, autant de clés étrangères que nécessaire, et deux actions référentielles au choix à la suppression du parent. Les contraintes se déclarent au niveau colonne ou table — le niveau table étant obligatoire pour une clé composite.",
    topic: "Contraintes référentielles", difficulty: "medium",
  },
  {
    id: "ocp1-q65", track: "ocp-dba-i", moduleId: "ocp1-session-3",
    question: "Quelles affirmations sont exactes concernant la suppression de colonnes ? (Choisissez trois réponses.)",
    options: ["Une colonne de clé primaire peut être supprimée avec CASCADE CONSTRAINTS", "Une colonne marquée UNUSED compte toujours dans la limite de 1 000 colonnes", "Une colonne de clé de partition ne peut pas être supprimée", "Toutes les colonnes d'une table peuvent être supprimées", "SET UNUSED libère immédiatement l'espace"],
    correctIndexes: [0, 1, 2],
    explanation: "CASCADE CONSTRAINTS lève les dépendances qui bloqueraient la suppression. Une colonne UNUSED reste comptabilisée tant que DROP UNUSED COLUMNS n'a pas été exécuté — et n'a donc rien libéré. Une table doit conserver au moins une colonne, et les clés de partition sont intouchables.",
    topic: "Suppression de colonnes", difficulty: "hard",
  },
  {
    id: "ocp1-q66", track: "ocp-dba-i", moduleId: "ocp1-session-3",
    question: "Quelles affirmations sont exactes sur les vues du dictionnaire de données ? (Choisissez trois réponses.)",
    options: ["Les familles USER_, ALL_ et DBA_ reposent sur les mêmes tables de base", "Le dictionnaire appartient au schéma SYS", "Les utilisateurs y accèdent par des vues, jamais par les tables de base", "Le dictionnaire est modifiable par un DML direct", "Il réside dans le tablespace SYSAUX"],
    correctIndexes: [0, 1, 2],
    explanation: "Les trois familles ne sont que des vues de périmètres différents sur les mêmes tables internes, propriété de SYS et logées dans SYSTEM. Toute modification directe de ces tables corrompt la base : le dictionnaire ne s'écrit que par du DDL.",
    topic: "Dictionnaire de données", difficulty: "medium",
  },
  {
    id: "ocp1-q67", track: "ocp-dba-i", moduleId: "ocp1-session-3",
    question: "Quelles affirmations sont exactes concernant l'usage d'une séquence par défaut sur une colonne ? (Choisissez deux réponses.)",
    options: ["Le privilège SELECT sur la séquence est requis pour l'utilisateur qui insère", "La séquence peut alimenter une clause DEFAULT depuis la 12c", "La séquence garantit l'absence de trous", "Une séquence ne peut servir qu'une seule table"],
    correctIndexes: [0, 1],
    explanation: "Depuis la 12c, une colonne peut porter DEFAULT ma_sequence.NEXTVAL ; l'insertion exige alors le privilège SELECT sur la séquence. Les trous restent normaux, et rien n'empêche plusieurs tables de partager une séquence.",
    topic: "Séquences et DEFAULT", difficulty: "hard",
  },
  {
    id: "ocp1-q68", track: "ocp-dba-i", moduleId: "ocp1-session-3",
    question: "Quelles opérations sont impossibles à travers une vue comportant GROUP BY ? (Choisissez deux réponses.)",
    options: ["INSERT", "DELETE", "SELECT", "Création d'un synonyme sur la vue"],
    correctIndexes: [0, 1],
    explanation: "Une vue devient non modifiable dès qu'elle agrège : GROUP BY, DISTINCT, fonction de groupe, ROWNUM ou opérateur ensembliste interdisent INSERT, UPDATE et DELETE. La lecture et les synonymes restent possibles ; un trigger INSTEAD OF lève la restriction.",
    topic: "Vues non modifiables", difficulty: "medium",
  },

  // ─── SQL, fonctions et requêtes ─────────────────────────────────────────
  {
    id: "ocp1-q69", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles affirmations sont exactes concernant la priorité des opérateurs dans une clause WHERE ? (Choisissez deux réponses.)",
    options: ["À priorité égale, l'évaluation se fait de gauche à droite", "Les parenthèses modifient l'ordre d'évaluation", "OR est évalué avant AND", "NOT est évalué en dernier"],
    correctIndexes: [0, 1],
    explanation: "L'ordre est NOT, puis AND, puis OR ; à priorité identique on évalue de gauche à droite. Les parenthèses priment sur tout — d'où l'intérêt d'en mettre systématiquement dès qu'un OR côtoie un AND.",
    topic: "Priorité des opérateurs", difficulty: "medium",
  },
  {
    id: "ocp1-q70", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles affirmations sont exactes concernant DISTINCT ? (Choisissez deux réponses.)",
    options: ["DISTINCT peut porter sur une expression de concaténation", "DISTINCT porte sur l'ensemble des colonnes projetées", "DISTINCT s'applique colonne par colonne", "DISTINCT est interdit avec un alias"],
    correctIndexes: [0, 1],
    explanation: "DISTINCT déduplique la ligne de résultat entière, y compris quand elle est le fruit d'une concaténation ou d'un calcul. Il ne s'applique jamais séparément à chaque colonne — erreur d'interprétation fréquente.",
    topic: "DISTINCT", difficulty: "medium",
  },
  {
    id: "ocp1-q71", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles clauses de tri sont valides pour SELECT cust_id, cust_name FROM customers ? (Choisissez trois réponses.)",
    options: ["ORDER BY 2, 1", "ORDER BY 2, cust_id", "ORDER BY \"Nom du client\" si cet alias est déclaré", "ORDER BY cust_name FROM", "ORDER BY (1)"],
    correctIndexes: [0, 1, 2],
    explanation: "ORDER BY accepte les positions, les noms de colonnes et les alias — y compris entre guillemets doubles quand ils contiennent des espaces. On peut mélanger position et nom dans la même clause.",
    topic: "ORDER BY", difficulty: "medium",
  },
  {
    id: "ocp1-q72", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles affirmations sont exactes concernant les alias de colonne ? (Choisissez deux réponses.)",
    options: ["Un alias contenant un espace doit être entre guillemets doubles", "Un alias simple s'écrit sans guillemets", "Un alias doit toujours être précédé de AS", "Un alias est utilisable dans la clause WHERE"],
    correctIndexes: [0, 1],
    explanation: "Les guillemets doubles ne sont nécessaires que pour préserver la casse ou autoriser un espace. AS reste facultatif. Un alias n'est jamais visible dans WHERE, évalué avant SELECT — mais il l'est dans ORDER BY.",
    topic: "Alias de colonne", difficulty: "medium",
  },
  {
    id: "ocp1-q73", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles affirmations sont exactes concernant la table DUAL ? (Choisissez deux réponses.)",
    options: ["Elle contient exactement une ligne", "Elle contient une seule colonne, de type VARCHAR2", "Elle contient une ligne par session", "Elle est de type NUMBER"],
    correctIndexes: [0, 1],
    explanation: "DUAL est une table système d'une ligne et d'une colonne DUMMY de type VARCHAR2(1) valant 'X'. Elle sert à évaluer une expression, une pseudo-colonne ou une fonction sans interroger de vraie table.",
    topic: "Table DUAL", difficulty: "easy",
  },
  {
    id: "ocp1-q74", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Que sélectionne la condition WHERE nom LIKE 'D_%' ?",
    options: ["Les noms commençant par D et comptant au moins deux caractères", "Les noms commençant par D uniquement", "Les noms contenant un D", "Les noms de deux caractères exactement"],
    correctIndexes: [0],
    explanation: "_ exige exactement un caractère, % en accepte zéro ou plus. 'D_%' impose donc un D, puis au moins un caractère, puis n'importe quoi : le nom fait au minimum deux caractères.",
    topic: "Jokers LIKE", difficulty: "medium",
  },
  {
    id: "ocp1-q75", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles expressions remplacent correctement une limite de crédit nulle par le texte « Non disponible » ? (Choisissez deux réponses.)",
    options: ["NVL(TO_CHAR(cust_credit_limit), 'Non disponible')", "NVL2(cust_credit_limit, TO_CHAR(cust_credit_limit), 'Non disponible')", "NVL(cust_credit_limit, 'Non disponible')", "COALESCE(cust_credit_limit, 'Non disponible')"],
    correctIndexes: [0, 1],
    explanation: "NVL et COALESCE exigent des arguments de types compatibles : mêler un NUMBER et une chaîne échoue. Il faut convertir d'abord — d'où le TO_CHAR — ou passer par NVL2, dont les deuxième et troisième arguments sont ici tous deux des chaînes.",
    topic: "NVL, NVL2 et types", difficulty: "hard",
  },
  {
    id: "ocp1-q76", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles affirmations sont exactes concernant CEIL et TRUNC ? (Choisissez deux réponses.)",
    options: ["CEIL fonctionne sur les nombres positifs comme négatifs", "TRUNC s'applique aussi bien aux nombres qu'aux dates", "CEIL n'accepte que des entiers", "TRUNC arrondit à l'entier supérieur"],
    correctIndexes: [0, 1],
    explanation: "CEIL renvoie le plus petit entier supérieur ou égal, y compris pour un négatif : CEIL(-4.2) donne -4. TRUNC tronque sans arrondir, et accepte un second argument pour les nombres comme pour les dates.",
    topic: "CEIL et TRUNC", difficulty: "medium",
  },
  {
    id: "ocp1-q77", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles affirmations sont exactes concernant MIN et MAX ? (Choisissez deux réponses.)",
    options: ["Elles s'appliquent aux chaînes de caractères", "Elles s'appliquent aux dates", "Elles n'acceptent que des valeurs numériques", "Elles comptent les valeurs NULL"],
    correctIndexes: [0, 1],
    explanation: "MIN et MAX ordonnent tout type comparable : nombres, chaînes et dates. Ce sont AVG et SUM qui exigent du numérique. Comme toute fonction de groupe hormis COUNT(*), elles ignorent les NULL.",
    topic: "MIN et MAX", difficulty: "medium",
  },
  {
    id: "ocp1-q78", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles affirmations sont exactes concernant une auto-jointure ? (Choisissez trois réponses.)",
    options: ["Deux alias distincts sont obligatoires", "La clause ON peut porter la condition", "Elle peut être réalisée en jointure externe", "Elle exige une vue intermédiaire", "Elle est impossible en syntaxe ANSI"],
    correctIndexes: [0, 1, 2],
    explanation: "Référencer deux fois la même table impose des alias pour distinguer les rôles. La syntaxe ANSI l'accepte parfaitement avec ON, et une jointure externe permet de conserver les lignes sans correspondance — les employés sans manager, typiquement.",
    topic: "Auto-jointure", difficulty: "medium",
  },
  {
    id: "ocp1-q79", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles affirmations comparent correctement la syntaxe de jointure Oracle historique et la syntaxe ANSI ? (Choisissez trois réponses.)",
    options: ["Omettre la condition en syntaxe Oracle produit un produit cartésien", "La syntaxe ANSI propose NATURAL JOIN", "La syntaxe ANSI propose CROSS JOIN", "La syntaxe ANSI est systématiquement plus rapide", "La syntaxe Oracle interdit les jointures externes"],
    correctIndexes: [0, 1, 2],
    explanation: "Les deux syntaxes produisent le même plan d'exécution : aucune n'est plus rapide. L'ANSI apporte NATURAL JOIN, CROSS JOIN et FULL OUTER JOIN, et rend la condition de jointure explicite — d'où moins de produits cartésiens accidentels.",
    topic: "Syntaxes de jointure", difficulty: "hard",
  },
  {
    id: "ocp1-q80", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles conditions un opérateur ensembliste impose-t-il aux requêtes qu'il relie ? (Choisissez deux réponses.)",
    options: ["Le même nombre de colonnes", "Des types de données convertibles implicitement", "Les mêmes noms de colonnes", "Le même nombre de lignes"],
    correctIndexes: [0, 1],
    explanation: "UNION, INTERSECT et MINUS exigent un nombre de colonnes identique et des types compatibles position par position. Les noms peuvent différer : ce sont ceux du premier SELECT qui titrent le résultat.",
    topic: "Opérateurs ensemblistes", difficulty: "medium",
  },
  {
    id: "ocp1-q81", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Comment INTERSECT traite-t-il les valeurs NULL ?",
    options: ["Il considère deux NULL de même position comme égaux", "Il exclut toute ligne contenant un NULL", "Il déclenche une erreur", "Il remplace NULL par zéro"],
    correctIndexes: [0],
    explanation: "Comme UNION, INTERSECT compare des lignes entières et traite deux NULL de même position comme équivalents — comportement opposé à celui de l'opérateur =, où NULL = NULL vaut UNKNOWN.",
    topic: "INTERSECT et NULL", difficulty: "hard",
  },
  {
    id: "ocp1-q82", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelle construction permet de comparer le salaire de chaque employé à la moyenne générale ?",
    options: ["WHERE salaire > AVG(salaire)", "WHERE salaire > (SELECT AVG(salaire) FROM employes)", "HAVING salaire > AVG(salaire)", "WHERE AVG(salaire) < salaire"],
    correctIndexes: [1],
    explanation: "Une fonction de groupe est interdite dans WHERE : il faut l'isoler dans une sous-requête scalaire. HAVING ne conviendrait pas non plus, puisqu'il filtre des groupes et non des lignes individuelles.",
    topic: "Sous-requête et moyenne", difficulty: "medium",
  },
  {
    id: "ocp1-q83", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles affirmations sont exactes concernant CURRENT_DATE et CURRENT_TIMESTAMP ? (Choisissez deux réponses.)",
    options: ["CURRENT_DATE suit le fuseau horaire de la session", "CURRENT_TIMESTAMP renvoie l'heure assortie du fuseau de la session", "SYSDATE suit le fuseau de la session", "CURRENT_DATE renvoie toujours l'heure UTC"],
    correctIndexes: [0, 1],
    explanation: "SYSDATE et SYSTIMESTAMP donnent l'heure du serveur ; CURRENT_DATE et CURRENT_TIMESTAMP celle de la session, telle que fixée par SESSIONTIMEZONE. La distinction est classique dès qu'une application est répartie sur plusieurs fuseaux.",
    topic: "Fonctions de date et fuseau", difficulty: "hard",
  },
  {
    id: "ocp1-q84", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quand une nouvelle transaction démarre-t-elle implicitement ? (Choisissez trois réponses.)",
    options: ["Au premier DML suivant un COMMIT ou un ROLLBACK", "Après un TRUNCATE, qui valide implicitement", "Au premier SELECT FOR UPDATE suivant une instruction DDL", "À chaque SELECT simple", "À l'ouverture de la session"],
    correctIndexes: [0, 1, 2],
    explanation: "Une transaction naît à la première instruction qui modifie ou verrouille des données après la fin de la précédente. Un DDL ou un DCL clôt implicitement la transaction en cours ; un SELECT simple n'en ouvre aucune.",
    topic: "Démarrage d'une transaction", difficulty: "hard",
  },
  {
    id: "ocp1-q85", track: "ocp-dba-i", moduleId: "ocp1-session-1",
    question: "Quelles affirmations sont exactes concernant ROLLBACK TO SAVEPOINT ? (Choisissez deux réponses.)",
    options: ["Il annule les modifications faites après le point de sauvegarde", "Un ROLLBACK ultérieur sans point annule toute la transaction", "Il valide les modifications antérieures au point", "Il termine la transaction"],
    correctIndexes: [0, 1],
    explanation: "SAVEPOINT découpe une transaction en étapes révocables : le retour à un point défait ce qui suit, sans rien valider ni clore la transaction. Celle-ci reste ouverte, et un ROLLBACK complet reste possible ensuite.",
    topic: "SAVEPOINT", difficulty: "medium",
  },

  // ─── Réseau et déplacement de données ───────────────────────────────────
  {
    id: "ocp1-q86", track: "ocp-dba-i", moduleId: "ocp1-session-5",
    question: "L'état d'un service affiché par lsnrctl status est UNKNOWN. Que faut-il en déduire ?",
    options: ["Le service a été déclaré statiquement dans listener.ora", "L'instance est arrêtée", "L'écouteur est mal configuré", "Le service est en panne"],
    correctIndexes: [0],
    explanation: "UNKNOWN signale simplement que l'écouteur n'a pas reçu d'enregistrement dynamique pour ce service : il le connaît par sa configuration statique et ignore donc l'état réel de l'instance. Un service enregistré dynamiquement afficherait READY.",
    topic: "État UNKNOWN de l'écouteur", difficulty: "hard",
  },
  {
    id: "ocp1-q87", track: "ocp-dba-i", moduleId: "ocp1-session-5",
    question: "Quel processus enregistre dynamiquement les services auprès de l'écouteur dans les versions récentes ?",
    options: ["PMON", "LREG", "SMON", "CKPT"],
    correctIndexes: [1],
    explanation: "Depuis la 12c, LREG (Listener Registration) a repris cette tâche, historiquement assurée par PMON. ALTER SYSTEM REGISTER force un enregistrement immédiat sans attendre le cycle automatique.",
    topic: "Enregistrement des services", difficulty: "hard",
  },
  {
    id: "ocp1-q88", track: "ocp-dba-i", moduleId: "ocp1-session-5",
    question: "Quelles fonctions Oracle Net améliorent la disponibilité ou la répartition de charge ? (Choisissez trois réponses.)",
    options: ["Connect Time Failover, qui essaie plusieurs adresses successivement", "Load Balancing, qui répartit les connexions entre dispatchers", "Source Routing, qui fait transiter la connexion par des étapes intermédiaires", "Block Change Tracking", "Flashback Query"],
    correctIndexes: [0, 1, 2],
    explanation: "Ces trois options se déclarent dans le descripteur de connexion. Les deux dernières propositions relèvent de la sauvegarde et de la récupération, sans rapport avec Oracle Net.",
    topic: "Options Oracle Net", difficulty: "hard",
  },
  {
    id: "ocp1-q89", track: "ocp-dba-i", moduleId: "ocp1-session-6",
    question: "Quelles affirmations sont exactes concernant Data Pump ? (Choisissez deux réponses.)",
    options: ["Les travaux peuvent s'exécuter en parallèle", "Un travail interrompu est redémarrable", "Les fichiers sont écrits côté client", "Le parallélisme est fixé définitivement au lancement"],
    correctIndexes: [0, 1],
    explanation: "PARALLEL répartit le travail sur plusieurs processus et s'ajuste en cours d'exécution après un ATTACH. Les travaux survivent à une interruption : la table maîtresse conserve l'avancement. L'écriture est toujours côté serveur.",
    topic: "Data Pump", difficulty: "medium",
  },
  {
    id: "ocp1-q90", track: "ocp-dba-i", moduleId: "ocp1-session-6",
    question: "Quelles affirmations sont exactes concernant le chargement conventionnel de SQL*Loader ? (Choisissez deux réponses.)",
    options: ["Il génère du redo", "Il respecte les contraintes référentielles pendant le chargement", "Il contourne le buffer cache", "Il désactive les triggers"],
    correctIndexes: [0, 1],
    explanation: "Le chemin conventionnel construit des INSERT ordinaires : il passe par le buffer cache, génère du redo et de l'undo, honore contraintes et triggers. Le chemin direct, plus rapide, écrit au-delà de la HWM et diffère la vérification de certaines contraintes.",
    topic: "SQL*Loader conventionnel", difficulty: "hard",
  },
  {
    id: "ocp1-q91", track: "ocp-dba-i", moduleId: "ocp1-session-6",
    question: "Quelles affirmations sont exactes concernant le journal produit par SQL*Loader ? (Choisissez deux réponses.)",
    options: ["Il reprend le contenu du fichier de contrôle utilisé", "Il indique le nombre de lignes chargées et rejetées", "Il contient les données rejetées elles-mêmes", "Il remplace le fichier de rejet"],
    correctIndexes: [0, 1],
    explanation: "Le fichier journal récapitule la configuration — fichier de contrôle inclus — et le bilan du chargement. Les lignes rejetées vont, elles, dans le fichier BAD ; celles écartées par une clause WHEN dans le fichier DISCARD.",
    topic: "Journal SQL*Loader", difficulty: "medium",
  },
];
