import type { QuizQuestionTranslation } from "./types";

/**
 * English rendering of the supplementary banks in `quiz-data-advanced-b.ts`
 * (1Z0-084 sessions 11–13, 1Z0-076 sessions 9–11, 1Z0-078 sessions 7–12).
 * Keyed by question id; option order preserved.
 */
export const advancedEnglishB: Record<string, QuizQuestionTranslation> = {
  "tun-q52": {
    question: "What essential difference separates row chaining from row migration?",
    options: [
      "Chaining is unavoidable, migration is prevented by an adequate PCTFREE",
      "Migration is unavoidable, chaining is prevented by an adequate PCTFREE",
      "Both are fixed by simply rebuilding the index",
      "Chaining only affects partitioned tables",
    ],
    explanation: "A chained row is larger than a block: Oracle has no choice. A migrated row used to fit in its block then grew through an UPDATE; reserving room with PCTFREE prevents it. Confusing the two leads to reorganising without ever fixing the cause.",
    topic: "Chaining and migration",
  },
  "tun-q53": {
    question: "Beyond how many columns is a row always chained, whatever its size?",
    options: ["255", "128", "512", "1000"],
    explanation: "Oracle stores columns in 255-column pieces in separate row chunks. A 300-column table therefore pays an extra read as soon as a query touches a column beyond the 255th — hence the value of putting the most-queried columns first.",
    topic: "Chaining",
  },
  "tun-q54": {
    question: "Which conditions must be met to run ALTER TABLE … SHRINK SPACE? (Choose two.)",
    options: [
      "The tablespace must use Automatic Segment Space Management (ASSM)",
      "ROW MOVEMENT must be enabled on the table",
      "The table must be partitioned",
      "The database must be in ARCHIVELOG mode",
    ],
    explanation: "Compaction physically moves rows, so their ROWIDs change: ROW MOVEMENT is an explicit consent. ASSM is required because the mechanism relies on free-space bitmaps. Neither partitioning nor archiving mode plays any part.",
    topic: "Shrink",
  },
  "tun-q55": {
    question: "What is the point of running SHRINK SPACE COMPACT before SHRINK SPACE?",
    options: [
      "Compaction runs online; only the second phase takes a brief exclusive lock",
      "Compaction alone is enough to lower the high water mark",
      "Compaction automatically rebuilds indexes",
      "Compaction avoids having to enable ROW MOVEMENT",
    ],
    explanation: "COMPACT moves rows without touching the high water mark, online and interruptibly. The second command lowers the mark and needs a very brief exclusive lock. Splitting the work lets you do the bulk of it during the day.",
    topic: "Shrink",
  },
  "tun-q56": {
    question: "A table declared ROW STORE COMPRESS BASIC takes no less space. Why?",
    options: [
      "The application loads with conventional INSERTs; BASIC only compresses on direct path",
      "BASIC compression requires the Advanced Compression option",
      "Statistics must be re-gathered for compression to apply",
      "BASIC only compresses LOB columns",
    ],
    explanation: "BASIC applies only to direct-path loads: INSERT /*+ APPEND */, CTAS, direct SQL*Loader. To compress ordinary DML too you need ADVANCED, which belongs to the Advanced Compression option. DBMS_COMPRESSION.GET_COMPRESSION_TYPE verifies row by row.",
    topic: "Compression",
  },
  "tun-q57": {
    question: "What is the advantage of making an index invisible rather than dropping it?",
    options: [
      "The optimizer ignores it, but it stays maintained and comes back with one command",
      "It stops being maintained, which speeds up DML",
      "It becomes usable by SYS only",
      "It is automatically rebuilt every night",
    ],
    explanation: "An invisible index is still maintained by DML: the write cost stays, but the optimizer no longer uses it. If a query collapses, ALTER INDEX … VISIBLE restores it instantly — where rebuilding a 40 GB index would take hours.",
    topic: "Invisible index",
  },
  "tun-q58": {
    question: "What does resumable space allocation allow?",
    options: [
      "Suspending an operation that runs out of space instead of failing it",
      "Automatically shrinking tablespaces",
      "Compressing segments on the fly",
      "Preventing any ORA-01555 error",
    ],
    explanation: "ALTER SESSION ENABLE RESUMABLE makes the session wait rather than fail with ORA-01653. DBA_RESUMABLE shows the suspension, the administrator adds space, and processing resumes exactly where it stopped — a six-hour load is not lost.",
    topic: "Resumable space",
  },
  "tun-q59": {
    question: "Why is a bitmap index banned on a highly concurrent OLTP table?",
    options: [
      "A single DML locks thousands of rows covered by the same bitmap entry",
      "It does not support NULL values",
      "It cannot be rebuilt online",
      "It takes more space than a B-tree",
    ],
    explanation: "A bitmap index entry covers a ROWID range: modifying it locks every row in that range. In a data warehouse, where writes are rare and bulk, that is harmless; in OLTP it is immediate serialisation.",
    topic: "Index types",
  },
  "tun-q60": {
    question: "What essential difference separates SQL Performance Analyzer from Database Replay?",
    options: [
      "SPA runs statements in isolation; Database Replay reproduces real concurrency",
      "SPA reproduces concurrency; Database Replay works statement by statement",
      "SPA only works in multitenant",
      "Database Replay only measures plans, not timings",
    ],
    explanation: "SPA compares statements one by one: it answers “which plans change?”. Database Replay replays all the traffic with its locks, commits and think times: it answers “does the system hold up?”. The two are complementary.",
    topic: "Real Application Testing",
  },
  "tun-q61": {
    question: "Which SPA execution type actually measures execution times?",
    options: ["TEST EXECUTE", "EXPLAIN PLAN", "COMPARE PERFORMANCE", "CONVERT SQLSET"],
    explanation: "TEST EXECUTE really runs each statement and records its statistics. EXPLAIN PLAN merely compares plans without executing: faster, but blind to timings. COMPARE PERFORMANCE compares two executions already performed.",
    topic: "SQL Performance Analyzer",
  },
  "tun-q62": {
    question: "Which statements about SQL Tuning Sets are correct? (Choose three.)",
    options: [
      "They hold statement text, bind variables and statistics",
      "They can be built from AWR or from the cursor cache",
      "They can be transported between databases via a staging table and Data Pump",
      "They replace SQL plan baselines",
      "They can only hold one statement at a time",
    ],
    explanation: "A SQL Tuning Set is a container of statements with their full context. SELECT_WORKLOAD_REPOSITORY fills it from AWR, SELECT_CURSOR_CACHE from the cache. PACK_STGTAB_SQLSET and UNPACK_STGTAB_SQLSET handle transport. It pins no plan: it is not a baseline.",
    topic: "SQL Tuning Sets",
  },
  "tun-q63": {
    question: "A Database Replay run produces hundreds of new errors. What is the most likely cause?",
    options: [
      "The test database was not at the capture-start SCN",
      "The capture files are corrupt",
      "There are not enough wrc clients",
      "The capture was not processed with PROCESS_CAPTURE",
    ],
    explanation: "Replay assumes the test database is exactly in production's state when capture started. Otherwise UPDATEs cannot find their rows and constraints break. The reliable method: a guaranteed restore point before START_CAPTURE, then Flashback before every replay.",
    topic: "Database Replay",
  },
  "tun-q64": {
    question: "Which category of the SPA report deserves attention first?",
    options: ["Regressed statements", "Improved statements", "Unchanged statements", "The total statement count"],
    explanation: "A change that improves ninety-nine queries and destroys one is still a failure if the hundredth is the month-end batch. Each regression comes with both plans side by side, which lets you decide: accept, pin a baseline, or drop the change.",
    topic: "SQL Performance Analyzer",
  },
  "tun-q65": {
    question: "What is the buffer cache's RECYCLE pool for?",
    options: [
      "Isolating large once-scanned segments so they do not evict the rest of the cache",
      "Keeping small constantly-read tables in memory",
      "Storing undo blocks",
      "Hosting tablespaces with a different block size",
    ],
    explanation: "RECYCLE confines blocks known not to be re-read: they evict each other instead of pushing useful data out of the DEFAULT pool. KEEP does the opposite, protecting small reference tables.",
    topic: "Buffer cache pools",
  },
  "tun-q66": {
    question: "What does DB_BIG_TABLE_CACHE_PERCENT_TARGET do?",
    options: [
      "Reserves part of the buffer cache to keep the most frequently scanned large tables in memory",
      "Caps the maximum size of a cached table",
      "Enables buffer cache compression",
      "Reserves memory for the Flash Cache",
    ],
    explanation: "By default a large-table scan uses direct path and bypasses the cache — right for a one-off scan, wrong if the same table is scanned a hundred times an hour. The parameter reserves part of the cache for the hottest tables, tracked in V$BT_SCAN_OBJ_TEMPS.",
    topic: "Large table caching",
  },
  "tun-q67": {
    question: "What effect does enabling a 200 GB Flash Cache have on the SGA?",
    options: [
      "About 2.5 GB of extra SGA is consumed by tracking headers",
      "None: the Flash Cache lives entirely on flash storage",
      "The SGA is automatically halved",
      "The buffer cache is disabled",
    ],
    explanation: "Every block placed in flash needs a tracking header in the SGA: about 100 bytes in single instance, 200 in RAC. 200 GB in 8 KB blocks is 25 million blocks, so roughly 2.5 GB. Without growing the SGA you shrink the buffer cache to gain a second-level cache.",
    topic: "Flash Cache",
  },
  "tun-q68": {
    question: "What must ESTD_OVERALLOC_COUNT be in V$PGA_TARGET_ADVICE at the chosen target?",
    options: ["Zero", "The number of active sessions", "At least 1", "It does not matter, the value is informational"],
    explanation: "A non-zero value means the instance will have to exceed PGA_AGGREGATE_TARGET to serve sessions, and so encroach on system memory — with a swapping risk. The chosen target must always sit where that counter falls back to zero.",
    topic: "PGA",
  },
  "tun-q69": {
    question: "Which work-area regime is the most costly?",
    options: ["Multi-pass", "One-pass", "Optimal", "Direct"],
    explanation: "Optimal: everything fits in memory. One-pass: a single trip through temporary disk, acceptable for a large one-off sort. Multi-pass: several trips, multiplying I/O. V$SQL_WORKAREA_HISTOGRAM gives the distribution; any multi-pass execution should be addressed first.",
    topic: "Work areas",
  },
  "tun-q70": {
    question: "What is a temporary tablespace group for?",
    options: [
      "Spreading a parallel query's work areas across several temp files",
      "Encrypting temporary data",
      "Automatically shrinking TEMP",
      "Enabling Flashback on temporary segments",
    ],
    explanation: "A group gathers several temporary tablespaces seen as one. A single query's parallel sessions spread across the members, stopping one file becoming the bottleneck. A user or the whole database can be attached to it.",
    topic: "Temporary tablespaces",
  },
  "tun-q71": {
    question: "Which view immediately identifies the session filling the temporary tablespace?",
    options: ["V$TEMPSEG_USAGE", "V$TEMPFILE", "DBA_TEMP_FILES", "V$SORT_SEGMENT"],
    explanation: "V$TEMPSEG_USAGE links each temporary segment to its session, with the SQL_ID and the blocks consumed. A join with V$SESSION names the culprit at once. The other views describe files, not consumers.",
    topic: "Temporary tablespaces",
  },

  "dg-q46": {
    question: "Which OPEN_MODE value proves Active Data Guard is genuinely active?",
    options: ["READ ONLY WITH APPLY", "READ ONLY", "MOUNTED", "READ WRITE"],
    explanation: "Plain READ ONLY means redo apply is stopped: the database answers, but with data ageing by the second. Only READ ONLY WITH APPLY attests that the database serves queries while applying redo.",
    topic: "Active Data Guard",
  },
  "dg-q47": {
    question: "What does STANDBY_MAX_DATA_DELAY do when the lag exceeds the threshold?",
    options: [
      "The query fails with ORA-03172 rather than returning stale data",
      "The query waits indefinitely for redo to be applied",
      "The query is redirected to the primary",
      "Redo apply is automatically accelerated",
    ],
    explanation: "The parameter guarantees freshness by failing the query rather than lying. A value of 0 demands absolute freshness and assumes real-time apply. It is the only way to contractually guarantee a report does not run on obsolete data.",
    topic: "Real-time query",
  },
  "dg-q48": {
    question: "Writing to a global temporary table fails on the standby. What do you check?",
    options: [
      "TEMP_UNDO_ENABLED, which must be TRUE",
      "STANDBY_FILE_MANAGEMENT, which must be AUTO",
      "The protection mode, which must be Maximum Availability",
      "FORCE LOGGING on the primary",
    ],
    explanation: "Without temporary undo, writing to a temporary table generates ordinary undo — impossible on a read-only database. TEMP_UNDO_ENABLED moves that undo into the temporary tablespace, making the write possible. It is the number-one cause of unexpected ORA-16000.",
    topic: "Active Data Guard workloads",
  },
  "dg-q49": {
    question: "Which operations are possible on a read-only Active Data Guard standby? (Choose three.)",
    options: [
      "Writing to a global temporary table",
      "Running RMAN backups",
      "Running DML redirected to the primary",
      "Creating an index",
      "Changing a table's structure",
    ],
    explanation: "Global temporary tables, RMAN backups and, since 19c, redirected DML all work. Any structural change is impossible: a physical standby is a block-for-block copy, and its structure necessarily follows the primary's.",
    topic: "Active Data Guard workloads",
  },
  "dg-q50": {
    question: "Where are standby AWR snapshots written?",
    options: [
      "Into the primary, identified by the standby's DBID",
      "Into the standby's SYSAUX tablespace",
      "Into a flat file in the ADR",
      "They are not retained",
    ],
    explanation: "A read-only database cannot write into its own dictionary. DBMS_WORKLOAD_REPOSITORY.REGISTER_REMOTE_DATABASE registers the standby as a remote node, and CREATE_REMOTE_SNAPSHOT writes the snapshots into the primary, identified by DBID.",
    topic: "Read-only diagnosis",
  },
  "dg-q51": {
    question: "On what basis should NET_TIMEOUT be set?",
    options: [
      "Three to five times the maximum round-trip latency measured on the link",
      "Always 30 seconds, the default",
      "The duration of a full switchover",
      "The time to apply one log file",
    ],
    explanation: "Too short, a brief glitch breaks the synchronous link and degrades the configuration several times a day. Too long, production stalls on every COMMIT during an outage. A latency measurement is the only rational starting point.",
    topic: "Automatic outage resolution",
  },
  "dg-q52": {
    question: "How is the recommended TCP buffer size for redo transport computed?",
    options: [
      "Bandwidth multiplied by round-trip latency",
      "Log file size divided by the number of destinations",
      "Always 64 kilobytes",
      "SGA size divided by ten",
    ],
    explanation: "It is the bandwidth-delay product. At 1 Gbit/s with 40 ms latency that is about 5 MB: a default 64 KB buffer then caps throughput at under 2 % of the link's capacity. The setting goes in sqlnet.ora and in the descriptor.",
    topic: "Transport tuning",
  },
  "dg-q53": {
    question: "MRP0 stays permanently in the WAIT_FOR_LOG state. What do you conclude?",
    options: [
      "Transport is not supplying redo fast enough: the problem is upstream",
      "Redo apply lacks parallelism",
      "The standby's storage is saturated",
      "The password file is out of step",
    ],
    explanation: "WAIT_FOR_LOG means the apply process is waiting for redo to process: it is not the bottleneck. Tuning parallelism or standby storage would change nothing. The lead is the network, compression, or redo production itself.",
    topic: "Apply tuning",
  },
  "dg-q54": {
    question: "Apply lag grows every morning on an Active Data Guard standby, while transport lag stays flat. What is the lead?",
    options: [
      "Reporting queries compete with redo apply for CPU and I/O",
      "The network saturates at peak hours",
      "The password file expires every night",
      "The protection mode switches automatically",
    ],
    explanation: "Zero transport lag means redo is arriving normally: it is the apply that lags. In Active Data Guard the database has two competing jobs. A Resource Manager plan capping reporting sessions restores the priority redo apply must keep.",
    topic: "Diagnosing lags",
  },
  "dg-q55": {
    question: "Which descriptor parameter avoids waiting out the OS TCP timeout before trying the second address?",
    options: ["TRANSPORT_CONNECT_TIMEOUT", "RETRY_DELAY", "CONNECT_TIMEOUT", "LOAD_BALANCE"],
    explanation: "Without it, a site unreachable at TCP level makes the client wait out the operating system timeout — often over two minutes — before even trying the second address. It is the most frequent cause of a failover that “took five minutes” when the database was ready in fifteen seconds.",
    topic: "Connect descriptor",
  },
  "dg-q56": {
    question: "Why is COMMIT_OUTCOME essential to Application Continuity?",
    options: [
      "It lets the driver know whether the COMMIT went through before the break",
      "It enables redo compression",
      "It triggers Fast-Start Failover",
      "It allows writes on the standby",
    ],
    explanation: "Without that information, replaying risks duplicating the transaction, and not replaying risks losing it. COMMIT_OUTCOME records each transaction's fate, letting the driver decide correctly after a failover.",
    topic: "Application Continuity",
  },
  "dg-q57": {
    question: "What makes a transaction non-replayable by Application Continuity? (Choose two.)",
    options: [
      "An external call such as UTL_HTTP or UTL_FILE",
      "A transaction longer than replay_init_time",
      "An explicit COMMIT",
      "The use of bind variables",
    ],
    explanation: "An external call has produced an effect outside the database: replaying it would duplicate that effect. Beyond replay_init_time the driver stops recording. COMMIT and bind variables are, by contrast, normal expected behaviour.",
    topic: "Application Continuity",
  },
  "dg-q58": {
    question: "What does Transparent Application Continuity, introduced in 19c, add?",
    options: [
      "Automatic detection of transaction boundaries, with no application change",
      "Replay of transactions on a logical standby",
      "Removal of the need for a configured service",
      "Automatic redo compression",
    ],
    explanation: "Classic Application Continuity assumes the application sets request boundaries. The transparent variant detects them, and session state, by itself, and is enabled with -failovertype AUTO. It is the only realistic path for legacy applications that can no longer be modified.",
    topic: "Application Continuity",
  },
  "dg-q59": {
    question: "Without Grid Infrastructure, how do you ensure a service starts only on the database holding the PRIMARY role?",
    options: [
      "With an AFTER DB_ROLE_CHANGE ON DATABASE trigger testing V$DATABASE.DATABASE_ROLE",
      "By setting SERVICE_NAMES statically in the SPFILE",
      "By declaring the service only on the primary",
      "With a TNS alias pointing at a single site",
    ],
    explanation: "srvctl's -role attribute exists only with Grid Infrastructure. Elsewhere a DB_ROLE_CHANGE trigger — completed by an AFTER STARTUP trigger — starts the service on the right side after every transition. A static SERVICE_NAMES would start it on both sides at once.",
    topic: "Role-bound service",
  },

  "rac-q39": {
    question: "Which problem does Flex ASM solve?",
    options: [
      "Losing a node's ASM instance no longer brings down all its databases",
      "It removes the need for disk groups",
      "It allows installing ASM without Grid Infrastructure",
      "It replaces shared storage with local storage",
    ],
    explanation: "Under classic ASM each node depends on its local ASM instance: if that fails, every database on the node fails. Flex ASM lets a database connect to another node's ASM instance over the ASM network, breaking that coupling.",
    topic: "Flex ASM",
  },
  "rac-q40": {
    question: "What is Flex ASM's default cardinality?",
    options: ["3", "1", "2", "One per node"],
    explanation: "Three ASM instances are maintained whatever the cluster's node count. `srvctl modify asm -count` changes it, and the value ALL restores the classic one-instance-per-node behaviour.",
    topic: "Flex ASM",
  },
  "rac-q41": {
    question: "Which prerequisite most often blocks enabling Flex ASM?",
    options: [
      "A disk group whose COMPATIBLE.ASM is still below 12.1",
      "Fewer than three nodes",
      "No shared temporary tablespace",
      "An administrator-managed cluster",
    ],
    explanation: "Flex ASM requires COMPATIBLE.ASM at 12.1 or higher on every disk group. A single group left at 11.2 blocks it, and the error message does not say so clearly. Raising the attribute is irreversible.",
    topic: "Flex ASM",
  },
  "rac-q42": {
    question: "Which component exposes an ASM disk group as an operating system block device?",
    options: ["ADVM", "ACFS", "ASMCMD", "OCR"],
    explanation: "ASM Dynamic Volume Manager creates volumes visible under /dev/asm/<volume>-<n>. ACFS is the clustered file system placed on top of those volumes; asmcmd is the command-line administration tool.",
    topic: "ADVM",
  },
  "rac-q43": {
    question: "Which advanced features does ACFS offer? (Choose three.)",
    options: [
      "Encryption at rest",
      "Auditing of file access",
      "Replication to a remote cluster",
      "Hybrid columnar compression",
      "Redo apply",
    ],
    explanation: "ACFS encrypts (acfsutil encr), audits (acfsutil audit) and replicates (acfsutil repl), with tagging to target subsets of files. Hybrid columnar compression applies to Oracle tables, and redo apply belongs to Data Guard.",
    topic: "ACFS",
  },
  "rac-q44": {
    question: "What underpins the high availability of an NFS export from ACFS?",
    options: [
      "A Clusterware-managed HAVIP that migrates if the exporting node fails",
      "Synchronous replication between two NFS servers",
      "An NFS mount on every client",
      "The SCAN's round-robin DNS",
    ],
    explanation: "srvctl add havip creates a dedicated virtual address, and srvctl add exportfs attaches the export to it. If the exporting node disappears, the VIP migrates to another node and NFS clients see only a brief stall.",
    topic: "NFS high availability",
  },
  "rac-q45": {
    question: "A newly added RAC instance refuses to start. Which two objects do you check first? (Choose two.)",
    options: [
      "Its redo thread, enabled and declared PUBLIC",
      "Its undo tablespace, declared for its SID",
      "Its dedicated control file",
      "Its own copy of the SPFILE",
    ],
    explanation: "Each instance has its redo thread and its undo. Those are the two classic omissions when adding a node. The control file and SPFILE are, by contrast, single and shared: a per-instance copy would be a mistake.",
    topic: "RAC administration",
  },
  "rac-q46": {
    question: "Why must a redo thread be declared PUBLIC?",
    options: [
      "So any instance can claim it, which policy-based management requires",
      "So it gets archived",
      "So it appears in V$LOG",
      "To allow multiplexing",
    ],
    explanation: "A private thread is reserved to a named instance. That is acceptable under administrator management, but blocking in a policy-managed database, where instances move between servers and must be able to take any free thread.",
    topic: "Redo threads",
  },
  "rac-q47": {
    question: "Which utility converts a single-instance database to RAC?",
    options: ["rconfig", "cluvfy", "opatchauto", "oclumon"],
    explanation: "rconfig is driven by an XML file: it moves files to ASM if needed, adds redo threads and undo tablespaces, then registers the database with Clusterware. You always start with a dry run, which writes nothing.",
    topic: "Conversion to RAC",
  },
  "rac-q48": {
    question: "How do you set a parameter for a single instance in a shared SPFILE?",
    options: [
      "ALTER SYSTEM SET … SID = 'orcl2' SCOPE = SPFILE",
      "By creating a local pfile on that node",
      "ALTER SESSION SET … on that instance",
      "By editing the file directly on ASM",
    ],
    explanation: "The SID clause targets a named instance; SID='*' targets all of them. V$SPPARAMETER shows the SPFILE's real content, per-instance values included. Editing an SPFILE directly on ASM is impossible: it is a binary file managed by the database.",
    topic: "Cluster parameters",
  },
  "rac-q49": {
    question: "Which CLBGOAL setting suits a web application with a connection pool?",
    options: ["SHORT", "LONG", "NONE", "THROUGHPUT"],
    explanation: "SHORT relies on the Load Balancing Advisory and suits short or pooled connections. LONG balances by session count and suits thick clients keeping a session open all day. THROUGHPUT is an RLBGOAL value, not a CLBGOAL one.",
    topic: "Load balancing",
  },
  "rac-q50": {
    question: "Why can FAN have no effect despite a correct database-side configuration?",
    options: [
      "The client does not listen for the events: a generic JDBC pool or a bare connection",
      "FAN requires ARCHIVELOG mode",
      "FAN only works with two nodes",
      "FAN requires Application Continuity",
    ],
    explanation: "FAN publishes the event, but you need a client able to hear it: UCP, WebLogic, ODP.NET or a configured OCI driver. A home-grown pool or a bare DriverManager ignore them, and the notification is published into the void.",
    topic: "FAN",
  },
  "rac-q51": {
    question: "What is the colocation tag for?",
    options: [
      "Routing sessions working on the same data to the same instance",
      "Identifying one user's sessions in AWR",
      "Naming ASM disk groups",
      "Tagging ACFS files for replication",
    ],
    explanation: "By grouping one tenant's or one data scope's sessions on a single instance, blocks stay in one buffer cache and Cache Fusion transfers drop accordingly. ACFS tagging is a separate, unrelated mechanism.",
    topic: "Colocation",
  },
  "rac-q52": {
    question: "What happens if a service is created without the -failback option?",
    options: [
      "Moved by a failure, it stays on the fallback node even after recovery",
      "It never fails over",
      "It starts on every instance at once",
      "It cannot be relocated manually",
    ],
    explanation: "Without -failback the intended distribution never returns by itself: the service stays indefinitely on its fallback instance. A manual srvctl relocate service is then needed, which nobody remembers once the incident is forgotten.",
    topic: "Fallback services",
  },
  "rac-q53": {
    question: "What characterises an Oracle RAC One Node database?",
    options: [
      "A single active instance at a time, but registered on several nodes",
      "Several active instances on a single node",
      "A single-instance database without Clusterware",
      "A database replicated by Data Guard",
    ],
    explanation: "RAC One Node delivers high availability and downtime-free maintenance — through online relocation — without the complexity of active-active: no Cache Fusion, no shared hot blocks. In exchange it does not scale horizontally.",
    topic: "RAC One Node",
  },
  "rac-q54": {
    question: "During an online relocation of a RAC One Node database, what happens?",
    options: [
      "Both instances coexist briefly, giving sessions time to migrate",
      "The old instance stops before the new one starts",
      "Every session is killed immediately",
      "The database goes read-only for the duration",
    ],
    explanation: "That overlap is what makes the operation transparent: the new instance accepts connections while the old one finishes its transactions. Sessions still there past the timeout are killed, however — hence the importance of FAN and Application Continuity.",
    topic: "RAC One Node",
  },
  "rac-q55": {
    question: "What does QoS Management use to arbitrate between applications?",
    options: [
      "A response-time objective declared per work class",
      "A CPU quota set manually per instance",
      "The number of open sessions per service",
      "The SGA size of each node",
    ],
    explanation: "Instead of tuning parameters you declare the expected outcome. QoS continuously measures the achieved response time and adjusts CPU shares, connection allocation or server moves to meet the objective, respecting each class's criticality rank.",
    topic: "Quality of Service",
  },
  "rac-q56": {
    question: "Which prerequisite, if unmet, renders most QoS levers inert?",
    options: [
      "A policy-managed cluster, with server pools",
      "ARCHIVELOG mode",
      "At least four nodes",
      "Flex ASM enabled",
    ],
    explanation: "Moving servers between pools, QoS's main lever, assumes declared pools. On an administrator-managed cluster, where each instance is nailed to a named node, QoS installs but can move nothing. The GIMR must also be active.",
    topic: "Quality of Service",
  },
  "rac-q57": {
    question: "What does the INSTANCES clause of ALTER PLUGGABLE DATABASE … OPEN allow in RAC?",
    options: [
      "Opening the PDB on a chosen subset of the CDB's instances",
      "Spreading the PDB's files across the instances",
      "Creating one undo tablespace per instance",
      "Setting the maximum sessions per instance",
    ],
    explanation: "A PDB can be opened on every instance, on some of them only, and in different modes per instance. It is a distribution tool: production on one side, read-only reporting on the other.",
    topic: "Multitenant in RAC",
  },
  "rac-q58": {
    question: "After an instance restart, an application service attached to a PDB does not start. First lead?",
    options: [
      "The PDB came back closed, for lack of a SAVE STATE",
      "The service was removed from the OCR",
      "The local listener is not started",
      "The PDB's undo tablespace is missing",
    ],
    explanation: "Without SAVE STATE a PDB comes back closed after an instance restart, and the dependent service cannot start. DBA_PDB_SAVED_STATES shows exactly what was recorded, instance by instance.",
    topic: "Multitenant in RAC",
  },
  "rac-q59": {
    question: "How do you patch a CDB without a lasting interruption to its PDBs' applications?",
    options: [
      "Relocate the PDBs to an already-patched CDB, patch the emptied CDB, then bring them back",
      "Stop every instance and apply the patch offline",
      "Convert the PDBs to single-instance databases for the duration",
      "Use Data Guard to replicate each PDB separately",
    ],
    explanation: "CREATE PLUGGABLE DATABASE … RELOCATE AVAILABILITY MAX moves a PDB between CDBs with about a second of downtime. You empty the CDB to be patched, upgrade it, then bring the PDBs back: application availability is preserved throughout.",
    topic: "PDB patching",
  },
  "rac-q60": {
    question: "What distinguishes a leaf node from a hub node in a Flex Cluster?",
    options: [
      "The leaf node has no shared storage access and hosts no database instance",
      "The leaf node has more memory",
      "The leaf node must host an ASM instance",
      "The leaf node has its own voting disks",
    ],
    explanation: "A leaf node depends on a hub to reach the OCR and the voting disks, and cannot carry a database instance. It serves application servers and jobs that do not need shared storage.",
    topic: "Flex Clusters",
  },
  "rac-q61": {
    question: "Why does losing a leaf node not trigger a cluster reconfiguration?",
    options: [
      "It takes no part in quorum, reaching neither the OCR nor the voting disks",
      "It is automatically replaced by a standby node",
      "Its state is continuously replicated to a hub",
      "Clusterware does not monitor it",
    ],
    explanation: "Quorum is decided on the voting disks, which a leaf node cannot reach. Its disappearance therefore cannot cause a split brain, and forces no membership renegotiation — unlike losing a hub node.",
    topic: "Flex Clusters",
  },
  "rac-q62": {
    question: "What separates an administrator-managed database from a policy-managed one?",
    options: [
      "One names its nodes explicitly, the other declares a need for servers",
      "One uses ASM, the other a file system",
      "One is in ARCHIVELOG mode, the other is not",
      "One accepts services, the other does not",
    ],
    explanation: "Under administrator management each instance is nailed to a named node. Under policy management you declare a pool with a minimum and maximum of servers, and Clusterware picks which and rebalances by itself. It is a prerequisite for QoS Management.",
    topic: "Policy-based management",
  },
  "rac-q63": {
    question: "What does crsctl eval allow?",
    options: [
      "Simulating the effect of an operation without executing it",
      "Evaluating a query's performance",
      "Validating the cluster's network configuration",
      "Estimating free space in disk groups",
    ],
    explanation: "crsctl eval answers “what would happen if…”: stopping a server, activating a policy, moving a resource. On a production cluster it is how you verify a maintenance operation will not trigger a cascade of unforeseen relocations.",
    topic: "What-if evaluation",
  },
  "rac-q64": {
    question: "Which PLACEMENT attribute restricts an application resource to the HOSTING_MEMBERS nodes only?",
    options: ["restricted", "favored", "balanced", "exclusive"],
    explanation: "restricted strictly limits the resource to the listed nodes. favored prefers them but accepts others, and balanced lets Clusterware pick the least-loaded node. The choice follows real constraints: licensing, hardware, network access.",
    topic: "Application resources",
  },
  "rac-q65": {
    question: "Why is an action script whose check only tests for the process insufficient?",
    options: [
      "A hung but living application will never be restarted",
      "Clusterware refuses scripts with no return code",
      "The check must be written in Perl",
      "Process presence cannot be measured on Linux",
    ],
    explanation: "A zombie process answers pgrep while serving nothing: high availability becomes illusory. The check must query the service the way a user would — an HTTP request, a connection, a test transaction.",
    topic: "Application resources",
  },
};
