import type { QuizQuestion } from "./types";

/**
 * Compléments de banques pour les sessions ajoutées aux trois parcours de
 * spécialisation : 1Z0-084 (sessions 11 à 13), 1Z0-076 (sessions 9 à 11)
 * et 1Z0-078 (sessions 7 à 12).
 */

export const tuningQuestionsB: QuizQuestion[] = [
  // ─── Session 11 — Réduire le coût des opérations SQL ────────────────────
  {
    id: "tun-q52", track: "ocp-tuning", moduleId: "tun-session-11",
    question: "Quelle différence essentielle sépare le chaînage de la migration de lignes ?",
    options: [
      "Le chaînage est inévitable, la migration s'évite par un PCTFREE suffisant",
      "La migration est inévitable, le chaînage s'évite par un PCTFREE suffisant",
      "Les deux se corrigent par un simple REBUILD d'index",
      "Le chaînage ne concerne que les tables partitionnées",
    ],
    correctIndexes: [0],
    explanation: "Une ligne chaînée est plus grande qu'un bloc : Oracle n'a pas le choix. Une ligne migrée tenait dans son bloc puis a grossi par UPDATE ; réserver de l'espace avec PCTFREE empêche le phénomène. Confondre les deux conduit à réorganiser sans jamais corriger la cause.",
    topic: "Chaînage et migration", difficulty: "hard",
  },
  {
    id: "tun-q53", track: "ocp-tuning", moduleId: "tun-session-11",
    question: "À partir de combien de colonnes une ligne est-elle toujours chaînée, quelle que soit sa taille ?",
    options: ["255", "128", "512", "1000"],
    correctIndexes: [0],
    explanation: "Oracle stocke les colonnes par tranches de 255 dans des morceaux de ligne distincts. Une table de 300 colonnes paie donc une lecture supplémentaire dès qu'une requête touche une colonne au-delà de la 255ᵉ — d'où l'intérêt de placer les colonnes les plus consultées en tête.",
    topic: "Chaînage", difficulty: "hard",
  },
  {
    id: "tun-q54", track: "ocp-tuning", moduleId: "tun-session-11",
    question: "Quelles conditions doivent être réunies pour exécuter ALTER TABLE … SHRINK SPACE ? (Choisissez deux réponses.)",
    options: [
      "Le tablespace doit être en gestion automatique de l'espace des segments (ASSM)",
      "ROW MOVEMENT doit être activé sur la table",
      "La table doit être partitionnée",
      "La base doit être en mode ARCHIVELOG",
    ],
    correctIndexes: [0, 1],
    explanation: "Le compactage déplace physiquement les lignes, donc change leurs ROWID : ROW MOVEMENT est un consentement explicite. ASSM est requis car le mécanisme s'appuie sur les bitmaps d'espace libre. Ni le partitionnement ni le mode d'archivage n'entrent en jeu.",
    topic: "Shrink", difficulty: "hard",
  },
  {
    id: "tun-q55", track: "ocp-tuning", moduleId: "tun-session-11",
    question: "Quel est l'intérêt de faire SHRINK SPACE COMPACT avant SHRINK SPACE ?",
    options: [
      "Le compactage se fait en ligne ; seule la seconde phase pose un bref verrou exclusif",
      "Le compactage seul suffit à abaisser la high water mark",
      "Le compactage reconstruit automatiquement les index",
      "Le compactage évite d'activer ROW MOVEMENT",
    ],
    correctIndexes: [0],
    explanation: "COMPACT déplace les lignes sans toucher à la high water mark, en ligne et de façon interruptible. La seconde commande abaisse la limite et exige un verrou exclusif très bref. Découper permet de faire le gros du travail en journée.",
    topic: "Shrink", difficulty: "hard",
  },
  {
    id: "tun-q56", track: "ocp-tuning", moduleId: "tun-session-11",
    question: "Une table déclarée ROW STORE COMPRESS BASIC n'occupe pas moins d'espace. Pourquoi ?",
    options: [
      "L'application charge en INSERT conventionnel ; BASIC ne compresse qu'en chemin direct",
      "La compression BASIC exige l'option Advanced Compression",
      "Il faut recollecter les statistiques pour que la compression s'applique",
      "BASIC ne compresse que les colonnes de type LOB",
    ],
    correctIndexes: [0],
    explanation: "BASIC ne s'applique qu'aux chargements en chemin direct : INSERT /*+ APPEND */, CTAS, SQL*Loader direct. Pour compresser aussi le DML ordinaire, il faut ADVANCED, qui relève de l'option Advanced Compression. DBMS_COMPRESSION.GET_COMPRESSION_TYPE vérifie ligne par ligne.",
    topic: "Compression", difficulty: "medium",
  },
  {
    id: "tun-q57", track: "ocp-tuning", moduleId: "tun-session-11",
    question: "Quel est l'avantage de rendre un index invisible plutôt que de le supprimer ?",
    options: [
      "L'optimiseur l'ignore, mais il reste maintenu et se réactive en une commande",
      "Il cesse d'être maintenu, ce qui accélère le DML",
      "Il devient utilisable uniquement par SYS",
      "Il est automatiquement reconstruit chaque nuit",
    ],
    correctIndexes: [0],
    explanation: "Un index invisible continue d'être maintenu par le DML : le coût d'écriture reste, mais l'optimiseur ne l'utilise plus. Si une requête s'effondre, ALTER INDEX … VISIBLE le remet en service instantanément — là où reconstruire un index de 40 Go prendrait des heures.",
    topic: "Index invisible", difficulty: "medium",
  },
  {
    id: "tun-q58", track: "ocp-tuning", moduleId: "tun-session-11",
    question: "Que permet l'allocation d'espace reprenable (resumable space allocation) ?",
    options: [
      "Suspendre une opération à court d'espace au lieu de la faire échouer",
      "Réduire automatiquement la taille des tablespaces",
      "Compresser les segments à la volée",
      "Empêcher toute erreur ORA-01555",
    ],
    correctIndexes: [0],
    explanation: "ALTER SESSION ENABLE RESUMABLE fait attendre la session plutôt que d'échouer sur ORA-01653. DBA_RESUMABLE montre la suspension, l'administrateur ajoute de l'espace, et le traitement repart exactement où il s'était arrêté — un chargement de six heures n'est pas perdu.",
    topic: "Espace reprenable", difficulty: "medium",
  },
  {
    id: "tun-q59", track: "ocp-tuning", moduleId: "tun-session-11",
    question: "Pourquoi un index bitmap est-il proscrit sur une table OLTP très concurrente ?",
    options: [
      "Un seul DML verrouille des milliers de lignes couvertes par la même entrée bitmap",
      "Il ne prend pas en charge les valeurs NULL",
      "Il ne peut pas être reconstruit en ligne",
      "Il occupe plus d'espace qu'un B-tree",
    ],
    correctIndexes: [0],
    explanation: "Une entrée d'index bitmap couvre une plage de ROWID : la modifier verrouille toutes les lignes de la plage. En entrepôt de données, où les écritures sont rares et massives, c'est sans conséquence ; en OLTP, c'est une sérialisation immédiate.",
    topic: "Types d'index", difficulty: "hard",
  },

  // ─── Session 12 — Real Application Testing ──────────────────────────────
  {
    id: "tun-q60", track: "ocp-tuning", moduleId: "tun-session-12",
    question: "Quelle différence essentielle sépare SQL Performance Analyzer de Database Replay ?",
    options: [
      "SPA exécute les instructions isolément ; Database Replay reproduit la concurrence réelle",
      "SPA reproduit la concurrence ; Database Replay travaille instruction par instruction",
      "SPA ne fonctionne qu'en multitenant",
      "Database Replay ne mesure que les plans, pas les temps",
    ],
    correctIndexes: [0],
    explanation: "SPA compare les instructions une par une : il répond à « quels plans changent ? ». Database Replay rejoue tout le trafic avec ses verrous, ses commits et ses temps de réflexion : il répond à « le système tient-il la charge ? ». Les deux sont complémentaires.",
    topic: "Real Application Testing", difficulty: "medium",
  },
  {
    id: "tun-q61", track: "ocp-tuning", moduleId: "tun-session-12",
    question: "Quel type d'exécution SPA mesure réellement les temps d'exécution ?",
    options: ["TEST EXECUTE", "EXPLAIN PLAN", "COMPARE PERFORMANCE", "CONVERT SQLSET"],
    correctIndexes: [0],
    explanation: "TEST EXECUTE exécute vraiment chaque instruction et relève ses statistiques. EXPLAIN PLAN se contente de comparer les plans, sans rien exécuter : plus rapide, mais aveugle sur les temps. COMPARE PERFORMANCE compare deux exécutions déjà faites.",
    topic: "SQL Performance Analyzer", difficulty: "medium",
  },
  {
    id: "tun-q62", track: "ocp-tuning", moduleId: "tun-session-12",
    question: "Quelles affirmations sont exactes concernant les SQL Tuning Sets ? (Choisissez trois réponses.)",
    options: [
      "Ils contiennent le texte des instructions, leurs variables de liaison et leurs statistiques",
      "Ils se constituent depuis AWR ou depuis le cache de curseurs",
      "Ils se transportent entre bases via une table intermédiaire et Data Pump",
      "Ils remplacent les SQL plan baselines",
      "Ils ne peuvent contenir qu'une seule instruction à la fois",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "Un SQL Tuning Set est un conteneur d'instructions avec leur contexte complet. SELECT_WORKLOAD_REPOSITORY le remplit depuis AWR, SELECT_CURSOR_CACHE depuis le cache. PACK_STGTAB_SQLSET et UNPACK_STGTAB_SQLSET assurent le transport. Il ne fige aucun plan : ce n'est pas une baseline.",
    topic: "SQL Tuning Sets", difficulty: "hard",
  },
  {
    id: "tun-q63", track: "ocp-tuning", moduleId: "tun-session-12",
    question: "Un rejeu Database Replay produit des centaines d'erreurs nouvelles. Quelle est la cause la plus probable ?",
    options: [
      "La base de test n'était pas à l'état du SCN de début de capture",
      "Les fichiers de capture sont corrompus",
      "Le nombre de clients wrc est insuffisant",
      "La capture n'a pas été traitée par PROCESS_CAPTURE",
    ],
    correctIndexes: [0],
    explanation: "Le rejeu suppose la base de test exactement dans l'état de la production au démarrage de la capture. Sinon les UPDATE ne trouvent pas leurs lignes et les contraintes cèdent. La méthode fiable : point de restauration garanti avant START_CAPTURE, puis Flashback avant chaque rejeu.",
    topic: "Database Replay", difficulty: "hard",
  },
  {
    id: "tun-q64", track: "ocp-tuning", moduleId: "tun-session-12",
    question: "Quelle catégorie du rapport SPA mérite l'attention en priorité ?",
    options: ["Les instructions régressées", "Les instructions améliorées", "Les instructions inchangées", "Le nombre total d'instructions"],
    correctIndexes: [0],
    explanation: "Un changement qui améliore quatre-vingt-dix-neuf requêtes et en détruit une reste un échec si la centième est le traitement de clôture. Chaque régression est livrée avec les deux plans côte à côte, ce qui permet de décider : accepter, poser une baseline, ou renoncer.",
    topic: "SQL Performance Analyzer", difficulty: "medium",
  },

  // ─── Session 13 — Caches avancés, PGA, TEMP ─────────────────────────────
  {
    id: "tun-q65", track: "ocp-tuning", moduleId: "tun-session-13",
    question: "À quoi sert le pool RECYCLE du buffer cache ?",
    options: [
      "Isoler les gros segments balayés une fois, pour qu'ils ne chassent pas le reste du cache",
      "Conserver en mémoire les petites tables lues sans cesse",
      "Stocker les blocs d'undo",
      "Accueillir les tablespaces d'une taille de bloc différente",
    ],
    correctIndexes: [0],
    explanation: "RECYCLE cantonne les blocs dont on sait qu'ils ne seront pas relus : ils s'évincent entre eux au lieu de chasser les données utiles du pool DEFAULT. KEEP fait l'inverse, en protégeant les petites tables de référence.",
    topic: "Pools du buffer cache", difficulty: "medium",
  },
  {
    id: "tun-q66", track: "ocp-tuning", moduleId: "tun-session-13",
    question: "Que fait DB_BIG_TABLE_CACHE_PERCENT_TARGET ?",
    options: [
      "Réserve une part du buffer cache pour garder en mémoire les grandes tables les plus fréquemment balayées",
      "Limite la taille maximale d'une table mise en cache",
      "Active la compression du buffer cache",
      "Réserve de la mémoire au Flash Cache",
    ],
    correctIndexes: [0],
    explanation: "Par défaut, un balayage de grande table utilise la lecture directe et contourne le cache — bon choix pour un balayage unique, mauvais si la même table est balayée cent fois par heure. Le paramètre réserve une part du cache aux tables les plus « chaudes », suivies dans V$BT_SCAN_OBJ_TEMPS.",
    topic: "Cache des grandes tables", difficulty: "hard",
  },
  {
    id: "tun-q67", track: "ocp-tuning", moduleId: "tun-session-13",
    question: "Quelle conséquence a l'activation d'un Flash Cache de 200 Go sur la SGA ?",
    options: [
      "Environ 2,5 Go de SGA supplémentaires sont consommés par les en-têtes de suivi",
      "Aucune : le Flash Cache est entièrement sur disque flash",
      "La SGA est automatiquement réduite de moitié",
      "Le buffer cache est désactivé",
    ],
    correctIndexes: [0],
    explanation: "Chaque bloc placé en flash exige un en-tête de suivi dans la SGA : environ 100 octets en mono-instance, 200 en RAC. 200 Go en blocs de 8 Ko font 25 millions de blocs, donc environ 2,5 Go. Sans augmenter la SGA, on rétrécit le buffer cache pour gagner un cache de second niveau.",
    topic: "Flash Cache", difficulty: "hard",
  },
  {
    id: "tun-q68", track: "ocp-tuning", moduleId: "tun-session-13",
    question: "Que doit valoir ESTD_OVERALLOC_COUNT dans V$PGA_TARGET_ADVICE à la cible retenue ?",
    options: ["Zéro", "Le nombre de sessions actives", "Au moins 1", "Peu importe, c'est une valeur informative"],
    correctIndexes: [0],
    explanation: "Une valeur non nulle signifie que l'instance devra dépasser PGA_AGGREGATE_TARGET pour servir les sessions, donc empiéter sur la mémoire du système — avec un risque de swap. La cible retenue doit toujours se situer là où ce compteur retombe à zéro.",
    topic: "PGA", difficulty: "hard",
  },
  {
    id: "tun-q69", track: "ocp-tuning", moduleId: "tun-session-13",
    question: "Quel régime de zone de travail est le plus coûteux ?",
    options: ["Multi-pass", "One-pass", "Optimal", "Direct"],
    correctIndexes: [0],
    explanation: "Optimal : tout tient en mémoire. One-pass : un seul passage par le disque temporaire, acceptable pour un gros tri ponctuel. Multi-pass : plusieurs passages, ce qui multiplie les entrées-sorties. V$SQL_WORKAREA_HISTOGRAM donne la répartition ; toute exécution multi-pass est à traiter en priorité.",
    topic: "Zones de travail", difficulty: "medium",
  },
  {
    id: "tun-q70", track: "ocp-tuning", moduleId: "tun-session-13",
    question: "À quoi sert un groupe de tablespaces temporaires ?",
    options: [
      "Répartir les zones de travail d'une requête parallèle sur plusieurs fichiers temporaires",
      "Chiffrer les données temporaires",
      "Réduire automatiquement la taille du TEMP",
      "Permettre le Flashback sur les segments temporaires",
    ],
    correctIndexes: [0],
    explanation: "Un groupe rassemble plusieurs tablespaces temporaires vus comme un seul. Les sessions parallèles d'une même requête se répartissent entre les membres, ce qui évite qu'un seul fichier devienne le goulot d'étranglement. Un utilisateur ou la base entière peut y être rattaché.",
    topic: "Tablespaces temporaires", difficulty: "hard",
  },
  {
    id: "tun-q71", track: "ocp-tuning", moduleId: "tun-session-13",
    question: "Quelle vue permet d'identifier immédiatement la session qui remplit le tablespace temporaire ?",
    options: ["V$TEMPSEG_USAGE", "V$TEMPFILE", "DBA_TEMP_FILES", "V$SORT_SEGMENT"],
    correctIndexes: [0],
    explanation: "V$TEMPSEG_USAGE relie chaque segment temporaire à sa session, avec le SQL_ID et le nombre de blocs consommés. Une jointure avec V$SESSION nomme immédiatement le coupable. Les autres vues décrivent les fichiers, pas les consommateurs.",
    topic: "Tablespaces temporaires", difficulty: "medium",
  },
];

export const dataGuardQuestionsB: QuizQuestion[] = [
  // ─── Session 9 — Active Data Guard ──────────────────────────────────────
  {
    id: "dg-q46", track: "ocp-dataguard", moduleId: "dg-session-9",
    question: "Quelle valeur d'OPEN_MODE prouve qu'Active Data Guard est réellement actif ?",
    options: ["READ ONLY WITH APPLY", "READ ONLY", "MOUNTED", "READ WRITE"],
    correctIndexes: [0],
    explanation: "READ ONLY seul signifie que l'application du redo est arrêtée : la base répond, mais avec des données qui vieillissent à chaque seconde. Seul READ ONLY WITH APPLY atteste que la base sert des requêtes pendant qu'elle applique le redo.",
    topic: "Active Data Guard", difficulty: "medium",
  },
  {
    id: "dg-q47", track: "ocp-dataguard", moduleId: "dg-session-9",
    question: "Que fait STANDBY_MAX_DATA_DELAY lorsque le retard dépasse le seuil fixé ?",
    options: [
      "La requête échoue sur ORA-03172 plutôt que de renvoyer des données périmées",
      "La requête attend indéfiniment que le redo soit appliqué",
      "La requête est redirigée vers la base principale",
      "L'application du redo est accélérée automatiquement",
    ],
    correctIndexes: [0],
    explanation: "Le paramètre garantit la fraîcheur en faisant échouer la requête plutôt qu'en mentant. La valeur 0 exige une fraîcheur absolue et suppose l'application temps réel. C'est le seul moyen de garantir contractuellement qu'un rapport ne travaille pas sur des données obsolètes.",
    topic: "Requête temps réel", difficulty: "hard",
  },
  {
    id: "dg-q48", track: "ocp-dataguard", moduleId: "dg-session-9",
    question: "Une écriture dans une table temporaire globale échoue sur la base de secours. Que vérifier ?",
    options: [
      "TEMP_UNDO_ENABLED, qui doit valoir TRUE",
      "STANDBY_FILE_MANAGEMENT, qui doit valoir AUTO",
      "Le mode de protection, qui doit être Maximum Availability",
      "FORCE LOGGING sur la base principale",
    ],
    correctIndexes: [0],
    explanation: "Sans undo temporaire, écrire dans une table temporaire génère de l'undo ordinaire — impossible sur une base ouverte en lecture seule. TEMP_UNDO_ENABLED bascule cet undo dans le tablespace temporaire, ce qui rend l'écriture possible. C'est la cause n° 1 des ORA-16000 inattendus.",
    topic: "Charges Active Data Guard", difficulty: "hard",
  },
  {
    id: "dg-q49", track: "ocp-dataguard", moduleId: "dg-session-9",
    question: "Quelles opérations sont possibles sur une base Active Data Guard ouverte en lecture ? (Choisissez trois réponses.)",
    options: [
      "Écrire dans une table temporaire globale",
      "Exécuter des sauvegardes RMAN",
      "Exécuter un DML redirigé vers la principale",
      "Créer un index",
      "Modifier la structure d'une table",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "Les tables temporaires globales, les sauvegardes RMAN et, depuis la 19c, le DML redirigé fonctionnent. Toute modification de structure est en revanche impossible : la base de secours physique est une copie bloc à bloc, sa structure suit obligatoirement celle de la principale.",
    topic: "Charges Active Data Guard", difficulty: "hard",
  },
  {
    id: "dg-q50", track: "ocp-dataguard", moduleId: "dg-session-9",
    question: "Où sont écrits les instantanés d'AWR pour base de secours ?",
    options: [
      "Dans la base principale, identifiés par le DBID de la base de secours",
      "Dans le tablespace SYSAUX de la base de secours",
      "Dans un fichier plat de l'ADR",
      "Ils ne sont pas conservés",
    ],
    correctIndexes: [0],
    explanation: "Une base en lecture seule ne peut rien écrire dans son propre dictionnaire. DBMS_WORKLOAD_REPOSITORY.REGISTER_REMOTE_DATABASE enregistre la base de secours comme nœud distant, et CREATE_REMOTE_SNAPSHOT écrit les instantanés dans la principale, identifiés par DBID.",
    topic: "Diagnostic en lecture seule", difficulty: "hard",
  },

  // ─── Session 10 — Résolution des pannes et optimisation ─────────────────
  {
    id: "dg-q51", track: "ocp-dataguard", moduleId: "dg-session-10",
    question: "Sur quelle base régler NET_TIMEOUT ?",
    options: [
      "Trois à cinq fois la latence aller-retour maximale mesurée sur la liaison",
      "Toujours 30 secondes, la valeur par défaut",
      "La durée d'un switchover complet",
      "Le temps d'application d'un fichier journal",
    ],
    correctIndexes: [0],
    explanation: "Trop court, une micro-coupure suffit à rompre la liaison synchrone et à faire basculer la configuration en mode dégradé plusieurs fois par jour. Trop long, la production reste bloquée à chaque COMMIT pendant une panne. La mesure de latence est le seul point de départ rationnel.",
    topic: "Résolution automatique des pannes", difficulty: "hard",
  },
  {
    id: "dg-q52", track: "ocp-dataguard", moduleId: "dg-session-10",
    question: "Comment se calcule la taille recommandée d'un tampon TCP pour le transport du redo ?",
    options: [
      "Bande passante multipliée par la latence aller-retour",
      "Taille d'un fichier journal divisée par le nombre de destinations",
      "Toujours 64 kilo-octets",
      "Taille de la SGA divisée par dix",
    ],
    correctIndexes: [0],
    explanation: "C'est le produit bande passante × délai. Sur 1 Gbit/s avec 40 ms de latence, cela fait environ 5 Mo : un tampon par défaut de 64 Ko plafonne alors le débit à moins de 2 % de la capacité du lien. Le réglage se fait dans sqlnet.ora et dans le descripteur.",
    topic: "Optimisation du transport", difficulty: "hard",
  },
  {
    id: "dg-q53", track: "ocp-dataguard", moduleId: "dg-session-10",
    question: "MRP0 reste en permanence dans l'état WAIT_FOR_LOG. Que faut-il en conclure ?",
    options: [
      "Le transport ne fournit pas le redo assez vite : le problème est en amont",
      "L'application du redo manque de parallélisme",
      "Le stockage de la base de secours est saturé",
      "Le fichier de mots de passe est désynchronisé",
    ],
    correctIndexes: [0],
    explanation: "WAIT_FOR_LOG signifie que le processus d'application attend du redo à traiter : il n'est pas le goulot d'étranglement. Régler le parallélisme ou le stockage côté secours ne changerait rien. La piste est le réseau, la compression, ou la production de redo elle-même.",
    topic: "Optimisation de l'application", difficulty: "hard",
  },
  {
    id: "dg-q54", track: "ocp-dataguard", moduleId: "dg-session-10",
    question: "L'apply lag grandit chaque matin sur une base Active Data Guard, sans que le transport lag bouge. Quelle piste ?",
    options: [
      "Les requêtes de rapport concurrencent l'application du redo pour le CPU et les E/S",
      "Le réseau est saturé aux heures de pointe",
      "Le fichier de mots de passe expire chaque nuit",
      "Le mode de protection bascule automatiquement",
    ],
    correctIndexes: [0],
    explanation: "Transport lag nul signifie que le redo arrive normalement : c'est l'application qui traîne. En Active Data Guard, la base a deux métiers concurrents. Un plan Resource Manager plafonnant les sessions de rapport rend à l'application du redo la priorité qu'elle doit garder.",
    topic: "Diagnostic des écarts", difficulty: "hard",
  },

  // ─── Session 11 — Connectivité client ───────────────────────────────────
  {
    id: "dg-q55", track: "ocp-dataguard", moduleId: "dg-session-11",
    question: "Quel paramètre du descripteur évite d'attendre le délai TCP du système avant d'essayer la seconde adresse ?",
    options: ["TRANSPORT_CONNECT_TIMEOUT", "RETRY_DELAY", "CONNECT_TIMEOUT", "LOAD_BALANCE"],
    correctIndexes: [0],
    explanation: "Sans lui, un site injoignable au niveau TCP fait attendre le client le délai du système d'exploitation — souvent plus de deux minutes — avant même de tenter la seconde adresse. C'est la cause la plus fréquente d'une bascule « qui a pris cinq minutes » alors que la base était prête en quinze secondes.",
    topic: "Descripteur de connexion", difficulty: "hard",
  },
  {
    id: "dg-q56", track: "ocp-dataguard", moduleId: "dg-session-11",
    question: "Pourquoi COMMIT_OUTCOME est-il indispensable à Application Continuity ?",
    options: [
      "Il permet au pilote de savoir si le COMMIT a été validé avant la coupure",
      "Il active la compression du redo",
      "Il déclenche le Fast-Start Failover",
      "Il autorise l'écriture sur la base de secours",
    ],
    correctIndexes: [0],
    explanation: "Sans cette information, rejouer risquerait de dupliquer la transaction, et ne pas rejouer risquerait de la perdre. COMMIT_OUTCOME enregistre le sort de chaque transaction, ce qui permet au pilote de trancher correctement après une bascule.",
    topic: "Application Continuity", difficulty: "hard",
  },
  {
    id: "dg-q57", track: "ocp-dataguard", moduleId: "dg-session-11",
    question: "Quels éléments rendent une transaction non rejouable par Application Continuity ? (Choisissez deux réponses.)",
    options: [
      "Un appel externe comme UTL_HTTP ou UTL_FILE",
      "Une transaction plus longue que replay_init_time",
      "Un COMMIT explicite",
      "L'utilisation de variables de liaison",
    ],
    correctIndexes: [0, 1],
    explanation: "Un appel externe a produit un effet hors de la base : le rejouer le dupliquerait. Au-delà de replay_init_time, le pilote cesse d'enregistrer. Le COMMIT et les variables de liaison sont au contraire le fonctionnement normal et attendu.",
    topic: "Application Continuity", difficulty: "hard",
  },
  {
    id: "dg-q58", track: "ocp-dataguard", moduleId: "dg-session-11",
    question: "Qu'apporte Transparent Application Continuity, introduit en 19c ?",
    options: [
      "La détection automatique des frontières de transaction, sans modifier l'application",
      "Le rejeu des transactions sur une base de secours logique",
      "La suppression du besoin d'un service configuré",
      "La compression automatique du redo",
    ],
    correctIndexes: [0],
    explanation: "Application Continuity classique suppose que l'application pose des frontières de requête. La variante transparente les détecte seule, ainsi que l'état de session, et s'active par -failovertype AUTO. C'est la seule voie réaliste pour des applications héritées qu'on ne peut plus modifier.",
    topic: "Application Continuity", difficulty: "hard",
  },
  {
    id: "dg-q59", track: "ocp-dataguard", moduleId: "dg-session-11",
    question: "Sans Grid Infrastructure, comment garantir qu'un service ne démarre que sur la base ayant le rôle PRIMARY ?",
    options: [
      "Par un trigger AFTER DB_ROLE_CHANGE ON DATABASE qui teste V$DATABASE.DATABASE_ROLE",
      "En fixant SERVICE_NAMES statiquement dans le SPFILE",
      "En déclarant le service uniquement sur la base principale",
      "Par un alias TNS pointant vers un seul site",
    ],
    correctIndexes: [0],
    explanation: "L'attribut -role de srvctl n'existe qu'avec Grid Infrastructure. Ailleurs, un trigger sur DB_ROLE_CHANGE — complété par un trigger AFTER STARTUP — démarre le service du bon côté après chaque bascule. SERVICE_NAMES statique le démarrerait des deux côtés à la fois.",
    topic: "Service lié au rôle", difficulty: "hard",
  },
];

export const racQuestionsB: QuizQuestion[] = [
  // ─── Session 7 — Flex ASM et CloudFS ────────────────────────────────────
  {
    id: "rac-q39", track: "ocp-rac", moduleId: "rac-session-7",
    question: "Quel problème Flex ASM résout-il ?",
    options: [
      "La perte de l'instance ASM d'un nœud n'entraîne plus la perte de toutes ses bases",
      "Il supprime le besoin de groupes de disques",
      "Il permet d'installer ASM sans Grid Infrastructure",
      "Il remplace le stockage partagé par du stockage local",
    ],
    correctIndexes: [0],
    explanation: "En ASM classique, chaque nœud dépend de son instance ASM locale : si elle tombe, toutes les bases du nœud tombent. Flex ASM permet à une base de se connecter à l'instance ASM d'un autre nœud par le réseau ASM, ce qui casse ce couplage.",
    topic: "Flex ASM", difficulty: "medium",
  },
  {
    id: "rac-q40", track: "ocp-rac", moduleId: "rac-session-7",
    question: "Quelle est la cardinalité par défaut de Flex ASM ?",
    options: ["3", "1", "2", "Autant que de nœuds"],
    correctIndexes: [0],
    explanation: "Trois instances ASM sont maintenues quel que soit le nombre de nœuds du cluster. `srvctl modify asm -count` la modifie, et la valeur ALL rétablit le comportement classique d'une instance par nœud.",
    topic: "Flex ASM", difficulty: "medium",
  },
  {
    id: "rac-q41", track: "ocp-rac", moduleId: "rac-session-7",
    question: "Quel prérequis bloque le plus souvent l'activation de Flex ASM ?",
    options: [
      "Un groupe de disques dont COMPATIBLE.ASM est resté inférieur à 12.1",
      "Un nombre de nœuds inférieur à trois",
      "L'absence de tablespace temporaire partagé",
      "Un cluster géré par administrateur",
    ],
    correctIndexes: [0],
    explanation: "Flex ASM exige COMPATIBLE.ASM à 12.1 ou plus sur tous les groupes de disques. Un seul groupe resté en 11.2 suffit à bloquer l'activation, et le message d'erreur ne le dit pas clairement. Relever l'attribut est irréversible.",
    topic: "Flex ASM", difficulty: "hard",
  },
  {
    id: "rac-q42", track: "ocp-rac", moduleId: "rac-session-7",
    question: "Quel composant expose un groupe de disques ASM comme un périphérique bloc du système ?",
    options: ["ADVM", "ACFS", "ASMCMD", "OCR"],
    correctIndexes: [0],
    explanation: "ASM Dynamic Volume Manager crée des volumes visibles sous /dev/asm/<volume>-<n>. ACFS est le système de fichiers en cluster posé au-dessus de ces volumes ; asmcmd est l'outil d'administration en ligne de commande.",
    topic: "ADVM", difficulty: "medium",
  },
  {
    id: "rac-q43", track: "ocp-rac", moduleId: "rac-session-7",
    question: "Quelles fonctionnalités avancées ACFS propose-t-il ? (Choisissez trois réponses.)",
    options: [
      "Chiffrement au repos",
      "Audit des accès aux fichiers",
      "Réplication vers un cluster distant",
      "Compression hybride en colonnes",
      "Application du redo",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "ACFS chiffre (acfsutil encr), audite (acfsutil audit) et réplique (acfsutil repl), avec l'étiquetage pour cibler des sous-ensembles de fichiers. La compression hybride en colonnes concerne les tables Oracle, et l'application du redo relève de Data Guard.",
    topic: "ACFS", difficulty: "hard",
  },
  {
    id: "rac-q44", track: "ocp-rac", moduleId: "rac-session-7",
    question: "Sur quoi repose la haute disponibilité d'un export NFS depuis ACFS ?",
    options: [
      "Une HAVIP gérée par Clusterware, qui migre si le nœud exportateur tombe",
      "Une réplication synchrone entre deux serveurs NFS",
      "Un montage NFS sur chaque client",
      "Le tourniquet DNS du SCAN",
    ],
    correctIndexes: [0],
    explanation: "srvctl add havip crée une adresse virtuelle dédiée, et srvctl add exportfs y rattache l'export. Si le nœud exportateur disparaît, la VIP migre vers un autre nœud et les clients NFS ne voient qu'une brève suspension.",
    topic: "Haute disponibilité NFS", difficulty: "hard",
  },

  // ─── Session 8 — Installer et administrer une base RAC ──────────────────
  {
    id: "rac-q45", track: "ocp-rac", moduleId: "rac-session-8",
    question: "Une instance RAC nouvellement ajoutée refuse de démarrer. Quels deux objets vérifier en priorité ? (Choisissez deux réponses.)",
    options: [
      "Son thread de redo, activé et déclaré PUBLIC",
      "Son tablespace d'annulation, déclaré pour son SID",
      "Son fichier de contrôle dédié",
      "Sa propre copie du SPFILE",
    ],
    correctIndexes: [0, 1],
    explanation: "Chaque instance a son thread de redo et son undo. Ce sont les deux oublis classiques lors de l'ajout d'un nœud. Le fichier de contrôle et le SPFILE sont au contraire uniques et partagés : une copie par instance serait une erreur.",
    topic: "Administration RAC", difficulty: "hard",
  },
  {
    id: "rac-q46", track: "ocp-rac", moduleId: "rac-session-8",
    question: "Pourquoi un thread de redo doit-il être déclaré PUBLIC ?",
    options: [
      "Pour qu'une instance quelconque puisse s'en emparer, ce qu'exige la gestion par politiques",
      "Pour qu'il soit archivé",
      "Pour qu'il soit visible dans V$LOG",
      "Pour permettre le multiplexage",
    ],
    correctIndexes: [0],
    explanation: "Un thread privé est réservé à une instance nommée. C'est acceptable en gestion par administrateur, mais bloquant dans une base gérée par politique, où les instances se déplacent entre serveurs et doivent pouvoir prendre n'importe quel thread libre.",
    topic: "Threads de redo", difficulty: "hard",
  },
  {
    id: "rac-q47", track: "ocp-rac", moduleId: "rac-session-8",
    question: "Quel utilitaire convertit une base mono-instance en base RAC ?",
    options: ["rconfig", "cluvfy", "opatchauto", "oclumon"],
    correctIndexes: [0],
    explanation: "rconfig est piloté par un fichier XML : il déplace au besoin les fichiers vers ASM, ajoute les threads de redo et les tablespaces d'annulation, puis enregistre la base auprès de Clusterware. On commence toujours par une vérification à blanc, qui n'écrit rien.",
    topic: "Conversion vers RAC", difficulty: "medium",
  },
  {
    id: "rac-q48", track: "ocp-rac", moduleId: "rac-session-8",
    question: "Comment fixer un paramètre pour une seule instance dans un SPFILE partagé ?",
    options: [
      "ALTER SYSTEM SET … SID = 'orcl2' SCOPE = SPFILE",
      "En créant un pfile local sur ce nœud",
      "ALTER SESSION SET … sur cette instance",
      "En modifiant directement le fichier sur ASM",
    ],
    correctIndexes: [0],
    explanation: "La clause SID cible une instance nommée ; SID='*' vise toutes les instances. V$SPPARAMETER montre le contenu réel du SPFILE, valeurs par instance comprises. Modifier un SPFILE directement sur ASM est impossible : c'est un fichier binaire géré par la base.",
    topic: "Paramètres en cluster", difficulty: "medium",
  },

  // ─── Session 9 — Haute disponibilité des connexions ─────────────────────
  {
    id: "rac-q49", track: "ocp-rac", moduleId: "rac-session-9",
    question: "Quel réglage CLBGOAL convient à une application web avec pool de connexions ?",
    options: ["SHORT", "LONG", "NONE", "THROUGHPUT"],
    correctIndexes: [0],
    explanation: "SHORT s'appuie sur le Load Balancing Advisory et convient aux connexions courtes ou pooled. LONG répartit par nombre de sessions et convient aux clients lourds gardant une session ouverte toute la journée. THROUGHPUT est une valeur de RLBGOAL, pas de CLBGOAL.",
    topic: "Équilibrage de charge", difficulty: "hard",
  },
  {
    id: "rac-q50", track: "ocp-rac", moduleId: "rac-session-9",
    question: "Pourquoi FAN peut-il rester sans effet malgré une configuration correcte côté base ?",
    options: [
      "Le client n'écoute pas les événements : pool JDBC générique ou connexion nue",
      "FAN exige le mode ARCHIVELOG",
      "FAN ne fonctionne qu'avec deux nœuds",
      "FAN nécessite Application Continuity",
    ],
    correctIndexes: [0],
    explanation: "FAN publie l'événement, mais il faut un client capable de l'entendre : UCP, WebLogic, ODP.NET ou un pilote OCI configuré. Un pool applicatif maison ou un DriverManager nu les ignorent, et la notification est publiée dans le vide.",
    topic: "FAN", difficulty: "hard",
  },
  {
    id: "rac-q51", track: "ocp-rac", moduleId: "rac-session-9",
    question: "À quoi sert l'étiquette de colocalisation (colocation tag) ?",
    options: [
      "Router vers la même instance les sessions travaillant sur les mêmes données",
      "Identifier les sessions d'un même utilisateur dans AWR",
      "Nommer les groupes de disques ASM",
      "Étiqueter les fichiers ACFS à répliquer",
    ],
    correctIndexes: [0],
    explanation: "En regroupant sur une seule instance les sessions d'un même locataire ou d'un même périmètre de données, les blocs restent dans un seul buffer cache et les transferts Cache Fusion diminuent d'autant. L'étiquetage ACFS est un mécanisme distinct, sans rapport.",
    topic: "Colocalisation", difficulty: "hard",
  },
  {
    id: "rac-q52", track: "ocp-rac", moduleId: "rac-session-9",
    question: "Que se passe-t-il si un service est créé sans l'option -failback ?",
    options: [
      "Déplacé par une panne, il reste sur le nœud de repli même après rétablissement",
      "Il ne bascule jamais en cas de panne",
      "Il démarre sur toutes les instances simultanément",
      "Il ne peut pas être relocalisé manuellement",
    ],
    correctIndexes: [0],
    explanation: "Sans -failback, la répartition prévue ne revient jamais d'elle-même : le service reste indéfiniment sur son instance de repli. Il faut alors un srvctl relocate service manuel, que personne ne pense à faire une fois l'incident oublié.",
    topic: "Services de repli", difficulty: "hard",
  },

  // ─── Session 10 — RAC One Node et QoS ───────────────────────────────────
  {
    id: "rac-q53", track: "ocp-rac", moduleId: "rac-session-10",
    question: "Qu'est-ce qui caractérise une base Oracle RAC One Node ?",
    options: [
      "Une seule instance active à la fois, mais enregistrée sur plusieurs nœuds",
      "Plusieurs instances actives sur un seul nœud",
      "Une base mono-instance sans Clusterware",
      "Une base répliquée par Data Guard",
    ],
    correctIndexes: [0],
    explanation: "RAC One Node donne la haute disponibilité et la maintenance sans coupure — par relocalisation en ligne — sans la complexité du cluster actif-actif : ni Cache Fusion, ni bloc chaud partagé. En revanche, elle ne monte pas en charge horizontalement.",
    topic: "RAC One Node", difficulty: "medium",
  },
  {
    id: "rac-q54", track: "ocp-rac", moduleId: "rac-session-10",
    question: "Pendant une relocalisation en ligne d'une base RAC One Node, que se passe-t-il ?",
    options: [
      "Les deux instances coexistent brièvement, le temps que les sessions migrent",
      "L'ancienne instance est arrêtée avant que la nouvelle démarre",
      "Toutes les sessions sont immédiatement tuées",
      "La base passe en lecture seule pendant l'opération",
    ],
    correctIndexes: [0],
    explanation: "C'est ce recouvrement qui rend l'opération transparente : la nouvelle instance accepte les connexions pendant que l'ancienne finit ses transactions. Les sessions restées au-delà du délai sont en revanche tuées, d'où l'importance de FAN et d'Application Continuity.",
    topic: "RAC One Node", difficulty: "hard",
  },
  {
    id: "rac-q55", track: "ocp-rac", moduleId: "rac-session-10",
    question: "Sur quoi repose QoS Management pour arbitrer entre applications ?",
    options: [
      "Un objectif de temps de réponse déclaré par classe de travail",
      "Un quota de CPU fixé manuellement par instance",
      "Le nombre de sessions ouvertes par service",
      "La taille de la SGA de chaque nœud",
    ],
    correctIndexes: [0],
    explanation: "Au lieu de régler des paramètres, on déclare le résultat attendu. QoS mesure en continu le temps de réponse obtenu et ajuste parts de CPU, allocation de connexions ou déplacement de serveurs pour tenir l'objectif, en respectant le rang de criticité des classes.",
    topic: "Qualité de service", difficulty: "hard",
  },
  {
    id: "rac-q56", track: "ocp-rac", moduleId: "rac-session-10",
    question: "Quel prérequis rend la plupart des leviers de QoS inopérants s'il n'est pas satisfait ?",
    options: [
      "Un cluster géré par politiques, avec des pools de serveurs",
      "Le mode ARCHIVELOG",
      "Au moins quatre nœuds",
      "Flex ASM activé",
    ],
    correctIndexes: [0],
    explanation: "Le déplacement de serveur entre pools, principal levier de QoS, suppose des pools déclarés. Sur un cluster géré par administrateur, où chaque instance est clouée à un nœud nommé, QoS s'installe mais ne peut rien déplacer. Le GIMR doit également être actif.",
    topic: "Qualité de service", difficulty: "hard",
  },

  // ─── Session 11 — Multitenant en RAC ────────────────────────────────────
  {
    id: "rac-q57", track: "ocp-rac", moduleId: "rac-session-11",
    question: "Que permet la clause INSTANCES d'un ALTER PLUGGABLE DATABASE … OPEN en RAC ?",
    options: [
      "Ouvrir la PDB sur un sous-ensemble choisi des instances de la CDB",
      "Répartir les fichiers de la PDB entre les instances",
      "Créer un tablespace d'annulation par instance",
      "Définir le nombre maximal de sessions par instance",
    ],
    correctIndexes: [0],
    explanation: "Une PDB peut être ouverte sur toutes les instances, sur certaines seulement, et dans des modes différents selon l'instance. C'est un outil de répartition : la production d'un côté, le décisionnel en lecture seule de l'autre.",
    topic: "Multitenant en RAC", difficulty: "medium",
  },
  {
    id: "rac-q58", track: "ocp-rac", moduleId: "rac-session-11",
    question: "Après le redémarrage d'une instance, un service applicatif rattaché à une PDB ne démarre pas. Première piste ?",
    options: [
      "La PDB est revenue fermée, faute d'un SAVE STATE",
      "Le service a été supprimé du fichier OCR",
      "Le listener local n'est pas démarré",
      "Le tablespace d'annulation de la PDB manque",
    ],
    correctIndexes: [0],
    explanation: "Sans SAVE STATE, une PDB revient fermée après le redémarrage d'une instance, et le service qui en dépend ne peut pas démarrer. DBA_PDB_SAVED_STATES montre exactement ce qui a été mémorisé, instance par instance.",
    topic: "Multitenant en RAC", difficulty: "hard",
  },
  {
    id: "rac-q59", track: "ocp-rac", moduleId: "rac-session-11",
    question: "Comment corriger une CDB sans interrompre durablement les applications de ses PDB ?",
    options: [
      "Relocaliser les PDB vers une CDB déjà corrigée, corriger la CDB vidée, puis les ramener",
      "Arrêter toutes les instances et appliquer le correctif hors ligne",
      "Convertir les PDB en bases mono-instances le temps du correctif",
      "Utiliser Data Guard pour répliquer chaque PDB séparément",
    ],
    correctIndexes: [0],
    explanation: "CREATE PLUGGABLE DATABASE … RELOCATE AVAILABILITY MAX déplace une PDB entre CDB avec une coupure de l'ordre de la seconde. On vide la CDB à corriger, on la met à niveau, puis on ramène les PDB : la disponibilité applicative est préservée de bout en bout.",
    topic: "Correctifs de PDB", difficulty: "hard",
  },

  // ─── Session 12 — Flex Clusters, politiques, HA applicative ─────────────
  {
    id: "rac-q60", track: "ocp-rac", moduleId: "rac-session-12",
    question: "Qu'est-ce qui distingue un nœud feuille d'un nœud concentrateur dans un Flex Cluster ?",
    options: [
      "Le nœud feuille n'accède pas au stockage partagé et n'héberge aucune instance de base",
      "Le nœud feuille dispose de plus de mémoire",
      "Le nœud feuille héberge obligatoirement une instance ASM",
      "Le nœud feuille possède ses propres voting disks",
    ],
    correctIndexes: [0],
    explanation: "Un nœud feuille dépend d'un concentrateur pour joindre l'OCR et les voting disks, et ne peut pas porter d'instance de base. Il sert aux serveurs d'application et aux traitements qui n'ont pas besoin du stockage partagé.",
    topic: "Flex Clusters", difficulty: "hard",
  },
  {
    id: "rac-q61", track: "ocp-rac", moduleId: "rac-session-12",
    question: "Pourquoi la perte d'un nœud feuille n'entraîne-t-elle pas de reconfiguration du cluster ?",
    options: [
      "Il ne participe pas au quorum, n'accédant ni à l'OCR ni aux voting disks",
      "Il est automatiquement remplacé par un nœud de secours",
      "Son état est répliqué en permanence sur un concentrateur",
      "Clusterware ne le surveille pas",
    ],
    correctIndexes: [0],
    explanation: "Le quorum se joue sur les voting disks, auxquels un nœud feuille n'accède pas. Sa disparition ne peut donc pas provoquer de split-brain, et n'oblige à renégocier aucune appartenance — contrairement à la perte d'un concentrateur.",
    topic: "Flex Clusters", difficulty: "hard",
  },
  {
    id: "rac-q62", track: "ocp-rac", moduleId: "rac-session-12",
    question: "Quelle différence sépare une base gérée par administrateur d'une base gérée par politiques ?",
    options: [
      "L'une nomme explicitement ses nœuds, l'autre déclare un besoin en serveurs",
      "L'une utilise ASM, l'autre un système de fichiers",
      "L'une est en ARCHIVELOG, l'autre non",
      "L'une accepte les services, l'autre non",
    ],
    correctIndexes: [0],
    explanation: "En gestion par administrateur, chaque instance est clouée à un nœud nommé. En gestion par politiques, on déclare un pool avec un minimum et un maximum de serveurs, et Clusterware choisit lesquels et rééquilibre seul. C'est un prérequis de QoS Management.",
    topic: "Gestion par politiques", difficulty: "medium",
  },
  {
    id: "rac-q63", track: "ocp-rac", moduleId: "rac-session-12",
    question: "Que permet crsctl eval ?",
    options: [
      "Simuler l'effet d'une opération sans l'exécuter",
      "Évaluer les performances d'une requête",
      "Valider la configuration réseau du cluster",
      "Estimer l'espace libre des groupes de disques",
    ],
    correctIndexes: [0],
    explanation: "crsctl eval répond à « que se passerait-il si… » : arrêter un serveur, activer une politique, déplacer une ressource. Sur un cluster de production, c'est ce qui permet de vérifier qu'une maintenance ne déclenchera pas une cascade de relocalisations imprévues.",
    topic: "Évaluation hypothétique", difficulty: "hard",
  },
  {
    id: "rac-q64", track: "ocp-rac", moduleId: "rac-session-12",
    question: "Quel attribut PLACEMENT restreint une ressource applicative aux seuls nœuds de HOSTING_MEMBERS ?",
    options: ["restricted", "favored", "balanced", "exclusive"],
    correctIndexes: [0],
    explanation: "restricted limite strictement la ressource aux nœuds listés. favored les préfère mais accepte les autres, et balanced laisse Clusterware choisir le nœud le moins chargé. Le choix dépend de contraintes réelles : licence, matériel, accès réseau.",
    topic: "Ressources applicatives", difficulty: "hard",
  },
  {
    id: "rac-q65", track: "ocp-rac", moduleId: "rac-session-12",
    question: "Pourquoi un script d'action dont le check teste seulement la présence du processus est-il insuffisant ?",
    options: [
      "Une application bloquée mais vivante ne sera jamais redémarrée",
      "Clusterware refuse les scripts sans code de retour",
      "Le check doit obligatoirement être écrit en Perl",
      "La présence du processus n'est pas mesurable sous Linux",
    ],
    correctIndexes: [0],
    explanation: "Un processus zombie répond à pgrep tout en ne servant plus rien : la haute disponibilité devient illusoire. Le contrôle doit interroger le service comme le ferait un utilisateur — une requête HTTP, une connexion, une transaction de test.",
    topic: "Ressources applicatives", difficulty: "hard",
  },
];
