import type { QuizQuestionTranslation } from "./types";

/**
 * English rendering of the 1Z0-078 bank (`quiz-data-rac.ts`).
 * Keyed by question id; option order preserved.
 */
export const racEnglish: Record<string, QuizQuestionTranslation> = {
  "rac-q1": {
    question: "Which risk does a RAC cluster NOT protect against?",
    options: [
      "Loss of the site, since every node shares the same storage",
      "Failure of one server in the cluster",
      "A planned instance shutdown for maintenance",
      "Saturation of a single node",
    ],
    explanation: "RAC protects against node failure, not site disaster: the shared disk array remains a single point of failure. Data Guard covers that risk, and backups cover logical error.",
    topic: "RAC scope",
  },
  "rac-q2": {
    question: "Which Clusterware component decides to evict a node?",
    options: ["CSSD", "CRSD", "EVMD", "OHASD"],
    explanation: "CSSD (Cluster Synchronization Services) manages cluster membership, network and disk heartbeats, and decides on eviction. CRSD manages high-level resources, EVMD publishes events, OHASD starts the stack at boot.",
    topic: "Clusterware components",
  },
  "rac-q3": {
    question: "How many addresses must the SCAN name resolve to, and by what means?",
    options: [
      "Three addresses, through round-robin DNS",
      "One address, declared in /etc/hosts",
      "One address per cluster node",
      "Two addresses, through GNS only",
    ],
    explanation: "The SCAN must resolve to three addresses via round-robin DNS. Declaring it in /etc/hosts returns only one address: the installer rejects it or produces a degraded cluster. It is the most frequent manual-installation mistake.",
    topic: "SCAN",
  },
  "rac-q4": {
    question: "Which addresses must be prepared per node before installation? (Choose three.)",
    options: [
      "A public address",
      "A private interconnect address",
      "A VIP not assigned before installation",
      "Three SCAN addresses per node",
      "An address for the OCR",
    ],
    explanation: "Each node has a public address, at least one private address dedicated to the interconnect, and a VIP that must resolve in DNS but must NOT be assigned before installation. The three SCAN addresses belong to the whole cluster, not per node.",
    topic: "Network prerequisites",
  },
  "rac-q5": {
    question: "Which utility checks cluster installation prerequisites?",
    options: ["cluvfy (runcluvfy.sh)", "opatchauto", "asmcmd", "srvctl"],
    explanation: "The Cluster Verification Utility runs before installation as runcluvfy.sh, then afterwards as cluvfy. It checks network, shared storage, kernel parameters, users and packages. Running it up front prevents most failures.",
    topic: "cluvfy",
  },
  "rac-q6": {
    question: "How must root.sh be run during a Grid Infrastructure installation?",
    options: [
      "Sequentially, one node after another, starting with the first",
      "Simultaneously on all nodes to save time",
      "Only on the node holding the SCAN",
      "After the RAC database has started",
    ],
    explanation: "root.sh configures the cluster stack and initialises the OCR and voting disks on the first node; the others then join. Running it in parallel corrupts the configuration.",
    topic: "Installation",
  },
  "rac-q7": {
    question: "Which tool stops a database instance in a cluster?",
    options: [
      "srvctl stop instance",
      "crsctl stop crs",
      "crsctl stop cluster",
      "asmcmd shutdown",
    ],
    explanation: "srvctl drives Oracle resources: databases, instances, services, listeners, ASM, VIPs. crsctl drives the cluster stack itself. Rule of thumb: if the object would exist without Oracle Database, it is crsctl.",
    topic: "crsctl vs srvctl",
  },
  "rac-q8": {
    question: "Why must the number of voting disks be odd?",
    options: [
      "Because a node must see more than half the voting disks to stay in the cluster",
      "Because ASM can only manage an odd number of disks",
      "Because the OCR requires one per node",
      "Because the SCAN uses three",
    ],
    explanation: "Quorum requires a strict majority. With two voting disks, losing one brings the whole cluster down: you need 1, 3 or 5. With normal redundancy, ASM places three automatically.",
    topic: "Voting disks",
  },
  "rac-q9": {
    question: "What distinguishes the OCR from the OLR?",
    options: [
      "The OCR describes the whole cluster; the OLR is local to a node and read before the OCR is reachable",
      "The OLR describes the whole cluster; the OCR is local",
      "Both are identical, the OLR is just a backup",
      "The OLR contains only the voting disks",
    ],
    explanation: "The OLR lets OHASD start the local stack before shared storage — hence the OCR — is reachable. It is backed up manually through ocrconfig -local -manualbackup, whereas the OCR is backed up automatically.",
    topic: "OCR and OLR",
  },
  "rac-q10": {
    question: "How often is the OCR backed up automatically?",
    options: ["Every 4 hours", "Every hour", "Once a day", "On every change"],
    explanation: "Clusterware backs up the OCR every 4 hours and keeps a week of backups. ocrconfig -showbackup lists them. Voting disks, by contrast, are not backed up: they are re-created.",
    topic: "OCR backup",
  },
  "rac-q11": {
    question: "Which process starts the Clusterware stack when the server boots?",
    options: ["OHASD", "CRSD", "CSSD", "GPNPD"],
    explanation: "OHASD (Oracle High Availability Services Daemon) starts at boot then launches GPNPD, GIPCD, MDNSD and CSSD. CSSD then reads the voting disks, ASM mounts the disk groups, and CRSD reads the OCR to start the resources.",
    topic: "Startup sequence",
  },
  "rac-q12": {
    question: "Which command shows the state of every cluster resource?",
    options: ["crsctl stat res -t", "srvctl config database", "ocrcheck", "oclumon dumpnodeview"],
    explanation: "crsctl stat res -t prints a readable table of all resources, local and cluster-wide, with their state per node. Adding -init shows the low-level resources managed by OHASD.",
    topic: "Cluster diagnostics",
  },
  "rac-q13": {
    question: "Which statement correctly describes an ASM instance?",
    options: [
      "It has an SGA and processes but no data files, and never serves user queries",
      "It holds a copy of the database dictionary",
      "It intercepts all database I/O",
      "It replaces the database instance's buffer cache",
    ],
    explanation: "ASM tells database instances where the extents are, then steps aside: I/O goes straight from the database server to the disk. It is a metadata manager, not a data intermediary.",
    topic: "ASM instance",
  },
  "rac-q14": {
    question: "Which privilege allows creating and dropping an ASM disk group?",
    options: ["SYSASM", "SYSDBA", "SYSOPER", "SYSBACKUP"],
    explanation: "SYSASM is the full ASM administration privilege since 11g. SYSDBA on an ASM instance only grants file access from a database; SYSOPER allows start, stop and mount without changing the configuration.",
    topic: "ASM privileges",
  },
  "rac-q15": {
    question: "How many failure groups does HIGH redundancy require at minimum?",
    options: ["Three", "Two", "One", "Five"],
    explanation: "HIGH keeps three copies of every extent and therefore requires three failure groups; NORMAL keeps two and requires two; EXTERNAL keeps one and delegates protection to the array.",
    topic: "ASM redundancy",
  },
  "rac-q16": {
    question: "What is a failure group for?",
    options: [
      "Grouping the disks that fail together, so ASM never places two copies of the same extent there",
      "Grouping disks of the same size",
      "Isolating disks reserved for the FRA",
      "Defining the rebalance order",
    ],
    explanation: "A failure group corresponds to a failure domain: an array, a controller, a rack. Declaring two failure groups on the same physical array gives an illusion of redundancy — the most expensive design mistake there is.",
    topic: "Failure groups",
  },
  "rac-q17": {
    question: "What does the POWER clause of ALTER DISKGROUP … REBALANCE control?",
    options: [
      "Rebalance speed, from 0 (suspended) to 1024",
      "The number of copies kept",
      "The allocation unit size",
      "The number of failure groups",
    ],
    explanation: "POWER ranges from 0 to 1024; its default comes from ASM_POWER_LIMIT. Value 0 suspends the rebalance. V$ASM_OPERATION reports progress and an estimate of the remaining time.",
    topic: "Rebalance",
  },
  "rac-q18": {
    question: "Why drop a disk and add another in a single statement?",
    options: [
      "To trigger only one rebalance instead of two",
      "To avoid losing redundancy",
      "Because ASM refuses two successive operations",
      "To preserve file aliases",
    ],
    explanation: "Two separate statements cause two successive full rebalances. A single statement triggers only one, twice as fast overall — on a large array the difference is measured in hours.",
    topic: "Rebalance",
  },
  "rac-q19": {
    question: "What does a negative USABLE_FILE_MB in V$ASM_DISKGROUP mean?",
    options: [
      "The group is too full to rebuild itself after losing a failure group",
      "The disk group is corrupt",
      "A rebalance is in progress",
      "Redundancy has been disabled",
    ],
    explanation: "USABLE_FILE_MB shows how much can still be written while keeping the ability to rebuild. A negative value means redundancy still exists, but the next disk failure will be permanent. That is the threshold to alert on, not FREE_MB.",
    topic: "ASM monitoring",
  },
  "rac-q20": {
    question: "What does ACFS allow that ASM alone does not?",
    options: [
      "Storing non-database files, mounted on every node",
      "Striping extents across several disks",
      "Providing data redundancy",
      "Hosting the voting disks",
    ],
    explanation: "ASM stores database files only. ACFS is a clustered file system mounted simultaneously on every node: Oracle binaries, Data Pump dumps, application logs. It offers snapshots and online resizing.",
    topic: "ACFS",
  },
  "rac-q21": {
    question: "Which utility browses ASM disk groups from the command line?",
    options: ["asmcmd", "adrci", "crsctl", "oclumon"],
    explanation: "asmcmd offers shell-like navigation: lsdg, ls, du, lsof, cp. It is the fastest way to inspect a disk group's contents without going through SQL.",
    topic: "asmcmd",
  },
  "rac-q22": {
    question: "What is an ASM template for?",
    options: [
      "Defining redundancy and striping granularity per file type",
      "Creating aliases automatically",
      "Setting the group's allocation unit size",
      "Declaring failure groups",
    ],
    explanation: "Templates let you apply HIGH to control files and NORMAL to data files within the same disk group, with fine or coarse striping depending on the type. V$ASM_TEMPLATE lists them.",
    topic: "ASM templates",
  },
  "rac-q23": {
    question: "Which process ships blocks between instances in Cache Fusion?",
    options: ["LMS", "LMD", "LMON", "LCK0"],
    explanation: "LMS (Global Cache Service Process) is the heart of Cache Fusion: it sends blocks to the requesting instance over the interconnect. LMD handles global lock requests, LMON membership and reconfiguration.",
    topic: "Cache Fusion",
  },
  "rac-q24": {
    question: "Why query GV$ views rather than V$ in RAC?",
    options: [
      "Because V$ shows only the local instance, whereas GV$ aggregates every instance",
      "Because V$ views are removed in RAC",
      "Because GV$ is faster",
      "Because V$ only works with ASM",
    ],
    explanation: "Every V$ view has a GV$ counterpart that adds an INST_ID column and aggregates the whole cluster. Diagnosing on V$SESSION in RAC shows only one node — a permanent source of error.",
    topic: "GV$ views",
  },
  "rac-q25": {
    question: "Which parameters must differ between RAC instances? (Choose two.)",
    options: [
      "UNDO_TABLESPACE",
      "INSTANCE_NUMBER",
      "DB_NAME",
      "DB_BLOCK_SIZE",
      "CONTROL_FILES",
    ],
    explanation: "Each instance has its own undo tablespace and its own instance number, hence its own redo thread. DB_NAME, DB_BLOCK_SIZE and CONTROL_FILES describe the single database and are necessarily identical.",
    topic: "RAC parameters",
  },
  "rac-q26": {
    question: "What happens when a client connects to the SCAN name?",
    options: [
      "A SCAN listener redirects it to the local listener of the least-loaded instance",
      "The client is connected to the first declared node",
      "The connection fails if the master node is down",
      "The client must name the instance in the descriptor",
    ],
    explanation: "The SCAN resolves to three addresses round-robin; the SCAN listener reached knows the load of every node and redirects to the right local listener. Adding or removing a node changes nothing client-side.",
    topic: "SCAN",
  },
  "rac-q27": {
    question: "What is a service for in a RAC environment?",
    options: [
      "Defining which instances an application runs on and where it fails over",
      "Replacing the local listener",
      "Declaring ASM disk groups",
      "Setting the degree of parallelism for queries",
    ],
    explanation: "A service is RAC's unit of work: preferred instances, available instances, balancing policy, resource measurement. Without services, every application connects everywhere and nothing can be isolated.",
    topic: "Services",
  },
  "rac-q28": {
    question: "What distinguishes a “preferred” instance from an “available” one?",
    options: [
      "The service starts on preferred instances and only moves to available ones on failure",
      "Available instances are faster",
      "Preferred instances are limited to one per service",
      "There is no functional difference",
    ],
    explanation: "A preferred instance hosts the service in normal operation; an available instance receives it only when a preferred one fails. That is what lets you reserve a node for a given workload.",
    topic: "Services",
  },
  "rac-q29": {
    question: "Which mechanisms improve client-side continuity in RAC? (Choose three.)",
    options: [
      "TAF (Transparent Application Failover)",
      "FAN with Fast Connection Failover",
      "Application Continuity",
      "ASM rebalancing",
      "The RMAN recovery catalog",
    ],
    explanation: "TAF reconnects the session and can continue an in-flight SELECT; FAN notifies the pool at once without waiting for a TCP timeout; Application Continuity replays the interrupted transaction. The other two have nothing to do with connectivity.",
    topic: "Client continuity",
  },
  "rac-q30": {
    question: "What does a “gc cr block lost” event indicate?",
    options: [
      "A hardware problem on the interconnect",
      "An inefficient execution plan",
      "Insufficient SGA memory",
      "Contention on a hot block",
    ],
    explanation: "A block lost on the interconnect signals a network fault: a saturated card, a mismatched MTU, packet loss. It is top priority, ahead of any SQL analysis.",
    topic: "Global waits",
  },
  "rac-q31": {
    question: "A significant “gc buffer busy acquire” wait indicates:",
    options: [
      "Several instances contending for the same block",
      "A failing disk",
      "A lagging standby database",
      "An undersized shared pool",
    ],
    explanation: "This is a hot block shared between instances: an uncached sequence, an ascending-key index, a counter row. The remedies are structural — CACHE NOORDER, reverse-key index, partitioning the application by service.",
    topic: "Global waits",
  },
  "rac-q32": {
    question: "How should a sequence be configured to limit contention in RAC?",
    options: [
      "CACHE 1000 NOORDER",
      "ORDER NOCACHE",
      "CACHE 20 ORDER",
      "NOCACHE NOORDER",
    ],
    explanation: "A large cache reduces dictionary access, and NOORDER avoids serialising allocation between instances. ORDER, by contrast, forces global coordination on every value: the worst possible choice in a cluster.",
    topic: "Sequences in RAC",
  },
  "rac-q33": {
    question: "During an RMAN recovery of a RAC database, what must you ensure?",
    options: [
      "That the archived logs of ALL threads are reachable",
      "That each instance restores its own part of the database",
      "That the recovery catalog is local to one node",
      "That every instance is open simultaneously",
    ],
    explanation: "Each instance produces its own redo thread. Recovery replays the redo of every thread: archives must therefore be in shared storage, typically the FRA on ASM. A single instance mounts the database to restore.",
    topic: "RAC backup",
  },
  "rac-q34": {
    question: "Which utility applies a patch in rolling mode on a cluster?",
    options: ["opatchauto", "cluvfy", "srvctl", "asmca"],
    explanation: "opatchauto stops the node's stack, applies the patch then restarts, while the other nodes keep serving. Check beforehand that the patch is declared rolling by opatch query.",
    topic: "Rolling patches",
  },
  "rac-q35": {
    question: "What are the two causes of node eviction? (Choose two.)",
    options: [
      "Loss of the network heartbeat beyond misscount",
      "Loss of access to the voting disks beyond disktimeout",
      "Buffer cache saturation",
      "Missing statistics on a table",
    ],
    explanation: "Those are the only two eviction criteria. The cluster would rather lose a node than risk a split brain: eviction is not a defect, it is the protection working. misscount defaults to 30 s, disktimeout to 200 s.",
    topic: "Node eviction",
  },
  "rac-q36": {
    question: "Which trace file gives the exact reason for a node eviction?",
    options: ["ocssd.trc", "crsd.trc", "alert_ORCL.log", "listener.log"],
    explanation: "ocssd.trc records CSSD's decisions, including the eviction reason: network heartbeat or disk heartbeat. The cluster alert log gives the context, crsd.trc resource start failures.",
    topic: "Troubleshooting",
  },
  "rac-q37": {
    question: "Which tool collects the cluster's full diagnostics for support?",
    options: [
      "diagcollection.sh",
      "tkprof",
      "opatch lsinventory",
      "ocrconfig -showbackup",
    ],
    explanation: "diagcollection.sh --collect --crs gathers the Clusterware stack's logs, traces and configuration into one archive. oclumon dumpnodeview complements it with per-node system resource history.",
    topic: "Troubleshooting",
  },
  "rac-q38": {
    question: "Which command moves a service from one instance to another without an outage?",
    options: [
      "srvctl relocate service",
      "srvctl stop service then srvctl start service",
      "crsctl relocate resource",
      "alter system set service_names",
    ],
    explanation: "srvctl relocate service starts the service on the target instance before stopping it on the source, letting connections migrate gradually. A stop followed by a start cuts the service in between.",
    topic: "Services",
  },
};
