import type { QuizQuestionTranslation } from "./types";

/**
 * English rendering of the 1Z0-082 bank (`quiz-data-ocp1.ts` + `-b.ts`).
 * Keyed by question id. Option order is preserved, so `correctIndexes`
 * stays valid without any remapping.
 */
export const ocp1English: Record<string, QuizQuestionTranslation> = {
  "ocp1-q1": {
    question: "Which statements are true about the relationship between an instance and a database? (Choose three.)",
    options: ["An instance can open at most one database at a time", "A database can be opened by several instances in a RAC configuration", "An instance can be started without any database mounted", "A database cannot exist without a running instance", "An instance contains the data files"],
    explanation: "An instance is a set of memory structures and processes; it opens one database at a time. One database can however be opened by several instances under Real Application Clusters. The NOMOUNT state proves an instance lives without a mounted database. Files belong to the database and survive a shutdown.",
    topic: "Instance and database",
  },
  "ocp1-q2": {
    question: "Which background process writes the redo log buffer to the online redo log files?",
    options: ["DBWn", "CKPT", "LGWR", "ARCn"],
    explanation: "LGWR flushes the redo log buffer to the online redo logs, notably on every COMMIT. DBWn writes dirty data blocks, CKPT updates file headers and ARCn archives full redo logs in ARCHIVELOG mode.",
    topic: "Background processes",
  },
  "ocp1-q3": {
    question: "What happens at the next startup after a SHUTDOWN ABORT? (Choose two.)",
    options: ["SMON performs instance recovery", "The database opens as soon as the roll forward phase completes", "An RMAN restore is mandatory", "Transactions committed before the shutdown are lost"],
    explanation: "SHUTDOWN ABORT leaves the database inconsistent: at startup SMON replays all redo (roll forward) then rolls back uncommitted transactions. The database opens as soon as the roll forward ends, the rollback continuing in the background. No restore is needed and nothing committed is lost.",
    topic: "Instance recovery",
  },
  "ocp1-q4": {
    question: "Which statements are true about an Oracle block? (Choose three.)",
    options: ["A row too large for one block is chained across several blocks", "The block header holds its own address (DBA)", "Fragments of the same row can live in different blocks", "An Oracle block always maps to one file-system block", "PCTFREE reserves space for new inserts"],
    explanation: "Chaining spreads an oversized row across several blocks, so its fragments are scattered. The header carries the Data Block Address. An Oracle block spans several file-system blocks, and PCTFREE reserves room for future updates — not inserts.",
    topic: "Block structure",
  },
  "ocp1-q5": {
    question: "Where does the sort area of a session connected in dedicated server mode live?",
    options: ["In the Shared Pool", "In the Large Pool", "In the Database Buffer Cache", "In the server process PGA"],
    explanation: "In dedicated server mode the sort area belongs to the PGA, private to the server process. In shared server mode the User Global Area moves into the SGA instead, specifically the Large Pool — hence the need to size it in that mode.",
    topic: "SGA and PGA",
  },
  "ocp1-q6": {
    question: "Which items are recorded in the alert log? (Choose three.)",
    options: ["Detected deadlocks", "Initialization parameters whose value differs from the default, at startup", "Detected block corruptions", "Every SQL statement run by users", "The detail of rows changed by each UPDATE"],
    explanation: "The alert log traces structural events: startups and shutdowns with non-default parameters, deadlocks, corruptions, internal errors, sensitive DDL. It logs neither ordinary statements nor changed data — that is what auditing and redo are for.",
    topic: "Alert log",
  },
  "ocp1-q7": {
    question: "Which statement correctly describes the write-ahead logging principle?",
    options: ["DBWn writes data blocks before LGWR writes the redo", "LGWR writes the redo before DBWn writes the data blocks", "A COMMIT waits for every dirty block to reach disk", "Redo is only written at checkpoint time"],
    explanation: "Redo is always written before the data blocks. That is what lets SMON replay committed transactions after a crash, without the COMMIT having had to wait for block writes — hence good write performance.",
    topic: "Write-ahead logging",
  },
  "ocp1-q8": {
    question: "Which components belong to the SGA? (Choose three.)",
    options: ["The Database Buffer Cache", "The Shared Pool", "The Redo Log Buffer", "The sort area of a dedicated-server session", "The control files"],
    explanation: "The SGA is the instance's shared memory: buffer cache, shared pool, redo log buffer, large pool, java pool and streams pool. A dedicated-server sort area belongs to the PGA, and control files live on disk.",
    topic: "SGA components",
  },
  "ocp1-q9": {
    question: "Which process releases resources and locks after a user process fails?",
    options: ["PMON", "SMON", "CKPT", "MMON"],
    explanation: "PMON (Process Monitor) cleans up after a failed user process: it rolls back its transaction, releases its locks and returns its resources. SMON handles instance recovery and space maintenance, CKPT checkpoints, MMON AWR statistics and alerts.",
    topic: "PMON and SMON",
  },
  "ocp1-q10": {
    question: "Which statements are true about row migration? (Choose two.)",
    options: ["It happens when an update grows a row beyond the free space of its block", "The original slot keeps a pointer to the new location", "It happens as soon as a row too large for one block is inserted", "It has no effect on read performance"],
    explanation: "Migration concerns a row that grows and no longer fits its block: it moves, the original slot keeping a pointer. Every index read therefore pays an extra access. A row too large at insert time is chaining, a distinct phenomenon. PCTFREE prevents migration.",
    topic: "Row migration",
  },
  "ocp1-q11": {
    question: "Which statements are true about the Automatic Diagnostic Repository? (Choose three.)",
    options: ["It supports Oracle Clusterware diagnostics", "It supports Automatic Storage Management diagnostics", "It is stored outside the database, as a file tree", "It resides in a database schema", "It is only readable while the instance is open"],
    explanation: "The ADR is a file tree outside the database: that is precisely what makes it readable when the instance is down, exactly when you need it most. It covers the database, ASM, Oracle Clusterware and Oracle Net. The adrci tool browses it and builds diagnostic packages.",
    topic: "ADR",
  },
  "ocp1-q12": {
    question: "Where does Oracle place the ADR base when the DIAGNOSTIC_DEST parameter is not set?",
    options: ["In $ORACLE_HOME/dbs", "In the directory named by the ORACLE_BASE environment variable", "In $ORACLE_HOME/rdbms/admin", "In the user's current directory"],
    explanation: "Resolution follows three steps: the DIAGNOSTIC_DEST parameter if set, otherwise the ORACLE_BASE variable, otherwise $ORACLE_HOME/log. The V$DIAG_INFO view shows the value actually in effect.",
    topic: "DIAGNOSTIC_DEST",
  },
  "ocp1-q13": {
    question: "Which scope makes a changed parameter both effective immediately and persistent across restarts?",
    options: ["SCOPE=MEMORY", "SCOPE=SPFILE", "SCOPE=BOTH", "SCOPE=SESSION"],
    explanation: "SCOPE=BOTH combines both effects, and is in fact the default when the instance started from an SPFILE. MEMORY lasts only until shutdown, SPFILE applies only from the next startup. A static parameter accepts SCOPE=SPFILE only.",
    topic: "SPFILE and scopes",
  },
  "ocp1-q14": {
    question: "What exactly happens during ALTER DATABASE MOUNT? (Choose two.)",
    options: ["The control file is read", "The operation is traced in the alert log", "The data files are opened", "The data dictionary becomes queryable"],
    explanation: "Mounting reads the control file, which describes the physical structure, and the event is written to the alert log. Data files and redo logs are only opened at the OPEN step, as is the dictionary, which lives in the SYSTEM tablespace.",
    topic: "Startup states",
  },
  "ocp1-q15": {
    question: "Which shutdown mode rolls back active transactions without waiting for users to disconnect, while still producing a clean shutdown?",
    options: ["SHUTDOWN NORMAL", "SHUTDOWN TRANSACTIONAL", "SHUTDOWN IMMEDIATE", "SHUTDOWN ABORT"],
    explanation: "IMMEDIATE rolls back active transactions, disconnects sessions, writes buffers and takes a checkpoint: the next startup needs no recovery. NORMAL waits for everyone to disconnect, TRANSACTIONAL for transactions to end, and ABORT stops dead, leaving instance recovery to do.",
    topic: "Shutdown modes",
  },
  "ocp1-q16": {
    question: "Which views can be queried from the NOMOUNT state? (Choose two.)",
    options: ["V$INSTANCE", "V$PARAMETER", "DBA_TABLES", "DBA_USERS"],
    explanation: "Dynamic V$ views read from memory — V$INSTANCE, V$SGA, V$PARAMETER — are available from NOMOUNT. Those fed by the control file, such as V$DATAFILE, need MOUNT. DBA_ dictionary views live in SYSTEM and only exist at OPEN.",
    topic: "Dynamic views",
  },
  "ocp1-q17": {
    question: "Which SQL*Plus command lists the substitution variables currently defined?",
    options: ["SHOW ALL", "DEFINE", "SHOW PARAMETER", "LIST"],
    explanation: "DEFINE with no argument lists the defined substitution variables, including those created with && which persist until UNDEFINE. SHOW PARAMETER covers initialization parameters, LIST the SQL buffer.",
    topic: "Substitution variables",
  },
  "ocp1-q18": {
    question: "Which statements are true about the Oracle optimizer? (Choose three.)",
    options: ["It picks the plan it estimates to be cheapest", "It determines the most favourable join order", "It can re-optimize a statement from statistics observed at run time", "It always follows the table order written in the FROM clause", "It ignores statistics when an index exists"],
    explanation: "The cost-based optimizer evaluates several plans and chooses the join order and access method. Since 12c, adaptive optimization lets it correct a plan from what it actually observes at execution. The FROM order does not constrain it, and statistics remain its main input.",
    topic: "Optimizer",
  },
  "ocp1-q19": {
    question: "Which command-line tool browses the ADR, lists incidents and builds a diagnostic package?",
    options: ["adrci", "opatch", "srvctl", "lsnrctl"],
    explanation: "adrci reads the alert log (show alert), lists incidents (show incident) and builds a package for support (ips pack). opatch applies patches, srvctl drives Oracle Restart and lsnrctl the listener.",
    topic: "adrci",
  },
  "ocp1-q20": {
    question: "Which analyses can DBMS_PRIVILEGE_CAPTURE perform? (Choose three.)",
    options: ["Privileges actually used by all users, administrative users included", "Privileges obtained through a role and actually exercised", "Privileges captured under a condition on the session context", "Privileges a user holds on their own objects and did use", "The number of logins per user per day"],
    explanation: "The four capture types are G_DATABASE (whole database, administrative users included), G_ROLE (through given roles), G_CONTEXT (under a session condition) and their combination. DBA_USED_PRIVS and DBA_UNUSED_PRIVS deliver the result, the basis for revoking what is never used.",
    topic: "Privilege analysis",
  },
  "ocp1-q21": {
    question: "A user must create a table in the SALES_Q1 tablespace. What do they need? (Choose three.)",
    options: ["A quota on SALES_Q1", "The CREATE SESSION privilege", "The CREATE TABLE privilege", "The DBA privilege", "The ALTER TABLESPACE privilege"],
    explanation: "Three conditions, no more: being able to connect (CREATE SESSION), being able to create a table (CREATE TABLE), and holding a quota on the target tablespace. Without the quota, creation fails despite the privilege — the classic trap.",
    topic: "Quotas and privileges",
  },
  "ocp1-q22": {
    question: "A user is granted a system privilege WITH ADMIN OPTION. What can they do? (Choose three.)",
    options: ["Exercise the privilege", "Revoke it from those they granted it to", "Re-grant it to others, including the ADMIN OPTION", "Take it away from the administrator who granted it to them", "Convert it into an object privilege"],
    explanation: "WITH ADMIN OPTION confers the right to propagate the privilege, option included, and to revoke it from its grantees. Important for the exam: revoking a **system** privilege does not cascade to derived grants — unlike an **object** privilege granted WITH GRANT OPTION.",
    topic: "WITH ADMIN OPTION",
  },
  "ocp1-q23": {
    question: "A user has reached their quota on a tablespace. Which solutions let inserts continue? (Choose three.)",
    options: ["Raise their quota on that tablespace", "Grant them the UNLIMITED TABLESPACE system privilege", "Drop some of their objects to free space", "Grant them the CREATE TABLE privilege", "Set the tablespace read only"],
    explanation: "The quota is raised with ALTER USER … QUOTA, bypassed with UNLIMITED TABLESPACE — best avoided, since it overrides every quota and defeats least privilege — or freed by dropping objects. CREATE TABLE plays no part here, and read-only mode would forbid all writes.",
    topic: "Managing quotas",
  },
  "ocp1-q24": {
    question: "Why can a user holding CREATE TABLE through a role not create a view based on that table?",
    options: ["Because creating a view requires a directly granted privilege, not one inherited from a role", "Because a view always requires the DBA privilege", "Because a role can never carry a system privilege", "Because views can only be built on SYS-owned tables"],
    explanation: "Stored objects — views, procedures, triggers — only take into account privileges granted directly to their owner. Privileges obtained through a role are disabled in that context, so the object stays valid even if the role is later revoked.",
    topic: "Roles and stored objects",
  },
  "ocp1-q25": {
    question: "Which profile limits apply regardless of the RESOURCE_LIMIT parameter? (Choose two.)",
    options: ["FAILED_LOGIN_ATTEMPTS", "PASSWORD_LIFE_TIME", "SESSIONS_PER_USER", "IDLE_TIME"],
    explanation: "Password-related limits always apply. Resource limits — sessions, idle time, CPU — only take effect when RESOURCE_LIMIT is TRUE, which has been the default since 12c.",
    topic: "Profiles",
  },
  "ocp1-q26": {
    question: "Which statements are true about synonyms? (Choose three.)",
    options: ["A synonym can point at an object owned by another user", "A synonym can point at a sequence", "A public synonym is visible to every user", "A synonym implicitly grants access to the target object", "A synonym can only point at a table"],
    explanation: "A synonym is just an alias: it can target tables, views, sequences, procedures or other synonyms, including in another schema, and it can be public. It confers no right at all — without the object privilege, access fails despite the synonym.",
    topic: "Synonyms",
  },
  "ocp1-q27": {
    question: "Which command locks an account without dropping it?",
    options: ["DROP USER marie", "ALTER USER marie ACCOUNT LOCK", "REVOKE CREATE SESSION FROM marie", "ALTER USER marie PASSWORD EXPIRE"],
    explanation: "ACCOUNT LOCK forbids any connection while keeping the account and its objects; ACCOUNT UNLOCK restores it. Revoking CREATE SESSION has a similar effect but is less explicit, PASSWORD EXPIRE only forces a password change, and DROP removes everything.",
    topic: "Account management",
  },
  "ocp1-q28": {
    question: "Which network security features does Oracle offer at the listener level? (Choose two.)",
    options: ["Restricting which IP addresses may connect", "Enabling predefined access-control rules", "Automatically encrypting every tablespace", "Automatically expiring passwords"],
    explanation: "Oracle Net can filter by address through valid node checking and apply predefined rules. Tablespace encryption belongs to Transparent Data Encryption, and password expiry to profiles.",
    topic: "Network security",
  },
  "ocp1-q29": {
    question: "What difference separates WITH ADMIN OPTION from WITH GRANT OPTION on revoke?",
    options: ["WITH ADMIN OPTION cascades on revoke, WITH GRANT OPTION does not", "WITH GRANT OPTION cascades on revoke, WITH ADMIN OPTION does not", "Both cascade on revoke", "Neither cascades on revoke"],
    explanation: "Revoking an **object** privilege granted WITH GRANT OPTION also removes the derived grants. Revoking a **system** privilege granted WITH ADMIN OPTION leaves whatever the grantee redistributed in place: it must be removed explicitly.",
    topic: "Cascading revoke",
  },
  "ocp1-q30": {
    question: "A table is created with SEGMENT CREATION DEFERRED. What happens?",
    options: ["No segment is allocated until a row is inserted", "A minimal extent is reserved immediately", "The table is created offline", "Creation fails if the tablespace is full"],
    explanation: "Deferred segment creation avoids consuming an extent for a table that may stay empty — valuable on application schemas with thousands of tables. The segment is born on the first insert.",
    topic: "Deferred segment creation",
  },
  "ocp1-q31": {
    question: "Which statements are true about the UNDO tablespace? (Choose three.)",
    options: ["It allows an uncommitted transaction to be rolled back", "It provides read consistency for long-running queries", "It feeds the undo-based Flashback technologies", "It holds the redo entries used after an instance failure", "It can be taken offline while the database is open"],
    explanation: "Undo stores the before-image of changed data: it serves ROLLBACK, read consistency and the Flashback features. Redo entries live in the redo logs. The active undo tablespace cannot be taken offline.",
    topic: "UNDO tablespace",
  },
  "ocp1-q32": {
    question: "A long-running query fails with ORA-01555. Which fixes are relevant? (Choose three.)",
    options: ["Raise the UNDO_RETENTION value", "Enlarge the undo tablespace", "Enable RETENTION GUARANTEE on the undo tablespace", "Increase the buffer cache size", "Switch the database to NOARCHIVELOG"],
    explanation: "ORA-01555 means undo was overwritten before a query finished. You lengthen retention, enlarge the tablespace, or guarantee retention — the last option failing new transactions rather than overwriting undo. Neither buffer cache nor archiving mode is involved.",
    topic: "ORA-01555",
  },
  "ocp1-q33": {
    question: "What must be enabled before running ALTER TABLE … SHRINK SPACE?",
    options: ["ARCHIVELOG mode", "Row movement on the table", "Advanced compression", "Block change tracking"],
    explanation: "Shrinking physically moves rows, so ALTER TABLE … ENABLE ROW MOVEMENT is mandatory. SHRINK SPACE COMPACT compacts without lowering the HWM; adding CASCADE propagates the operation to dependent indexes.",
    topic: "SHRINK SPACE",
  },
  "ocp1-q34": {
    question: "What is resumable space allocation for? (Choose two.)",
    options: ["To suspend an out-of-space operation instead of failing it", "To give the administrator time to enlarge the tablespace, the operation then resuming", "To automatically compress saturated segments", "To move segments to another tablespace"],
    explanation: "ALTER SESSION ENABLE RESUMABLE turns an out-of-space error into a suspension: the session waits, the administrator extends, the operation resumes where it stopped. DBA_RESUMABLE lists waiting sessions. It is the answer to overnight loads that fail at 90%.",
    topic: "Resumable allocation",
  },
  "ocp1-q35": {
    question: "Which tablespace can never be taken offline?",
    options: ["SYSAUX", "TEMP", "SYSTEM", "USERS"],
    explanation: "SYSTEM hosts the data dictionary: the database cannot run without it. SYSAUX can be taken offline at the cost of losing some features (AWR among them), and temporary or application tablespaces handle it without difficulty.",
    topic: "System tablespaces",
  },
  "ocp1-q36": {
    question: "What difference separates COMPRESS BASIC from ROW STORE COMPRESS ADVANCED?",
    options: ["BASIC only compresses direct-path loads, ADVANCED maintains compression through ordinary DML", "ADVANCED only works on indexes", "BASIC requires ARCHIVELOG mode", "The two are strictly equivalent"],
    explanation: "Basic compression only applies to direct-path inserts: rows added later by an ordinary INSERT stay uncompressed. Advanced compression keeps the gain through DML, at the cost of an extra option.",
    topic: "Compression",
  },
  "ocp1-q37": {
    question: "Which statements are true about the logical storage hierarchy? (Choose two.)",
    options: ["A segment is made of one or more extents", "An extent is a set of contiguous Oracle blocks", "A tablespace is contained within a segment", "An Oracle block maps to one data file"],
    explanation: "The hierarchy runs from database to tablespace, tablespace to segment, segment to extent, and extent to block. An extent groups contiguous blocks within a single data file; it is the allocation unit.",
    topic: "Storage hierarchy",
  },
  "ocp1-q38": {
    question: "A connection fails with ORA-12154: “TNS: could not resolve the connect identifier”. What is the most likely cause?",
    options: ["The instance is down", "The listener is not started", "The connect identifier is not resolved by the configured naming method", "The password is wrong"],
    explanation: "ORA-12154 happens before any network attempt: the client could not translate the alias into an address. Check tnsnames.ora, the TNS_ADMIN variable or the naming method. A stopped listener would give ORA-12541, a stopped instance ORA-01034.",
    topic: "Name resolution",
  },
  "ocp1-q39": {
    question: "In which cases is a static registration in listener.ora still required? (Choose two.)",
    options: ["To run a remote STARTUP against a stopped instance", "To connect the auxiliary instance of an RMAN duplicate, started in NOMOUNT", "For any ordinary application connection", "To enable dynamic registration by PMON"],
    explanation: "Dynamic registration assumes an already-running instance: it cannot advertise itself while down. Hence the need for a static entry in exactly the two cases where you connect to an instance that is not yet running.",
    topic: "Listener",
  },
  "ocp1-q40": {
    question: "Which resolution method requires no configuration file on the client?",
    options: ["Local naming", "Easy Connect", "Directory naming", "External naming"],
    explanation: "Easy Connect only needs the host:port/service string passed at connect time. Local naming requires tnsnames.ora, directory naming an LDAP server, and external naming a third-party service.",
    topic: "Naming methods",
  },
  "ocp1-q41": {
    question: "Which statements are true about shared server mode? (Choose two.)",
    options: ["The User Global Area moves from the PGA into the SGA", "Sessions go through dispatchers rather than a dedicated server process", "RMAN can connect to it without restriction", "It removes the need for a listener"],
    explanation: "Shared server pools processes behind dispatchers, which moves the UGA into the SGA's Large Pool. RMAN and administration tasks, however, require a dedicated server connection, and the listener stays essential.",
    topic: "Shared server",
  },
  "ocp1-q42": {
    question: "Which statements are true about the ORACLE_DATAPUMP access driver for external tables? (Choose three.)",
    options: ["It can unload data to a file", "It can reload that data into another database", "The files it produces are reusable on another instance", "It allows UPDATE on the external table", "It automatically creates indexes on the external table"],
    explanation: "ORACLE_DATAPUMP writes a Data Pump-format file from a CREATE TABLE … ORGANIZATION EXTERNAL … AS SELECT, which another database can then read. The external table stays read-only and accepts no index — reading flat files is the ORACLE_LOADER driver's job.",
    topic: "External tables",
  },
  "ocp1-q43": {
    question: "What are the two prerequisites for reading a flat file through an external table? (Choose two.)",
    options: ["A DIRECTORY object pointing at a server directory", "The READ privilege on that DIRECTORY object", "The DBA role", "ARCHIVELOG mode"],
    explanation: "The DIRECTORY and the READ privilege are enough — plus WRITE if you want log and bad files. Neither the DBA role nor archiving mode is involved. The directory names a server path, never a client one.",
    topic: "DIRECTORY objects",
  },
  "ocp1-q44": {
    question: "Which Data Pump option transfers straight from one database to another, with no intermediate file?",
    options: ["DUMPFILE", "NETWORK_LINK", "REMAP_SCHEMA", "ESTIMATE_ONLY"],
    explanation: "NETWORK_LINK relies on a database link: impdp reads the remote source and writes directly into the target. REMAP_SCHEMA changes the destination schema, ESTIMATE_ONLY sizes the job without exporting.",
    topic: "Data Pump",
  },
  "ocp1-q45": {
    question: "Where does Data Pump write its export files?",
    options: ["In the client's current directory", "In the server directory named by the DIRECTORY object", "In $ORACLE_HOME/dbs", "In the fast recovery area"],
    explanation: "Data Pump runs server-side: the server process writes, into the directory named by the DIRECTORY. That is the major difference from the legacy exp utility, which wrote on the client.",
    topic: "Data Pump server-side",
  },
  "ocp1-q46": {
    question: "How do you reattach to an interrupted Data Pump job to carry it on?",
    options: ["By running expdp again identically", "With the ATTACH parameter followed by the job name", "With the RESUME parameter", "It is not possible: you must start over"],
    explanation: "Data Pump jobs are restartable by design. ATTACH=job_name opens the interactive console, where CONTINUE_CLIENT resumes, STATUS queries, PARALLEL adjusts parallelism and KILL_JOB abandons.",
    topic: "Data Pump jobs",
  },

  // ─── quiz-data-ocp1-b ───────────────────────────────────────────────────
  "ocp1-q50": {
    question: "In the NOMOUNT state, which file has Oracle read?",
    options: ["The control file", "The parameter file (SPFILE or PFILE)", "The data files", "The redo log files"],
    explanation: "NOMOUNT only reads the parameter file to allocate the SGA and start the processes. The control file is read at MOUNT, the data files and redo logs at OPEN.",
    topic: "NOMOUNT state",
  },
  "ocp1-q51": {
    question: "An ALTER SYSTEM is run with no SCOPE clause, the instance having started from a PFILE. What happens?",
    options: ["The change applies to the running instance only and is lost at restart", "It is written to the PFILE", "The statement fails", "It applies only from the next startup"],
    explanation: "Without an SPFILE the only accepted scope is MEMORY: the change lives as long as the instance. With an SPFILE, omitting SCOPE is equivalent to BOTH, so memory and file.",
    topic: "ALTER SYSTEM without SCOPE",
  },
  "ocp1-q52": {
    question: "Which processes write trace files into the ADR? (Choose two.)",
    options: ["Background processes", "Server processes", "The SQL*Plus client process", "The listener only"],
    explanation: "Both families produce traces: background processes in their dedicated directory, server processes in the user trace directory. The ADR also covers the listener, but in a separate tree.",
    topic: "Trace files",
  },
  "ocp1-q53": {
    question: "Which views help analyse a session's waits? (Choose two.)",
    options: ["V$SESSION_WAIT", "V$SESSION", "V$PARAMETER", "V$CONTROLFILE"],
    explanation: "V$SESSION_WAIT exposes a session's current wait; since 10g V$SESSION also carries the wait columns. V$SESSION_EVENT accumulates waits since connect time.",
    topic: "Wait diagnostics",
  },
  "ocp1-q54": {
    question: "Why does generating undo itself produce redo?",
    options: ["Because undo lives in segments of a database that must stay recoverable", "Because undo is written into the redo logs", "Because redo replaces undo after a COMMIT", "It is false: undo generates no redo"],
    explanation: "Undo segments are data blocks like any other: every change must be logged so instance recovery can rebuild them. A transaction therefore generates redo both for the data and for its undo.",
    topic: "Undo and redo",
  },
  "ocp1-q55": {
    question: "Which statements are true about a BIGFILE tablespace? (Choose two.)",
    options: ["It contains a single data file", "That file can be set to auto-extend", "It accepts up to 1,022 files", "It forces dictionary-managed extents"],
    explanation: "A BIGFILE has one file, but a much larger one thanks to different addressing. AUTOEXTEND remains available. It is SMALLFILE that accepts up to 1,022 files — so a multi-file smallfile can exceed a bigfile.",
    topic: "BIGFILE and SMALLFILE",
  },
  "ocp1-q56": {
    question: "Which statements are true about the relationship between segments, extents and files? (Choose two.)",
    options: ["A segment can span several data files of the same tablespace", "A segment may occupy a single extent", "An extent can straddle two data files", "A segment necessarily belongs to a single extent"],
    explanation: "A segment grows by extents that may spread across every file of the tablespace. An extent, however, is always contiguous within one file. A freshly created segment has just one extent.",
    topic: "Segments and extents",
  },
  "ocp1-q57": {
    question: "Which statements are true about undo segments? (Choose three.)",
    options: ["They extend automatically if the tablespace allows it", "Several transactions can share the same undo segment", "An undo segment can wrap back to its first extent once the undo has expired", "Each transaction gets a dedicated undo tablespace", "They are stored in the temporary tablespace"],
    explanation: "Undo segments are circular: they extend while the tablespace allows, then reuse their first extents as soon as the undo they hold has passed the retention period. Several transactions can coexist in one.",
    topic: "Undo segments",
  },
  "ocp1-q58": {
    question: "A transaction fails with ORA-30036 “unable to extend segment in undo tablespace”. What is the cause?",
    options: ["The undo tablespace is full and cannot extend", "The user's quota is exhausted", "The temporary tablespace is full", "The redo logs are full"],
    explanation: "ORA-30036 signals an undo tablespace out of space. You enlarge it, enable AUTOEXTEND, or lower UNDO_RETENTION — not to be confused with ORA-01555, which is about undo overwritten too early.",
    topic: "ORA-30036",
  },
  "ocp1-q59": {
    question: "What effects does RETENTION GUARANTEE have on an undo tablespace? (Choose two.)",
    options: ["Unexpired undo is never overwritten", "“Snapshot too old” errors become rare", "New transactions can no longer fail", "Retention becomes unlimited"],
    explanation: "Guaranteed retention protects undo until UNDO_RETENTION expires, which all but eliminates ORA-01555. The price is the mirror image: a transaction can now fail for lack of space rather than overwrite still-useful undo.",
    topic: "RETENTION GUARANTEE",
  },
  "ocp1-q60": {
    question: "Which compression syntax maintains the gain through ordinary DML?",
    options: ["COMPRESS BASIC", "ROW STORE COMPRESS ADVANCED", "COMPRESS FOR QUERY LOW", "NOCOMPRESS"],
    explanation: "ROW STORE COMPRESS ADVANCED recompresses blocks as inserts and updates occur. BASIC only compresses the direct path, and the FOR QUERY modes belong to Hybrid Columnar Compression, restricted to certain storage.",
    topic: "Advanced compression",
  },
  "ocp1-q61": {
    question: "Which conditions allow a data file to be renamed? (Choose two.)",
    options: ["Take its tablespace offline, the database staying open", "Mount the database without opening it", "Have the database in NOARCHIVELOG", "Drop the tablespace first"],
    explanation: "Renaming assumes the file is not in use: either you take its tablespace offline with the database open, or you work at the MOUNT state. The file must be copied at OS level before running ALTER DATABASE RENAME FILE.",
    topic: "Renaming a data file",
  },
  "ocp1-q62": {
    question: "How do you create a tablespace without specifying a file path?",
    options: ["By setting DB_CREATE_FILE_DEST", "By omitting the DATAFILE clause, with no other setting", "By using BIGFILE", "It is not possible"],
    explanation: "The DB_CREATE_FILE_DEST parameter enables Oracle Managed Files: Oracle names and places the file itself, and removes it with the tablespace. Without that parameter, the DATAFILE clause is mandatory.",
    topic: "Oracle Managed Files",
  },
  "ocp1-q63": {
    question: "Which clause creates an account whose authentication is delegated to the operating system?",
    options: ["IDENTIFIED BY VALUES", "IDENTIFIED EXTERNALLY", "IDENTIFIED GLOBALLY", "IDENTIFIED BY OS"],
    explanation: "IDENTIFIED EXTERNALLY delegates to the OS: the account name is prefixed by OS_AUTHENT_PREFIX, often OPS$. IDENTIFIED GLOBALLY delegates to an enterprise directory.",
    topic: "External authentication",
  },
  "ocp1-q64": {
    question: "Which statements are true about a table's keys? (Choose three.)",
    options: ["A table admits only one primary key", "A table can carry several foreign keys", "ON DELETE SET NULL and ON DELETE CASCADE are two possible behaviours", "A constraint can only be declared at column level", "A foreign key requires a primary key on the child table"],
    explanation: "One primary key, as many foreign keys as needed, and two referential actions to choose from when the parent row is deleted. Constraints are declared at column or table level — table level being mandatory for a composite key.",
    topic: "Referential constraints",
  },
  "ocp1-q65": {
    question: "Which statements are true about dropping columns? (Choose three.)",
    options: ["A primary key column can be dropped with CASCADE CONSTRAINTS", "A column marked UNUSED still counts towards the 1,000-column limit", "A partition key column cannot be dropped", "Every column of a table can be dropped", "SET UNUSED frees the space immediately"],
    explanation: "CASCADE CONSTRAINTS removes the dependencies that would block the drop. An UNUSED column keeps counting until DROP UNUSED COLUMNS runs — and has therefore freed nothing. A table must keep at least one column, and partition keys are untouchable.",
    topic: "Dropping columns",
  },
  "ocp1-q66": {
    question: "Which statements are true about the data dictionary views? (Choose three.)",
    options: ["The USER_, ALL_ and DBA_ families rest on the same base tables", "The dictionary belongs to the SYS schema", "Users reach it through views, never through the base tables", "The dictionary can be changed by direct DML", "It lives in the SYSAUX tablespace"],
    explanation: "The three families are only views with different scopes over the same internal tables, owned by SYS and housed in SYSTEM. Changing those tables directly corrupts the database: the dictionary is written by DDL only.",
    topic: "Data dictionary",
  },
  "ocp1-q67": {
    question: "Which statements are true about using a sequence as a column default? (Choose two.)",
    options: ["The inserting user needs the SELECT privilege on the sequence", "A sequence can feed a DEFAULT clause as of 12c", "The sequence guarantees no gaps", "A sequence can only serve one table"],
    explanation: "Since 12c a column can carry DEFAULT my_sequence.NEXTVAL; inserting then requires SELECT on the sequence. Gaps remain normal, and nothing stops several tables from sharing a sequence.",
    topic: "Sequences and DEFAULT",
  },
  "ocp1-q68": {
    question: "Which operations are impossible through a view containing GROUP BY? (Choose two.)",
    options: ["INSERT", "DELETE", "SELECT", "Creating a synonym on the view"],
    explanation: "A view becomes non-updatable as soon as it aggregates: GROUP BY, DISTINCT, a group function, ROWNUM or a set operator forbid INSERT, UPDATE and DELETE. Reading and synonyms stay available; an INSTEAD OF trigger lifts the restriction.",
    topic: "Non-updatable views",
  },
  "ocp1-q69": {
    question: "Which statements are true about operator precedence in a WHERE clause? (Choose two.)",
    options: ["At equal precedence, evaluation runs left to right", "Parentheses change the evaluation order", "OR is evaluated before AND", "NOT is evaluated last"],
    explanation: "The order is NOT, then AND, then OR; at equal precedence evaluation runs left to right. Parentheses override everything — hence the value of always using them as soon as an OR sits next to an AND.",
    topic: "Operator precedence",
  },
  "ocp1-q70": {
    question: "Which statements are true about DISTINCT? (Choose two.)",
    options: ["DISTINCT can apply to a concatenation expression", "DISTINCT applies to the whole set of projected columns", "DISTINCT applies column by column", "DISTINCT is forbidden with an alias"],
    explanation: "DISTINCT deduplicates the whole result row, including when it comes from a concatenation or a calculation. It never applies separately to each column — a frequent misreading.",
    topic: "DISTINCT",
  },
  "ocp1-q71": {
    question: "Which ORDER BY clauses are valid for SELECT cust_id, cust_name FROM customers? (Choose three.)",
    options: ["ORDER BY 2, 1", "ORDER BY 2, cust_id", "ORDER BY \"Customer name\" if that alias is declared", "ORDER BY cust_name FROM", "ORDER BY (1)"],
    explanation: "ORDER BY accepts positions, column names and aliases — including double-quoted ones when they contain spaces. Position and name can be mixed in the same clause.",
    topic: "ORDER BY",
  },
  "ocp1-q72": {
    question: "Which statements are true about column aliases? (Choose two.)",
    options: ["An alias containing a space must be double-quoted", "A simple alias is written without quotes", "An alias must always be preceded by AS", "An alias can be used in the WHERE clause"],
    explanation: "Double quotes are only needed to preserve case or allow a space. AS stays optional. An alias is never visible in WHERE, which is evaluated before SELECT — but it is visible in ORDER BY.",
    topic: "Column aliases",
  },
  "ocp1-q73": {
    question: "Which statements are true about the DUAL table? (Choose two.)",
    options: ["It contains exactly one row", "It contains a single column, of VARCHAR2 type", "It contains one row per session", "It is of NUMBER type"],
    explanation: "DUAL is a system table with one row and one DUMMY column of type VARCHAR2(1) holding 'X'. It serves to evaluate an expression, a pseudocolumn or a function without querying a real table.",
    topic: "The DUAL table",
  },
  "ocp1-q74": {
    question: "What does the condition WHERE name LIKE 'D_%' select?",
    options: ["Names starting with D and at least two characters long", "Names starting with D only", "Names containing a D", "Names of exactly two characters"],
    explanation: "_ requires exactly one character, % accepts zero or more. 'D_%' therefore requires a D, then at least one character, then anything: the name is at least two characters long.",
    topic: "LIKE wildcards",
  },
  "ocp1-q75": {
    question: "Which expressions correctly replace a null credit limit with the text “Not available”? (Choose two.)",
    options: ["NVL(TO_CHAR(cust_credit_limit), 'Not available')", "NVL2(cust_credit_limit, TO_CHAR(cust_credit_limit), 'Not available')", "NVL(cust_credit_limit, 'Not available')", "COALESCE(cust_credit_limit, 'Not available')"],
    explanation: "NVL and COALESCE require type-compatible arguments: mixing a NUMBER with a string fails. Convert first — hence the TO_CHAR — or use NVL2, whose second and third arguments are both strings here.",
    topic: "NVL, NVL2 and types",
  },
  "ocp1-q76": {
    question: "Which statements are true about CEIL and TRUNC? (Choose two.)",
    options: ["CEIL works on positive and negative numbers alike", "TRUNC applies to numbers as well as dates", "CEIL only accepts integers", "TRUNC rounds up to the next integer"],
    explanation: "CEIL returns the smallest integer greater than or equal, including for a negative: CEIL(-4.2) gives -4. TRUNC truncates without rounding, and takes a second argument for numbers as for dates.",
    topic: "CEIL and TRUNC",
  },
  "ocp1-q77": {
    question: "Which statements are true about MIN and MAX? (Choose two.)",
    options: ["They apply to character strings", "They apply to dates", "They only accept numeric values", "They count NULL values"],
    explanation: "MIN and MAX order any comparable type: numbers, strings and dates. It is AVG and SUM that require numerics. Like every group function except COUNT(*), they ignore NULLs.",
    topic: "MIN and MAX",
  },
  "ocp1-q78": {
    question: "Which statements are true about a self-join? (Choose three.)",
    options: ["Two distinct aliases are mandatory", "The ON clause can carry the condition", "It can be written as an outer join", "It requires an intermediate view", "It is impossible in ANSI syntax"],
    explanation: "Referencing the same table twice requires aliases to tell the roles apart. ANSI syntax handles it perfectly with ON, and an outer join lets you keep rows with no match — employees without a manager, typically.",
    topic: "Self-join",
  },
  "ocp1-q79": {
    question: "Which statements correctly compare the legacy Oracle join syntax with the ANSI syntax? (Choose three.)",
    options: ["Omitting the condition in Oracle syntax produces a Cartesian product", "ANSI syntax offers NATURAL JOIN", "ANSI syntax offers CROSS JOIN", "ANSI syntax is systematically faster", "Oracle syntax forbids outer joins"],
    explanation: "Both syntaxes produce the same execution plan: neither is faster. ANSI adds NATURAL JOIN, CROSS JOIN and FULL OUTER JOIN, and makes the join condition explicit — hence fewer accidental Cartesian products.",
    topic: "Join syntaxes",
  },
  "ocp1-q80": {
    question: "What conditions does a set operator impose on the queries it links? (Choose two.)",
    options: ["The same number of columns", "Implicitly convertible data types", "The same column names", "The same number of rows"],
    explanation: "UNION, INTERSECT and MINUS require an identical column count and compatible types position by position. Names may differ: those of the first SELECT title the result.",
    topic: "Set operators",
  },
  "ocp1-q81": {
    question: "How does INTERSECT treat NULL values?",
    options: ["It treats two NULLs in the same position as equal", "It excludes any row containing a NULL", "It raises an error", "It replaces NULL with zero"],
    explanation: "Like UNION, INTERSECT compares whole rows and treats two NULLs in the same position as equivalent — the opposite of the = operator, where NULL = NULL is UNKNOWN.",
    topic: "INTERSECT and NULL",
  },
  "ocp1-q82": {
    question: "Which construct compares each employee's salary with the overall average?",
    options: ["WHERE salary > AVG(salary)", "WHERE salary > (SELECT AVG(salary) FROM employees)", "HAVING salary > AVG(salary)", "WHERE AVG(salary) < salary"],
    explanation: "A group function is forbidden in WHERE: it must be isolated in a scalar subquery. HAVING would not do either, since it filters groups rather than individual rows.",
    topic: "Subquery and average",
  },
  "ocp1-q83": {
    question: "Which statements are true about CURRENT_DATE and CURRENT_TIMESTAMP? (Choose two.)",
    options: ["CURRENT_DATE follows the session time zone", "CURRENT_TIMESTAMP returns the time together with the session time zone", "SYSDATE follows the session time zone", "CURRENT_DATE always returns UTC"],
    explanation: "SYSDATE and SYSTIMESTAMP give the server time; CURRENT_DATE and CURRENT_TIMESTAMP the session time, as set by SESSIONTIMEZONE. The distinction is classic as soon as an application spans several time zones.",
    topic: "Date functions and time zone",
  },
  "ocp1-q84": {
    question: "When does a new transaction start implicitly? (Choose three.)",
    options: ["At the first DML following a COMMIT or a ROLLBACK", "After a TRUNCATE, which commits implicitly", "At the first SELECT FOR UPDATE following a DDL statement", "At every plain SELECT", "When the session opens"],
    explanation: "A transaction is born at the first statement that changes or locks data after the previous one ended. A DDL or DCL statement implicitly closes the current transaction; a plain SELECT opens none.",
    topic: "Transaction start",
  },
  "ocp1-q85": {
    question: "Which statements are true about ROLLBACK TO SAVEPOINT? (Choose two.)",
    options: ["It undoes the changes made after the savepoint", "A later plain ROLLBACK undoes the whole transaction", "It commits the changes made before the savepoint", "It ends the transaction"],
    explanation: "SAVEPOINT splits a transaction into revocable steps: rolling back to a point undoes what follows, without committing anything or closing the transaction. It stays open, and a full ROLLBACK remains possible afterwards.",
    topic: "SAVEPOINT",
  },
  "ocp1-q86": {
    question: "A service shows as UNKNOWN in lsnrctl status output. What does that mean?",
    options: ["The service was declared statically in listener.ora", "The instance is down", "The listener is misconfigured", "The service has failed"],
    explanation: "UNKNOWN simply means the listener received no dynamic registration for that service: it knows it from its configuration and therefore ignores the instance's real state. A dynamically registered service would show READY.",
    topic: "Listener UNKNOWN state",
  },
  "ocp1-q87": {
    question: "Which process dynamically registers services with the listener in recent releases?",
    options: ["PMON", "LREG", "SMON", "CKPT"],
    explanation: "Since 12c, LREG (Listener Registration) has taken over this task, historically handled by PMON. ALTER SYSTEM REGISTER forces an immediate registration rather than waiting for the automatic cycle.",
    topic: "Service registration",
  },
  "ocp1-q88": {
    question: "Which Oracle Net features improve availability or load distribution? (Choose three.)",
    options: ["Connect Time Failover, which tries several addresses in turn", "Load Balancing, which spreads connections across dispatchers", "Source Routing, which routes the connection through intermediate hops", "Block Change Tracking", "Flashback Query"],
    explanation: "These three options are declared in the connect descriptor. The last two belong to backup and recovery, with nothing to do with Oracle Net.",
    topic: "Oracle Net options",
  },
  "ocp1-q89": {
    question: "Which statements are true about Data Pump? (Choose two.)",
    options: ["Jobs can run in parallel", "An interrupted job is restartable", "Files are written on the client", "Parallelism is fixed for good at launch"],
    explanation: "PARALLEL spreads the work across several processes and can be adjusted mid-run after an ATTACH. Jobs survive an interruption: the master table keeps the progress. Writing is always server-side.",
    topic: "Data Pump",
  },
  "ocp1-q90": {
    question: "Which statements are true about the SQL*Loader conventional path? (Choose two.)",
    options: ["It generates redo", "It enforces referential constraints during the load", "It bypasses the buffer cache", "It disables triggers"],
    explanation: "The conventional path builds ordinary INSERTs: it goes through the buffer cache, generates redo and undo, and honours constraints and triggers. The direct path, faster, writes above the HWM and defers some constraint checking.",
    topic: "SQL*Loader conventional path",
  },
  "ocp1-q91": {
    question: "Which statements are true about the log file produced by SQL*Loader? (Choose two.)",
    options: ["It reproduces the content of the control file used", "It reports how many rows were loaded and rejected", "It contains the rejected data itself", "It replaces the bad file"],
    explanation: "The log file summarises the configuration — control file included — and the load outcome. Rejected rows go to the BAD file; those excluded by a WHEN clause to the DISCARD file.",
    topic: "SQL*Loader log",
  },
};
