import type { QuizQuestion } from "./types";

export const quizQuestions: QuizQuestion[] = [
  // Module 1 - Fundamentals
  {
    id: "q1",
    moduleId: "m1",
    question: "Quelle commande SQL est auto-validante (COMMIT implicite) ?",
    options: ["DELETE", "INSERT", "TRUNCATE", "SELECT"],
    correctIndex: 2,
    explanation: "TRUNCATE est une commande DDL qui déclenche un COMMIT implicite avant et après son exécution. DELETE et INSERT sont des commandes DML transactionnelles (annulables). SELECT ne modifie pas les données.",
    topic: "DDL vs DML",
    difficulty: "easy",
  },
  {
    id: "q2",
    moduleId: "m1",
    question: "Quelle est la différence entre TRUNCATE et DELETE ?",
    options: [
      "TRUNCATE est plus lent que DELETE",
      "TRUNCATE est DDL (non annulable), DELETE est DML (annulable)",
      "TRUNCATE déclenche les triggers, DELETE non",
      "TRUNCATE supporte WHERE, DELETE non",
    ],
    correctIndex: 1,
    explanation: "TRUNCATE est DDL : ultra-rapide, non annulable (auto-commit), réinitialise le storage, ne déclenche pas les triggers. DELETE est DML : transactionnel, annulable, déclenche les triggers, supporte WHERE.",
    topic: "DDL vs DML",
    difficulty: "easy",
  },
  {
    id: "q3",
    moduleId: "m1",
    question: "Quelle contrainte ne peut être définie qu'au niveau colonne ?",
    options: ["PRIMARY KEY", "FOREIGN KEY", "CHECK", "NOT NULL"],
    correctIndex: 3,
    explanation: "NOT NULL est la seule contrainte qui ne peut se définir qu'au niveau colonne. Toutes les autres (PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK) peuvent se définir au niveau table ou colonne.",
    topic: "Contraintes",
    difficulty: "medium",
  },
  // Module 2 - SELECT
  {
    id: "q4",
    moduleId: "m2",
    question: "Que retourne la requête : SELECT * FROM employees WHERE commission = NULL ?",
    options: [
      "Tous les employés sans commission",
      "Tous les employés avec commission NULL",
      "Aucune ligne",
      "Une erreur",
    ],
    correctIndex: 2,
    explanation: "NULL ne peut pas être comparé avec =. La condition commission = NULL retourne toujours UNKNOWN, donc aucune ligne n'est retournée. Il faut utiliser IS NULL.",
    topic: "NULL handling",
    difficulty: "easy",
  },
  {
    id: "q5",
    moduleId: "m2",
    question: "Quel est l'ordre d'exécution logique des clauses SQL ?",
    options: [
      "SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY",
      "FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY",
      "FROM → SELECT → WHERE → GROUP BY → HAVING → ORDER BY",
      "SELECT → WHERE → FROM → GROUP BY → HAVING → ORDER BY",
    ],
    correctIndex: 1,
    explanation: "L'ordre d'exécution logique est : FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY. L'ordre d'écriture est différent (SELECT en premier), mais l'exécution commence par FROM.",
    topic: "Clause order",
    difficulty: "medium",
  },
  {
    id: "q6",
    moduleId: "m2",
    question: "Peut-on utiliser un alias de colonne défini dans SELECT dans la clause WHERE ?",
    options: [
      "Oui, toujours",
      "Non, jamais",
      "Oui, mais seulement avec AS",
      "Oui, seulement si l'alias est entre guillemets",
    ],
    correctIndex: 1,
    explanation: "Non. WHERE s'exécute avant SELECT dans l'ordre logique. L'alias n'existe pas encore au moment de l'évaluation de WHERE. ORDER BY, en revanche, peut utiliser les alias car il s'exécute en dernier.",
    topic: "Aliases",
    difficulty: "medium",
  },
  {
    id: "q7",
    moduleId: "m2",
    question: "Que fait SELECT DISTINCT department_id FROM employees ?",
    options: [
      "Retourne tous les department_id y compris les doublons",
      "Retourne les department_id uniques uniquement",
      "Retourne une erreur si il y a des NULL",
      "Retourne le nombre de department_id distincts",
    ],
    correctIndex: 1,
    explanation: "DISTINCT élimine les doublons sur toutes les colonnes listées. Il retourne chaque valeur de department_id une seule fois. Les NULL sont inclus comme une valeur distincte.",
    topic: "DISTINCT",
    difficulty: "easy",
  },
  // Module 3 - ORDER BY
  {
    id: "q8",
    moduleId: "m3",
    question: "Dans Oracle, où apparaissent les NULL avec ORDER BY ASC par défaut ?",
    options: ["En premier", "En dernier", "Au milieu", "Cela dépend du type de colonne"],
    correctIndex: 1,
    explanation: "Dans Oracle, ORDER BY ASC place les NULL en dernier par défaut. C'est une spécificité Oracle. On peut forcer avec NULLS FIRST ou NULLS LAST.",
    topic: "ORDER BY NULL",
    difficulty: "medium",
  },
  {
    id: "q9",
    moduleId: "m3",
    question: "Que se passe-t-il si on utilise ROWNUM <= 5 avec ORDER BY ?",
    options: [
      "Retourne les 5 premières lignes triées correctement",
      "Retourne 5 lignes aléatoires puis les trie",
      "Retourne une erreur",
      "Retourne les 5 dernières lignes",
    ],
    correctIndex: 1,
    explanation: "ROWNUM est assigné AVANT le tri ORDER BY. La requête prend 5 lignes aléatoires, puis les trie. Pour un 'top N' correct, il faut une sous-requête ou FETCH FIRST.",
    topic: "ROWNUM",
    difficulty: "hard",
  },
  {
    id: "q10",
    moduleId: "m3",
    question: "Que fait FETCH FIRST 5 ROWS WITH TIES ?",
    options: [
      "Retourne exactement 5 lignes",
      "Retourne 5 lignes plus les ex aequo de la 5e ligne",
      "Retourne 5 lignes aléatoires",
      "Retourne une erreur",
    ],
    correctIndex: 1,
    explanation: "WITH TIES inclut toutes les lignes ayant la même valeur de tri que la 5e ligne. Si la 5e et 6e ligne ont la même valeur, les deux sont incluses. WITHOUT TIES (par défaut avec ONLY) retourne exactement 5.",
    topic: "FETCH FIRST",
    difficulty: "medium",
  },
  // Module 4 - Functions
  {
    id: "q11",
    moduleId: "m4",
    question: "Que retourne SUBSTR('Oracle', -3) ?",
    options: ["Ora", "cle", "acle", "Une erreur"],
    correctIndex: 1,
    explanation: "Les positions négatives dans SUBSTR comptent depuis la fin. -3 commence 3 caractères avant la fin, donc SUBSTR('Oracle', -3) retourne 'cle'.",
    topic: "SUBSTR",
    difficulty: "medium",
  },
  {
    id: "q12",
    moduleId: "m4",
    question: "Combien d'arguments la fonction CONCAT accepte-t-elle ?",
    options: ["1", "2", "3", "Illimité"],
    correctIndex: 1,
    explanation: "CONCAT accepte exactement 2 arguments. Pour concaténer plus de chaînes, utilisez l'opérateur || : 'a' || 'b' || 'c'.",
    topic: "CONCAT",
    difficulty: "easy",
  },
  {
    id: "q13",
    moduleId: "m4",
    question: "Que retourne INSTR('Hello World', 'o', 6) ?",
    options: ["5", "7", "0", "Une erreur"],
    correctIndex: 1,
    explanation: "INSTR cherche 'o' à partir de la position 6. La première occurrence à partir de la position 6 est à la position 7 (le 'o' de 'World').",
    topic: "INSTR",
    difficulty: "medium",
  },
  {
    id: "q14",
    moduleId: "m4",
    question: "Que retourne SYSDATE - hire_date ?",
    options: [
      "Le nombre de mois entre les dates",
      "Le nombre de jours entre les dates",
      "Le nombre d'années",
      "Une erreur de type",
    ],
    correctIndex: 1,
    explanation: "Soustraire deux dates dans Oracle retourne le nombre de jours entre elles (un nombre décimal). Pour les mois, utilisez MONTHS_BETWEEN.",
    topic: "Date arithmetic",
    difficulty: "easy",
  },
  {
    id: "q15",
    moduleId: "m4",
    question: "Comment ajouter 2 heures à une date ?",
    options: [
      "SYSDATE + 2",
      "SYSDATE + 2/24",
      "SYSDATE + 2/24/60",
      "ADD_HOURS(SYSDATE, 2)",
    ],
    correctIndex: 1,
    explanation: "L'arithmétique des dates fonctionne en jours. 1 jour = 1, donc 1 heure = 1/24. Pour 2 heures : SYSDATE + 2/24. Pour 30 minutes : SYSDATE + 30/(24*60).",
    topic: "Date arithmetic",
    difficulty: "medium",
  },
  {
    id: "q16",
    moduleId: "m4",
    question: "Quelle est la différence entre NVL et COALESCE ?",
    options: [
      "Aucune, ce sont des synonymes",
      "NVL accepte 2 arguments, COALESCE en accepte N",
      "NVL est standard SQL, COALESCE est Oracle",
      "COALESCE est plus rapide",
    ],
    correctIndex: 1,
    explanation: "NVL accepte exactement 2 arguments et évalue toujours les deux. COALESCE accepte N arguments, est standard SQL, et utilise short-circuit evaluation (n'évalue que ce qui est nécessaire).",
    topic: "NULL functions",
    difficulty: "medium",
  },
  {
    id: "q17",
    moduleId: "m4",
    question: "Que fait NULLIF(a, b) ?",
    options: [
      "Retourne NULL si a est NULL",
      "Retourne NULL si a = b, sinon a",
      "Retourne b si a est NULL",
      "Retourne a si a = b",
    ],
    correctIndex: 1,
    explanation: "NULLIF(a, b) retourne NULL si a = b, sinon retourne a. Utile pour éviter la division par zéro : NULLIF(count, 0).",
    topic: "NULL functions",
    difficulty: "medium",
  },
  // Module 5 - GROUP BY
  {
    id: "q18",
    moduleId: "m5",
    question: "Quelle est la différence entre COUNT(*) et COUNT(column) ?",
    options: [
      "Aucune différence",
      "COUNT(*) compte toutes les lignes, COUNT(column) ignore les NULL",
      "COUNT(*) est plus rapide",
      "COUNT(column) compte toutes les lignes",
    ],
    correctIndex: 1,
    explanation: "COUNT(*) compte toutes les lignes y compris celles avec NULL. COUNT(column) ignore les lignes où column IS NULL. C'est un piège classique de l'examen.",
    topic: "COUNT",
    difficulty: "easy",
  },
  {
    id: "q19",
    moduleId: "m5",
    question: "Que vaut AVG d'une colonne contenant [10, 20, NULL] ?",
    options: ["10", "15", "20", "NULL"],
    correctIndex: 1,
    explanation: "AVG ignore les NULL. Donc AVG(10, 20, NULL) = (10+20)/2 = 15, pas (10+20+0)/3 = 10. C'est un piège fréquent.",
    topic: "AVG NULL",
    difficulty: "medium",
  },
  {
    id: "q20",
    moduleId: "m5",
    question: "Quelle clause filtre les groupes APRÈS le regroupement ?",
    options: ["WHERE", "HAVING", "GROUP BY", "ORDER BY"],
    correctIndex: 1,
    explanation: "HAVING filtre les groupes après GROUP BY. WHERE filtre les lignes avant GROUP BY. HAVING peut utiliser les fonctions d'agrégation, WHERE ne le peut pas.",
    topic: "HAVING",
    difficulty: "easy",
  },
  {
    id: "q21",
    moduleId: "m5",
    question: "Que se passe-t-il si une colonne non-agrégée du SELECT n'est pas dans GROUP BY ?",
    options: [
      "Oracle retourne NULL pour cette colonne",
      "Oracle lève ORA-00979",
      "Oracle prend la première valeur",
      "Oracle l'agrège automatiquement",
    ],
    correctIndex: 1,
    explanation: "Oracle lève l'erreur ORA-00979 : not a GROUP BY expression. Toute colonne non-agrégée dans le SELECT doit apparaître dans le GROUP BY.",
    topic: "GROUP BY rules",
    difficulty: "medium",
  },
  // Module 6 - Joins
  {
    id: "q22",
    moduleId: "m6",
    question: "Que retourne un INNER JOIN ?",
    options: [
      "Toutes les lignes des deux tables",
      "Uniquement les lignes avec correspondance dans les deux tables",
      "Toutes les lignes de la table de gauche",
      "Toutes les lignes de la table de droite",
    ],
    correctIndex: 1,
    explanation: "INNER JOIN ne retourne que les lignes qui ont une correspondance dans les deux tables. Les lignes sans correspondance sont exclues des deux côtés.",
    topic: "INNER JOIN",
    difficulty: "easy",
  },
  {
    id: "q23",
    moduleId: "m6",
    question: "Dans l'ancienne syntaxe Oracle, où place-t-on le (+) pour un LEFT JOIN ?",
    options: [
      "Sur la table de gauche",
      "Sur la table de droite",
      "Sur les deux tables",
      "Sur la condition WHERE",
    ],
    correctIndex: 1,
    explanation: "Le (+) va sur la table qui peut manquer (qui recevra des NULL). Pour un LEFT JOIN (garder toutes les lignes de gauche), le (+) va sur la table de droite.",
    topic: "Oracle JOIN syntax",
    difficulty: "hard",
  },
  {
    id: "q24",
    moduleId: "m6",
    question: "L'ancienne syntaxe Oracle supporte-t-elle le FULL OUTER JOIN ?",
    options: [
      "Oui, avec (+) des deux côtés",
      "Non, le (+) ne peut pas être des deux côtés",
      "Oui, avec une syntaxe spéciale",
      "Oui, mais seulement avec des vues",
    ],
    correctIndex: 1,
    explanation: "Non. Le (+) ne peut pas être placé des deux côtés simultanément. Pour un FULL OUTER JOIN, il faut utiliser la syntaxe standard FULL OUTER JOIN ... ON.",
    topic: "Oracle JOIN syntax",
    difficulty: "medium",
  },
  {
    id: "q25",
    moduleId: "m6",
    question: "Pourquoi NATURAL JOIN est-il dangereux ?",
    options: [
      "Il est plus lent que INNER JOIN",
      "Il joint sur toutes les colonnes de même nom, ce qui peut changer silencieusement",
      "Il ne supporte pas les index",
      "Il nécessite des privilèges DBA",
    ],
    correctIndex: 1,
    explanation: "NATURAL JOIN joint automatiquement sur toutes les colonnes de même nom. L'ajout d'une colonne de même nom dans les deux tables modifie la jointure silencieusement, pouvant casser des requêtes.",
    topic: "NATURAL JOIN",
    difficulty: "medium",
  },
  {
    id: "q26",
    moduleId: "m6",
    question: "Qu'est-ce qu'un CROSS JOIN ?",
    options: [
      "Une jointure sur des colonnes croisées",
      "Un produit cartésien (N×M lignes)",
      "Une jointure optimisée",
      "Une jointure avec condition complexe",
    ],
    correctIndex: 1,
    explanation: "CROSS JOIN produit un produit cartésien : chaque ligne de la table A est combinée avec chaque ligne de la table B. Si A a 100 lignes et B en a 50, le résultat a 5000 lignes.",
    topic: "CROSS JOIN",
    difficulty: "easy",
  },
  // Module 7 - Subqueries
  {
    id: "q27",
    moduleId: "m7",
    question: "Que signifie > ALL (subquery) ?",
    options: [
      "Plus grand qu'au moins une valeur",
      "Plus grand que toutes les valeurs",
      "Plus grand que la moyenne",
      "Plus grand que la première valeur",
    ],
    correctIndex: 1,
    explanation: "> ALL signifie plus grand que TOUTES les valeurs de la sous-requête. C'est équivalent à > MAX(subquery). > ANY signifie plus grand qu'au moins une, équivalent à > MIN.",
    topic: "ALL/ANY",
    difficulty: "medium",
  },
  {
    id: "q28",
    moduleId: "m7",
    question: "Quelle erreur se produit si une single-row subquery retourne plusieurs lignes ?",
    options: ["ORA-00942", "ORA-01427", "ORA-01797", "ORA-00904"],
    correctIndex: 1,
    explanation: "ORA-01427 : single-row subquery returns more than one row. Solution : utiliser IN, ANY, ALL ou ajouter un filtre pour garantir une seule ligne.",
    topic: "Subquery errors",
    difficulty: "medium",
  },
  {
    id: "q29",
    moduleId: "m7",
    question: "Pourquoi NOT IN avec NULL est-il dangereux ?",
    options: [
      "Il est plus lent que NOT EXISTS",
      "Si la sous-requête retourne un NULL, NOT IN retourne 0 lignes",
      "Il ne supporte pas les index",
      "Il lève une erreur systématique",
    ],
    correctIndex: 1,
    explanation: "Si la sous-requête retourne ne serait-ce qu'un NULL, NOT IN retourne 0 lignes car NULL != valeur est UNKNOWN. NOT EXISTS n'a pas ce problème.",
    topic: "NOT IN NULL",
    difficulty: "hard",
  },
  {
    id: "q30",
    moduleId: "m7",
    question: "Quand préférer EXISTS à IN ?",
    options: [
      "Quand la sous-requête retourne peu de lignes",
      "Quand la sous-requête retourne beaucoup de lignes",
      "Quand il n'y a pas d'index",
      "Toujours",
    ],
    correctIndex: 1,
    explanation: "EXISTS est préférable quand la sous-requête retourne beaucoup de lignes, car il s'arrête à la première correspondance. IN est préférable quand la sous-requête retourne peu de lignes.",
    topic: "EXISTS vs IN",
    difficulty: "medium",
  },
  // Module 8 - Set Operators
  {
    id: "q31",
    moduleId: "m8",
    question: "Quelle est la différence entre UNION et UNION ALL ?",
    options: [
      "UNION est plus rapide",
      "UNION élimine les doublons et trie, UNION ALL conserve tout",
      "UNION ALL élimine les doublons",
      "Aucune différence",
    ],
    correctIndex: 1,
    explanation: "UNION élimine les doublons et trie (plus lent). UNION ALL conserve tous les doublons et ne trie pas (plus rapide). Préférez UNION ALL si pas de doublons.",
    topic: "UNION vs UNION ALL",
    difficulty: "easy",
  },
  {
    id: "q32",
    moduleId: "m8",
    question: "D'où viennent les noms de colonnes du résultat d'un UNION ?",
    options: [
      "De la deuxième requête",
      "De la première requête",
      "De l'union des deux",
      "Oracle génère des noms automatiques",
    ],
    correctIndex: 1,
    explanation: "Les noms de colonnes du résultat viennent de la PREMIÈRE requête. Les noms de la deuxième requête sont ignorés.",
    topic: "UNION columns",
    difficulty: "medium",
  },
  {
    id: "q33",
    moduleId: "m8",
    question: "Où peut-on placer ORDER BY avec des opérateurs ensemblistes ?",
    options: [
      "Dans chaque requête individuellement",
      "Uniquement à la fin, sur tout l'ensemble combiné",
      "Avant le premier SELECT",
      "N'importe où",
    ],
    correctIndex: 1,
    explanation: "ORDER BY ne peut apparaître qu'à la fin, sur tout l'ensemble combiné. Pas de ORDER BY dans les requêtes individuelles.",
    topic: "Set operators ORDER BY",
    difficulty: "medium",
  },
  {
    id: "q34",
    moduleId: "m8",
    question: "Que fait MINUS ?",
    options: [
      "Retourne les lignes communes aux deux requêtes",
      "Retourne les lignes du premier SELECT non dans le second",
      "Retourne la différence numérique",
      "Retourne toutes les lignes des deux requêtes",
    ],
    correctIndex: 1,
    explanation: "MINUS retourne les lignes présentes dans le premier SELECT mais pas dans le second. Les doublons sont éliminés et le résultat est trié.",
    topic: "MINUS",
    difficulty: "easy",
  },
  // Module 9 - DML
  {
    id: "q35",
    moduleId: "m9",
    question: "DELETE déclenche-t-il les triggers ?",
    options: [
      "Oui, DELETE est DML et déclenche les triggers",
      "Non, DELETE ne déclenche jamais les triggers",
      "Seulement les triggers AFTER",
      "Seulement si il y a un WHERE",
    ],
    correctIndex: 0,
    explanation: "Oui. DELETE est une commande DML et déclenche les triggers de type DELETE. TRUNCATE, en revanche, est DDL et ne déclenche PAS les triggers.",
    topic: "DELETE triggers",
    difficulty: "medium",
  },
  {
    id: "q36",
    moduleId: "m9",
    question: "Peut-on faire un ROLLBACK après un DELETE sans WHERE ?",
    options: [
      "Non, toutes les lignes sont définitivement supprimées",
      "Oui, DELETE est transactionnel et annulable",
      "Seulement si on n'a pas fait de COMMIT",
      "Seulement avec des privilèges DBA",
    ],
    correctIndex: 1,
    explanation: "Oui. DELETE est transactionnel (DML), même sans WHERE. ROLLBACK annule la suppression. TRUNCATE, en revanche, ne peut pas être annulé car c'est DDL avec auto-commit.",
    topic: "DELETE ROLLBACK",
    difficulty: "medium",
  },
  {
    id: "q37",
    moduleId: "m9",
    question: "Qu'est-ce que MERGE ?",
    options: [
      "Une jointure spéciale",
      "Un upsert : UPDATE si existe, INSERT sinon",
      "Une fusion de tables",
      "Un type de contrainte",
    ],
    correctIndex: 1,
    explanation: "MERGE est un upsert : si la ligne existe (condition ON satisfaite), UPDATE. Sinon, INSERT. Il combine les deux opérations en une seule passe, idéal pour la synchronisation.",
    topic: "MERGE",
    difficulty: "medium",
  },
  {
    id: "q38",
    moduleId: "m9",
    question: "Quelle erreur si on update une colonne du ON dans MERGE ?",
    options: ["ORA-00904", "ORA-38104", "ORA-01427", "ORA-00979"],
    correctIndex: 1,
    explanation: "ORA-38104 : columns referenced in the ON clause cannot be updated. Les colonnes utilisées dans la condition de jointure (ON) ne peuvent pas être modifiées dans le UPDATE.",
    topic: "MERGE errors",
    difficulty: "hard",
  },
  // Module 10 - DDL
  {
    id: "q39",
    moduleId: "m10",
    question: "Quelle est la différence entre VARCHAR2 et CHAR ?",
    options: [
      "VARCHAR2 est plus rapide",
      "VARCHAR2 stocke les caractères réels, CHAR complète avec des espaces",
      "CHAR supporte l'Unicode, VARCHAR2 non",
      "Aucune différence",
    ],
    correctIndex: 1,
    explanation: "VARCHAR2(n) stocke uniquement les caractères réels (variable). CHAR(n) complète avec des espaces jusqu'à n (fixe). Préférez toujours VARCHAR2 pour économiser l'espace.",
    topic: "Data types",
    difficulty: "easy",
  },
  {
    id: "q40",
    moduleId: "m10",
    question: "Que signifie NUMBER(8,2) ?",
    options: [
      "8 chiffres avant la virgule, 2 après",
      "8 chiffres au total, 2 décimales",
      "8 octets, 2 décimales",
      "8 caractères, 2 décimales",
    ],
    correctIndex: 1,
    explanation: "NUMBER(p, s) : p = précision (nombre total de chiffres), s = échelle (décimales). NUMBER(8,2) = 8 chiffres au total dont 2 décimales, donc 6 chiffres avant la virgule. Exemple : 123456.78",
    topic: "NUMBER type",
    difficulty: "medium",
  },
  {
    id: "q41",
    moduleId: "m10",
    question: "Quand doit-on appeler NEXTVAL avant CURRVAL ?",
    options: [
      "Toujours, avant chaque utilisation de CURRVAL",
      "Au moins une fois dans la session avant CURRVAL",
      "Jamais, CURRVAL fonctionne indépendamment",
      "Seulement si la séquence est nouvelle",
    ],
    correctIndex: 1,
    explanation: "NEXTVAL doit être appelé au moins une fois dans la session avant CURRVAL. Sinon, Oracle lève ORA-08002 : sequence CURRVAL is not yet defined in this session.",
    topic: "Sequences",
    difficulty: "medium",
  },
  {
    id: "q42",
    moduleId: "m10",
    question: "Que fait WITH CHECK OPTION sur une vue ?",
    options: [
      "Vérifie les contraintes de la table sous-jacente",
      "Empêche les INSERT/UPDATE qui produiraient des lignes hors scope de la vue",
      "Active le cache de la vue",
      "Vérifie les permissions de l'utilisateur",
    ],
    correctIndex: 1,
    explanation: "WITH CHECK OPTION empêche les INSERT ou UPDATE qui produiraient des lignes hors du scope de la vue (qui ne seraient pas visibles via la vue après la modification).",
    topic: "Views",
    difficulty: "medium",
  },
  // Module 11 - Analytic Functions
  {
    id: "q43",
    moduleId: "m11",
    question: "Quelle est la différence entre RANK et DENSE_RANK ?",
    options: [
      "RANK est plus rapide",
      "RANK saute les rangs après un ex aequo, DENSE_RANK ne saute pas",
      "DENSE_RANK saute les rangs, RANK non",
      "Aucune différence",
    ],
    correctIndex: 1,
    explanation: "RANK saute les rangs après un ex aequo (1, 1, 3). DENSE_RANK ne saute pas (1, 1, 2). ROW_NUMBER donne toujours des numéros uniques (1, 2, 3).",
    topic: "RANK vs DENSE_RANK",
    difficulty: "medium",
  },
  {
    id: "q44",
    moduleId: "m11",
    question: "Que font LAG et LEAD ?",
    options: [
      "Ils trient les résultats",
      "LAG accède à la ligne précédente, LEAD à la suivante",
      "Ils calculent des moyennes mobiles",
      "Ils créent des numéros de ligne",
    ],
    correctIndex: 1,
    explanation: "LAG accède à la valeur de la ligne précédente, LEAD à la valeur de la ligne suivante, sans self-join. Utile pour comparer des valeurs consécutives.",
    topic: "LAG/LEAD",
    difficulty: "medium",
  },
  {
    id: "q45",
    moduleId: "m11",
    question: "Quand s'exécutent les fonctions analytiques ?",
    options: [
      "Avant WHERE",
      "Après WHERE, GROUP BY et HAVING, avant ORDER BY",
      "Après ORDER BY",
      "Avant FROM",
    ],
    correctIndex: 1,
    explanation: "Les fonctions analytiques s'exécutent après WHERE, GROUP BY et HAVING, mais avant ORDER BY. Pour filtrer sur leur résultat, il faut une sous-requête (CTE).",
    topic: "Analytic execution order",
    difficulty: "hard",
  },
  // Module 12 - Regex
  {
    id: "q46",
    moduleId: "m12",
    question: "Quelle fonction regex utilise-t-on dans WHERE ?",
    options: ["REGEXP_SUBSTR", "REGEXP_LIKE", "REGEXP_REPLACE", "REGEXP_INSTR"],
    correctIndex: 1,
    explanation: "REGEXP_LIKE est la seule qui retourne un booléen, ce qui permet de l'utiliser dans WHERE. Les autres retournent des valeurs (chaîne, nombre, etc.).",
    topic: "REGEXP_LIKE",
    difficulty: "easy",
  },
  {
    id: "q47",
    moduleId: "m12",
    question: "Que fait le 6e paramètre de REGEXP_SUBSTR ?",
    options: [
      "La position de départ",
      "Le numéro d'occurrence",
      "subexpr : retourne un groupe capturant spécifique",
      "Le mode de correspondance",
    ],
    correctIndex: 2,
    explanation: "Le 6e paramètre est subexpr : il retourne un groupe capturant spécifique. Par exemple, REGEXP_SUBSTR(email, '@(.+)', 1, 1, 'i', 1) retourne le domaine sans le @.",
    topic: "REGEXP_SUBSTR",
    difficulty: "hard",
  },
  // Module 13 - Data Dictionary
  {
    id: "q48",
    moduleId: "m13",
    question: "Quelle est la différence entre USER_, ALL_ et DBA_ ?",
    options: [
      "USER_ est plus rapide, ALL_ plus complet, DBA_ pour les DBA",
      "USER_ = mes objets, ALL_ = accessibles, DBA_ = tous (privilégié)",
      "Aucune différence, ce sont des synonymes",
      "USER_ = tables, ALL_ = vues, DBA_ = index",
    ],
    correctIndex: 1,
    explanation: "USER_ = objets possédés par l'utilisateur. ALL_ = objets accessibles (propres + avec droits). DBA_ = tous les objets de la base (requiert des privilèges DBA).",
    topic: "Data dictionary",
    difficulty: "medium",
  },
  {
    id: "q49",
    moduleId: "m13",
    question: "Dans quelle casse sont les noms d'objets dans le dictionnaire ?",
    options: ["Minuscules", "Majuscules", "Telles que définies", "CamelCase"],
    correctIndex: 1,
    explanation: "Les noms d'objets sont en MAJUSCULES dans le dictionnaire. Oracle convertit les identificateurs non quotés en majuscules. Toujours utiliser WHERE table_name = 'EMPLOYEES'.",
    topic: "Data dictionary",
    difficulty: "medium",
  },
  // Module 14 - Exam
  {
    id: "q50",
    moduleId: "m14",
    question: "Combien de questions et quel score minimum pour l'examen 1Z0-071 ?",
    options: [
      "50 questions, 70%",
      "63 questions, 63%",
      "70 questions, 60%",
      "63 questions, 70%",
    ],
    correctIndex: 1,
    explanation: "L'examen 1Z0-071 contient 63 questions à choix multiples en 100 minutes. Le score minimum pour réussir est de 63%.",
    topic: "Exam format",
    difficulty: "easy",
  },
  {
    id: "q51",
    moduleId: "m14",
    question: "Y a-t-il une pénalité pour les mauvaises réponses à l'examen ?",
    options: [
      "Oui, -1 point par mauvaise réponse",
      "Non, pas de pénalité",
      "Oui, mais seulement pour les questions non répondues",
      "Ça dépend du type de question",
    ],
    correctIndex: 1,
    explanation: "Non, il n'y a pas de pénalité pour les mauvaises réponses. Il faut répondre à toutes les questions, même en devinant, car il n'y a rien à perdre.",
    topic: "Exam strategy",
    difficulty: "easy",
  },
  // Additional questions
  {
    id: "q52",
    moduleId: "m2",
    question: "Que fait l'opérateur || en Oracle ?",
    options: [
      "Division entière",
      "Concaténation de chaînes",
      "OU logique",
      "Comparaison",
    ],
    correctIndex: 1,
    explanation: "L'opérateur || est l'opérateur de concaténation de chaînes en Oracle. 'Hello' || ' ' || 'World' = 'Hello World'. CONCAT() ne prend que 2 arguments, || en prend illimité.",
    topic: "Operators",
    difficulty: "easy",
  },
  {
    id: "q53",
    moduleId: "m4",
    question: "Que retourne TO_CHAR(SYSDATE, 'DD/MM/YYYY') ?",
    options: [
      "03-07-2026",
      "03/07/2026",
      "2026/07/03",
      "03-JUL-26",
    ],
    correctIndex: 1,
    explanation: "TO_CHAR avec le masque 'DD/MM/YYYY' formate la date avec des slashes. Le résultat serait '03/07/2026'. Sans masque, Oracle utilise le format par défaut (DD-MON-YY).",
    topic: "TO_CHAR",
    difficulty: "easy",
  },
  {
    id: "q54",
    moduleId: "m5",
    question: "Peut-on utiliser une fonction d'agrégation dans WHERE ?",
    options: [
      "Oui, toujours",
      "Non, jamais. Il faut utiliser HAVING",
      "Oui, mais seulement COUNT",
      "Oui, avec une sous-requête",
    ],
    correctIndex: 1,
    explanation: "Non. WHERE ne peut pas utiliser de fonctions d'agrégation car elle s'exécute avant GROUP BY. Pour filtrer sur des agrégats, il faut utiliser HAVING (après GROUP BY).",
    topic: "WHERE vs HAVING",
    difficulty: "medium",
  },
  {
    id: "q55",
    moduleId: "m6",
    question: "Quelle est la syntaxe recommandée pour les jointures ?",
    options: [
      "FROM a, b WHERE a.id = b.id",
      "FROM a JOIN b ON a.id = b.id",
      "FROM a NATURAL JOIN b",
      "FROM a CROSS JOIN b",
    ],
    correctIndex: 1,
    explanation: "JOIN ... ON est la syntaxe standard SQL recommandée. Elle sépare clairement la condition de jointure du filtrage, contrairement à l'ancienne syntaxe Oracle (FROM a, b WHERE ...).",
    topic: "JOIN syntax",
    difficulty: "easy",
  },
  {
    id: "q56",
    moduleId: "m7",
    question: "Qu'est-ce qu'une sous-requête corrélée ?",
    options: [
      "Une sous-requête qui retourne plusieurs colonnes",
      "Une sous-requête qui référence la requête externe",
      "Une sous-requête dans le FROM",
      "Une sous-requête avec JOIN",
    ],
    correctIndex: 1,
    explanation: "Une sous-requête corrélée référence une colonne de la requête externe. Elle est ré-exécutée pour chaque ligne de la requête externe. EXISTS est l'opérateur principal pour ce pattern.",
    topic: "Correlated subquery",
    difficulty: "medium",
  },
  {
    id: "q57",
    moduleId: "m8",
    question: "Que fait INTERSECT ?",
    options: [
      "Retourne toutes les lignes des deux requêtes",
      "Retourne les lignes communes aux deux requêtes",
      "Retourne les lignes uniques",
      "Retourne la première requête seulement",
    ],
    correctIndex: 1,
    explanation: "INTERSECT retourne les lignes présentes dans les DEUX requêtes (intersection). Les doublons sont éliminés et le résultat est trié.",
    topic: "INTERSECT",
    difficulty: "easy",
  },
  {
    id: "q58",
    moduleId: "m10",
    question: "Pourquoi ne pas indexer toutes les colonnes ?",
    options: [
      "Les index occupent trop de mémoire",
      "Les index ralentissent les INSERT/UPDATE/DELETE",
      "Les index ne fonctionnent qu'avec des nombres",
      "Il y a une limite de 5 index par table",
    ],
    correctIndex: 1,
    explanation: "Les index accélèrent la lecture mais ralentissent les INSERT/UPDATE/DELETE car chaque index doit être maintenu. Indexer uniquement les colonnes fréquemment utilisées dans WHERE, JOIN, ORDER BY.",
    topic: "Indexes",
    difficulty: "medium",
  },
  {
    id: "q59",
    moduleId: "m11",
    question: "Que fait ROW_NUMBER() ?",
    options: [
      "Compte le nombre de lignes",
      "Attribue un numéro unique à chaque ligne (même avec ex aequo)",
      "Retourne le rang avec sauts",
      "Retourne le rang sans sauts",
    ],
    correctIndex: 1,
    explanation: "ROW_NUMBER() attribue un numéro unique séquentiel à chaque ligne. Même en cas d'ex aequo, chaque ligne reçoit un numéro différent (l'ordre est arbitraire).",
    topic: "ROW_NUMBER",
    difficulty: "medium",
  },
  {
    id: "q60",
    moduleId: "m4",
    question: "Que fait la fonction DECODE ?",
    options: [
      "Elle décode une chaîne base64",
      "Elle fonctionne comme un IF/THEN/ELSE",
      "Elle convertit un type",
      "Elle décompresse des données",
    ],
    correctIndex: 1,
    explanation: "DECODE fonctionne comme un IF/THEN/ELSE : DECODE(expr, val1, result1, val2, result2, default). C'est spécifique Oracle. CASE est l'équivalent standard SQL et plus puissant.",
    topic: "DECODE",
    difficulty: "medium",
  },
];
