import type { QuizQuestion } from "./types";

/**
 * Banque 1Z0-076 — Oracle Database 19c: Data Guard Administration.
 *
 * Une question par concept distinct, rattachée à la session du cursus qui le
 * traite (`lib/course-dataguard.ts`).
 */
export const dataGuardQuestions: QuizQuestion[] = [
  // ─── Session 1 — Concepts et architecture ───────────────────────────────
  {
    id: "dg-q1", track: "ocp-dataguard", moduleId: "dg-session-1",
    question: "Contre quel risque Data Guard ne protège-t-il PAS ?",
    options: [
      "La panne du serveur principal",
      "La perte du site de production",
      "Une erreur logique, comme un DROP TABLE malheureux",
      "La corruption physique d'un fichier de données",
    ],
    correctIndexes: [2],
    explanation: "Data Guard réplique fidèlement tout ce qui est validé, y compris les erreurs : un DROP TABLE atteint la base de secours en quelques secondes. Seules les sauvegardes, Flashback et les points de restauration protègent d'une erreur logique.",
    topic: "Périmètre de Data Guard", difficulty: "medium",
  },
  {
    id: "dg-q2", track: "ocp-dataguard", moduleId: "dg-session-1",
    question: "Quel processus applique le redo sur une base de secours physique ?",
    options: ["LNS", "LSP0", "RFS", "MRP0"],
    correctIndexes: [3],
    explanation: "MRP0 (Managed Recovery Process) applique le redo sur une base de secours physique — c'est le Redo Apply. LSP0 rejoue les instructions SQL sur une base logique, RFS reçoit le redo côté secours, LNS le transmet côté principal.",
    topic: "Processus", difficulty: "medium",
  },
  {
    id: "dg-q3", track: "ocp-dataguard", moduleId: "dg-session-1",
    question: "Quelles affirmations sont exactes concernant une base de secours instantanée (snapshot standby) ? (Choisissez trois réponses.)",
    options: [
      "Elle est ouverte en lecture-écriture",
      "Un point de restauration garanti est créé automatiquement lors de la conversion",
      "Elle continue de recevoir le redo sans l'appliquer",
      "Elle applique le redo en continu",
      "Elle ne peut jamais redevenir une base de secours physique",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "La conversion pose un point de restauration garanti et ouvre la base en écriture pour des tests. Le redo continue d'arriver mais reste en attente. CONVERT … TO PHYSICAL STANDBY effectue un Flashback vers ce point puis rattrape tout le redo accumulé.",
    topic: "Snapshot standby", difficulty: "hard",
  },
  {
    id: "dg-q4", track: "ocp-dataguard", moduleId: "dg-session-1",
    question: "En environnement multitenant, à quel niveau s'applique une configuration Data Guard ?",
    options: [
      "À chaque PDB indépendamment",
      "À la CDB entière",
      "Uniquement au CDB$ROOT",
      "Au conteneur applicatif seul",
    ],
    correctIndexes: [1],
    explanation: "Le redo est commun à tous les conteneurs d'une CDB : Data Guard réplique donc la CDB entière. Répliquer une PDB seule relève du clone rafraîchissable ou de GoldenGate, pas de Data Guard.",
    topic: "Multitenant", difficulty: "hard",
  },
  {
    id: "dg-q5", track: "ocp-dataguard", moduleId: "dg-session-1",
    question: "Quel type de base de secours permet de créer des index supplémentaires absents de la base principale ?",
    options: ["Logique", "Physique", "Instantanée", "Far Sync"],
    correctIndexes: [0],
    explanation: "Une base de secours logique rejoue des instructions SQL et reste ouverte en écriture : elle peut porter ses propres index, vues matérialisées et même tables. Une base physique est une copie bloc à bloc, structurellement identique.",
    topic: "Types de base de secours", difficulty: "medium",
  },

  // ─── Session 2 — Préparer et créer ──────────────────────────────────────
  {
    id: "dg-q6", track: "ocp-dataguard", moduleId: "dg-session-2",
    question: "Pourquoi une entrée statique dans listener.ora est-elle indispensable côté base de secours ?",
    options: [
      "Parce qu'elle est requise par FORCE LOGGING",
      "Parce que l'enregistrement dynamique est désactivé en 19c",
      "Parce qu'elle accélère le transport du redo",
      "Parce que PMON ne peut pas enregistrer une instance arrêtée, que RMAN et le Broker doivent pourtant joindre",
    ],
    correctIndexes: [3],
    explanation: "L'enregistrement dynamique par PMON suppose une instance démarrée. Or la duplication RMAN et le Broker doivent atteindre une instance en NOMOUNT, voire arrêtée, pour la démarrer. Seule une entrée statique le permet — avec le suffixe _DGMGRL pour le Broker.",
    topic: "Oracle Net", difficulty: "hard",
  },
  {
    id: "dg-q7", track: "ocp-dataguard", moduleId: "dg-session-2",
    question: "Combien de groupes de standby redo logs faut-il prévoir, et de quelle taille ?",
    options: [
      "Autant que de groupes en ligne, de taille double",
      "Un de plus que le nombre de groupes de redo en ligne, de taille identique",
      "Un seul groupe, quelle que soit la taille",
      "Deux fois le nombre de groupes en ligne, de taille moitié",
    ],
    correctIndexes: [1],
    explanation: "La règle est n+1 groupes de la même taille exactement que les redo logs en ligne. Une taille différente empêche le processus RFS d'utiliser le groupe, et le transport bascule silencieusement en mode archive.",
    topic: "Standby redo logs", difficulty: "hard",
  },
  {
    id: "dg-q8", track: "ocp-dataguard", moduleId: "dg-session-2",
    question: "Quels prérequis doivent être satisfaits sur la base principale ? (Choisissez trois réponses.)",
    options: [
      "FORCE LOGGING",
      "Mode ARCHIVELOG",
      "Flashback Database activé pour permettre REINSTATE",
      "Mode NOARCHIVELOG",
      "Le paramètre COMPATIBLE fixé à 11.2",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "FORCE LOGGING interdit les opérations non journalisées, le mode ARCHIVELOG est obligatoire pour tout transport de redo, et Flashback Database permet de réinstancier l'ancienne base principale après un failover sans la recréer.",
    topic: "Prérequis", difficulty: "medium",
  },
  {
    id: "dg-q9", track: "ocp-dataguard", moduleId: "dg-session-2",
    question: "Quelle commande RMAN crée une base de secours physique directement depuis la base active ?",
    options: [
      "RESTORE STANDBY CONTROLFILE",
      "BACKUP DATABASE PLUS ARCHIVELOG",
      "DUPLICATE TARGET DATABASE FOR STANDBY FROM ACTIVE DATABASE",
      "RECOVER DATABASE UNTIL CANCEL",
    ],
    correctIndexes: [2],
    explanation: "DUPLICATE … FOR STANDBY FROM ACTIVE DATABASE copie la base en cours d'exécution vers l'instance auxiliaire, sans sauvegarde préalable. L'option DORECOVER applique le redo produit pendant la copie.",
    topic: "Création par RMAN", difficulty: "medium",
  },
  {
    id: "dg-q10", track: "ocp-dataguard", moduleId: "dg-session-2",
    question: "Que fait la procédure DBMS_DBCOMP.DBCOMP ?",
    options: [
      "Elle compare bloc à bloc la base principale et sa base de secours et signale les divergences",
      "Elle compresse le redo transporté",
      "Elle compare les plans d'exécution entre les deux bases",
      "Elle convertit une base physique en base logique",
    ],
    correctIndexes: [0],
    explanation: "Introduite en 12.2, DBCOMP compare physiquement les blocs des deux bases. C'est le contrôle qui prouve la fidélité de la réplique — utile après un incident de transport ou une opération NOLOGGING suspecte.",
    topic: "DBMS_DBCOMP", difficulty: "hard",
  },
  {
    id: "dg-q11", track: "ocp-dataguard", moduleId: "dg-session-2",
    question: "Quelle vue permet de vérifier qu'aucun fichier d'archive ne manque sur la base de secours ?",
    options: ["V$LOGFILE", "V$ARCHIVE_GAP", "V$DATAFILE_HEADER", "V$RECOVERY_FILE_DEST"],
    correctIndexes: [1],
    explanation: "V$ARCHIVE_GAP doit rester vide. Si elle renvoie des lignes, le paramètre FAL_SERVER n'a pas permis de combler l'écart automatiquement et il faut transférer les archives manquantes à la main.",
    topic: "Contrôle du transport", difficulty: "medium",
  },
  {
    id: "dg-q12", track: "ocp-dataguard", moduleId: "dg-session-2",
    question: "Quel paramètre évite d'avoir à créer les fichiers de données manuellement sur la base de secours ?",
    options: [
      "LOG_ARCHIVE_CONFIG",
      "DB_FILE_NAME_CONVERT",
      "STANDBY_FILE_MANAGEMENT = AUTO",
      "FAL_CLIENT",
    ],
    correctIndexes: [2],
    explanation: "Avec STANDBY_FILE_MANAGEMENT = AUTO, un fichier ajouté sur la principale est créé automatiquement côté secours. DB_FILE_NAME_CONVERT ne fait que traduire les chemins ; sans le premier paramètre, l'application du redo s'arrête.",
    topic: "Gestion des fichiers", difficulty: "medium",
  },

  // ─── Session 3 — Bases logiques et instantanées ─────────────────────────
  {
    id: "dg-q13", track: "ocp-dataguard", moduleId: "dg-session-3",
    question: "Quelle vue faut-il consulter AVANT de créer une base de secours logique ?",
    options: [
      "V$MANAGED_STANDBY",
      "V$DATAGUARD_STATS",
      "DBA_LOGSTDBY_LOG",
      "DBA_LOGSTDBY_UNSUPPORTED",
    ],
    correctIndexes: [3],
    explanation: "DBA_LOGSTDBY_UNSUPPORTED liste les objets que SQL Apply ne sait pas répliquer, à cause de types de données non pris en charge. Si des tables critiques y figurent, elles ne seront jamais synchronisées — et on ne s'en aperçoit qu'après la bascule.",
    topic: "Base de secours logique", difficulty: "hard",
  },
  {
    id: "dg-q14", track: "ocp-dataguard", moduleId: "dg-session-3",
    question: "Quelle journalisation supplémentaire est requise pour SQL Apply ?",
    options: [
      "ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY, UNIQUE INDEX) COLUMNS",
      "ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS uniquement",
      "Aucune : le redo suffit",
      "ALTER DATABASE FORCE LOGGING seul",
    ],
    correctIndexes: [0],
    explanation: "SQL Apply doit pouvoir identifier chaque ligne de manière unique pour rejouer un UPDATE ou un DELETE. La journalisation supplémentaire des clés primaires et des index uniques rend cette identification possible.",
    topic: "Supplemental logging", difficulty: "hard",
  },
  {
    id: "dg-q15", track: "ocp-dataguard", moduleId: "dg-session-3",
    question: "Quelle procédure permet de resynchroniser une seule table divergente sur une base logique ?",
    options: [
      "DBMS_LOGSTDBY.APPLY_SET",
      "DBMS_LOGSTDBY.SKIP",
      "DBMS_LOGSTDBY.INSTANTIATE_TABLE",
      "DBMS_LOGSTDBY.SKIP_ERROR",
    ],
    correctIndexes: [2],
    explanation: "INSTANTIATE_TABLE recopie une table depuis la principale et la remet dans le flux de SQL Apply, sans recréer toute la base de secours. SKIP exclut un objet, SKIP_ERROR ignore une erreur, APPLY_SET règle le parallélisme.",
    topic: "SQL Apply", difficulty: "hard",
  },

  // ─── Session 4 — Transport et modes de protection ───────────────────────
  {
    id: "dg-q16", track: "ocp-dataguard", moduleId: "dg-session-4",
    question: "Que se passe-t-il en mode Maximum Protection si aucune base de secours ne peut accuser réception ?",
    options: [
      "Le mode passe automatiquement en Maximum Availability",
      "Le transport bascule automatiquement en asynchrone",
      "Les transactions sont mises en file d'attente puis validées",
      "La base principale s'arrête",
    ],
    correctIndexes: [3],
    explanation: "Maximum Protection garantit littéralement zéro perte : plutôt que de valider une transaction non répliquée, la base principale s'arrête. C'est pourquoi ce mode exige en pratique au moins deux bases de secours.",
    topic: "Modes de protection", difficulty: "medium",
  },
  {
    id: "dg-q17", track: "ocp-dataguard", moduleId: "dg-session-4",
    question: "Que signifie FASTSYNC ?",
    options: [
      "ASYNC avec compression activée",
      "SYNC NOAFFIRM : la base de secours accuse réception dès la réception en mémoire",
      "Un transport synchrone doublé d'une écriture disque immédiate",
      "Le mode par défaut de Maximum Performance",
    ],
    correctIndexes: [1],
    explanation: "FASTSYNC = SYNC NOAFFIRM. La base de secours confirme dès que le redo est en mémoire, sans attendre l'écriture disque. On conserve l'essentiel de la garantie synchrone en réduisant nettement la latence des COMMIT.",
    topic: "Transport du redo", difficulty: "hard",
  },
  {
    id: "dg-q18", track: "ocp-dataguard", moduleId: "dg-session-4",
    question: "Quel est l'apport principal d'Active Data Guard ?",
    options: [
      "Servir des requêtes en lecture pendant que le redo est appliqué",
      "Répliquer une PDB isolée",
      "Supprimer le besoin de standby redo logs",
      "Transformer une base physique en base logique",
    ],
    correctIndexes: [0],
    explanation: "Sans Active Data Guard, une base de secours physique est soit ouverte en lecture seule, soit en train d'appliquer — jamais les deux. Active Data Guard lève cette exclusion : OPEN MODE devient READ ONLY WITH APPLY. C'est une option payante.",
    topic: "Active Data Guard", difficulty: "medium",
  },
  {
    id: "dg-q19", track: "ocp-dataguard", moduleId: "dg-session-4",
    question: "Quel problème une instance Far Sync résout-elle ?",
    options: [
      "Compresser les sauvegardes RMAN",
      "Appliquer le redo plus rapidement sur la base de secours",
      "Répliquer plusieurs PDB séparément",
      "Obtenir zéro perte de données sans imposer la latence intercontinentale à chaque COMMIT",
    ],
    correctIndexes: [3],
    explanation: "Far Sync est une instance légère — fichier de contrôle et standby redo logs, aucun fichier de données — placée près de la production. Elle reçoit le redo en synchrone, puis le retransmet en asynchrone vers la base de secours distante.",
    topic: "Far Sync", difficulty: "hard",
  },
  {
    id: "dg-q20", track: "ocp-dataguard", moduleId: "dg-session-4",
    question: "Que contient une instance Far Sync ? (Choisissez deux réponses.)",
    options: [
      "Un fichier de contrôle",
      "Des standby redo logs",
      "Les fichiers de données de la base",
      "Un processus MRP0 appliquant le redo",
    ],
    correctIndexes: [0, 1],
    explanation: "Une instance Far Sync n'a ni fichier de données, ni application du redo : elle ne fait que recevoir et retransmettre. Son rôle apparaît comme FAR SYNC dans V$DATABASE.DATABASE_ROLE.",
    topic: "Far Sync", difficulty: "hard",
  },
  {
    id: "dg-q21", track: "ocp-dataguard", moduleId: "dg-session-4",
    question: "Qu'apporte le Real-Time Cascade depuis la 12c ?",
    options: [
      "Le redo est transmis simultanément à toutes les bases de secours par la principale",
      "La base de secours retransmet le redo au fil de sa réception, sans attendre la fin du fichier journal",
      "L'application du redo devient parallèle",
      "Les fichiers d'archive sont compressés automatiquement",
    ],
    correctIndexes: [1],
    explanation: "Avant la 12c, une base en cascade attendait la complétion du fichier journal avant de retransmettre. Depuis, la retransmission est immédiate : une configuration à trois niveaux devient presque aussi réactive qu'une liaison directe.",
    topic: "Cascade", difficulty: "hard",
  },
  {
    id: "dg-q22", track: "ocp-dataguard", moduleId: "dg-session-4",
    question: "Quelle vue permet de vérifier le mode de protection réellement en vigueur ?",
    options: [
      "V$ARCHIVE_DEST_STATUS uniquement",
      "V$MANAGED_STANDBY",
      "V$DATABASE, colonnes PROTECTION_MODE et PROTECTION_LEVEL",
      "V$LOGFILE",
    ],
    correctIndexes: [2],
    explanation: "PROTECTION_MODE indique le mode configuré, PROTECTION_LEVEL le mode effectivement assuré à cet instant. Un écart entre les deux — MAXIMUM AVAILABILITY configuré, RESYNCHRONIZATION en cours — signale une configuration dégradée.",
    topic: "Contrôle du mode", difficulty: "hard",
  },

  // ─── Session 5 — Broker ─────────────────────────────────────────────────
  {
    id: "dg-q23", track: "ocp-dataguard", moduleId: "dg-session-5",
    question: "Quel paramètre doit être activé sur chaque base pour utiliser le Broker ?",
    options: ["DG_BROKER_START = TRUE", "DG_BROKER_CONFIG_FILE1", "LOG_ARCHIVE_CONFIG", "FAL_SERVER"],
    correctIndexes: [0],
    explanation: "DG_BROKER_START = TRUE démarre le processus DMON sur chaque base. Les paramètres DG_BROKER_CONFIG_FILE1 et 2 désignent seulement l'emplacement des fichiers de configuration.",
    topic: "Broker", difficulty: "easy",
  },
  {
    id: "dg-q24", track: "ocp-dataguard", moduleId: "dg-session-5",
    question: "Une fois le Broker actif, comment modifier une destination de transport ?",
    options: [
      "Par ALTER SYSTEM SET log_archive_dest_2 en SQL",
      "Par EDIT DATABASE … SET PROPERTY dans DGMGRL",
      "En éditant directement le fichier de configuration du Broker",
      "En redémarrant l'instance avec un pfile modifié",
    ],
    correctIndexes: [1],
    explanation: "Le Broker réécrit les paramètres LOG_ARCHIVE_DEST_n à partir de sa propre configuration : toute modification en SQL disparaît sans avertissement. Il faut passer par EDIT DATABASE … SET PROPERTY.",
    topic: "Broker", difficulty: "medium",
  },
  {
    id: "dg-q25", track: "ocp-dataguard", moduleId: "dg-session-5",
    question: "Que rapporte la commande VALIDATE DATABASE de DGMGRL ? (Choisissez trois réponses.)",
    options: [
      "La capacité de la base à assurer un switchover ou un failover",
      "Les fichiers de données manquants ou en écart",
      "L'état du fichier de mots de passe et de Flashback",
      "Le plan d'exécution des requêtes les plus lentes",
      "Le taux de compression des sauvegardes",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "VALIDATE DATABASE, introduite en 12.2, répond à la question qui compte avant un incident : « puis-je basculer maintenant, et que perdrais-je ? ». Elle vérifie fichiers, redo manquant, mots de passe, Flashback, standby redo logs et rôle des services.",
    topic: "VALIDATE", difficulty: "medium",
  },
  {
    id: "dg-q26", track: "ocp-dataguard", moduleId: "dg-session-5",
    question: "Quel suffixe doit porter GLOBAL_DBNAME dans listener.ora pour le Broker ?",
    options: ["_BROKER", "_STANDBY", "_DGMGRL", "_DG"],
    correctIndexes: [2],
    explanation: "Le Broker attend une entrée statique dont le GLOBAL_DBNAME vaut <db_unique_name>_DGMGRL. Sans elle, VALIDATE STATIC CONNECT IDENTIFIER échoue et le Broker ne peut pas redémarrer l'instance lors d'une transition de rôle.",
    topic: "Broker", difficulty: "hard",
  },

  // ─── Session 6 — Transitions de rôle ────────────────────────────────────
  {
    id: "dg-q27", track: "ocp-dataguard", moduleId: "dg-session-6",
    question: "Quelle différence essentielle sépare un switchover d'un failover ?",
    options: [
      "Le switchover exige un observateur",
      "Le switchover ne fonctionne qu'avec une base logique",
      "Le failover est réversible sans intervention",
      "Le switchover est planifié et sans perte ; le failover est subi et peut perdre des données",
    ],
    correctIndexes: [3],
    explanation: "Un switchover échange proprement les rôles : l'ancienne principale devient base de secours sans recréation. Un failover est subi et laisse l'ancienne principale divergente : elle doit être réinstanciée ou recréée.",
    topic: "Transitions de rôle", difficulty: "medium",
  },
  {
    id: "dg-q28", track: "ocp-dataguard", moduleId: "dg-session-6",
    question: "Pourquoi Flashback Database doit-il être activé avant un failover ?",
    options: [
      "Pour permettre REINSTATE DATABASE sans recréer l'ancienne base principale",
      "Pour accélérer le transport du redo",
      "Pour autoriser le mode Maximum Protection",
      "Pour créer les standby redo logs automatiquement",
    ],
    correctIndexes: [0],
    explanation: "Après un failover, l'ancienne base principale contient des transactions que la nouvelle n'a jamais reçues. Avec Flashback, REINSTATE la ramène au SCN de divergence puis la resynchronise en quelques minutes ; sans lui, il faut tout recréer.",
    topic: "Flashback et REINSTATE", difficulty: "hard",
  },
  {
    id: "dg-q29", track: "ocp-dataguard", moduleId: "dg-session-6",
    question: "Où l'observateur du Fast-Start Failover doit-il s'exécuter ?",
    options: [
      "Sur la base de secours",
      "Sur la base principale",
      "Sur un troisième site, distinct de la principale et de la base de secours",
      "Indifféremment sur l'une des deux bases",
    ],
    correctIndexes: [2],
    explanation: "Un observateur hébergé sur la principale disparaîtrait avec elle et ne pourrait rien décider ; hébergé sur la base de secours, il ne pourrait pas distinguer une panne réelle d'une coupure réseau. Le troisième site fournit l'arbitrage.",
    topic: "Fast-Start Failover", difficulty: "hard",
  },
  {
    id: "dg-q30", track: "ocp-dataguard", moduleId: "dg-session-6",
    question: "Quel mode de protection minimum le Fast-Start Failover exige-t-il ?",
    options: [
      "Maximum Performance uniquement",
      "Maximum Protection obligatoirement",
      "Aucun mode particulier",
      "Maximum Availability (ou Maximum Performance selon la configuration)",
    ],
    correctIndexes: [3],
    explanation: "Fast-Start Failover est pris en charge en Maximum Availability — configuration de référence, zéro perte — et en Maximum Performance depuis la 11.2, avec un objectif de perte défini par FastStartFailoverLagLimit.",
    topic: "Fast-Start Failover", difficulty: "hard",
  },
  {
    id: "dg-q31", track: "ocp-dataguard", moduleId: "dg-session-6",
    question: "Quelle procédure permet à une application de déclencher immédiatement un Fast-Start Failover ?",
    options: [
      "DBMS_SERVICE.STOP_SERVICE",
      "DBMS_DG.INITIATE_FS_FAILOVER",
      "DBMS_LOGSTDBY.SKIP",
      "DBMS_DBCOMP.DBCOMP",
    ],
    correctIndexes: [1],
    explanation: "DBMS_DG.INITIATE_FS_FAILOVER permet à une application ayant détecté une corruption ou une indisponibilité de demander la bascule sans attendre l'expiration de FastStartFailoverThreshold.",
    topic: "Fast-Start Failover", difficulty: "hard",
  },
  {
    id: "dg-q32", track: "ocp-dataguard", moduleId: "dg-session-6",
    question: "Depuis la 12.2, que devient un point de restauration créé sur la base principale ?",
    options: [
      "Il est automatiquement propagé à la base de secours, préfixé par son nom d'origine",
      "Il reste local à la base principale",
      "Il interrompt l'application du redo",
      "Il ne peut plus être garanti",
    ],
    correctIndexes: [0],
    explanation: "Les points de restauration répliqués permettent de ramener les deux bases au même instant logique après une erreur applicative. La colonne REPLICATED de V$RESTORE_POINT les identifie côté secours.",
    topic: "Points de restauration répliqués", difficulty: "hard",
  },

  // ─── Session 7 — Sauvegarde, correctifs, mises à niveau ─────────────────
  {
    id: "dg-q33", track: "ocp-dataguard", moduleId: "dg-session-7",
    question: "Que permet la récupération automatique de blocs (Automatic Block Media Recovery) ?",
    options: [
      "Compresser les blocs transférés",
      "Reconstruire un fichier de données entier",
      "Convertir une base physique en base logique",
      "Réparer un bloc corrompu depuis l'autre base, sans intervention ni interruption",
    ],
    correctIndexes: [3],
    explanation: "Avec Active Data Guard, un bloc corrompu détecté sur la principale est réparé automatiquement depuis la base de secours — et réciproquement. La session concernée attend quelques instants puis poursuit ; l'événement est tracé dans l'alert log.",
    topic: "Réparation de blocs", difficulty: "hard",
  },
  {
    id: "dg-q34", track: "ocp-dataguard", moduleId: "dg-session-7",
    question: "Quelle commande RMAN resynchronise une base de secours très en retard, sans restauration de fichiers ?",
    options: [
      "RESTORE DATABASE FROM TAG standby",
      "RECOVER STANDBY DATABASE FROM SERVICE orcl_pr",
      "DUPLICATE DATABASE FOR STANDBY",
      "RECOVER DATABASE UNTIL CANCEL",
    ],
    correctIndexes: [1],
    explanation: "RECOVER … FROM SERVICE récupère les blocs directement par le réseau depuis la base source, sans passer par une sauvegarde. La même syntaxe sert dans l'autre sens pour récupérer la principale depuis la base de secours.",
    topic: "Récupération par le réseau", difficulty: "hard",
  },
  {
    id: "dg-q35", track: "ocp-dataguard", moduleId: "dg-session-7",
    question: "Quel paquetage automatise une mise à niveau progressive de la base ?",
    options: ["DBMS_DG", "DBMS_LOGSTDBY", "DBMS_ROLLING", "DBMS_REDEFINITION"],
    correctIndexes: [2],
    explanation: "DBMS_ROLLING enchaîne INIT_PLAN, BUILD_PLAN, START_PLAN, SWITCHOVER et FINISH_PLAN : il convertit la base de secours en base logique transitoire, la met à niveau, bascule, puis remet tout en ordre. C'est la méthode recommandée depuis la 12c.",
    topic: "Mise à niveau progressive", difficulty: "hard",
  },
  {
    id: "dg-q36", track: "ocp-dataguard", moduleId: "dg-session-7",
    question: "Pourquoi décharger les sauvegardes RMAN sur la base de secours physique ?",
    options: [
      "Parce que la copie est identique bloc à bloc, donc utilisable pour restaurer la principale",
      "Parce que RMAN ne peut pas sauvegarder une base ouverte",
      "Parce que le catalogue de récupération l'exige",
      "Parce que la base de secours dispose de plus d'espace",
    ],
    correctIndexes: [0],
    explanation: "Une base de secours physique est une réplique bloc à bloc : une sauvegarde prise sur elle restaure la principale. La production est ainsi déchargée du coût des sauvegardes — l'un des retours sur investissement immédiats de Data Guard.",
    topic: "Sauvegarde déchargée", difficulty: "medium",
  },
  {
    id: "dg-q37", track: "ocp-dataguard", moduleId: "dg-session-7",
    question: "Quels modes NOLOGGING la 19c introduit-elle pour concilier chargements rapides et base de secours utilisable ? (Choisissez deux réponses.)",
    options: [
      "STANDBY NOLOGGING FOR DATA AVAILABILITY",
      "STANDBY NOLOGGING FOR LOAD PERFORMANCE",
      "FORCE LOGGING FOR STANDBY",
      "NOLOGGING FOR REDO APPLY",
    ],
    correctIndexes: [0, 1],
    explanation: "Ces deux modes autorisent des chargements peu journalisés tout en garantissant que la base de secours reste exploitable : le premier privilégie la disponibilité des données, le second la vitesse du chargement.",
    topic: "NOLOGGING 19c", difficulty: "hard",
  },

  // ─── Session 8 — Optimisation et exploitation ───────────────────────────
  {
    id: "dg-q38", track: "ocp-dataguard", moduleId: "dg-session-8",
    question: "Un transport lag élevé accompagné d'un apply lag faible indique :",
    options: [
      "Une base de secours qui n'applique pas assez vite",
      "Un problème de réseau entre la principale et la base de secours",
      "Des statistiques périmées",
      "Un fichier de mots de passe désynchronisé",
    ],
    correctIndexes: [1],
    explanation: "Le transport lag mesure le retard de réception, l'apply lag le retard d'application. Un transport lag seul élevé désigne le réseau : SDU, tampons TCP, compression du redo. Si c'est l'inverse, la piste est du côté des E/S de la base de secours.",
    topic: "Diagnostic des écarts", difficulty: "hard",
  },
  {
    id: "dg-q39", track: "ocp-dataguard", moduleId: "dg-session-8",
    question: "Quelle vue donne le transport lag et l'apply lag ?",
    options: ["V$MANAGED_STANDBY", "V$DATAGUARD_STATUS", "V$DATAGUARD_STATS", "V$ARCHIVED_LOG"],
    correctIndexes: [2],
    explanation: "V$DATAGUARD_STATS expose transport lag, apply lag et apply finish time. V$DATAGUARD_STATUS contient les messages d'événements, V$MANAGED_STANDBY l'état des processus de transport et d'application.",
    topic: "Surveillance", difficulty: "medium",
  },
  {
    id: "dg-q40", track: "ocp-dataguard", moduleId: "dg-session-8",
    question: "Quel changement sur la base principale exige une intervention MANUELLE côté base de secours ? (Choisissez deux réponses.)",
    options: [
      "L'ajout d'un groupe de redo logs",
      "Le changement du mot de passe SYS",
      "L'ajout d'un fichier de données avec STANDBY_FILE_MANAGEMENT = AUTO",
      "La création d'une table",
    ],
    correctIndexes: [0, 1],
    explanation: "L'ajout d'un groupe de redo impose d'ajouter aussi un standby redo log. Un changement de mot de passe SYS impose de recopier le fichier de mots de passe, faute de quoi le transport s'arrête sur ORA-16191.",
    topic: "Changements structurels", difficulty: "hard",
  },
  {
    id: "dg-q41", track: "ocp-dataguard", moduleId: "dg-session-8",
    question: "Quelle erreur signale un fichier de mots de passe désynchronisé entre les deux bases ?",
    options: ["ORA-00600", "ORA-01017 uniquement", "ORA-16000", "ORA-16191"],
    correctIndexes: [3],
    explanation: "ORA-16191 (« Primary log shipping client not logged on standby ») apparaît dans l'alert log de la principale lorsque le fichier de mots de passe diffère. C'est la panne d'exploitation la plus fréquente après une rotation de mot de passe.",
    topic: "Dépannage", difficulty: "hard",
  },
  {
    id: "dg-q42", track: "ocp-dataguard", moduleId: "dg-session-8",
    question: "Comment garantir qu'un service ne démarre que sur la base ayant le rôle PRIMARY ?",
    options: [
      "Un service déclenché par un trigger sur DB_ROLE_CHANGE, ou déclaré avec srvctl -role PRIMARY",
      "Un alias TNS pointant vers la seule base principale",
      "Un profil utilisateur restreint",
      "Le paramètre SERVICE_NAMES fixé statiquement",
    ],
    correctIndexes: [0],
    explanation: "Un service lié au rôle démarre automatiquement du bon côté après une bascule. Un alias TNS figé oblige à reconfigurer tous les clients ; SERVICE_NAMES statique démarrerait le service sur les deux bases à la fois.",
    topic: "Connectivité client", difficulty: "hard",
  },
  {
    id: "dg-q43", track: "ocp-dataguard", moduleId: "dg-session-8",
    question: "Qu'apporte Application Continuity par rapport au basculement de connexion TAF ?",
    options: [
      "Aucune configuration de service n'est nécessaire",
      "La reconnexion est plus rapide",
      "Le pilote rejoue la transaction interrompue sur la nouvelle base principale",
      "Il fonctionne sans Data Guard",
    ],
    correctIndexes: [2],
    explanation: "TAF reconnecte la session, mais l'application reçoit tout de même une erreur sur la transaction en cours. Application Continuity la rejoue de façon transparente ; il exige un service en FAILOVER_TYPE=TRANSACTION et un pilote compatible.",
    topic: "Application Continuity", difficulty: "hard",
  },
  {
    id: "dg-q44", track: "ocp-dataguard", moduleId: "dg-session-8",
    question: "Quelle commande augmente le parallélisme de l'application du redo ?",
    options: [
      "ALTER SYSTEM SET log_archive_max_processes = 8",
      "ALTER SYSTEM SET parallel_degree_policy = AUTO",
      "ALTER DATABASE ADD STANDBY LOGFILE",
      "ALTER DATABASE RECOVER MANAGED STANDBY DATABASE PARALLEL 8 DISCONNECT",
    ],
    correctIndexes: [3],
    explanation: "La clause PARALLEL du RECOVER MANAGED STANDBY DATABASE fixe le nombre de processus d'application. LOG_ARCHIVE_MAX_PROCESSES agit sur l'archivage, pas sur l'application côté secours.",
    topic: "Optimisation de l'application", difficulty: "hard",
  },
  {
    id: "dg-q45", track: "ocp-dataguard", moduleId: "dg-session-8",
    question: "Quel attribut de LOG_ARCHIVE_DEST_n active la compression du redo transporté ?",
    options: ["SYNC AFFIRM", "COMPRESSION=ENABLE", "VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE)", "REOPEN=60"],
    correctIndexes: [1],
    explanation: "COMPRESSION=ENABLE réduit le volume transporté sur une liaison lente ; l'attribut relève de l'option Advanced Compression. Les autres attributs contrôlent respectivement le mode de transport, la validité selon le rôle et le délai de reprise.",
    topic: "Transport du redo", difficulty: "hard",
  },
];
