import type { QuizQuestion } from "./types";

/**
 * Banque 1Z0-084 — Oracle Database 19c: Performance Management and Tuning.
 *
 * Une question par concept distinct, rattachée à la session du cursus qui le
 * traite (`lib/course-tuning.ts`). Les questions multi-réponses annoncent
 * explicitement le nombre attendu, comme à l'examen.
 */
export const tuningQuestions: QuizQuestion[] = [
  // ─── Session 1 — Méthode d'optimisation ─────────────────────────────────
  {
    id: "tun-q1", track: "ocp-tuning", moduleId: "tun-session-1",
    question: "Quel est le premier geste d'une démarche d'optimisation rigoureuse ?",
    options: [
      "Recollecter les statistiques de tous les schémas",
      "Augmenter la SGA pour écarter une piste mémoire",
      "Définir un objectif chiffré et mesurable avant toute modification",
      "Activer une trace 10046 sur l'instance entière",
    ],
    correctIndexes: [2],
    explanation: "Sans objectif chiffré — « ce traitement doit passer sous 4 minutes » — on ne peut ni prouver un gain, ni savoir quand s'arrêter. Toutes les autres options sont des actions : elles viennent après le diagnostic, jamais avant.",
    topic: "Méthodologie", difficulty: "easy",
  },
  {
    id: "tun-q2", track: "ocp-tuning", moduleId: "tun-session-1",
    question: "Que mesure la statistique DB time du modèle de temps ?",
    options: [
      "Le temps écoulé depuis le démarrage de l'instance",
      "Le temps CPU consommé par les processus d'arrière-plan",
      "La durée d'exécution de la requête la plus lente",
      "Le temps total passé par les sessions utilisateur dans la base, CPU et attentes comprises",
    ],
    correctIndexes: [3],
    explanation: "DB time additionne, pour toutes les sessions utilisateur actives, le temps CPU et le temps d'attente. C'est la mesure de référence de la charge : réduire DB time, c'est optimiser. Les processus d'arrière-plan en sont exclus.",
    topic: "Modèle de temps", difficulty: "medium",
  },
  {
    id: "tun-q3", track: "ocp-tuning", moduleId: "tun-session-1",
    question: "Quelles vues exposent le modèle de temps ? (Choisissez deux réponses.)",
    options: ["V$SYS_TIME_MODEL", "V$SESS_TIME_MODEL", "V$SQL_PLAN", "V$LOCK", "V$DATAFILE"],
    correctIndexes: [0, 1],
    explanation: "V$SYS_TIME_MODEL donne le modèle de temps au niveau de l'instance, V$SESS_TIME_MODEL au niveau de chaque session. Les trois autres vues décrivent des plans, des verrous et des fichiers.",
    topic: "Modèle de temps", difficulty: "medium",
  },
  {
    id: "tun-q4", track: "ocp-tuning", moduleId: "tun-session-1",
    question: "À quelle phase du cycle de vie l'optimisation coûte-t-elle le moins cher ?",
    options: [
      "Pendant la recette fonctionnelle",
      "À la conception du modèle de données et des accès",
      "Au premier incident de production",
      "Lors de la migration vers une nouvelle version",
    ],
    correctIndexes: [1],
    explanation: "Un modèle mal normalisé ou un chemin d'accès absent coûte quelques heures à corriger sur le papier, et des mois une fois l'application écrite et les données chargées. L'optimisation en production est toujours la plus contrainte.",
    topic: "Cycle de vie", difficulty: "easy",
  },
  {
    id: "tun-q5", track: "ocp-tuning", moduleId: "tun-session-1",
    question: "Un rapport indique 92 % de hit ratio sur le buffer cache. Que peut-on en conclure ?",
    options: [
      "Rien de fiable : un hit ratio élevé peut accompagner un système très lent",
      "Le buffer cache est correctement dimensionné",
      "Les entrées-sorties ne sont pas un problème",
      "Il faut réduire DB_CACHE_SIZE pour libérer de la mémoire",
    ],
    correctIndexes: [0],
    explanation: "Le hit ratio est un ratio, pas un temps. Une requête qui relit mille fois le même bloc par une jointure imbriquée inefficace affiche un excellent ratio tout en saturant le CPU. Seul le temps — DB time, événements d'attente — permet de conclure.",
    topic: "Indicateurs trompeurs", difficulty: "hard",
  },

  // ─── Session 2 — AWR, ASH et ADDM ───────────────────────────────────────
  {
    id: "tun-q6", track: "ocp-tuning", moduleId: "tun-session-2",
    question: "Quel est l'intervalle de capture AWR par défaut, et la rétention par défaut en 19c ?",
    options: [
      "15 minutes, conservées 14 jours",
      "30 minutes, conservées 7 jours",
      "60 minutes, conservées 30 jours",
      "60 minutes, conservées 8 jours",
    ],
    correctIndexes: [3],
    explanation: "Par défaut AWR capture un instantané toutes les 60 minutes et les conserve 8 jours. Les deux valeurs se modifient par DBMS_WORKLOAD_REPOSITORY.MODIFY_SNAPSHOT_SETTINGS.",
    topic: "AWR", difficulty: "medium",
  },
  {
    id: "tun-q7", track: "ocp-tuning", moduleId: "tun-session-2",
    question: "À quelle fréquence ASH échantillonne-t-il les sessions actives ?",
    options: [
      "Une fois toutes les 10 secondes",
      "Une fois par seconde",
      "À chaque commit",
      "Une fois par instantané AWR",
    ],
    correctIndexes: [1],
    explanation: "ASH prélève l'état de toutes les sessions actives chaque seconde dans un tampon circulaire de la SGA (V$ACTIVE_SESSION_HISTORY). Un dixième de ces échantillons est conservé sur disque dans DBA_HIST_ACTIVE_SESS_HISTORY.",
    topic: "ASH", difficulty: "medium",
  },
  {
    id: "tun-q8", track: "ocp-tuning", moduleId: "tun-session-2",
    question: "Un incident a duré trois minutes il y a deux heures. Quel outil permet de l'analyser ?",
    options: [
      "ADDM, qui analyse un intervalle entre deux instantanés",
      "AWR, dont l'intervalle est horaire",
      "ASH, qui échantillonne à la seconde",
      "Le Segment Advisor",
    ],
    correctIndexes: [2],
    explanation: "Un pic de trois minutes se dilue dans un instantané AWR d'une heure : ADDM, qui s'appuie sur AWR, ne le verra pas. ASH conserve la trace à la seconde et permet de cibler l'intervalle exact.",
    topic: "ASH vs AWR", difficulty: "hard",
  },
  {
    id: "tun-q9", track: "ocp-tuning", moduleId: "tun-session-2",
    question: "Quelles affirmations sont exactes concernant ADDM ? (Choisissez trois réponses.)",
    options: [
      "Il s'exécute automatiquement après chaque instantané AWR",
      "Il classe ses constats par impact sur DB time",
      "Il propose des recommandations chiffrées",
      "Il applique automatiquement ses recommandations",
      "Il remplace la collecte de statistiques",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "ADDM s'exécute après chaque instantané, ordonne ses constats par part de DB time et chiffre le gain attendu. Il ne modifie jamais rien de lui-même : la décision d'appliquer reste humaine.",
    topic: "ADDM", difficulty: "medium",
  },
  {
    id: "tun-q10", track: "ocp-tuning", moduleId: "tun-session-2",
    question: "À quoi sert une ligne de base AWR (AWR baseline) ?",
    options: [
      "Figer une période de référence pour comparer une charge future",
      "Sauvegarder les statistiques de l'optimiseur",
      "Empêcher la purge des fichiers d'archive",
      "Forcer un plan d'exécution donné",
    ],
    correctIndexes: [0],
    explanation: "Une ligne de base AWR conserve indéfiniment les instantanés d'une période représentative — la clôture mensuelle, par exemple — pour comparer un comportement futur à une référence connue. Elle échappe à la purge automatique.",
    topic: "Lignes de base AWR", difficulty: "medium",
  },
  {
    id: "tun-q11", track: "ocp-tuning", moduleId: "tun-session-2",
    question: "Quel paquetage permet de créer un instantané AWR à la demande ?",
    options: [
      "DBMS_STATS.GATHER_DATABASE_STATS",
      "DBMS_WORKLOAD_REPOSITORY.CREATE_SNAPSHOT",
      "DBMS_ADVISOR.CREATE_TASK",
      "DBMS_MONITOR.SESSION_TRACE_ENABLE",
    ],
    correctIndexes: [1],
    explanation: "DBMS_WORKLOAD_REPOSITORY gère l'ensemble d'AWR : CREATE_SNAPSHOT, DROP_SNAPSHOT_RANGE, MODIFY_SNAPSHOT_SETTINGS et CREATE_BASELINE. Encadrer un test par deux instantanés manuels est la bonne pratique.",
    topic: "AWR", difficulty: "easy",
  },
  {
    id: "tun-q12", track: "ocp-tuning", moduleId: "tun-session-2",
    question: "Quelle option est nécessaire pour utiliser AWR, ASH et ADDM ?",
    options: [
      "Aucune : ces outils sont inclus en Standard Edition",
      "L'option Tuning Pack seule",
      "L'option Diagnostics Pack de l'Enterprise Edition",
      "L'option Advanced Compression",
    ],
    correctIndexes: [2],
    explanation: "AWR, ASH et ADDM relèvent du Diagnostics Pack, facturé en supplément de l'Enterprise Edition. Le paramètre CONTROL_MANAGEMENT_PACK_ACCESS en contrôle l'usage. Sans cette licence, Statspack reste l'alternative gratuite.",
    topic: "Licences", difficulty: "hard",
  },

  // ─── Session 3 — Événements d'attente et surveillance ────────────────────
  {
    id: "tun-q13", track: "ocp-tuning", moduleId: "tun-session-3",
    question: "Que traduit l'événement d'attente « db file sequential read » ?",
    options: [
      "Une attente sur le journal de rétablissement",
      "Une lecture multiblocs, typiquement un balayage complet",
      "Une écriture du DBWn vers les fichiers de données",
      "Une lecture d'un bloc unique, typiquement un accès par index",
    ],
    correctIndexes: [3],
    explanation: "Malgré son nom, « sequential read » désigne la lecture d'un bloc à la fois — l'accès par index. C'est « db file scattered read » qui correspond à la lecture multiblocs d'un balayage complet. Le vocabulaire est contre-intuitif et tombe régulièrement à l'examen.",
    topic: "Événements d'attente", difficulty: "hard",
  },
  {
    id: "tun-q14", track: "ocp-tuning", moduleId: "tun-session-3",
    question: "Une session attend sur « log file sync ». Quelle est la cause la plus probable ?",
    options: [
      "Des commits trop fréquents ou un stockage lent pour les fichiers de journalisation",
      "Un buffer cache trop petit",
      "Des statistiques périmées",
      "Un balayage complet sur une grosse table",
    ],
    correctIndexes: [0],
    explanation: "« log file sync » mesure l'attente d'une session pendant que LGWR écrit le redo au COMMIT. Deux causes : trop de commits (une boucle qui valide ligne à ligne) ou un stockage lent pour les redo logs. Ni le cache ni les statistiques n'entrent en jeu.",
    topic: "Événements d'attente", difficulty: "medium",
  },
  {
    id: "tun-q15", track: "ocp-tuning", moduleId: "tun-session-3",
    question: "Quelles classes d'attente sont considérées comme systématiquement inactives (idle) ? (Choisissez deux réponses.)",
    options: ["Idle", "Network", "User I/O", "Concurrency", "Configuration"],
    correctIndexes: [0, 1],
    explanation: "La classe Idle regroupe les attentes d'une session au repos (SQL*Net message from client). La classe Network mesure les échanges réseau, souvent hors du périmètre de la base. Les trois autres classes décrivent des attentes réelles à analyser.",
    topic: "Classes d'attente", difficulty: "hard",
  },
  {
    id: "tun-q16", track: "ocp-tuning", moduleId: "tun-session-3",
    question: "Quelle vue donne l'attente en cours d'une session, à l'instant de l'interrogation ?",
    options: ["V$SYSTEM_EVENT", "V$SESSION_EVENT", "V$SESSION", "DBA_HIST_SNAPSHOT"],
    correctIndexes: [2],
    explanation: "Depuis la 10g, V$SESSION porte directement EVENT, WAIT_CLASS et STATE : c'est la photo instantanée. V$SESSION_EVENT cumule depuis la connexion, V$SYSTEM_EVENT depuis le démarrage de l'instance.",
    topic: "Vues de diagnostic", difficulty: "medium",
  },
  {
    id: "tun-q17", track: "ocp-tuning", moduleId: "tun-session-3",
    question: "Quel paquetage permet de définir un seuil d'alerte sur une métrique ?",
    options: [
      "DBMS_MONITOR.CLIENT_ID_TRACE_ENABLE",
      "DBMS_ALERT.SIGNAL",
      "DBMS_STATS.SET_TABLE_PREFS",
      "DBMS_SERVER_ALERT.SET_THRESHOLD",
    ],
    correctIndexes: [3],
    explanation: "DBMS_SERVER_ALERT.SET_THRESHOLD associe un seuil d'avertissement et un seuil critique à une métrique. Les alertes déclenchées apparaissent dans DBA_OUTSTANDING_ALERTS puis DBA_ALERT_HISTORY. DBMS_ALERT est un mécanisme applicatif sans rapport.",
    topic: "Seuils et alertes", difficulty: "medium",
  },
  {
    id: "tun-q18", track: "ocp-tuning", moduleId: "tun-session-3",
    question: "Une alerte avec état (stateful) disparaît de DBA_OUTSTANDING_ALERTS lorsque :",
    options: [
      "Un administrateur la supprime manuellement",
      "La condition qui l'a déclenchée cesse d'être vraie",
      "L'instance redémarre",
      "La rétention AWR expire",
    ],
    correctIndexes: [1],
    explanation: "Une alerte avec état — un tablespace à 90 % par exemple — suit une condition persistante : elle s'efface d'elle-même dès que la condition n'est plus vraie et rejoint l'historique. Une alerte sans état, elle, doit être effacée à la main.",
    topic: "Alertes", difficulty: "hard",
  },

  // ─── Session 4 — Optimiseur et plans d'exécution ────────────────────────
  {
    id: "tun-q19", track: "ocp-tuning", moduleId: "tun-session-4",
    question: "Dans quel ordre s'enchaînent les phases de traitement d'une instruction SQL ?",
    options: [
      "Analyse syntaxique, optimisation, génération de la source de ligne, exécution, extraction",
      "Optimisation, analyse syntaxique, exécution, extraction",
      "Analyse syntaxique, exécution, optimisation, extraction",
      "Génération du plan, analyse syntaxique, extraction, exécution",
    ],
    correctIndexes: [0],
    explanation: "Parse (syntaxe, sémantique, recherche dans le shared pool), puis optimisation par le CBO, puis génération du plan par le row source generator, puis exécution, et enfin fetch pour les requêtes. Un soft parse court-circuite l'optimisation.",
    topic: "Traitement SQL", difficulty: "medium",
  },
  {
    id: "tun-q20", track: "ocp-tuning", moduleId: "tun-session-4",
    question: "Quelle différence essentielle sépare EXPLAIN PLAN de DBMS_XPLAN.DISPLAY_CURSOR ?",
    options: [
      "Les deux produisent toujours le même résultat",
      "EXPLAIN PLAN est plus précis car il tient compte des variables de liaison",
      "DISPLAY_CURSOR ne fonctionne que sur les vues matérialisées",
      "EXPLAIN PLAN prédit un plan sans exécuter ; DISPLAY_CURSOR montre le plan réellement utilisé",
    ],
    correctIndexes: [3],
    explanation: "EXPLAIN PLAN prédit ce que l'optimiseur ferait, sans peuplement de variables de liaison ni exécution. DISPLAY_CURSOR lit le plan du curseur réellement exécuté, avec GATHER_PLAN_STATISTICS les lignes estimées et réelles. En diagnostic, c'est toujours DISPLAY_CURSOR qui fait foi.",
    topic: "Plans d'exécution", difficulty: "hard",
  },
  {
    id: "tun-q21", track: "ocp-tuning", moduleId: "tun-session-4",
    question: "Dans un plan obtenu avec le format ALLSTATS LAST, un écart important entre E-Rows et A-Rows indique :",
    options: [
      "Un problème de verrouillage",
      "Une estimation de cardinalité erronée, souvent due à des statistiques inadaptées",
      "Un manque d'espace dans la PGA",
      "Un plan adaptatif désactivé",
    ],
    correctIndexes: [1],
    explanation: "E-Rows est l'estimation de l'optimiseur, A-Rows le réel. Un facteur dix ou plus signale que l'optimiseur travaille sur une mauvaise image des données : statistiques périmées, corrélation entre colonnes, prédicat complexe. C'est le premier diagnostic à faire sur un plan.",
    topic: "Cardinalité", difficulty: "hard",
  },
  {
    id: "tun-q22", track: "ocp-tuning", moduleId: "tun-session-4",
    question: "Quelles affirmations sont exactes concernant les plans adaptatifs ? (Choisissez deux réponses.)",
    options: [
      "L'optimiseur peut changer de méthode de jointure pendant la première exécution",
      "Un collecteur de statistiques compte les lignes réelles au moment de l'exécution",
      "Ils remplacent les SQL plan baselines",
      "Ils sont désactivés par défaut en 19c",
    ],
    correctIndexes: [0, 1],
    explanation: "Un plan adaptatif embarque un sous-plan alternatif et un statistics collector : si le nombre réel de lignes franchit un seuil, l'optimiseur bascule de nested loops vers hash join en cours d'exécution. OPTIMIZER_ADAPTIVE_PLANS vaut TRUE par défaut en 19c.",
    topic: "Plans adaptatifs", difficulty: "hard",
  },
  {
    id: "tun-q23", track: "ocp-tuning", moduleId: "tun-session-4",
    question: "Qu'est-ce qu'une directive de plan SQL (SQL plan directive) ?",
    options: [
      "Un profil SQL généré par SQL Tuning Advisor",
      "Un plan figé imposé à une instruction",
      "Une note persistante indiquant à l'optimiseur d'utiliser un mécanisme supplémentaire sur un ensemble de colonnes",
      "Une contrainte d'intégrité sur les statistiques",
    ],
    correctIndexes: [2],
    explanation: "Une directive naît d'une erreur d'estimation répétée : l'optimiseur retient qu'un groupe de colonnes est mal estimé et déclenche de l'échantillonnage dynamique ou la création de statistiques étendues. Elle porte sur des colonnes, pas sur une instruction — contrairement au profil ou à la baseline.",
    topic: "Directives de plan", difficulty: "hard",
  },
  {
    id: "tun-q24", track: "ocp-tuning", moduleId: "tun-session-4",
    question: "Que fait la réoptimisation automatique (automatic reoptimization) ?",
    options: [
      "Elle corrige le plan lors des exécutions SUIVANTES, à partir des écarts constatés",
      "Elle change le plan en cours d'exécution",
      "Elle recollecte les statistiques de la table",
      "Elle invalide tout le shared pool",
    ],
    correctIndexes: [0],
    explanation: "À la différence d'un plan adaptatif, qui agit pendant l'exécution, la réoptimisation enregistre les écarts de cardinalité observés et les réutilise au prochain hard parse. La colonne IS_REOPTIMIZABLE de V$SQL signale un curseur concerné.",
    topic: "Réoptimisation", difficulty: "hard",
  },

  // ─── Session 5 — Statistiques de l'optimiseur ───────────────────────────
  {
    id: "tun-q25", track: "ocp-tuning", moduleId: "tun-session-5",
    question: "Quelle valeur de ESTIMATE_PERCENT est recommandée depuis la 11g ?",
    options: [
      "100, pour la précision maximale",
      "DBMS_STATS.AUTO_SAMPLE_SIZE",
      "10, comme compromis",
      "1, pour la rapidité",
    ],
    correctIndexes: [1],
    explanation: "AUTO_SAMPLE_SIZE s'appuie depuis la 11g sur un algorithme de hachage à passe unique qui donne la précision d'un échantillon à 100 % pour le coût d'un échantillon réduit. Fixer un pourcentage à la main est devenu contre-productif.",
    topic: "Collecte de statistiques", difficulty: "medium",
  },
  {
    id: "tun-q26", track: "ocp-tuning", moduleId: "tun-session-5",
    question: "À quoi sert un histogramme sur une colonne ?",
    options: [
      "Remplacer un index",
      "Accélérer les insertions",
      "Décrire une distribution inégale des valeurs pour affiner les estimations",
      "Compresser les données de la colonne",
    ],
    correctIndexes: [2],
    explanation: "Sans histogramme, l'optimiseur suppose les valeurs uniformément réparties. Sur une colonne STATUT où 99 % des lignes valent « clos », cette hypothèse produit une estimation absurde. L'histogramme décrit la distribution réelle.",
    topic: "Histogrammes", difficulty: "medium",
  },
  {
    id: "tun-q27", track: "ocp-tuning", moduleId: "tun-session-5",
    question: "Quels types d'histogrammes ont été introduits en 12c ? (Choisissez deux réponses.)",
    options: ["Hybrid", "Top-Frequency", "Frequency", "Height-Balanced", "Bitmap"],
    correctIndexes: [0, 1],
    explanation: "La 12c ajoute l'histogramme hybride — qui combine fréquence et hauteur équilibrée — et le top-frequency, qui ne retient que les valeurs dominantes. Frequency et height-balanced existaient déjà ; « bitmap » désigne un type d'index, pas d'histogramme.",
    topic: "Histogrammes", difficulty: "hard",
  },
  {
    id: "tun-q28", track: "ocp-tuning", moduleId: "tun-session-5",
    question: "Que permettent les statistiques étendues (extended statistics) ?",
    options: [
      "Étendre AWR aux bases de secours",
      "Conserver l'historique des statistiques plus longtemps",
      "Collecter les statistiques système",
      "Décrire la corrélation entre plusieurs colonnes ou une expression",
    ],
    correctIndexes: [3],
    explanation: "L'optimiseur suppose les prédicats indépendants : sur VILLE = 'Lyon' AND DEPARTEMENT = 69, il multiplie deux sélectivités et sous-estime massivement. Un groupe de colonnes créé par DBMS_STATS.CREATE_EXTENDED_STATS restitue la corrélation réelle.",
    topic: "Statistiques étendues", difficulty: "hard",
  },
  {
    id: "tun-q29", track: "ocp-tuning", moduleId: "tun-session-5",
    question: "Combien de temps l'historique des statistiques est-il conservé par défaut ?",
    options: ["31 jours", "8 jours", "7 jours", "90 jours"],
    correctIndexes: [0],
    explanation: "DBMS_STATS conserve 31 jours d'historique par défaut, ce qui permet DBMS_STATS.RESTORE_TABLE_STATS après une collecte qui a dégradé un plan. La valeur se lit par GET_STATS_HISTORY_RETENTION et se modifie par ALTER_STATS_HISTORY_RETENTION.",
    topic: "Historique des statistiques", difficulty: "hard",
  },
  {
    id: "tun-q30", track: "ocp-tuning", moduleId: "tun-session-5",
    question: "Quel paramètre contrôle le degré d'échantillonnage dynamique ?",
    options: [
      "OPTIMIZER_MODE",
      "OPTIMIZER_INDEX_COST_ADJ",
      "OPTIMIZER_DYNAMIC_SAMPLING",
      "DB_FILE_MULTIBLOCK_READ_COUNT",
    ],
    correctIndexes: [2],
    explanation: "OPTIMIZER_DYNAMIC_SAMPLING va de 0 à 11. La valeur 11 laisse l'optimiseur décider seul quand échantillonner à l'analyse — comportement retenu par l'échantillonnage adaptatif de la 12c et suivantes.",
    topic: "Paramètres de l'optimiseur", difficulty: "medium",
  },
  {
    id: "tun-q31", track: "ocp-tuning", moduleId: "tun-session-5",
    question: "Quelle tâche de maintenance automatique collecte les statistiques périmées ?",
    options: [
      "auto segment shrink",
      "auto space advisor",
      "sql tuning advisor",
      "auto optimizer stats collection",
    ],
    correctIndexes: [3],
    explanation: "Trois tâches s'exécutent dans la fenêtre de maintenance : auto optimizer stats collection, auto space advisor et sql tuning advisor. La première recollecte les statistiques des objets dont plus de 10 % des lignes ont changé.",
    topic: "Tâches automatiques", difficulty: "medium",
  },

  // ─── Session 6 — Conseillers et stabilité des plans ─────────────────────
  {
    id: "tun-q32", track: "ocp-tuning", moduleId: "tun-session-6",
    question: "Quelle est la différence entre un profil SQL et une SQL plan baseline ?",
    options: [
      "Le profil fige un plan ; la baseline corrige les estimations",
      "Le profil corrige les estimations de l'optimiseur ; la baseline fige un ensemble de plans acceptés",
      "Les deux figent le même plan, seul le nom diffère",
      "La baseline ne s'applique qu'aux vues matérialisées",
    ],
    correctIndexes: [1],
    explanation: "Un profil SQL fournit à l'optimiseur des facteurs de correction de cardinalité : le plan peut encore évoluer. Une baseline liste des plans explicitement acceptés et interdit tout nouveau plan tant qu'il n'est pas vérifié. Le profil guide, la baseline verrouille.",
    topic: "Profils et baselines", difficulty: "hard",
  },
  {
    id: "tun-q33", track: "ocp-tuning", moduleId: "tun-session-6",
    question: "Que recommande SQL Access Advisor ?",
    options: [
      "Des index, vues matérialisées et partitionnements pour une charge de travail",
      "Une réécriture de l'instruction SQL",
      "Un dimensionnement de la SGA",
      "Une stratégie de sauvegarde",
    ],
    correctIndexes: [0],
    explanation: "SQL Access Advisor raisonne sur des structures d'accès pour une charge complète : index, vues matérialisées, journaux de vues matérialisées, partitionnement. SQL Tuning Advisor, lui, travaille instruction par instruction.",
    topic: "Conseillers", difficulty: "medium",
  },
  {
    id: "tun-q34", track: "ocp-tuning", moduleId: "tun-session-6",
    question: "Quelles recommandations SQL Tuning Advisor peut-il produire ? (Choisissez trois réponses.)",
    options: [
      "Accepter un profil SQL",
      "Collecter des statistiques manquantes ou périmées",
      "Créer un index",
      "Augmenter la taille du buffer cache",
      "Modifier le mode d'archivage",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "SQL Tuning Advisor analyse une instruction et peut recommander un profil, des statistiques, un index ou une réécriture. Le dimensionnement mémoire relève du Memory Advisor, l'archivage n'a aucun rapport avec l'optimisation d'une requête.",
    topic: "SQL Tuning Advisor", difficulty: "medium",
  },
  {
    id: "tun-q35", track: "ocp-tuning", moduleId: "tun-session-6",
    question: "Que fait DBMS_SPM.EVOLVE_SQL_PLAN_BASELINE ?",
    options: [
      "Recollecte les statistiques des objets concernés",
      "Supprime toutes les baselines d'un schéma",
      "Force l'utilisation du dernier plan trouvé",
      "Vérifie qu'un nouveau plan est plus performant avant de l'accepter",
    ],
    correctIndexes: [3],
    explanation: "Quand l'optimiseur trouve un plan absent de la baseline, il l'enregistre comme non accepté. EVOLVE l'exécute et le compare au plan accepté : il n'est promu que s'il fait mieux. C'est ce qui empêche une régression de plan de gagner silencieusement.",
    topic: "SQL Plan Management", difficulty: "hard",
  },

  // ─── Session 7 — Mémoire de l'instance ──────────────────────────────────
  {
    id: "tun-q36", track: "ocp-tuning", moduleId: "tun-session-7",
    question: "Quel paramètre active la gestion automatique de la mémoire (AMM), SGA et PGA confondues ?",
    options: ["SGA_TARGET", "MEMORY_TARGET", "PGA_AGGREGATE_TARGET", "DB_CACHE_SIZE"],
    correctIndexes: [1],
    explanation: "MEMORY_TARGET pilote AMM et arbitre entre SGA et PGA. SGA_TARGET seul active ASMM, qui n'ajuste que les composants de la SGA. PGA_AGGREGATE_TARGET plafonne la mémoire de travail des sessions.",
    topic: "Gestion mémoire", difficulty: "medium",
  },
  {
    id: "tun-q37", track: "ocp-tuning", moduleId: "tun-session-7",
    question: "Quelle vue chiffre le gain attendu d'un buffer cache plus grand ?",
    options: [
      "V$PGA_TARGET_ADVICE",
      "V$SGA_DYNAMIC_COMPONENTS",
      "V$DB_CACHE_ADVICE",
      "V$SHARED_POOL_ADVICE",
    ],
    correctIndexes: [2],
    explanation: "V$DB_CACHE_ADVICE simule plusieurs tailles de cache et donne, pour chacune, le nombre de lectures physiques qui seraient évitées. C'est un tableau de décision chiffré, à préférer au hit ratio.",
    topic: "Conseillers mémoire", difficulty: "medium",
  },
  {
    id: "tun-q38", track: "ocp-tuning", moduleId: "tun-session-7",
    question: "Une charge décisionnelle produit beaucoup de tris sur disque. Quel levier agir en priorité ?",
    options: [
      "Augmenter PGA_AGGREGATE_TARGET",
      "Augmenter DB_CACHE_SIZE",
      "Augmenter SHARED_POOL_SIZE",
      "Réduire LOG_BUFFER",
    ],
    correctIndexes: [0],
    explanation: "Les tris, hachages et créations d'index consomment la mémoire de travail des sessions, gouvernée par PGA_AGGREGATE_TARGET. Un débordement se lit dans V$SQL_WORKAREA_HISTOGRAM (passes multiples) et dans les attentes « direct path read temp ».",
    topic: "PGA", difficulty: "medium",
  },
  {
    id: "tun-q39", track: "ocp-tuning", moduleId: "tun-session-7",
    question: "Quelle est la conséquence d'un shared pool sous-dimensionné ?",
    options: [
      "Des lectures physiques supplémentaires sur les tables",
      "Des hard parses excessifs et des erreurs ORA-04031",
      "Des tris sur disque",
      "Un ralentissement du DBWn",
    ],
    correctIndexes: [1],
    explanation: "Le shared pool héberge le library cache et le dictionnaire. Trop petit, il évince les curseurs, ce qui force à réanalyser en permanence et peut produire ORA-04031. L'absence de variables de liaison produit le même symptôme sans que la taille soit en cause.",
    topic: "Shared pool", difficulty: "medium",
  },

  // ─── Session 8 — Entrées-sorties et concurrence ─────────────────────────
  {
    id: "tun-q40", track: "ocp-tuning", moduleId: "tun-session-8",
    question: "Quel outil mesure la capacité d'entrées-sorties du stockage indépendamment de la charge SQL ?",
    options: [
      "DBMS_ADVISOR.QUICK_TUNE",
      "DBMS_STATS.GATHER_SYSTEM_STATS",
      "DBMS_RESOURCE_MANAGER.CALIBRATE_IO",
      "DBMS_MONITOR.DATABASE_TRACE_ENABLE",
    ],
    correctIndexes: [2],
    explanation: "CALIBRATE_IO soumet le stockage à une charge de lecture aléatoire et séquentielle, et renvoie IOPS maximaux, débit et latence. Les résultats alimentent V$IO_CALIBRATION_STATUS et servent de référence objective.",
    topic: "Entrées-sorties", difficulty: "hard",
  },
  {
    id: "tun-q41", track: "ocp-tuning", moduleId: "tun-session-8",
    question: "Un événement « buffer busy waits » élevé sur un segment indique :",
    options: [
      "Un shared pool saturé",
      "Un disque défaillant",
      "Des statistiques périmées",
      "Plusieurs sessions se disputant le même bloc en mémoire",
    ],
    correctIndexes: [3],
    explanation: "Ce sont des blocs chauds : bloc d'en-tête de segment, dernier bloc d'un index sur clé croissante, ligne de compteur unique. Les remèdes portent sur la structure — index inversé, séquence en cache, ASSM, plus de freelists — pas sur le matériel.",
    topic: "Concurrence", difficulty: "hard",
  },
  {
    id: "tun-q42", track: "ocp-tuning", moduleId: "tun-session-8",
    question: "Que traduit l'attente « enq: TX - row lock contention » ?",
    options: [
      "Une session attend qu'une autre valide ou annule sa transaction sur la même ligne",
      "Un verrou sur la définition d'une table",
      "Une saturation du journal de rétablissement",
      "Un blocage sur le fichier de contrôle",
    ],
    correctIndexes: [0],
    explanation: "Le verrou TX en mode exclusif signale un conflit ligne à ligne : la session bloquée attend le COMMIT ou le ROLLBACK de la bloquante. V$SESSION.BLOCKING_SESSION désigne directement le coupable. Un verrou sur la définition d'objet serait un enq: TM.",
    topic: "Verrouillage", difficulty: "medium",
  },

  // ─── Session 9 — Statspack, traces et surveillance temps réel ───────────
  {
    id: "tun-q43", track: "ocp-tuning", moduleId: "tun-session-9",
    question: "Dans quel cas Statspack reste-t-il pertinent en 19c ?",
    options: [
      "Lorsque la base dépasse 10 To",
      "Lorsque la base est en mode NOARCHIVELOG",
      "Lorsque le Diagnostics Pack n'est pas sous licence",
      "Lorsque la base est une base de secours",
    ],
    correctIndexes: [2],
    explanation: "Statspack est gratuit et livré avec la base : il reste la seule instrumentation historique légale quand AWR — donc le Diagnostics Pack — n'est pas acquis. Il s'installe par spcreate.sql sous l'utilisateur PERFSTAT.",
    topic: "Statspack", difficulty: "medium",
  },
  {
    id: "tun-q44", track: "ocp-tuning", moduleId: "tun-session-9",
    question: "Quel niveau de trace 10046 inclut à la fois les valeurs des variables de liaison et les événements d'attente ?",
    options: ["Niveau 1", "Niveau 4", "Niveau 8", "Niveau 12"],
    correctIndexes: [3],
    explanation: "Niveau 1 : trace de base. Niveau 4 : ajoute les variables de liaison. Niveau 8 : ajoute les événements d'attente. Niveau 12 : les deux, soit 4 + 8. C'est le niveau retenu pour un diagnostic complet.",
    topic: "SQL Trace", difficulty: "hard",
  },
  {
    id: "tun-q45", track: "ocp-tuning", moduleId: "tun-session-9",
    question: "À partir de quel seuil une instruction est-elle automatiquement suivie par Real-Time SQL Monitoring ?",
    options: [
      "1 seconde de temps écoulé",
      "5 secondes de CPU ou d'entrées-sorties, ou une exécution en parallèle",
      "30 secondes de temps écoulé",
      "Dès qu'elle lit plus de 1 000 blocs",
    ],
    correctIndexes: [1],
    explanation: "Le suivi démarre seul dès qu'une instruction consomme 5 secondes de CPU ou d'E/S, ou dès qu'elle s'exécute en parallèle. Le hint /*+ MONITOR */ le force sur une instruction plus courte. Les données se lisent dans V$SQL_MONITOR.",
    topic: "SQL Monitoring", difficulty: "hard",
  },
  {
    id: "tun-q46", track: "ocp-tuning", moduleId: "tun-session-9",
    question: "Que permet DBMS_SQL_MONITOR.BEGIN_OPERATION ?",
    options: [
      "Regrouper plusieurs instructions en une opération suivie de bout en bout",
      "Forcer un plan d'exécution",
      "Créer un instantané AWR",
      "Activer la trace pour un service",
    ],
    correctIndexes: [0],
    explanation: "BEGIN_OPERATION / END_OPERATION délimitent une opération de base de données composite — un batch nocturne, un chargement en plusieurs étapes — et permettent d'obtenir un rapport unique couvrant l'ensemble, au lieu de rapports séparés par instruction.",
    topic: "Database Operations Monitoring", difficulty: "hard",
  },
  {
    id: "tun-q47", track: "ocp-tuning", moduleId: "tun-session-9",
    question: "Quel utilitaire met en forme un fichier de trace brut produit par SQL Trace ?",
    options: ["expdp", "adrci", "orapwd", "tkprof"],
    correctIndexes: [3],
    explanation: "tkprof transforme la trace brute en rapport lisible, avec les compteurs parse/execute/fetch, le temps écoulé et les attentes. adrci navigue dans le référentiel de diagnostic, sans mise en forme des traces SQL.",
    topic: "SQL Trace", difficulty: "easy",
  },

  // ─── Session 10 — In-Memory et Result Cache ─────────────────────────────
  {
    id: "tun-q48", track: "ocp-tuning", moduleId: "tun-session-10",
    question: "Quel paramètre active le magasin de colonnes In-Memory ?",
    options: ["MEMORY_TARGET", "INMEMORY_SIZE", "DB_CACHE_SIZE", "RESULT_CACHE_MAX_SIZE"],
    correctIndexes: [1],
    explanation: "INMEMORY_SIZE réserve une zone dédiée dans la SGA, distincte du buffer cache. Le paramètre n'est pas dynamique à la baisse et exige un redémarrage lors de la première activation. L'option Database In-Memory est facturée séparément.",
    topic: "In-Memory", difficulty: "medium",
  },
  {
    id: "tun-q49", track: "ocp-tuning", moduleId: "tun-session-10",
    question: "Quelles affirmations sont exactes concernant le magasin de colonnes In-Memory ? (Choisissez trois réponses.)",
    options: [
      "Il stocke les données par colonne, en plus du format ligne sur disque",
      "Il accélère les analyses balayant beaucoup de lignes et peu de colonnes",
      "Il ne remplace pas les index pour les accès à une ligne unique",
      "Il rend les fichiers de données inutiles",
      "Il s'active uniquement au niveau de la base entière",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "In-Memory duplique les données au format colonne en mémoire — le format ligne persiste sur disque, inchangé. Il excelle sur les balayages analytiques, reste inutile pour un accès par clé primaire, et s'active table par table, partition par partition.",
    topic: "In-Memory", difficulty: "hard",
  },
  {
    id: "tun-q50", track: "ocp-tuning", moduleId: "tun-session-10",
    question: "Quelle valeur de RESULT_CACHE_MODE met en cache uniquement les requêtes portant le hint RESULT_CACHE ?",
    options: ["AUTO", "FORCE", "MANUAL", "NONE"],
    correctIndexes: [2],
    explanation: "MANUAL est la valeur par défaut : seules les requêtes annotées /*+ RESULT_CACHE */ sont mises en cache. FORCE tente de tout mettre en cache et provoque presque toujours une contention sur le latch « Result Cache: RC Latch ».",
    topic: "Result Cache", difficulty: "medium",
  },
  {
    id: "tun-q51", track: "ocp-tuning", moduleId: "tun-session-10",
    question: "Quand une entrée du result cache est-elle invalidée ?",
    options: [
      "Dès qu'une transaction modifie l'un des objets dont dépend le résultat",
      "À chaque instantané AWR",
      "Au bout d'une heure",
      "Seulement au redémarrage de l'instance",
    ],
    correctIndexes: [0],
    explanation: "L'invalidation est immédiate et par dépendance : tout DML validé sur une table source rend inutilisables les résultats qui en dépendent. C'est pourquoi le result cache convient aux tables de référence peu modifiées, pas aux tables transactionnelles.",
    topic: "Result Cache", difficulty: "hard",
  },
];
