import type { GlossaryTerm, OracleFunction } from "./types";

export const glossary: GlossaryTerm[] = [
  { term: "ACL (Access Control List)", definition: "Liste contrôlant les permissions d'accès aux objets.", category: "Sécurité" },
  { term: "Aggregate Function", definition: "Fonction opérant sur un ensemble de lignes pour retourner une valeur unique (COUNT, SUM, AVG, MIN, MAX).", category: "Fonctions", example: "SELECT AVG(salary) FROM employees;" },
  { term: "Alias", definition: "Nom alternatif pour une table ou colonne dans une requête.", category: "SQL", example: "SELECT e.first_name FROM employees e;" },
  { term: "Analytic Function", definition: "Fonction calculant des valeurs sur un ensemble de lignes liées (fenêtre) sans regrouper.", category: "Fonctions", example: "RANK() OVER (ORDER BY salary DESC)" },
  { term: "ANSI", definition: "American National Standards Institute. Définit les standards SQL.", category: "Standard" },
  { term: "BFILE", definition: "Type pour stocker des références à des fichiers externes LOB.", category: "Types" },
  { term: "BLOB", definition: "Binary Large Object. Type pour données binaires jusqu'à 4 GB.", category: "Types" },
  { term: "Cartesian Product", definition: "Résultat d'un CROSS JOIN : chaque ligne de A combinée avec chaque ligne de B.", category: "JOIN" },
  { term: "CHECK Constraint", definition: "Contrainte vérifiant qu'une condition est vraie pour chaque ligne.", category: "Contraintes" },
  { term: "CLOB", definition: "Character Large Object. Type pour texte long jusqu'à 4 GB.", category: "Types" },
  { term: "Cluster", definition: "Groupe de tables stockées physiquement ensemble pour optimiser les jointures.", category: "Structure" },
  { term: "COMMIT", definition: "Valide définitivement toutes les modifications d'une transaction.", category: "TCL" },
  { term: "Correlated Subquery", definition: "Sous-requête référençant la requête externe, ré-exécutée pour chaque ligne.", category: "Subquery" },
  { term: "CYCLE", definition: "Option de séquence qui recommence à START WITH après MAXVALUE.", category: "Séquence" },
  { term: "Data Dictionary", definition: "Ensemble de vues contenant les métadonnées de la base.", category: "Dictionnaire" },
  { term: "DDL", definition: "Data Definition Language. Commandes définissant la structure (CREATE, ALTER, DROP, TRUNCATE).", category: "Catégorie" },
  { term: "DCL", definition: "Data Control Language. Commandes gérant les droits (GRANT, REVOKE).", category: "Catégorie" },
  { term: "DML", definition: "Data Manipulation Language. Commandes manipulant les données (INSERT, UPDATE, DELETE, MERGE).", category: "Catégorie" },
  { term: "DQL", definition: "Data Query Language. Sous-catégorie contenant uniquement SELECT.", category: "Catégorie" },
  { term: "DECODE", definition: "Fonction Oracle de type IF/THEN/ELSE. Spécifique Oracle, préférez CASE.", category: "Fonctions" },
  { term: "DISTINCT", definition: "Clause éliminant les doublons du résultat.", category: "SELECT" },
  { term: "Equi-Join", definition: "Jointure basée sur l'égalité entre colonnes de deux tables.", category: "JOIN" },
  { term: "EXISTS", definition: "Opérateur testant si une sous-requête retourne au moins une ligne.", category: "Subquery" },
  { term: "FETCH FIRST", definition: "Clause limitant le nombre de lignes retournées (Oracle 12c+).", category: "SELECT" },
  { term: "Foreign Key", definition: "Colonne référençant la clé primaire d'une autre table.", category: "Contraintes" },
  { term: "FULL OUTER JOIN", definition: "Jointure retournant toutes les lignes des deux tables, avec NULL si pas de correspondance.", category: "JOIN" },
  { term: "GROUP BY", definition: "Clause regroupant les lignes par valeurs communes pour les agrégations.", category: "Agrégation" },
  { term: "HAVING", definition: "Clause filtrant les groupes après GROUP BY. Peut utiliser les fonctions d'agrégation.", category: "Agrégation" },
  { term: "Index", definition: "Structure accélérant la recherche de données. Ralentit les écritures.", category: "Performance" },
  { term: "INNER JOIN", definition: "Jointure ne retournant que les lignes avec correspondance dans les deux tables.", category: "JOIN" },
  { term: "INSTR", definition: "Fonction retournant la position d'une sous-chaîne (base 1, 0 si non trouvé).", category: "Fonctions" },
  { term: "INTERSECT", definition: "Opérateur ensembliste retournant les lignes communes à deux requêtes.", category: "Set Operator" },
  { term: "LEFT JOIN", definition: "Jointure gardant toutes les lignes de gauche, NULL à droite si pas de match.", category: "JOIN" },
  { term: "LIKE", definition: "Opérateur de pattern matching avec % (0-N) et _ (1 caractère).", category: "Opérateur" },
  { term: "MINUS", definition: "Opérateur retournant les lignes du premier SELECT non dans le second.", category: "Set Operator" },
  { term: "NATURAL JOIN", definition: "Jointure automatique sur toutes les colonnes de même nom. Dangereux.", category: "JOIN" },
  { term: "NEXTVAL", definition: "Pseudo-colonne de séquence retournant la valeur suivante.", category: "Séquence" },
  { term: "NOT NULL", definition: "Contrainte empêchant les valeurs NULL. Niveau colonne uniquement.", category: "Contraintes" },
  { term: "NVL", definition: "Fonction remplaçant NULL par une valeur. 2 arguments uniquement.", category: "Fonctions" },
  { term: "COALESCE", definition: "Fonction retournant la première valeur non-NULL. N arguments, standard SQL.", category: "Fonctions" },
  { term: "NULLIF", definition: "Fonction retournant NULL si deux valeurs sont égales.", category: "Fonctions" },
  { term: "Oracle Database", definition: "SGBD relationnel d'Oracle Corporation. Un des plus utilisés en entreprise.", category: "Général" },
  { term: "ORDER BY", definition: "Clause triant le résultat. Dernière clause exécutée.", category: "SELECT" },
  { term: "Outer Join", definition: "Jointure incluant les lignes sans correspondance (LEFT, RIGHT, FULL).", category: "JOIN" },
  { term: "PARTITION BY", definition: "Clause des fonctions analytiques définissant le groupe de lignes.", category: "Analytic" },
  { term: "Primary Key", definition: "Colonne identifiant de manière unique chaque ligne. NOT NULL + UNIQUE.", category: "Contraintes" },
  { term: "ROLLBACK", definition: "Annule toutes les modifications d'une transaction non validée.", category: "TCL" },
  { term: "ROWNUM", definition: "Pseudo-colonne attribuant un numéro à chaque ligne. Assigné avant ORDER BY.", category: "Pseudo-colonne" },
  { term: "ROWID", definition: "Pseudo-colonne identifiant physiquement une ligne dans la base.", category: "Pseudo-colonne" },
  { term: "SAVEPOINT", definition: "Point de sauvegarde intermédiaire dans une transaction.", category: "TCL" },
  { term: "Schema", definition: "Collection d'objets appartenant à un utilisateur.", category: "Structure" },
  { term: "SELECT", definition: "Commande interrogant la base pour récupérer des données.", category: "DQL" },
  { term: "Self Join", definition: "Jointure d'une table avec elle-même via des alias différents.", category: "JOIN" },
  { term: "Sequence", definition: "Objet générant des nombres séquentiels uniques.", category: "Objet" },
  { term: "SUBSTR", definition: "Fonction extrayant une sous-chaîne. Positions en base 1, négatives depuis la fin.", category: "Fonctions" },
  { term: "Synonym", definition: "Alias pour un objet de la base, simplifiant l'accès.", category: "Objet" },
  { term: "SYSDATE", definition: "Fonction retournant la date et l'heure actuelles.", category: "Fonctions" },
  { term: "TCL", definition: "Transaction Control Language. Commandes gérant les transactions (COMMIT, ROLLBACK, SAVEPOINT).", category: "Catégorie" },
  { term: "TO_CHAR", definition: "Fonction convertissant un nombre ou date en chaîne avec format.", category: "Fonctions" },
  { term: "TO_DATE", definition: "Fonction convertissant une chaîne en date avec format.", category: "Fonctions" },
  { term: "TO_NUMBER", definition: "Fonction convertissant une chaîne en nombre avec format.", category: "Fonctions" },
  { term: "TRUNCATE", definition: "Commande DDL vidant une table. Ultra-rapide, non annulable.", category: "DDL" },
  { term: "UNION", definition: "Opérateur combinant deux requêtes, éliminant les doublons.", category: "Set Operator" },
  { term: "UNION ALL", definition: "Opérateur combinant deux requêtes, conservant les doublons. Plus rapide.", category: "Set Operator" },
  { term: "Unique Constraint", definition: "Contrainte garantissant l'unicité. NULL autorisé (contrairement à PK).", category: "Contraintes" },
  { term: "USING", definition: "Clause de jointure sur des colonnes de même nom. Plus sûr que NATURAL JOIN.", category: "JOIN" },
  { term: "VARCHAR2", definition: "Type chaîne de caractères de longueur variable. Préférer à CHAR.", category: "Types" },
  { term: "View", definition: "Requête stockée se présentant comme une table virtuelle.", category: "Objet" },
  { term: "WHERE", definition: "Clause filtrant les lignes. S'exécute avant GROUP BY.", category: "SELECT" },
  { term: "WITH", definition: "Clause définissant des sous-requêtes réutilisables (CTE).", category: "SELECT" },
  { term: "Window Function", definition: "Voir Analytic Function. Fonction calculant sur un ensemble de lignes liées.", category: "Fonctions" },
  { term: "EXPLAIN PLAN", definition: "Commande générant le plan d'exécution d'une requête.", category: "Performance" },
  { term: "Materialized View", definition: "Vue stockée physiquement, rafraîchie périodiquement.", category: "Objet" },
  { term: "Flashback", definition: "Fonctionnalité permettant de restaurer des objets supprimés (recycle bin).", category: "Récupération" },
  { term: "Pseudocolumn", definition: "Colonne virtuelle comme ROWNUM, ROWID, NEXTVAL, CURRVAL.", category: "Concept" },
  { term: "Dual", definition: "Table virtuelle d'une seule ligne, utilisée pour les calculs.", category: "Table", example: "SELECT 1+1 FROM dual;" },
];

export const oracleFunctions: OracleFunction[] = [
  {
    name: "NVL",
    category: "NULL",
    syntax: "NVL(expr, replacement)",
    description: "Remplace NULL par une valeur de remplacement. Accepte exactement 2 arguments.",
    example: "SELECT NVL(commission, 0) FROM employees;",
    result: "0 (si commission est NULL)",
  },
  {
    name: "NVL2",
    category: "NULL",
    syntax: "NVL2(expr, if_not_null, if_null)",
    description: "Retourne if_not_null si expr n'est pas NULL, sinon if_null.",
    example: "SELECT NVL2(comm, comm, 0) FROM employees;",
    result: "valeur de comm si non-NULL, sinon 0",
  },
  {
    name: "COALESCE",
    category: "NULL",
    syntax: "COALESCE(expr1, expr2, ...)",
    description: "Retourne la première valeur non-NULL. Standard SQL, N arguments, short-circuit.",
    example: "SELECT COALESCE(phone, mobile, email) FROM employees;",
    result: "première valeur non-NULL",
  },
  {
    name: "NULLIF",
    category: "NULL",
    syntax: "NULLIF(expr1, expr2)",
    description: "Retourne NULL si expr1 = expr2, sinon expr1. Utile pour éviter division par zéro.",
    example: "SELECT NULLIF(count, 0) FROM stats;",
    result: "NULL si count = 0",
  },
  {
    name: "DECODE",
    category: "Conditionnel",
    syntax: "DECODE(expr, val1, result1, val2, result2, ..., default)",
    description: "IF/THEN/ELSE spécifique Oracle. Préférez CASE (standard SQL).",
    example: "SELECT DECODE(dept, 10, 'IT', 20, 'HR', 'Autre') FROM emp;",
    result: "'IT' si dept=10, 'HR' si dept=20, sinon 'Autre'",
  },
  {
    name: "CASE",
    category: "Conditionnel",
    syntax: "CASE WHEN cond1 THEN result1 WHEN cond2 THEN result2 ELSE default END",
    description: "Expression conditionnelle standard SQL. Plus puissante que DECODE.",
    example: "SELECT CASE WHEN salary > 5000 THEN 'High' ELSE 'Low' END FROM emp;",
    result: "'High' ou 'Low'",
  },
  {
    name: "UPPER",
    category: "Caractères",
    syntax: "UPPER(string)",
    description: "Convertit une chaîne en majuscules.",
    example: "SELECT UPPER('oracle') FROM dual;",
    result: "ORACLE",
  },
  {
    name: "LOWER",
    category: "Caractères",
    syntax: "LOWER(string)",
    description: "Convertit une chaîne en minuscules.",
    example: "SELECT LOWER('ORACLE') FROM dual;",
    result: "oracle",
  },
  {
    name: "INITCAP",
    category: "Caractères",
    syntax: "INITCAP(string)",
    description: "Met la première lettre de chaque mot en majuscule.",
    example: "SELECT INITCAP('hello world') FROM dual;",
    result: "Hello World",
  },
  {
    name: "SUBSTR",
    category: "Caractères",
    syntax: "SUBSTR(string, position, length)",
    description: "Extrait une sous-chaîne. Position en base 1, négative depuis la fin.",
    example: "SELECT SUBSTR('Oracle', 1, 3) FROM dual;",
    result: "Ora",
  },
  {
    name: "LENGTH",
    category: "Caractères",
    syntax: "LENGTH(string)",
    description: "Retourne la longueur d'une chaîne.",
    example: "SELECT LENGTH('Oracle') FROM dual;",
    result: "6",
  },
  {
    name: "INSTR",
    category: "Caractères",
    syntax: "INSTR(string, substring, start, occurrence)",
    description: "Retourne la position d'une sous-chaîne. Base 1, 0 si non trouvé.",
    example: "SELECT INSTR('Oracle', 'cl') FROM dual;",
    result: "4",
  },
  {
    name: "LPAD",
    category: "Caractères",
    syntax: "LPAD(string, length, pad_char)",
    description: "Remplit à gauche jusqu'à la longueur spécifiée.",
    example: "SELECT LPAD('5', 3, '0') FROM dual;",
    result: "005",
  },
  {
    name: "RPAD",
    category: "Caractères",
    syntax: "RPAD(string, length, pad_char)",
    description: "Remplit à droite jusqu'à la longueur spécifiée.",
    example: "SELECT RPAD('5', 3, '0') FROM dual;",
    result: "500",
  },
  {
    name: "TRIM",
    category: "Caractères",
    syntax: "TRIM([LEADING|TRAILING|BOTH] [char FROM] string)",
    description: "Supprime les caractères spécifiés (espaces par défaut).",
    example: "SELECT TRIM('  hi  ') FROM dual;",
    result: "hi",
  },
  {
    name: "REPLACE",
    category: "Caractères",
    syntax: "REPLACE(string, search, replacement)",
    description: "Remplace toutes les occurrences d'une sous-chaîne.",
    example: "SELECT REPLACE('ABC', 'B', 'X') FROM dual;",
    result: "AXC",
  },
  {
    name: "ROUND",
    category: "Numérique",
    syntax: "ROUND(number, decimals)",
    description: "Arrondit un nombre à un nombre de décimales spécifié.",
    example: "SELECT ROUND(45.927, 2) FROM dual;",
    result: "45.93",
  },
  {
    name: "TRUNC",
    category: "Numérique",
    syntax: "TRUNC(number, decimals)",
    description: "Tronque un nombre vers zéro à un nombre de décimales.",
    example: "SELECT TRUNC(45.927, 2) FROM dual;",
    result: "45.92",
  },
  {
    name: "MOD",
    category: "Numérique",
    syntax: "MOD(dividend, divisor)",
    description: "Retourne le reste de la division (modulo).",
    example: "SELECT MOD(10, 3) FROM dual;",
    result: "1",
  },
  {
    name: "CEIL",
    category: "Numérique",
    syntax: "CEIL(number)",
    description: "Retourne le plus petit entier supérieur ou égal.",
    example: "SELECT CEIL(45.1) FROM dual;",
    result: "46",
  },
  {
    name: "FLOOR",
    category: "Numérique",
    syntax: "FLOOR(number)",
    description: "Retourne le plus grand entier inférieur ou égal.",
    example: "SELECT FLOOR(45.9) FROM dual;",
    result: "45",
  },
  {
    name: "ABS",
    category: "Numérique",
    syntax: "ABS(number)",
    description: "Retourne la valeur absolue.",
    example: "SELECT ABS(-5) FROM dual;",
    result: "5",
  },
  {
    name: "POWER",
    category: "Numérique",
    syntax: "POWER(base, exponent)",
    description: "Retourne base élevée à la puissance exponent.",
    example: "SELECT POWER(2, 10) FROM dual;",
    result: "1024",
  },
  {
    name: "SYSDATE",
    category: "Date",
    syntax: "SYSDATE",
    description: "Retourne la date et l'heure actuelles du serveur.",
    example: "SELECT SYSDATE FROM dual;",
    result: "03-JUL-26",
  },
  {
    name: "ADD_MONTHS",
    category: "Date",
    syntax: "ADD_MONTHS(date, n)",
    description: "Ajoute n mois à une date.",
    example: "SELECT ADD_MONTHS(SYSDATE, 6) FROM dual;",
    result: "date + 6 mois",
  },
  {
    name: "MONTHS_BETWEEN",
    category: "Date",
    syntax: "MONTHS_BETWEEN(date1, date2)",
    description: "Retourne le nombre de mois entre deux dates.",
    example: "SELECT MONTHS_BETWEEN(SYSDATE, hire_date) FROM emp;",
    result: "12.3 (mois décimaux)",
  },
  {
    name: "LAST_DAY",
    category: "Date",
    syntax: "LAST_DAY(date)",
    description: "Retourne le dernier jour du mois de la date.",
    example: "SELECT LAST_DAY(SYSDATE) FROM dual;",
    result: "31-JUL-26",
  },
  {
    name: "NEXT_DAY",
    category: "Date",
    syntax: "NEXT_DAY(date, day_of_week)",
    description: "Retourne la date du prochain jour de la semaine spécifié.",
    example: "SELECT NEXT_DAY(SYSDATE, 'FRIDAY') FROM dual;",
    result: "prochain vendredi",
  },
  {
    name: "EXTRACT",
    category: "Date",
    syntax: "EXTRACT(component FROM date)",
    description: "Extrait une composante (YEAR, MONTH, DAY, etc.) d'une date.",
    example: "SELECT EXTRACT(YEAR FROM SYSDATE) FROM dual;",
    result: "2026",
  },
  {
    name: "TO_CHAR",
    category: "Conversion",
    syntax: "TO_CHAR(value, format)",
    description: "Convertit un nombre ou une date en chaîne avec format.",
    example: "SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY') FROM dual;",
    result: "03/07/2026",
  },
  {
    name: "TO_DATE",
    category: "Conversion",
    syntax: "TO_DATE(string, format)",
    description: "Convertit une chaîne en date avec format.",
    example: "SELECT TO_DATE('2026-07-03', 'YYYY-MM-DD') FROM dual;",
    result: "03-JUL-26",
  },
  {
    name: "TO_NUMBER",
    category: "Conversion",
    syntax: "TO_NUMBER(string, format)",
    description: "Convertit une chaîne en nombre avec format.",
    example: "SELECT TO_NUMBER('1,234.56', '999,999.99') FROM dual;",
    result: "1234.56",
  },
  {
    name: "REGEXP_LIKE",
    category: "Regex",
    syntax: "REGEXP_LIKE(string, pattern, match_mode)",
    description: "Teste si une chaîne correspond à un pattern regex. Utilisable dans WHERE.",
    example: "SELECT * FROM emp WHERE REGEXP_LIKE(name, '^A');",
    result: "lignes où name commence par A",
  },
  {
    name: "REGEXP_SUBSTR",
    category: "Regex",
    syntax: "REGEXP_SUBSTR(string, pattern, pos, occ, mode, subexpr)",
    description: "Extrait la sous-chaîne correspondant au pattern.",
    example: "SELECT REGEXP_SUBSTR('abc123', '[0-9]+') FROM dual;",
    result: "123",
  },
  {
    name: "REGEXP_REPLACE",
    category: "Regex",
    syntax: "REGEXP_REPLACE(string, pattern, replacement)",
    description: "Remplace les occurrences d'un pattern regex.",
    example: "SELECT REGEXP_REPLACE('abc123', '[0-9]', '#') FROM dual;",
    result: "abc###",
  },
  {
    name: "RANK",
    category: "Analytique",
    syntax: "RANK() OVER (PARTITION BY ... ORDER BY ...)",
    description: "Attribue un rang. Saute les rangs après un ex aequo (1, 1, 3).",
    example: "SELECT RANK() OVER (ORDER BY salary DESC) FROM emp;",
    result: "1, 1, 3 (avec ex aequo)",
  },
  {
    name: "DENSE_RANK",
    category: "Analytique",
    syntax: "DENSE_RANK() OVER (PARTITION BY ... ORDER BY ...)",
    description: "Attribue un rang. Ne saute pas (1, 1, 2).",
    example: "SELECT DENSE_RANK() OVER (ORDER BY salary DESC) FROM emp;",
    result: "1, 1, 2 (avec ex aequo)",
  },
  {
    name: "ROW_NUMBER",
    category: "Analytique",
    syntax: "ROW_NUMBER() OVER (PARTITION BY ... ORDER BY ...)",
    description: "Attribue un numéro unique à chaque ligne (1, 2, 3 même avec ex aequo).",
    example: "SELECT ROW_NUMBER() OVER (ORDER BY salary DESC) FROM emp;",
    result: "1, 2, 3 (unique)",
  },
  {
    name: "LAG",
    category: "Analytique",
    syntax: "LAG(expr, offset, default) OVER (ORDER BY ...)",
    description: "Accède à la valeur d'une ligne précédente.",
    example: "SELECT LAG(salary, 1) OVER (ORDER BY hire_date) FROM emp;",
    result: "salaire de la ligne précédente",
  },
  {
    name: "LEAD",
    category: "Analytique",
    syntax: "LEAD(expr, offset, default) OVER (ORDER BY ...)",
    description: "Accède à la valeur d'une ligne suivante.",
    example: "SELECT LEAD(salary, 1) OVER (ORDER BY hire_date) FROM emp;",
    result: "salaire de la ligne suivante",
  },
];
